// Code generated by sgoiter emit go127; DO NOT EDIT.
package libinjection_sqli

func Is_mysql_comment(cs []int, len uint64, pos uint64) uint64 {
	v4 := pos + uint64(2)
	if v4 >= len {
	return uint64(0)
	}
	v7 := pos + uint64(2)
	v8 := cs[int(int(v7))]
	if v8 != 33 {
	return uint64(0)
	}
	return uint64(1)
}

