// Code generated by sgoiter emit go127; DO NOT EDIT.
package src

import "encoding/binary"

var blake2b_sigma = []byte{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 14, 10, 4, 8, 9, 15, 13, 6, 1, 12, 0, 2, 11, 7, 5, 3, 11, 8, 12, 0, 5, 2, 15, 13, 10, 14, 3, 6, 7, 1, 9, 4, 7, 9, 3, 1, 13, 12, 11, 14, 2, 6, 5, 10, 4, 0, 15, 8, 9, 0, 5, 7, 2, 4, 10, 15, 14, 1, 11, 12, 6, 8, 3, 13, 2, 12, 6, 10, 0, 11, 8, 3, 4, 13, 7, 5, 15, 14, 1, 9, 12, 5, 1, 15, 14, 13, 4, 10, 0, 7, 6, 3, 9, 2, 8, 11, 13, 11, 7, 14, 12, 1, 3, 9, 5, 0, 15, 4, 8, 6, 2, 10, 6, 15, 14, 9, 11, 3, 0, 8, 12, 2, 13, 7, 1, 4, 10, 5, 10, 2, 8, 4, 7, 6, 1, 5, 15, 11, 9, 14, 3, 12, 13, 0, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 14, 10, 4, 8, 9, 15, 13, 6, 1, 12, 0, 2, 11, 7, 5, 3}

func Blake2b_compress_block(h []uint64, block []byte, t0 uint64, t1 uint64, f0 uint64, f1 uint64) {
	var v627 uint64
	var v728 uint64
	var v906 uint64
	var v959 uint64
	var v970 uint64
	var v248 uint64
	var v376 uint64
	var v377 uint64
	var v493 uint64
	var v651 uint64
	var v762 uint64
	var v838 uint64
	var v974 uint64
	var v148 uint64
	var v302 uint64
	var v118 uint64
	var v167 uint64
	var v409 uint8
	var v60 uint64
	var v369 uint64
	var v714 uint64
	var v853 uint64
	var v884 uint64
	var v934 uint64
	var v68 uint64
	var v812 uint64
	var v927 uint64
	var v727 uint64
	var v738 uint64
	var v831 uint64
	var v941 uint64
	var v105 uint64
	var v273 uint64
	var v299 uint64
	var v476 uint64
	var v700 uint64
	var v108 uint64
	var v53 uint64
	var v143 uint64
	var v435 uint64
	var v175 uint8
	var v177 uint64
	var v717 uint64
	var v266 uint64
	var v323 uint64
	var v414 uint64
	var v617 uint64
	var v858 uint64
	var v867 uint64
	var v290 uint64
	var v541 uint64
	var v702 uint8
	var v778 uint64
	var v895 uint64
	var v232 uint64
	var v380 uint64
	var v675 uint64
	var v988 uint64
	var v991 uint64
	var v110 uint64
	var v119 uint64
	var v552 uint64
	var v225 uint64
	var v58 uint8
	var v284 uint64
	var v937 uint64
	var v956 uint64
	var v31 uint64
	var v359 uint64
	var v833 uint64
	var v102 uint64
	var v311 uint64
	var v491 uint64
	var v621 uint64
	var v635 uint64
	var v758 uint64
	var v869 uint64
	var v34 uint64
	var v401 uint64
	var v521 uint64
	var v555 uint64
	var v592 uint64
	var v716 uint64
	var v146 uint64
	var v174 uint64
	var v198 uint64
	var v395 uint64
	var v534 uint64
	var v611 uint64
	var v642 uint64
	var v783 uint64
	var v643 uint8
	var v789 uint64
	var v920 uint64
	var v938 uint64
	var v116 uint64
	var v193 uint64
	var v809 uint64
	var v107 uint64
	var v366 uint64
	var v16 uint64
	var v268 uint64
	var v424 uint64
	var v234 uint8
	var v452 uint64
	var v889 uint64
	var v160 uint64
	var v524 uint64
	var v657 uint64
	var v845 uint64
	var v473 uint64
	var v573 uint64
	var v624 uint64
	var v681 uint64
	var v731 uint64
	var v761 uint64
	var v775 uint64
	var v347 uint64
	var v432 uint64
	var v562 uint64
	var v583 uint64
	var v603 uint64
	var v77 uint64
	var v423 uint64
	var v879 uint64
	var v946 uint64
	var v986 uint64
	var v821 uint64
	var v132 uint64
	var v358 uint64
	var v382 uint64
	var v587 uint64
	var v672 uint64
	var v936 uint8
	var v568 uint64
	var v819 uint8
	var v824 uint64
	var v129 uint64
	var v253 uint64
	var v544 uint64
	var v655 uint64
	var v662 uint64
	var v897 uint64
	var v242 uint64
	var v569 uint64
	var v575 uint64
	var v679 uint64
	var v701 uint64
	var v703 uint64
	var v752 uint64
	var v96 uint64
	var v127 uint64
	var v170 uint64
	var v270 uint64
	var v407 uint64
	var v844 uint64
	var v872 uint64
	var v932 uint64
	var v149 uint64
	var v239 uint64
	var v363 uint64
	var v870 uint64
	var v908 uint64
	var v260 uint64
	var v324 uint64
	var v820 uint64
	var v159 uint64
	var v351 uint8
	var v370 uint64
	var v487 uint64
	var v619 uint64
	var v929 uint64
	var v259 uint64
	var v263 uint64
	var v350 uint64
	var v500 uint64
	var v584 uint64
	var v629 uint64
	var v10 uint64
	var v57 uint64
	var v441 uint64
	var v796 uint64
	var v985 uint64
	var v344 uint64
	var v540 uint64
	var v839 uint64
	var v877 uint8
	var v887 uint64
	var v924 uint64
	var v443 uint64
	var v827 uint64
	var v902 uint64
	var v285 uint64
	var v399 uint64
	var v518 uint64
	var v772 uint64
	var v244 uint64
	var v610 uint64
	var v185 uint64
	var v506 uint64
	var v581 uint64
	var v644 uint64
	var v387 uint64
	var v416 uint64
	var v641 uint64
	var v650 uint64
	var v741 uint64
	var v862 uint64
	var v125 uint64
	var v317 uint64
	var v753 uint64
	var v142 uint64
	var v545 uint64
	var v710 uint64
	var v63 uint64
	var v84 uint64
	var v356 uint64
	var v45 uint64
	var v66 uint64
	var v217 uint64
	var v230 uint64
	var v235 uint64
	var v287 uint64
	var v328 uint64
	var v341 uint64
	var v353 uint64
	var v352 uint64
	var v447 uint64
	var v605 uint64
	var v616 uint64
	var v623 uint64
	var v648 uint64
	var v855 uint64
	var v861 uint64
	var v81 uint64
	var v241 uint64
	var v633 uint64
	var v165 uint64
	var v538 uint64
	var v668 uint64
	var v909 uint64
	var v955 uint64
	var v992 uint64
	var v204 uint64
	var v211 uint64
	var v277 uint64
	var v349 uint64
	var v779 uint64
	var v768 uint64
	var v770 uint64
	var v466 uint64
	var v774 uint64
	var v73 uint64
	var v802 uint64
	var v900 uint64
	var v944 uint64
	var v815 uint64
	var v478 uint64
	var v733 uint64
	var v374 uint64
	var v458 uint64
	var v851 uint64
	var v227 uint64
	var v306 uint64
	var v394 uint64
	var v461 uint64
	var v685 uint64
	var v131 uint64
	var v339 uint64
	var v470 uint64
	var v528 uint64
	var v595 uint64
	var v59 uint64
	var v207 uint64
	var v390 uint64
	var v663 uint64
	var v744 uint64
	var v252 uint64
	var v254 uint64
	var v310 uint64
	var v419 uint64
	var v507 uint64
	var v837 uint64
	var v100 uint64
	var v677 uint64
	var v745 uint64
	var v56 uint64
	var v161 uint64
	var v531 uint64
	var v818 uint64
	var v92 uint64
	var v293 uint64
	var v674 uint64
	var v951 uint64
	var v83 uint64
	var v707 uint64
	var v765 uint64
	var v173 uint64
	var v176 uint64
	var v291 uint64
	var v335 uint64
	var v512 uint64
	var v124 uint64
	var v294 uint64
	var v402 uint64
	var v829 uint64
	var v70 uint64
	var v312 uint64
	var v404 uint64
	var v593 uint64
	var v599 uint64
	var v878 uint64
	var v979 uint64
	var v21 uint64
	var v453 uint64
	var v736 uint64
	var v183 uint64
	var v469 uint64
	var v536 uint64
	var v604 uint64
	var v740 uint64
	var v804 uint64
	var v321 uint64
	var v546 uint64
	var v746 uint64
	var v791 uint64
	var v282 uint64
	var v411 uint64
	var v427 uint64
	var v482 uint64
	var v669 uint64
	var v557 uint64
	var v564 uint64
	var v682 uint64
	var v690 uint64
	var v65 uint64
	var v209 uint64
	var v980 uint64
	var v135 uint64
	var v315 uint64
	var v428 uint64
	var v451 uint64
	var v525 uint64
	var v608 uint64
	var v975 uint64
	var v300 uint64
	var v560 uint64
	var v807 uint64
	var v834 uint64
	var v875 uint64
	var v876 uint64
	var v155 uint64
	var v194 uint64
	var v628 uint64
	var v722 uint64
	var v926 uint64
	var v331 uint64
	var v767 uint64
	var v187 uint64
	var v330 uint64
	var v590 uint64
	var v750 uint64
	var v842 uint64
	var v978 uint64
	var v236 uint64
	var v578 uint64
	var v585 uint8
	var v686 uint64
	var v850 uint64
	var v882 uint64
	var v361 uint64
	var v371 uint64
	var v817 uint64
	var v213 uint64
	var v224 uint64
	var v516 uint64
	var v600 uint64
	var v636 uint64
	var v780 uint64
	var v919 uint64
	var v72 uint64
	var v410 uint64
	var v438 uint64
	var v468 uint8
	var v551 uint64
	var v693 uint64
	var v915 uint64
	var v916 uint64
	var v497 uint64
	var v504 uint64
	var v510 uint64
	var v965 uint64
	var v709 uint64
	var v51 uint64
	var v721 uint64
	var v48 uint64
	var v101 uint64
	var v385 uint64
	var v486 uint64
	var v526 uint8
	var v692 uint64
	var v803 uint64
	var v297 uint64
	var v483 uint64
	var v972 uint64
	var v249 uint64
	var v421 uint64
	var v87 uint64
	var v189 uint64
	var v218 uint64
	var v661 uint64
	var v759 uint64
	var v794 uint64
	var v961 uint64
	var v151 uint64
	var v304 uint64
	var v666 uint64
	var v863 uint64
	var v37 uint64
	var v50 uint64
	var v136 uint64
	var v549 uint64
	var v954 uint64
	var v687 uint64
	var v734 uint64
	var v786 uint64
	var v950 uint64
	var v14 uint64
	var v219 uint64
	var v448 uint64
	var v638 uint64
	var v962 uint64
	var v89 uint64
	var v153 uint64
	var v195 uint64
	var v342 uint64
	var v760 uint8
	var v117 uint8
	var v206 uint64
	var v389 uint64
	var v968 uint64
	var v658 uint64
	var v885 uint64
	var v911 uint64
	var v943 uint64
	var v948 uint64
	var v201 uint64
	var v307 uint64
	var v334 uint64
	var v480 uint64
	var v292 uint8
	var v570 uint64
	var v720 uint64
	var v122 uint64
	var v257 uint64
	var v365 uint64
	var v494 uint64
	var v558 uint64
	var v78 uint64
	var v97 uint64
	var v417 uint64
	var v511 uint64
	var v712 uint64
	var v967 uint64
	var v137 uint64
	var v459 uint64
	var v792 uint64
	var v891 uint64
	var v76 uint64
	var v326 uint64
	var v393 uint64
	var v935 uint64
	var v6 []byte
	var v40 uint64
	var v140 uint64
	var v921 uint64
	var v156 uint64
	var v182 uint64
	var v272 uint64
	var v445 uint64
	var v499 uint64
	var v586 uint64
	var v265 uint64
	var v440 uint64
	var v896 uint64
	var v115 uint64
	var v408 uint64
	var v848 uint64
	var v467 uint64
	var v990 uint64
	var v913 uint64
	var v233 uint64
	var v246 uint64
	var v434 uint64
	var v597 uint64
	var v614 uint64
	var v799 uint64
	var v222 uint64
	var v276 uint64
	var v456 uint64
	var v565 uint64
	var v725 uint64
	var v214 uint64
	var v318 uint64
	var v704 uint64
	var v645 uint64
	var v475 uint64
	var v527 uint64
	var v892 uint64
	var v987 uint64
	var v698 uint64
	var v857 uint64
	var v9 uint64
	var v90 uint64
	var v190 uint64
	var v200 uint64
	var v576 uint64
	var v785 uint64
	var v903 uint64
	var v20 uint64
	var v383 uint64
	var v464 uint64
	var v519 uint64
	var v798 uint64
	var v810 uint64
	var v826 uint64
	var v168 uint64
	var v180 uint64
	var v336 uint64
	var v488 uint64
	var v653 uint64
	var v695 uint64
	var v113 uint64
	var v502 uint64
	var v533 uint64
	var v429 uint64
	var v755 uint64
	var v94 uint64
	var v278 uint64
	v6 = blake2b_sigma
	var _arr_v7 [16]uint64
	v7 := _arr_v7[:]
	var _arr_v8 [16]uint64
	v8 := _arr_v8[:]
	v9 = uint64(0)
	for v9 < uint64(16) {
	v16 = binary.LittleEndian.Uint64(block[int(int(v9)):])
	v7[int(int(v9))] = v16
	v14 = v9 + uint64(1)
	v9 = v14
	}
	v9 = uint64(0)
	for v9 < uint64(8) {
	v21 = h[int(int(v9))]
	v8[int(int(v9))] = v21
	v20 = v9 + uint64(1)
	v9 = v20
	}
	v8[int(8)] = uint64(7640891576956012808)
	v8[int(9)] = uint64(13503953896175478587)
	v8[int(10)] = uint64(4354685564936845355)
	v8[int(11)] = uint64(11912009170470909681)
	v31 = uint64(5840696476095770973) ^ t0
	v8[int(12)] = v31
	v34 = uint64(11170449401992604703) ^ t1
	v8[int(13)] = v34
	v37 = uint64(2270897969802886507) ^ f0
	v8[int(14)] = v37
	v40 = uint64(6620516959819538809) ^ f1
	v8[int(15)] = v40
	v10 = uint64(0)
	for v10 < uint64(12) {
	for {
	v48 = v8[int(0)]
	v50 = v8[int(4)]
	v51 = v48 + v50
	v53 = v10 * uint64(16)
	v56 = uint64(2) * uint64(0)
	v57 = v53 + v56
	v58 = v6[int(int(v57))]
	v59 = v7[int(int(v58))]
	v60 = v51 + v59
	v8[int(0)] = v60
	v63 = v8[int(12)]
	v65 = v8[int(0)]
	v66 = v63 ^ v65
	v68 = v66 >> uint8(32)
	v70 = v8[int(12)]
	v72 = v8[int(0)]
	v73 = v70 ^ v72
	v76 = uint64(64) - uint64(32)
	v77 = v73 << uint8(v76)
	v78 = v68 ^ v77
	v8[int(12)] = v78
	v81 = v8[int(8)]
	v83 = v8[int(12)]
	v84 = v81 + v83
	v8[int(8)] = v84
	v87 = v8[int(4)]
	v89 = v8[int(8)]
	v90 = v87 ^ v89
	v92 = v90 >> uint8(24)
	v94 = v8[int(4)]
	v96 = v8[int(8)]
	v97 = v94 ^ v96
	v100 = uint64(64) - uint64(24)
	v101 = v97 << uint8(v100)
	v102 = v92 ^ v101
	v8[int(4)] = v102
	v105 = v8[int(0)]
	v107 = v8[int(4)]
	v108 = v105 + v107
	v110 = v10 * uint64(16)
	v113 = uint64(2) * uint64(0)
	v115 = v113 + uint64(1)
	v116 = v110 + v115
	v117 = v6[int(int(v116))]
	v118 = v7[int(int(v117))]
	v119 = v108 + v118
	v8[int(0)] = v119
	v122 = v8[int(12)]
	v124 = v8[int(0)]
	v125 = v122 ^ v124
	v127 = v125 >> uint8(16)
	v129 = v8[int(12)]
	v131 = v8[int(0)]
	v132 = v129 ^ v131
	v135 = uint64(64) - uint64(16)
	v136 = v132 << uint8(v135)
	v137 = v127 ^ v136
	v8[int(12)] = v137
	v140 = v8[int(8)]
	v142 = v8[int(12)]
	v143 = v140 + v142
	v8[int(8)] = v143
	v146 = v8[int(4)]
	v148 = v8[int(8)]
	v149 = v146 ^ v148
	v151 = v149 >> uint8(63)
	v153 = v8[int(4)]
	v155 = v8[int(8)]
	v156 = v153 ^ v155
	v159 = uint64(64) - uint64(63)
	v160 = v156 << uint8(v159)
	v161 = v151 ^ v160
	v8[int(4)] = v161
		if !(uint64(0) != 0) { break }
	}
	for {
	v165 = v8[int(1)]
	v167 = v8[int(5)]
	v168 = v165 + v167
	v170 = v10 * uint64(16)
	v173 = uint64(2) * uint64(1)
	v174 = v170 + v173
	v175 = v6[int(int(v174))]
	v176 = v7[int(int(v175))]
	v177 = v168 + v176
	v8[int(1)] = v177
	v180 = v8[int(13)]
	v182 = v8[int(1)]
	v183 = v180 ^ v182
	v185 = v183 >> uint8(32)
	v187 = v8[int(13)]
	v189 = v8[int(1)]
	v190 = v187 ^ v189
	v193 = uint64(64) - uint64(32)
	v194 = v190 << uint8(v193)
	v195 = v185 ^ v194
	v8[int(13)] = v195
	v198 = v8[int(9)]
	v200 = v8[int(13)]
	v201 = v198 + v200
	v8[int(9)] = v201
	v204 = v8[int(5)]
	v206 = v8[int(9)]
	v207 = v204 ^ v206
	v209 = v207 >> uint8(24)
	v211 = v8[int(5)]
	v213 = v8[int(9)]
	v214 = v211 ^ v213
	v217 = uint64(64) - uint64(24)
	v218 = v214 << uint8(v217)
	v219 = v209 ^ v218
	v8[int(5)] = v219
	v222 = v8[int(1)]
	v224 = v8[int(5)]
	v225 = v222 + v224
	v227 = v10 * uint64(16)
	v230 = uint64(2) * uint64(1)
	v232 = v230 + uint64(1)
	v233 = v227 + v232
	v234 = v6[int(int(v233))]
	v235 = v7[int(int(v234))]
	v236 = v225 + v235
	v8[int(1)] = v236
	v239 = v8[int(13)]
	v241 = v8[int(1)]
	v242 = v239 ^ v241
	v244 = v242 >> uint8(16)
	v246 = v8[int(13)]
	v248 = v8[int(1)]
	v249 = v246 ^ v248
	v252 = uint64(64) - uint64(16)
	v253 = v249 << uint8(v252)
	v254 = v244 ^ v253
	v8[int(13)] = v254
	v257 = v8[int(9)]
	v259 = v8[int(13)]
	v260 = v257 + v259
	v8[int(9)] = v260
	v263 = v8[int(5)]
	v265 = v8[int(9)]
	v266 = v263 ^ v265
	v268 = v266 >> uint8(63)
	v270 = v8[int(5)]
	v272 = v8[int(9)]
	v273 = v270 ^ v272
	v276 = uint64(64) - uint64(63)
	v277 = v273 << uint8(v276)
	v278 = v268 ^ v277
	v8[int(5)] = v278
		if !(uint64(0) != 0) { break }
	}
	for {
	v282 = v8[int(2)]
	v284 = v8[int(6)]
	v285 = v282 + v284
	v287 = v10 * uint64(16)
	v290 = uint64(2) * uint64(2)
	v291 = v287 + v290
	v292 = v6[int(int(v291))]
	v293 = v7[int(int(v292))]
	v294 = v285 + v293
	v8[int(2)] = v294
	v297 = v8[int(14)]
	v299 = v8[int(2)]
	v300 = v297 ^ v299
	v302 = v300 >> uint8(32)
	v304 = v8[int(14)]
	v306 = v8[int(2)]
	v307 = v304 ^ v306
	v310 = uint64(64) - uint64(32)
	v311 = v307 << uint8(v310)
	v312 = v302 ^ v311
	v8[int(14)] = v312
	v315 = v8[int(10)]
	v317 = v8[int(14)]
	v318 = v315 + v317
	v8[int(10)] = v318
	v321 = v8[int(6)]
	v323 = v8[int(10)]
	v324 = v321 ^ v323
	v326 = v324 >> uint8(24)
	v328 = v8[int(6)]
	v330 = v8[int(10)]
	v331 = v328 ^ v330
	v334 = uint64(64) - uint64(24)
	v335 = v331 << uint8(v334)
	v336 = v326 ^ v335
	v8[int(6)] = v336
	v339 = v8[int(2)]
	v341 = v8[int(6)]
	v342 = v339 + v341
	v344 = v10 * uint64(16)
	v347 = uint64(2) * uint64(2)
	v349 = v347 + uint64(1)
	v350 = v344 + v349
	v351 = v6[int(int(v350))]
	v352 = v7[int(int(v351))]
	v353 = v342 + v352
	v8[int(2)] = v353
	v356 = v8[int(14)]
	v358 = v8[int(2)]
	v359 = v356 ^ v358
	v361 = v359 >> uint8(16)
	v363 = v8[int(14)]
	v365 = v8[int(2)]
	v366 = v363 ^ v365
	v369 = uint64(64) - uint64(16)
	v370 = v366 << uint8(v369)
	v371 = v361 ^ v370
	v8[int(14)] = v371
	v374 = v8[int(10)]
	v376 = v8[int(14)]
	v377 = v374 + v376
	v8[int(10)] = v377
	v380 = v8[int(6)]
	v382 = v8[int(10)]
	v383 = v380 ^ v382
	v385 = v383 >> uint8(63)
	v387 = v8[int(6)]
	v389 = v8[int(10)]
	v390 = v387 ^ v389
	v393 = uint64(64) - uint64(63)
	v394 = v390 << uint8(v393)
	v395 = v385 ^ v394
	v8[int(6)] = v395
		if !(uint64(0) != 0) { break }
	}
	for {
	v399 = v8[int(3)]
	v401 = v8[int(7)]
	v402 = v399 + v401
	v404 = v10 * uint64(16)
	v407 = uint64(2) * uint64(3)
	v408 = v404 + v407
	v409 = v6[int(int(v408))]
	v410 = v7[int(int(v409))]
	v411 = v402 + v410
	v8[int(3)] = v411
	v414 = v8[int(15)]
	v416 = v8[int(3)]
	v417 = v414 ^ v416
	v419 = v417 >> uint8(32)
	v421 = v8[int(15)]
	v423 = v8[int(3)]
	v424 = v421 ^ v423
	v427 = uint64(64) - uint64(32)
	v428 = v424 << uint8(v427)
	v429 = v419 ^ v428
	v8[int(15)] = v429
	v432 = v8[int(11)]
	v434 = v8[int(15)]
	v435 = v432 + v434
	v8[int(11)] = v435
	v438 = v8[int(7)]
	v440 = v8[int(11)]
	v441 = v438 ^ v440
	v443 = v441 >> uint8(24)
	v445 = v8[int(7)]
	v447 = v8[int(11)]
	v448 = v445 ^ v447
	v451 = uint64(64) - uint64(24)
	v452 = v448 << uint8(v451)
	v453 = v443 ^ v452
	v8[int(7)] = v453
	v456 = v8[int(3)]
	v458 = v8[int(7)]
	v459 = v456 + v458
	v461 = v10 * uint64(16)
	v464 = uint64(2) * uint64(3)
	v466 = v464 + uint64(1)
	v467 = v461 + v466
	v468 = v6[int(int(v467))]
	v469 = v7[int(int(v468))]
	v470 = v459 + v469
	v8[int(3)] = v470
	v473 = v8[int(15)]
	v475 = v8[int(3)]
	v476 = v473 ^ v475
	v478 = v476 >> uint8(16)
	v480 = v8[int(15)]
	v482 = v8[int(3)]
	v483 = v480 ^ v482
	v486 = uint64(64) - uint64(16)
	v487 = v483 << uint8(v486)
	v488 = v478 ^ v487
	v8[int(15)] = v488
	v491 = v8[int(11)]
	v493 = v8[int(15)]
	v494 = v491 + v493
	v8[int(11)] = v494
	v497 = v8[int(7)]
	v499 = v8[int(11)]
	v500 = v497 ^ v499
	v502 = v500 >> uint8(63)
	v504 = v8[int(7)]
	v506 = v8[int(11)]
	v507 = v504 ^ v506
	v510 = uint64(64) - uint64(63)
	v511 = v507 << uint8(v510)
	v512 = v502 ^ v511
	v8[int(7)] = v512
		if !(uint64(0) != 0) { break }
	}
	for {
	v516 = v8[int(0)]
	v518 = v8[int(5)]
	v519 = v516 + v518
	v521 = v10 * uint64(16)
	v524 = uint64(2) * uint64(4)
	v525 = v521 + v524
	v526 = v6[int(int(v525))]
	v527 = v7[int(int(v526))]
	v528 = v519 + v527
	v8[int(0)] = v528
	v531 = v8[int(15)]
	v533 = v8[int(0)]
	v534 = v531 ^ v533
	v536 = v534 >> uint8(32)
	v538 = v8[int(15)]
	v540 = v8[int(0)]
	v541 = v538 ^ v540
	v544 = uint64(64) - uint64(32)
	v545 = v541 << uint8(v544)
	v546 = v536 ^ v545
	v8[int(15)] = v546
	v549 = v8[int(10)]
	v551 = v8[int(15)]
	v552 = v549 + v551
	v8[int(10)] = v552
	v555 = v8[int(5)]
	v557 = v8[int(10)]
	v558 = v555 ^ v557
	v560 = v558 >> uint8(24)
	v562 = v8[int(5)]
	v564 = v8[int(10)]
	v565 = v562 ^ v564
	v568 = uint64(64) - uint64(24)
	v569 = v565 << uint8(v568)
	v570 = v560 ^ v569
	v8[int(5)] = v570
	v573 = v8[int(0)]
	v575 = v8[int(5)]
	v576 = v573 + v575
	v578 = v10 * uint64(16)
	v581 = uint64(2) * uint64(4)
	v583 = v581 + uint64(1)
	v584 = v578 + v583
	v585 = v6[int(int(v584))]
	v586 = v7[int(int(v585))]
	v587 = v576 + v586
	v8[int(0)] = v587
	v590 = v8[int(15)]
	v592 = v8[int(0)]
	v593 = v590 ^ v592
	v595 = v593 >> uint8(16)
	v597 = v8[int(15)]
	v599 = v8[int(0)]
	v600 = v597 ^ v599
	v603 = uint64(64) - uint64(16)
	v604 = v600 << uint8(v603)
	v605 = v595 ^ v604
	v8[int(15)] = v605
	v608 = v8[int(10)]
	v610 = v8[int(15)]
	v611 = v608 + v610
	v8[int(10)] = v611
	v614 = v8[int(5)]
	v616 = v8[int(10)]
	v617 = v614 ^ v616
	v619 = v617 >> uint8(63)
	v621 = v8[int(5)]
	v623 = v8[int(10)]
	v624 = v621 ^ v623
	v627 = uint64(64) - uint64(63)
	v628 = v624 << uint8(v627)
	v629 = v619 ^ v628
	v8[int(5)] = v629
		if !(uint64(0) != 0) { break }
	}
	for {
	v633 = v8[int(1)]
	v635 = v8[int(6)]
	v636 = v633 + v635
	v638 = v10 * uint64(16)
	v641 = uint64(2) * uint64(5)
	v642 = v638 + v641
	v643 = v6[int(int(v642))]
	v644 = v7[int(int(v643))]
	v645 = v636 + v644
	v8[int(1)] = v645
	v648 = v8[int(12)]
	v650 = v8[int(1)]
	v651 = v648 ^ v650
	v653 = v651 >> uint8(32)
	v655 = v8[int(12)]
	v657 = v8[int(1)]
	v658 = v655 ^ v657
	v661 = uint64(64) - uint64(32)
	v662 = v658 << uint8(v661)
	v663 = v653 ^ v662
	v8[int(12)] = v663
	v666 = v8[int(11)]
	v668 = v8[int(12)]
	v669 = v666 + v668
	v8[int(11)] = v669
	v672 = v8[int(6)]
	v674 = v8[int(11)]
	v675 = v672 ^ v674
	v677 = v675 >> uint8(24)
	v679 = v8[int(6)]
	v681 = v8[int(11)]
	v682 = v679 ^ v681
	v685 = uint64(64) - uint64(24)
	v686 = v682 << uint8(v685)
	v687 = v677 ^ v686
	v8[int(6)] = v687
	v690 = v8[int(1)]
	v692 = v8[int(6)]
	v693 = v690 + v692
	v695 = v10 * uint64(16)
	v698 = uint64(2) * uint64(5)
	v700 = v698 + uint64(1)
	v701 = v695 + v700
	v702 = v6[int(int(v701))]
	v703 = v7[int(int(v702))]
	v704 = v693 + v703
	v8[int(1)] = v704
	v707 = v8[int(12)]
	v709 = v8[int(1)]
	v710 = v707 ^ v709
	v712 = v710 >> uint8(16)
	v714 = v8[int(12)]
	v716 = v8[int(1)]
	v717 = v714 ^ v716
	v720 = uint64(64) - uint64(16)
	v721 = v717 << uint8(v720)
	v722 = v712 ^ v721
	v8[int(12)] = v722
	v725 = v8[int(11)]
	v727 = v8[int(12)]
	v728 = v725 + v727
	v8[int(11)] = v728
	v731 = v8[int(6)]
	v733 = v8[int(11)]
	v734 = v731 ^ v733
	v736 = v734 >> uint8(63)
	v738 = v8[int(6)]
	v740 = v8[int(11)]
	v741 = v738 ^ v740
	v744 = uint64(64) - uint64(63)
	v745 = v741 << uint8(v744)
	v746 = v736 ^ v745
	v8[int(6)] = v746
		if !(uint64(0) != 0) { break }
	}
	for {
	v750 = v8[int(2)]
	v752 = v8[int(7)]
	v753 = v750 + v752
	v755 = v10 * uint64(16)
	v758 = uint64(2) * uint64(6)
	v759 = v755 + v758
	v760 = v6[int(int(v759))]
	v761 = v7[int(int(v760))]
	v762 = v753 + v761
	v8[int(2)] = v762
	v765 = v8[int(13)]
	v767 = v8[int(2)]
	v768 = v765 ^ v767
	v770 = v768 >> uint8(32)
	v772 = v8[int(13)]
	v774 = v8[int(2)]
	v775 = v772 ^ v774
	v778 = uint64(64) - uint64(32)
	v779 = v775 << uint8(v778)
	v780 = v770 ^ v779
	v8[int(13)] = v780
	v783 = v8[int(8)]
	v785 = v8[int(13)]
	v786 = v783 + v785
	v8[int(8)] = v786
	v789 = v8[int(7)]
	v791 = v8[int(8)]
	v792 = v789 ^ v791
	v794 = v792 >> uint8(24)
	v796 = v8[int(7)]
	v798 = v8[int(8)]
	v799 = v796 ^ v798
	v802 = uint64(64) - uint64(24)
	v803 = v799 << uint8(v802)
	v804 = v794 ^ v803
	v8[int(7)] = v804
	v807 = v8[int(2)]
	v809 = v8[int(7)]
	v810 = v807 + v809
	v812 = v10 * uint64(16)
	v815 = uint64(2) * uint64(6)
	v817 = v815 + uint64(1)
	v818 = v812 + v817
	v819 = v6[int(int(v818))]
	v820 = v7[int(int(v819))]
	v821 = v810 + v820
	v8[int(2)] = v821
	v824 = v8[int(13)]
	v826 = v8[int(2)]
	v827 = v824 ^ v826
	v829 = v827 >> uint8(16)
	v831 = v8[int(13)]
	v833 = v8[int(2)]
	v834 = v831 ^ v833
	v837 = uint64(64) - uint64(16)
	v838 = v834 << uint8(v837)
	v839 = v829 ^ v838
	v8[int(13)] = v839
	v842 = v8[int(8)]
	v844 = v8[int(13)]
	v845 = v842 + v844
	v8[int(8)] = v845
	v848 = v8[int(7)]
	v850 = v8[int(8)]
	v851 = v848 ^ v850
	v853 = v851 >> uint8(63)
	v855 = v8[int(7)]
	v857 = v8[int(8)]
	v858 = v855 ^ v857
	v861 = uint64(64) - uint64(63)
	v862 = v858 << uint8(v861)
	v863 = v853 ^ v862
	v8[int(7)] = v863
		if !(uint64(0) != 0) { break }
	}
	for {
	v867 = v8[int(3)]
	v869 = v8[int(4)]
	v870 = v867 + v869
	v872 = v10 * uint64(16)
	v875 = uint64(2) * uint64(7)
	v876 = v872 + v875
	v877 = v6[int(int(v876))]
	v878 = v7[int(int(v877))]
	v879 = v870 + v878
	v8[int(3)] = v879
	v882 = v8[int(14)]
	v884 = v8[int(3)]
	v885 = v882 ^ v884
	v887 = v885 >> uint8(32)
	v889 = v8[int(14)]
	v891 = v8[int(3)]
	v892 = v889 ^ v891
	v895 = uint64(64) - uint64(32)
	v896 = v892 << uint8(v895)
	v897 = v887 ^ v896
	v8[int(14)] = v897
	v900 = v8[int(9)]
	v902 = v8[int(14)]
	v903 = v900 + v902
	v8[int(9)] = v903
	v906 = v8[int(4)]
	v908 = v8[int(9)]
	v909 = v906 ^ v908
	v911 = v909 >> uint8(24)
	v913 = v8[int(4)]
	v915 = v8[int(9)]
	v916 = v913 ^ v915
	v919 = uint64(64) - uint64(24)
	v920 = v916 << uint8(v919)
	v921 = v911 ^ v920
	v8[int(4)] = v921
	v924 = v8[int(3)]
	v926 = v8[int(4)]
	v927 = v924 + v926
	v929 = v10 * uint64(16)
	v932 = uint64(2) * uint64(7)
	v934 = v932 + uint64(1)
	v935 = v929 + v934
	v936 = v6[int(int(v935))]
	v937 = v7[int(int(v936))]
	v938 = v927 + v937
	v8[int(3)] = v938
	v941 = v8[int(14)]
	v943 = v8[int(3)]
	v944 = v941 ^ v943
	v946 = v944 >> uint8(16)
	v948 = v8[int(14)]
	v950 = v8[int(3)]
	v951 = v948 ^ v950
	v954 = uint64(64) - uint64(16)
	v955 = v951 << uint8(v954)
	v956 = v946 ^ v955
	v8[int(14)] = v956
	v959 = v8[int(9)]
	v961 = v8[int(14)]
	v962 = v959 + v961
	v8[int(9)] = v962
	v965 = v8[int(4)]
	v967 = v8[int(9)]
	v968 = v965 ^ v967
	v970 = v968 >> uint8(63)
	v972 = v8[int(4)]
	v974 = v8[int(9)]
	v975 = v972 ^ v974
	v978 = uint64(64) - uint64(63)
	v979 = v975 << uint8(v978)
	v980 = v970 ^ v979
	v8[int(4)] = v980
		if !(uint64(0) != 0) { break }
	}
	v45 = v10 + uint64(1)
	v10 = v45
	}
	v9 = uint64(0)
	for v9 < uint64(8) {
	v986 = h[int(int(v9))]
	v987 = v8[int(int(v9))]
	v988 = v986 ^ v987
	v990 = v9 + uint64(8)
	v991 = v8[int(int(v990))]
	v992 = v988 ^ v991
	h[int(int(v9))] = v992
	v985 = v9 + uint64(1)
	v9 = v985
	}
}

