// Code generated by sgoiter emit go127; DO NOT EDIT.
package monocypher_amalg

import "math/bits"

type Crypto_aead_ctx struct {
	Counter uint64
	Key [32]uint8
	Nonce [8]uint8
}

type Crypto_blake2b_ctx struct {
	Hash [8]uint64
	Input_offset [2]uint64
	Input [16]uint64
	Input_idx uint64
	Hash_size uint64
}

type Crypto_argon2_config struct {
	Algorithm uint32
	Nb_blocks uint32
	Nb_passes uint32
	Nb_lanes uint32
}

type Crypto_argon2_inputs struct {
	Pass_size uint32
	Salt_size uint32
}

type Crypto_argon2_extras struct {
	Key_size uint32
	Ad_size uint32
}

type Crypto_poly1305_ctx struct {
	C [16]uint8
	C_idx uint64
	R [4]uint32
	Pad [4]uint32
	H [5]uint32
}

type Blk struct {
	A [128]uint64
}

type S25 struct {
	X uint64
}

type S26 struct {
	X uint64
}

type Ge struct {
	X [10]int
	Y [10]int
	Z [10]int
	T [10]int
}

type Ge_cached struct {
	Yp [10]int
	Ym [10]int
	Z [10]int
	T2 [10]int
}

type Ge_precomp struct {
	Yp [10]int
	Ym [10]int
	T2 [10]int
}

type Slide_ctx struct {
	Next_index uint32
	Next_digit uint8
	Next_check uint8
}

var chacha20_constant = []byte("expand 32-byte k")
var zero = make([]byte, 128)
var key_block = make([]byte, 128)
var sigma = [192]byte{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 14, 10, 4, 8, 9, 15, 13, 6, 1, 12, 0, 2, 11, 7, 5, 3, 11, 8, 12, 0, 5, 2, 15, 13, 10, 14, 3, 6, 7, 1, 9, 4, 7, 9, 3, 1, 13, 12, 11, 14, 2, 6, 5, 10, 4, 0, 15, 8, 9, 0, 5, 7, 2, 4, 10, 15, 14, 1, 11, 12, 6, 8, 3, 13, 2, 12, 6, 10, 0, 11, 8, 3, 4, 13, 7, 5, 15, 14, 1, 9, 12, 5, 1, 15, 14, 13, 4, 10, 0, 7, 6, 3, 9, 2, 8, 11, 13, 11, 7, 14, 12, 1, 3, 9, 5, 0, 15, 4, 8, 6, 2, 10, 6, 15, 14, 9, 11, 3, 0, 8, 12, 2, 13, 7, 1, 4, 10, 5, 10, 2, 8, 4, 7, 6, 1, 5, 15, 11, 9, 14, 3, 12, 13, 0, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 14, 10, 4, 8, 9, 15, 13, 6, 1, 12, 0, 2, 11, 7, 5, 3}
var iv = [8]uint64{0x6a09e667f3bcc908, 0xbb67ae8584caa73b, 0x3c6ef372fe94f82b, 0xa54ff53a5f1d36f1, 0x510e527fade682d1, 0x9b05688c2b3e6c1f, 0x1f83d9abfb41bd6b, 0x5be0cd19137e2179}
var base_point = [1]byte{9}
var L = [8]uint32{0x5cf5d3ed, 0x5812631a, 0xa2f79cd6, 0x14def9de, 0x00000000, 0x00000000, 0x00000000, 0x10000000}
var r = [9]uint32{0x0a2c131b, 0xed9ce5a3, 0x086329a7, 0x2106215d, 0xffffffeb, 0xffffffff, 0xffffffff, 0xffffffff, 0xf}
var xr = [1]uint32{0}
var zero_point = [1]byte{1}
var half_mod_L = [32]byte{247, 233, 122, 46, 141, 49, 9, 44, 107, 206, 123, 81, 239, 124, 111, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8}
var half_ones = [32]byte{142, 74, 204, 70, 186, 24, 118, 107, 184, 231, 190, 57, 250, 173, 119, 99, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 7}
var dirty_base_point = [32]byte{0xd8, 0x86, 0x1a, 0xa2, 0x78, 0x7a, 0xd9, 0x26, 0x8b, 0x74, 0x74, 0xb6, 0x82, 0xe3, 0xbe, 0xc3, 0xce, 0x36, 0x9a, 0x1e, 0x5e, 0x31, 0x47, 0xa2, 0x6d, 0x37, 0x7c, 0xfd, 0x20, 0xb5, 0xdf, 0x75}
var k = [8]uint32{0x12547e1b, 0xd2b51da3, 0xfdba84ff, 0xb1a206f2, 0xffa36bea, 0x14e75438, 0x6fe91836, 0x9db6c6f2}
var s = [1]uint32{0}
var t = [1]uint32{0}
var Lm2 = [32]byte{0xeb, 0xd3, 0xf5, 0x5c, 0x1a, 0x63, 0x12, 0x58, 0xd6, 0x9c, 0xf7, 0xa2, 0xde, 0xf9, 0xde, 0x14, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x10}
var m_inv = [8]uint32{0x8d98951d, 0xd6ec3174, 0x737dcf70, 0xc6ef5bf4, 0xfffffffe, 0xffffffff, 0xffffffff, 0x0fffffff}

func Gap(x uint64, pow_2 uint64) uint64 {
	return uint64((^x + 1) & (pow_2 - 1))
}

func Load24_le(s []byte) uint32 {
	return uint32(uint32(s[0]) << 0 | uint32(s[1]) << 8 | uint32(s[2]) << 16)
}

func Load32_le(s []byte) uint32 {
	return uint32(uint32(s[0]) << 0 | uint32(s[1]) << 8 | uint32(s[2]) << 16 | uint32(s[3]) << 24)
}

func Load64_le(s []byte) uint64 {
	return uint64(uint64(Load32_le(s)) | uint64(Load32_le(s[4:])) << 32)
}

func Store32_le(out []byte, in uint32) {
	out[0] = uint8(in & 0xff)
	out[1] = uint8((in >> 8) & uint32(0xff))
	out[2] = uint8((in >> 16) & uint32(0xff))
	out[3] = uint8((in >> 24) & uint32(0xff))
}

func Store64_le(out []byte, in uint64) {
	Store32_le(out, uint32(in))
	Store32_le(out[4:], uint32(in >> 32))
}

func Load32_le_buf(dst []uint32, src []byte, size uint64) {
	var v3 uint64
	v3 = 0
	for v3 < size {
		dst[int(v3)] = Load32_le(src[int(v3 * 4):])
		v3 = v3 + 1
	}
}

func Load64_le_buf(dst []uint64, src []byte, size uint64) {
	var v3 uint64
	v3 = 0
	for v3 < size {
		dst[int(v3)] = Load64_le(src[int(v3 * 8):])
		v3 = v3 + 1
	}
}

func Store32_le_buf(dst []byte, src []uint32, size uint64) {
	var v3 uint64
	v3 = 0
	for v3 < size {
		Store32_le(dst[int(v3 * 4):], src[int(v3)])
		v3 = v3 + 1
	}
}

func Store64_le_buf(dst []byte, src []uint64, size uint64) {
	var v3 uint64
	v3 = 0
	for v3 < size {
		Store64_le(dst[int(v3 * 8):], src[int(v3)])
		v3 = v3 + 1
	}
}

func Rotr64(x uint64, n uint64) uint64 {
	return uint64(bits.RotateLeft64(x, 64-int(n)))
}

func Rotl32(x uint32, n uint32) uint32 {
	return uint32(bits.RotateLeft32(x, int(n)))
}

func Neq0(diff uint64) int {
	return int(uint64(1) & ((((diff >> 32) | uint64(uint32(diff))) - uint64(1)) >> 32) - uint64(1))
}

func X16(a []byte, b []byte) uint64 {
	return uint64(Load64_le(a) ^ Load64_le(b) | Load64_le(a[8:]) ^ Load64_le(b[8:]))
}

func X32(a []byte, b []byte) uint64 {
	return uint64(X16(a, b) | X16(a[16:], b[16:]))
}

func X64(a []byte, b []byte) uint64 {
	return uint64(X32(a, b) | X32(a[32:], b[32:]))
}

func Crypto_verify16(a []byte, b []byte) int {
	return Neq0(X16(a, b))
}

func Crypto_verify32(a []byte, b []byte) int {
	return Neq0(X32(a, b))
}

func Crypto_verify64(a []byte, b []byte) int {
	return Neq0(X64(a, b))
}

func Crypto_wipe(secret []byte, size uint64) {
	var v4 uint64
	v4 = 0
	for v4 < size {
		secret[int(v4)] = uint8(0)
		v4 = v4 + 1
	}
}

func Chacha20_rounds(out []uint32, in []uint32) {
	var v2 uint32
	var v5 uint32
	var v8 uint32
	var v11 uint32
	var v14 uint32
	var v17 uint32
	var v20 uint32
	var v23 uint32
	var v26 uint32
	var v29 uint32
	var v32 uint32
	var v35 uint32
	var v38 uint32
	var v41 uint32
	var v44 uint32
	var v47 uint32
	var v50 uint64
	v2 = in[0]
	v5 = in[1]
	v8 = in[2]
	v11 = in[3]
	v14 = in[4]
	v17 = in[5]
	v20 = in[6]
	v23 = in[7]
	v26 = in[8]
	v29 = in[9]
	v32 = in[10]
	v35 = in[11]
	v38 = in[12]
	v41 = in[13]
	v44 = in[14]
	v47 = in[15]
	v50 = 0
	for v50 < 10 {
		v2 = v2 + v14
		v38 = Rotl32((v38 ^ v2), 16)
		v26 = v26 + v38
		v14 = Rotl32((v14 ^ v26), 12)
		v2 = v2 + v14
		v38 = Rotl32((v38 ^ v2), 8)
		v26 = v26 + v38
		v14 = Rotl32((v14 ^ v26), 7)
		v5 = v5 + v17
		v41 = Rotl32((v41 ^ v5), 16)
		v29 = v29 + v41
		v17 = Rotl32((v17 ^ v29), 12)
		v5 = v5 + v17
		v41 = Rotl32((v41 ^ v5), 8)
		v29 = v29 + v41
		v17 = Rotl32((v17 ^ v29), 7)
		v8 = v8 + v20
		v44 = Rotl32((v44 ^ v8), 16)
		v32 = v32 + v44
		v20 = Rotl32((v20 ^ v32), 12)
		v8 = v8 + v20
		v44 = Rotl32((v44 ^ v8), 8)
		v32 = v32 + v44
		v20 = Rotl32((v20 ^ v32), 7)
		v11 = v11 + v23
		v47 = Rotl32((v47 ^ v11), 16)
		v35 = v35 + v47
		v23 = Rotl32((v23 ^ v35), 12)
		v11 = v11 + v23
		v47 = Rotl32((v47 ^ v11), 8)
		v35 = v35 + v47
		v23 = Rotl32((v23 ^ v35), 7)
		v2 = v2 + v17
		v47 = Rotl32((v47 ^ v2), 16)
		v32 = v32 + v47
		v17 = Rotl32((v17 ^ v32), 12)
		v2 = v2 + v17
		v47 = Rotl32((v47 ^ v2), 8)
		v32 = v32 + v47
		v17 = Rotl32((v17 ^ v32), 7)
		v5 = v5 + v20
		v38 = Rotl32((v38 ^ v5), 16)
		v35 = v35 + v38
		v20 = Rotl32((v20 ^ v35), 12)
		v5 = v5 + v20
		v38 = Rotl32((v38 ^ v5), 8)
		v35 = v35 + v38
		v20 = Rotl32((v20 ^ v35), 7)
		v8 = v8 + v23
		v41 = Rotl32((v41 ^ v8), 16)
		v26 = v26 + v41
		v23 = Rotl32((v23 ^ v26), 12)
		v8 = v8 + v23
		v41 = Rotl32((v41 ^ v8), 8)
		v26 = v26 + v41
		v23 = Rotl32((v23 ^ v26), 7)
		v11 = v11 + v14
		v44 = Rotl32((v44 ^ v11), 16)
		v29 = v29 + v44
		v14 = Rotl32((v14 ^ v29), 12)
		v11 = v11 + v14
		v44 = Rotl32((v44 ^ v11), 8)
		v29 = v29 + v44
		v14 = Rotl32((v14 ^ v29), 7)
		v50 = v50 + 1
	}
	out[0] = v2
	out[1] = v5
	out[2] = v8
	out[3] = v11
	out[4] = v14
	out[5] = v17
	out[6] = v20
	out[7] = v23
	out[8] = v26
	out[9] = v29
	out[10] = v32
	out[11] = v35
	out[12] = v38
	out[13] = v41
	out[14] = v44
	out[15] = v47
}

func Crypto_chacha20_h(out []byte, key []byte, in []byte) {
	var _arr_v4 [16]uint32
	v4 := _arr_v4[:]
	Load32_le_buf(v4, chacha20_constant, uint64(4))
	Load32_le_buf(v4[4:], key, uint64(8))
	v14 := v4[12:]
	Load32_le_buf(v14, in, uint64(4))
	Chacha20_rounds(v4, v4)
	Store32_le_buf(out, v4, uint64(4))
	Store32_le_buf(out[16:], v14, uint64(4))
	for _i := range v4 { v4[_i] = 0 }
}

func Crypto_chacha20_djb(cipher_text []byte, plain_text []byte, text_size uint64, key []byte, nonce []byte, ctr uint64) uint64 {
	var v6 uint64
	var v8 uint64
	var v35 uint64
	var v41 uint64
	var v59 uint64
	var v93 uint64
	var v106 uint64
	v6 = 0
	v8 = v6
	var _arr_v12 [16]uint32
	v12 := _arr_v12[:]
	Load32_le_buf(v12, chacha20_constant, uint64(4))
	Load32_le_buf(v12[4:], key, uint64(8))
	Load32_le_buf(v12[14:], nonce, uint64(2))
	v12[12] = uint32(ctr)
	v12[13] = uint32(ctr >> 32)
	var _arr_v31 [16]uint32
	v31 := _arr_v31[:]
	v34 := text_size >> 6
	v35 = 0
	for v35 < v34 {
		Chacha20_rounds(v31, v12)
		if plain_text != nil {
			v41 = 0
			for v41 < 16 {
				Store32_le(cipher_text[int(v6):], v31[int(v41)] + v12[int(v41)] ^ Load32_le(plain_text[int(v8):]))
				v6 = v6 + 4
				v8 = v8 + 4
				v41 = v41 + 1
			}
		} else {
			v59 = 0
			for v59 < 16 {
				Store32_le(cipher_text[int(v6):], v31[int(v59)] + v12[int(v59)])
				v6 = v6 + 4
				v59 = v59 + 1
			}
		}
		v12[12] = v12[12] + uint32(1)
		if v12[12] == uint32(0) {
			v12[13] = v12[13] + uint32(1)
		}
		v35 = v35 + 1
	}
	text_size = text_size & 63
	if text_size > 0 {
		if plain_text == nil {
			plain_text = zero
		}
		Chacha20_rounds(v31, v12)
		var _arr_v92 [64]uint8
		v92 := _arr_v92[:]
		v93 = 0
		for v93 < 16 {
			Store32_le(v92[int(v93 * 4):], v31[int(v93)] + v12[int(v93)])
			v93 = v93 + 1
		}
		v106 = 0
		for v106 < text_size {
			cipher_text[int(v6 + v106)] = v92[int(v106)] ^ plain_text[int(uint64(0) + v106)]
			v106 = v106 + 1
		}
		for _i := range v92 { v92[_i] = 0 }
	}
	ctr = uint64(int(v12[12] + uint32(uint64(v12[13]) << 32)) + func() int { if text_size > 0 { return 1 }; return 0 }())
	for _i := range v31 { v31[_i] = 0 }
	for _i := range v12 { v12[_i] = 0 }
	return ctr
}

func Crypto_chacha20_ietf(cipher_text []byte, plain_text []byte, text_size uint64, key []byte, nonce []byte, ctr uint32) uint32 {
	return uint32(Crypto_chacha20_djb(cipher_text, plain_text, text_size, key, nonce[4:], uint64(ctr + uint32(uint64(Load32_le(nonce)) << 32))))
}

func Crypto_chacha20_x(cipher_text []byte, plain_text []byte, text_size uint64, key []byte, nonce []byte, ctr uint64) uint64 {
	var _arr_v6 [32]uint8
	v6 := _arr_v6[:]
	Crypto_chacha20_h(v6, key, nonce)
	ctr = Crypto_chacha20_djb(cipher_text, plain_text, text_size, v6, nonce[16:], ctr)
	for _i := range v6 { v6[_i] = 0 }
	return ctr
}

func Poly_blocks(ctx *Crypto_poly1305_ctx, in []byte, nb_blocks uint64, end uint32) {
	var v4 uint64
	var v42 uint32
	var v46 uint32
	var v50 uint32
	var v54 uint32
	var v58 uint32
	var v62 uint64
	v4 = 0
	v9 := ctx.R[0]
	v13 := ctx.R[1]
	v17 := ctx.R[2]
	v21 := ctx.R[3]
	v27 := uint32(uint64(v13) >> 2 + uint64(v13))
	v31 := uint32(uint64(v17) >> 2 + uint64(v17))
	v35 := uint32(uint64(v21) >> 2 + uint64(v21))
	v42 = ctx.H[0]
	v46 = ctx.H[1]
	v50 = ctx.H[2]
	v54 = ctx.H[3]
	v58 = ctx.H[4]
	v62 = 0
	for v62 < nb_blocks {
		v70 := uint64(v42) + uint64(Load32_le(in[int(v4):]))
		v4 = v4 + 4
		v77 := uint64(v46) + uint64(Load32_le(in[int(v4):]))
		v4 = v4 + 4
		v84 := uint64(v50) + uint64(Load32_le(in[int(v4):]))
		v4 = v4 + 4
		v91 := uint64(v54) + uint64(Load32_le(in[int(v4):]))
		v4 = v4 + 4
		v95 := v58 + end
		v105 := ((((v70 * uint64(v9)) + (v77 * uint64(v35))) + (v84 * uint64(v31))) + (v91 * uint64(v27))) + uint64(v95 * uint32(uint64(v9) >> 2 * uint64(5)))
		v115 := ((((v70 * uint64(v13)) + (v77 * uint64(v9))) + (v84 * uint64(v35))) + (v91 * uint64(v31))) + uint64(v95 * v27)
		v125 := ((((v70 * uint64(v17)) + (v77 * uint64(v13))) + (v84 * uint64(v9))) + (v91 * uint64(v35))) + uint64(v95 * v31)
		v135 := ((((v70 * uint64(v21)) + (v77 * uint64(v17))) + (v84 * uint64(v13))) + (v91 * uint64(v9))) + uint64(v95 * v35)
		v141 := (v95 * (v9 & uint32(3))) + uint32(v135 >> 32)
		v149 := uint64(v141) >> 2 * uint64(5) + (v105 & uint64(0xffffffff))
		v158 := ((v149 >> 32) + (v115 & uint64(0xffffffff))) + (v105 >> 32)
		v167 := ((v158 >> 32) + (v125 & uint64(0xffffffff))) + (v115 >> 32)
		v176 := ((v167 >> 32) + (v135 & uint64(0xffffffff))) + (v125 >> 32)
		v42 = uint32(v149 & 0xffffffff)
		v46 = uint32(v158 & uint64(0xffffffff))
		v50 = uint32(v167 & uint64(0xffffffff))
		v54 = uint32(v176 & uint64(0xffffffff))
		v58 = uint32((v176 >> 32) + uint64(v141 & 3))
		v62 = v62 + 1
	}
	ctx.H[0] = v42
	ctx.H[1] = v46
	ctx.H[2] = v50
	ctx.H[3] = v54
	ctx.H[4] = v58
}

func Crypto_poly1305_init(ctx *Crypto_poly1305_ctx, key []byte) {
	var v2 uint64
	var v19 uint64
	var v29 uint64
	v2 = 0
	for v2 < 5 {
		ctx.H[int(v2)] = uint32(0)
		v2 = v2 + 1
	}
	ctx.C_idx = uint64(0)
	Load32_le_buf(ctx.R[:], key, uint64(4))
	Load32_le_buf(ctx.Pad[:], key[16:], uint64(4))
	v19 = 0
	for v19 < 1 {
		ctx.R[int(v19)] = ctx.R[int(v19)] & uint32(0xfffffff)
		v19 = v19 + 1
	}
	v29 = 1
	for v29 < 4 {
		ctx.R[int(v29)] = ctx.R[int(v29)] & uint32(0xffffffc)
		v29 = v29 + 1
	}
}

func Crypto_poly1305_update(ctx *Crypto_poly1305_ctx, message []byte, message_size uint64) {
	var v3 uint64
	var v15 uint64
	var v47 uint64
	v3 = 0
	if message_size == 0 {
		return
	}
	v14 := func() uint64 { if (func() int { if Gap(ctx.C_idx, uint64(16)) <= message_size { return 1 }; return 0 }()) != 0 { return Gap(ctx.C_idx, uint64(16)) }; return message_size }()
	v15 = 0
	for v15 < v14 {
		ctx.C[int(ctx.C_idx)] = uint8(uint32(message[0]))
		ctx.C_idx = ctx.C_idx + uint64(1)
		message_size = message_size - 1
		v15 = v15 + 1
	}
	if ctx.C_idx == uint64(16) {
		Poly_blocks(ctx, ctx.C[:], uint64(1), uint32(1))
		ctx.C_idx = uint64(0)
	}
	v38 := message_size >> 4
	Poly_blocks(ctx, message[int(v3):], v38, uint32(1))
	v3 = v3 + (v38 << 4)
	message_size = message_size & 15
	v47 = 0
	for v47 < message_size {
		ctx.C[int(ctx.C_idx)] = message[int(v3 + v47)]
		ctx.C_idx = ctx.C_idx + uint64(1)
		v47 = v47 + 1
	}
}

func Crypto_poly1305_final(ctx *Crypto_poly1305_ctx, mac []byte) {
	var v4 uint64
	var v23 uint64
	var v25 uint64
	var v43 uint64
	if ctx.C_idx != uint64(0) {
		v4 = 0
		for v4 < uint64(16 - int(ctx.C_idx)) {
			ctx.C[int(ctx.C_idx + v4)] = uint8(0)
			v4 = v4 + 1
		}
		ctx.C[int(ctx.C_idx)] = uint8(1)
		Poly_blocks(ctx, ctx.C[:], uint64(1), uint32(0))
	}
	v23 = 5
	v25 = 0
	for v25 < 4 {
		v23 = v23 + uint64(ctx.H[int(v25)])
		v23 = v23 >> 32
		v25 = v25 + 1
	}
	v23 = v23 + uint64(ctx.H[4])
	v23 = (v23 >> 2) * 5
	v43 = 0
	for v43 < 4 {
		v23 = v23 + uint64(ctx.H[int(v43)]) + uint64(ctx.Pad[int(v43)])
		Store32_le(mac[int(v43 * 4):], uint32(v23))
		v23 = v23 >> 32
		v43 = v43 + 1
	}
	_ = ctx // wipe skipped struct
}

func Crypto_poly1305(mac []byte, message []byte, message_size uint64, key []byte) {
	var v4 Crypto_poly1305_ctx
	Crypto_poly1305_init(&v4, key)
	Crypto_poly1305_update(&v4, message, message_size)
	Crypto_poly1305_final(&v4, mac)
}

func Crypto_blake2b_init(ctx *Crypto_blake2b_ctx, hash_size uint64) {
	Crypto_blake2b_keyed_init(ctx, hash_size, uint64(0), uint64(0))
}

func Crypto_blake2b_final(ctx *Crypto_blake2b_ctx, hash []byte) {
	var v16 uint64
	Blake2b_compress(ctx, 1)
	v10 := func() uint64 { if (func() int { if ctx.Hash_size <= uint64(64) { return 1 }; return 0 }()) != 0 { return ctx.Hash_size }; return uint64(64) }()
	v13 := v10 >> 3
	Store64_le_buf(hash, ctx.Hash[:], v13)
	v16 = v13 << 3
	for v16 < v10 {
		hash[int(v16)] = uint8(ctx.Hash[int(v16 >> 3)] >> uint8(8 * int(v16 & 7)) & uint64(0xff))
		v16 = v16 + 1
	}
	_ = ctx // wipe skipped struct
}

func Crypto_blake2b_keyed(hash []byte, hash_size uint64, key []byte, key_size uint64, message []byte, message_size uint64) {
	var v6 Crypto_blake2b_ctx
	Crypto_blake2b_keyed_init(&v6, hash_size, key, key_size)
	Crypto_blake2b_update(&v6, message, message_size)
	Crypto_blake2b_final(&v6, hash)
}

func Crypto_blake2b(hash []byte, hash_size uint64, msg []byte, msg_size uint64) {
	Crypto_blake2b_keyed(hash, hash_size, nil, uint64(0), msg, msg_size)
}

func Blake_update_32(ctx *Crypto_blake2b_ctx, input uint32) {
	var _arr_v2 [4]uint8
	v2 := _arr_v2[:]
	Store32_le(v2, input)
	Crypto_blake2b_update(ctx, v2, uint32(4))
	for _i := range v2 { v2[_i] = 0 }
}

func Blake_update_32_buf(ctx *Crypto_blake2b_ctx, buf []byte, size uint32) {
	Blake_update_32(ctx, size)
	Crypto_blake2b_update(ctx, buf, size)
}

func Copy_block(o *Blk, in *Blk) {
	var v2 uint64
	v2 = 0
	for v2 < 0x80 {
		o.A[int(v2)] = in.A[int(v2)]
		v2 = v2 + 1
	}
}

func Xor_block(o *Blk, in *Blk) {
	var v2 uint64
	v2 = 0
	for v2 < 0x80 {
		o.A[int(v2)] = o.A[int(v2)] ^ in.A[int(v2)]
		v2 = v2 + 1
	}
}

func G_rounds(b *Blk) {
	var v1 int
	var v1542 int
	v1 = 0
	for v1 < 128 {
		v8 := v1 + 4
		b.A[v1] = b.A[v1] + b.A[v8] + uint64(uint32(b.A[v1])) * uint64(uint32(b.A[v8])) << 1
		v32 := v1 + 12
		b.A[v32] = b.A[v32] ^ b.A[v1]
		b.A[v32] = Rotr64(b.A[v32], uint64(32))
		v53 := v1 + 8
		b.A[v53] = b.A[v53] + b.A[v32] + uint64(uint32(b.A[v53])) * uint64(uint32(b.A[v32])) << 1
		b.A[v8] = b.A[v8] ^ b.A[v53]
		b.A[v8] = Rotr64(b.A[v8], uint64(24))
		b.A[v1] = b.A[v1] + b.A[v8] + uint64(uint32(b.A[v1])) * uint64(uint32(b.A[v8])) << 1
		b.A[v32] = b.A[v32] ^ b.A[v1]
		b.A[v32] = Rotr64(b.A[v32], uint64(16))
		b.A[v53] = b.A[v53] + b.A[v32] + uint64(uint32(b.A[v53])) * uint64(uint32(b.A[v32])) << 1
		b.A[v8] = b.A[v8] ^ b.A[v53]
		b.A[v8] = Rotr64(b.A[v8], uint64(63))
		v188 := v1 + 5
		v192 := v1 + 1
		b.A[v192] = b.A[v192] + b.A[v188] + uint64(uint32(b.A[v192])) * uint64(uint32(b.A[v188])) << 1
		v220 := v1 + 13
		b.A[v220] = b.A[v220] ^ b.A[v192]
		b.A[v220] = Rotr64(b.A[v220], uint64(32))
		v241 := v1 + 9
		b.A[v241] = b.A[v241] + b.A[v220] + uint64(uint32(b.A[v241])) * uint64(uint32(b.A[v220])) << 1
		b.A[v188] = b.A[v188] ^ b.A[v241]
		b.A[v188] = Rotr64(b.A[v188], uint64(24))
		b.A[v192] = b.A[v192] + b.A[v188] + uint64(uint32(b.A[v192])) * uint64(uint32(b.A[v188])) << 1
		b.A[v220] = b.A[v220] ^ b.A[v192]
		b.A[v220] = Rotr64(b.A[v220], uint64(16))
		b.A[v241] = b.A[v241] + b.A[v220] + uint64(uint32(b.A[v241])) * uint64(uint32(b.A[v220])) << 1
		b.A[v188] = b.A[v188] ^ b.A[v241]
		b.A[v188] = Rotr64(b.A[v188], uint64(63))
		v384 := v1 + 6
		v388 := v1 + 2
		b.A[v388] = b.A[v388] + b.A[v384] + uint64(uint32(b.A[v388])) * uint64(uint32(b.A[v384])) << 1
		v416 := v1 + 14
		b.A[v416] = b.A[v416] ^ b.A[v388]
		b.A[v416] = Rotr64(b.A[v416], uint64(32))
		v437 := v1 + 10
		b.A[v437] = b.A[v437] + b.A[v416] + uint64(uint32(b.A[v437])) * uint64(uint32(b.A[v416])) << 1
		b.A[v384] = b.A[v384] ^ b.A[v437]
		b.A[v384] = Rotr64(b.A[v384], uint64(24))
		b.A[v388] = b.A[v388] + b.A[v384] + uint64(uint32(b.A[v388])) * uint64(uint32(b.A[v384])) << 1
		b.A[v416] = b.A[v416] ^ b.A[v388]
		b.A[v416] = Rotr64(b.A[v416], uint64(16))
		b.A[v437] = b.A[v437] + b.A[v416] + uint64(uint32(b.A[v437])) * uint64(uint32(b.A[v416])) << 1
		b.A[v384] = b.A[v384] ^ b.A[v437]
		b.A[v384] = Rotr64(b.A[v384], uint64(63))
		v580 := v1 + 7
		v584 := v1 + 3
		b.A[v584] = b.A[v584] + b.A[v580] + uint64(uint32(b.A[v584])) * uint64(uint32(b.A[v580])) << 1
		v612 := v1 + 15
		b.A[v612] = b.A[v612] ^ b.A[v584]
		b.A[v612] = Rotr64(b.A[v612], uint64(32))
		v633 := v1 + 11
		b.A[v633] = b.A[v633] + b.A[v612] + uint64(uint32(b.A[v633])) * uint64(uint32(b.A[v612])) << 1
		b.A[v580] = b.A[v580] ^ b.A[v633]
		b.A[v580] = Rotr64(b.A[v580], uint64(24))
		b.A[v584] = b.A[v584] + b.A[v580] + uint64(uint32(b.A[v584])) * uint64(uint32(b.A[v580])) << 1
		b.A[v612] = b.A[v612] ^ b.A[v584]
		b.A[v612] = Rotr64(b.A[v612], uint64(16))
		b.A[v633] = b.A[v633] + b.A[v612] + uint64(uint32(b.A[v633])) * uint64(uint32(b.A[v612])) << 1
		b.A[v580] = b.A[v580] ^ b.A[v633]
		b.A[v580] = Rotr64(b.A[v580], uint64(63))
		b.A[v1] = b.A[v1] + b.A[v188] + uint64(uint32(b.A[v1])) * uint64(uint32(b.A[v188])) << 1
		b.A[v612] = b.A[v612] ^ b.A[v1]
		b.A[v612] = Rotr64(b.A[v612], uint64(32))
		b.A[v437] = b.A[v437] + b.A[v612] + uint64(uint32(b.A[v437])) * uint64(uint32(b.A[v612])) << 1
		b.A[v188] = b.A[v188] ^ b.A[v437]
		b.A[v188] = Rotr64(b.A[v188], uint64(24))
		b.A[v1] = b.A[v1] + b.A[v188] + uint64(uint32(b.A[v1])) * uint64(uint32(b.A[v188])) << 1
		b.A[v612] = b.A[v612] ^ b.A[v1]
		b.A[v612] = Rotr64(b.A[v612], uint64(16))
		b.A[v437] = b.A[v437] + b.A[v612] + uint64(uint32(b.A[v437])) * uint64(uint32(b.A[v612])) << 1
		b.A[v188] = b.A[v188] ^ b.A[v437]
		b.A[v188] = Rotr64(b.A[v188], uint64(63))
		b.A[v192] = b.A[v192] + b.A[v384] + uint64(uint32(b.A[v192])) * uint64(uint32(b.A[v384])) << 1
		b.A[v32] = b.A[v32] ^ b.A[v192]
		b.A[v32] = Rotr64(b.A[v32], uint64(32))
		b.A[v633] = b.A[v633] + b.A[v32] + uint64(uint32(b.A[v633])) * uint64(uint32(b.A[v32])) << 1
		b.A[v384] = b.A[v384] ^ b.A[v633]
		b.A[v384] = Rotr64(b.A[v384], uint64(24))
		b.A[v192] = b.A[v192] + b.A[v384] + uint64(uint32(b.A[v192])) * uint64(uint32(b.A[v384])) << 1
		b.A[v32] = b.A[v32] ^ b.A[v192]
		b.A[v32] = Rotr64(b.A[v32], uint64(16))
		b.A[v633] = b.A[v633] + b.A[v32] + uint64(uint32(b.A[v633])) * uint64(uint32(b.A[v32])) << 1
		b.A[v384] = b.A[v384] ^ b.A[v633]
		b.A[v384] = Rotr64(b.A[v384], uint64(63))
		b.A[v388] = b.A[v388] + b.A[v580] + uint64(uint32(b.A[v388])) * uint64(uint32(b.A[v580])) << 1
		b.A[v220] = b.A[v220] ^ b.A[v388]
		b.A[v220] = Rotr64(b.A[v220], uint64(32))
		b.A[v53] = b.A[v53] + b.A[v220] + uint64(uint32(b.A[v53])) * uint64(uint32(b.A[v220])) << 1
		b.A[v580] = b.A[v580] ^ b.A[v53]
		b.A[v580] = Rotr64(b.A[v580], uint64(24))
		b.A[v388] = b.A[v388] + b.A[v580] + uint64(uint32(b.A[v388])) * uint64(uint32(b.A[v580])) << 1
		b.A[v220] = b.A[v220] ^ b.A[v388]
		b.A[v220] = Rotr64(b.A[v220], uint64(16))
		b.A[v53] = b.A[v53] + b.A[v220] + uint64(uint32(b.A[v53])) * uint64(uint32(b.A[v220])) << 1
		b.A[v580] = b.A[v580] ^ b.A[v53]
		b.A[v580] = Rotr64(b.A[v580], uint64(63))
		b.A[v584] = b.A[v584] + b.A[v8] + uint64(uint32(b.A[v584])) * uint64(uint32(b.A[v8])) << 1
		b.A[v416] = b.A[v416] ^ b.A[v584]
		b.A[v416] = Rotr64(b.A[v416], uint64(32))
		b.A[v241] = b.A[v241] + b.A[v416] + uint64(uint32(b.A[v241])) * uint64(uint32(b.A[v416])) << 1
		b.A[v8] = b.A[v8] ^ b.A[v241]
		b.A[v8] = Rotr64(b.A[v8], uint64(24))
		b.A[v584] = b.A[v584] + b.A[v8] + uint64(uint32(b.A[v584])) * uint64(uint32(b.A[v8])) << 1
		b.A[v416] = b.A[v416] ^ b.A[v584]
		b.A[v416] = Rotr64(b.A[v416], uint64(16))
		b.A[v241] = b.A[v241] + b.A[v416] + uint64(uint32(b.A[v241])) * uint64(uint32(b.A[v416])) << 1
		b.A[v8] = b.A[v8] ^ b.A[v241]
		b.A[v8] = Rotr64(b.A[v8], uint64(63))
		v1 = v1 + 16
	}
	v1542 = 0
	for v1542 < 16 {
		v1549 := v1542 + 32
		b.A[v1542] = b.A[v1542] + b.A[v1549] + uint64(uint32(b.A[v1542])) * uint64(uint32(b.A[v1549])) << 1
		v1573 := v1542 + 96
		b.A[v1573] = b.A[v1573] ^ b.A[v1542]
		b.A[v1573] = Rotr64(b.A[v1573], uint64(32))
		v1594 := v1542 + 64
		b.A[v1594] = b.A[v1594] + b.A[v1573] + uint64(uint32(b.A[v1594])) * uint64(uint32(b.A[v1573])) << 1
		b.A[v1549] = b.A[v1549] ^ b.A[v1594]
		b.A[v1549] = Rotr64(b.A[v1549], uint64(24))
		b.A[v1542] = b.A[v1542] + b.A[v1549] + uint64(uint32(b.A[v1542])) * uint64(uint32(b.A[v1549])) << 1
		b.A[v1573] = b.A[v1573] ^ b.A[v1542]
		b.A[v1573] = Rotr64(b.A[v1573], uint64(16))
		b.A[v1594] = b.A[v1594] + b.A[v1573] + uint64(uint32(b.A[v1594])) * uint64(uint32(b.A[v1573])) << 1
		b.A[v1549] = b.A[v1549] ^ b.A[v1594]
		b.A[v1549] = Rotr64(b.A[v1549], uint64(63))
		v1729 := v1542 + 33
		v1733 := v1542 + 1
		b.A[v1733] = b.A[v1733] + b.A[v1729] + uint64(uint32(b.A[v1733])) * uint64(uint32(b.A[v1729])) << 1
		v1761 := v1542 + 97
		b.A[v1761] = b.A[v1761] ^ b.A[v1733]
		b.A[v1761] = Rotr64(b.A[v1761], uint64(32))
		v1782 := v1542 + 65
		b.A[v1782] = b.A[v1782] + b.A[v1761] + uint64(uint32(b.A[v1782])) * uint64(uint32(b.A[v1761])) << 1
		b.A[v1729] = b.A[v1729] ^ b.A[v1782]
		b.A[v1729] = Rotr64(b.A[v1729], uint64(24))
		b.A[v1733] = b.A[v1733] + b.A[v1729] + uint64(uint32(b.A[v1733])) * uint64(uint32(b.A[v1729])) << 1
		b.A[v1761] = b.A[v1761] ^ b.A[v1733]
		b.A[v1761] = Rotr64(b.A[v1761], uint64(16))
		b.A[v1782] = b.A[v1782] + b.A[v1761] + uint64(uint32(b.A[v1782])) * uint64(uint32(b.A[v1761])) << 1
		b.A[v1729] = b.A[v1729] ^ b.A[v1782]
		b.A[v1729] = Rotr64(b.A[v1729], uint64(63))
		v1925 := v1542 + 48
		v1929 := v1542 + 16
		b.A[v1929] = b.A[v1929] + b.A[v1925] + uint64(uint32(b.A[v1929])) * uint64(uint32(b.A[v1925])) << 1
		v1957 := v1542 + 112
		b.A[v1957] = b.A[v1957] ^ b.A[v1929]
		b.A[v1957] = Rotr64(b.A[v1957], uint64(32))
		v1978 := v1542 + 80
		b.A[v1978] = b.A[v1978] + b.A[v1957] + uint64(uint32(b.A[v1978])) * uint64(uint32(b.A[v1957])) << 1
		b.A[v1925] = b.A[v1925] ^ b.A[v1978]
		b.A[v1925] = Rotr64(b.A[v1925], uint64(24))
		b.A[v1929] = b.A[v1929] + b.A[v1925] + uint64(uint32(b.A[v1929])) * uint64(uint32(b.A[v1925])) << 1
		b.A[v1957] = b.A[v1957] ^ b.A[v1929]
		b.A[v1957] = Rotr64(b.A[v1957], uint64(16))
		b.A[v1978] = b.A[v1978] + b.A[v1957] + uint64(uint32(b.A[v1978])) * uint64(uint32(b.A[v1957])) << 1
		b.A[v1925] = b.A[v1925] ^ b.A[v1978]
		b.A[v1925] = Rotr64(b.A[v1925], uint64(63))
		v2121 := v1542 + 49
		v2125 := v1542 + 17
		b.A[v2125] = b.A[v2125] + b.A[v2121] + uint64(uint32(b.A[v2125])) * uint64(uint32(b.A[v2121])) << 1
		v2153 := v1542 + 113
		b.A[v2153] = b.A[v2153] ^ b.A[v2125]
		b.A[v2153] = Rotr64(b.A[v2153], uint64(32))
		v2174 := v1542 + 81
		b.A[v2174] = b.A[v2174] + b.A[v2153] + uint64(uint32(b.A[v2174])) * uint64(uint32(b.A[v2153])) << 1
		b.A[v2121] = b.A[v2121] ^ b.A[v2174]
		b.A[v2121] = Rotr64(b.A[v2121], uint64(24))
		b.A[v2125] = b.A[v2125] + b.A[v2121] + uint64(uint32(b.A[v2125])) * uint64(uint32(b.A[v2121])) << 1
		b.A[v2153] = b.A[v2153] ^ b.A[v2125]
		b.A[v2153] = Rotr64(b.A[v2153], uint64(16))
		b.A[v2174] = b.A[v2174] + b.A[v2153] + uint64(uint32(b.A[v2174])) * uint64(uint32(b.A[v2153])) << 1
		b.A[v2121] = b.A[v2121] ^ b.A[v2174]
		b.A[v2121] = Rotr64(b.A[v2121], uint64(63))
		b.A[v1542] = b.A[v1542] + b.A[v1729] + uint64(uint32(b.A[v1542])) * uint64(uint32(b.A[v1729])) << 1
		b.A[v2153] = b.A[v2153] ^ b.A[v1542]
		b.A[v2153] = Rotr64(b.A[v2153], uint64(32))
		b.A[v1978] = b.A[v1978] + b.A[v2153] + uint64(uint32(b.A[v1978])) * uint64(uint32(b.A[v2153])) << 1
		b.A[v1729] = b.A[v1729] ^ b.A[v1978]
		b.A[v1729] = Rotr64(b.A[v1729], uint64(24))
		b.A[v1542] = b.A[v1542] + b.A[v1729] + uint64(uint32(b.A[v1542])) * uint64(uint32(b.A[v1729])) << 1
		b.A[v2153] = b.A[v2153] ^ b.A[v1542]
		b.A[v2153] = Rotr64(b.A[v2153], uint64(16))
		b.A[v1978] = b.A[v1978] + b.A[v2153] + uint64(uint32(b.A[v1978])) * uint64(uint32(b.A[v2153])) << 1
		b.A[v1729] = b.A[v1729] ^ b.A[v1978]
		b.A[v1729] = Rotr64(b.A[v1729], uint64(63))
		b.A[v1733] = b.A[v1733] + b.A[v1925] + uint64(uint32(b.A[v1733])) * uint64(uint32(b.A[v1925])) << 1
		b.A[v1573] = b.A[v1573] ^ b.A[v1733]
		b.A[v1573] = Rotr64(b.A[v1573], uint64(32))
		b.A[v2174] = b.A[v2174] + b.A[v1573] + uint64(uint32(b.A[v2174])) * uint64(uint32(b.A[v1573])) << 1
		b.A[v1925] = b.A[v1925] ^ b.A[v2174]
		b.A[v1925] = Rotr64(b.A[v1925], uint64(24))
		b.A[v1733] = b.A[v1733] + b.A[v1925] + uint64(uint32(b.A[v1733])) * uint64(uint32(b.A[v1925])) << 1
		b.A[v1573] = b.A[v1573] ^ b.A[v1733]
		b.A[v1573] = Rotr64(b.A[v1573], uint64(16))
		b.A[v2174] = b.A[v2174] + b.A[v1573] + uint64(uint32(b.A[v2174])) * uint64(uint32(b.A[v1573])) << 1
		b.A[v1925] = b.A[v1925] ^ b.A[v2174]
		b.A[v1925] = Rotr64(b.A[v1925], uint64(63))
		b.A[v1929] = b.A[v1929] + b.A[v2121] + uint64(uint32(b.A[v1929])) * uint64(uint32(b.A[v2121])) << 1
		b.A[v1761] = b.A[v1761] ^ b.A[v1929]
		b.A[v1761] = Rotr64(b.A[v1761], uint64(32))
		b.A[v1594] = b.A[v1594] + b.A[v1761] + uint64(uint32(b.A[v1594])) * uint64(uint32(b.A[v1761])) << 1
		b.A[v2121] = b.A[v2121] ^ b.A[v1594]
		b.A[v2121] = Rotr64(b.A[v2121], uint64(24))
		b.A[v1929] = b.A[v1929] + b.A[v2121] + uint64(uint32(b.A[v1929])) * uint64(uint32(b.A[v2121])) << 1
		b.A[v1761] = b.A[v1761] ^ b.A[v1929]
		b.A[v1761] = Rotr64(b.A[v1761], uint64(16))
		b.A[v1594] = b.A[v1594] + b.A[v1761] + uint64(uint32(b.A[v1594])) * uint64(uint32(b.A[v1761])) << 1
		b.A[v2121] = b.A[v2121] ^ b.A[v1594]
		b.A[v2121] = Rotr64(b.A[v2121], uint64(63))
		b.A[v2125] = b.A[v2125] + b.A[v1549] + uint64(uint32(b.A[v2125])) * uint64(uint32(b.A[v1549])) << 1
		b.A[v1957] = b.A[v1957] ^ b.A[v2125]
		b.A[v1957] = Rotr64(b.A[v1957], uint64(32))
		b.A[v1782] = b.A[v1782] + b.A[v1957] + uint64(uint32(b.A[v1782])) * uint64(uint32(b.A[v1957])) << 1
		b.A[v1549] = b.A[v1549] ^ b.A[v1782]
		b.A[v1549] = Rotr64(b.A[v1549], uint64(24))
		b.A[v2125] = b.A[v2125] + b.A[v1549] + uint64(uint32(b.A[v2125])) * uint64(uint32(b.A[v1549])) << 1
		b.A[v1957] = b.A[v1957] ^ b.A[v2125]
		b.A[v1957] = Rotr64(b.A[v1957], uint64(16))
		b.A[v1782] = b.A[v1782] + b.A[v1957] + uint64(uint32(b.A[v1782])) * uint64(uint32(b.A[v1957])) << 1
		b.A[v1549] = b.A[v1549] ^ b.A[v1782]
		b.A[v1549] = Rotr64(b.A[v1549], uint64(63))
		v1542 = v1542 + 2
	}
}

func Fe_0(h []int) {
	var v1 uint64
	v1 = 0
	for v1 < 10 {
		h[int(v1)] = 0
		v1 = v1 + 1
	}
}

func Fe_1(h []int) {
	var v3 uint64
	h[0] = 1
	v3 = 0
	for v3 < 9 {
		h[int(1 + int(v3))] = 0
		v3 = v3 + 1
	}
}

func Fe_copy(h []int, f []int) {
	var v2 uint64
	v2 = 0
	for v2 < 10 {
		h[int(v2)] = f[int(v2)]
		v2 = v2 + 1
	}
}

func Fe_neg(h []int, f []int) {
	var v2 uint64
	v2 = 0
	for v2 < 10 {
		h[int(v2)] = -int(f[int(v2)])
		v2 = v2 + 1
	}
}

func Fe_add(h []int, f []int, g []int) {
	var v3 uint64
	v3 = 0
	for v3 < 10 {
		h[int(v3)] = f[int(v3)] + g[int(v3)]
		v3 = v3 + 1
	}
}

func Fe_sub(h []int, f []int, g []int) {
	var v3 uint64
	v3 = 0
	for v3 < 10 {
		h[int(v3)] = f[int(v3)] - g[int(v3)]
		v3 = v3 + 1
	}
}

func Fe_cswap(f []int, g []int, b int) {
	var v6 uint64
	v6 = 0
	for v6 < 10 {
		v12 := f[int(v6)]
		v13 := g[int(v6)]
		v15 := (v12 ^ v13) & -b
		f[int(v6)] = v12 ^ v15
		g[int(v6)] = v13 ^ v15
		v6 = v6 + 1
	}
}

func Fe_ccopy(f []int, g []int, b int) {
	var v6 uint64
	v6 = 0
	for v6 < 10 {
		f[int(v6)] = f[int(v6)] ^ ((f[int(v6)] ^ g[int(v6)]) & -b)
		v6 = v6 + 1
	}
}

func Fe_frombytes_mask(h []int, s []byte, nb_mask uint32) {
	var v6 uint64
	var v8 uint64
	var v15 uint64
	var v22 uint64
	var v29 uint64
	var v36 uint64
	var v41 uint64
	var v48 uint64
	var v55 uint64
	var v62 uint64
	var v70 uint64
	v6 = uint64(Load32_le(s))
	v8 = uint64(Load24_le(s[4:]) << 6)
	v15 = uint64(Load24_le(s[7:]) << 5)
	v22 = uint64(Load24_le(s[10:]) << 3)
	v29 = uint64(Load24_le(s[13:]) << 2)
	v36 = uint64(Load32_le(s[16:]))
	v41 = uint64(Load24_le(s[20:]) << 7)
	v48 = uint64(Load24_le(s[23:]) << 5)
	v55 = uint64(Load24_le(s[26:]) << 4)
	v62 = uint64(Load24_le(s[29:]) & uint32(0xffffff) >> uint8(nb_mask) << 2)
	v72 := uint64(1)
	v74 := v72 << 25
	v70 = (v6 + v74) >> 26
	v81 := v72 << 26
	v6 = v6 - (v70 * v81)
	v8 = v8 + v70
	v70 = (v29 + v74) >> 26
	v29 = v29 - (v70 * v81)
	v36 = v36 + v70
	v102 := v72 << 24
	v70 = (v8 + v102) >> 25
	v8 = v8 - (v70 * v74)
	v15 = v15 + v70
	v70 = (v36 + v102) >> 25
	v36 = v36 - (v70 * v74)
	v41 = v41 + v70
	v70 = (v15 + v74) >> 26
	v15 = v15 - (v70 * v81)
	v22 = v22 + v70
	v70 = (v41 + v74) >> 26
	v41 = v41 - (v70 * v81)
	v48 = v48 + v70
	v70 = (v22 + v102) >> 25
	v22 = v22 - (v70 * v74)
	v29 = v29 + v70
	v70 = (v48 + v102) >> 25
	v48 = v48 - (v70 * v74)
	v55 = v55 + v70
	v70 = (v29 + v74) >> 26
	v29 = v29 - (v70 * v81)
	v36 = v36 + v70
	v70 = (v55 + v74) >> 26
	v55 = v55 - (v70 * v81)
	v62 = v62 + v70
	v70 = (v62 + v102) >> 25
	v62 = v62 - (v70 * v74)
	v6 = v6 + (v70 * 19)
	v70 = (v6 + v74) >> 26
	v6 = v6 - (v70 * v81)
	v8 = v8 + v70
	h[0] = int(v6)
	h[1] = int(v8)
	h[2] = int(v15)
	h[3] = int(v22)
	h[4] = int(v29)
	h[5] = int(v36)
	h[6] = int(v41)
	h[7] = int(v48)
	h[8] = int(v55)
	h[9] = int(v62)
}

func Fe_frombytes(h []int, s []byte) {
	Fe_frombytes_mask(h, s, uint32(1))
}

func Fe_tobytes(s []byte, h []int) {
	var v3 uint64
	var v9 int
	var v21 uint64
	var v42 uint64
	var _arr_v2 [10]int
	v2 := _arr_v2[:]
	v3 = 0
	for v3 < 10 {
		v2[int(v3)] = h[int(v3)]
		v3 = v3 + 1
	}
	v9 = ((19 * v2[9]) + (1 << 24)) >> 25
	v21 = 0
	for v21 < 5 {
		v27 := 2 * int(v21)
		v9 = v9 + v2[int(v27)]
		v9 = v9 >> 26
		v9 = v9 + v2[int(v27 + 1)]
		v9 = v9 >> 25
		v21 = v21 + 1
	}
	v9 = v9 * 19
	v42 = 0
	for v42 < 5 {
		v48 := v42 * 2
		v2[int(v48)] = v2[int(v48)] + v9
		v55 := v2[int(v48)]
		v9 = v55 >> 26
		v59 := 1
		v2[int(v48)] = v55 - (v9 * (v59 << 26))
		v72 := v48 + uint64(1)
		v2[int(v72)] = v2[int(v72)] + v9
		v83 := v2[int(v72)]
		v9 = v83 >> 25
		v2[int(v72)] = v83 - (v9 * (v59 << 25))
		v42 = v42 + 1
	}
	v111 := uint32(v2[1])
	Store32_le(s, uint32(v2[0]) >> 0 | (v111 << 26))
	v126 := uint32(v2[2])
	Store32_le(s[4:], ((v111 >> 6) | (v126 << 19)))
	v141 := uint32(v2[3])
	Store32_le(s[8:], ((v126 >> 13) | (v141 << 13)))
	Store32_le(s[12:], ((v141 >> 19) | uint32(v2[4]) << 6))
	v171 := uint32(v2[6])
	Store32_le(s[16:], uint32(v2[5]) >> 0 | (v171 << 25))
	v186 := uint32(v2[7])
	Store32_le(s[20:], ((v171 >> 7) | (v186 << 19)))
	v201 := uint32(v2[8])
	Store32_le(s[24:], ((v186 >> 13) | (v201 << 12)))
	Store32_le(s[28:], ((v201 >> 20) | uint32(v2[9]) << 6))
	for _i := range v2 { v2[_i] = 0 }
}

func Fe_mul_small(h []int, f []int, g int) {
	var v3 uint64
	var v8 uint64
	var v13 uint64
	var v18 uint64
	var v23 uint64
	var v28 uint64
	var v33 uint64
	var v38 uint64
	var v43 uint64
	var v48 uint64
	var v53 uint64
	v6 := uint64(g)
	v3 = uint64(f[0] * int(v6))
	v8 = uint64(f[1] * int(v6))
	v13 = uint64(f[2] * int(v6))
	v18 = uint64(f[3] * int(v6))
	v23 = uint64(f[4] * int(v6))
	v28 = uint64(f[5] * int(v6))
	v33 = uint64(f[6] * int(v6))
	v38 = uint64(f[7] * int(v6))
	v43 = uint64(f[8] * int(v6))
	v48 = uint64(f[9] * int(v6))
	v55 := uint64(1)
	v57 := v55 << 25
	v53 = (v3 + v57) >> 26
	v64 := v55 << 26
	v3 = v3 - (v53 * v64)
	v8 = v8 + v53
	v53 = (v23 + v57) >> 26
	v23 = v23 - (v53 * v64)
	v28 = v28 + v53
	v85 := v55 << 24
	v53 = (v8 + v85) >> 25
	v8 = v8 - (v53 * v57)
	v13 = v13 + v53
	v53 = (v28 + v85) >> 25
	v28 = v28 - (v53 * v57)
	v33 = v33 + v53
	v53 = (v13 + v57) >> 26
	v13 = v13 - (v53 * v64)
	v18 = v18 + v53
	v53 = (v33 + v57) >> 26
	v33 = v33 - (v53 * v64)
	v38 = v38 + v53
	v53 = (v18 + v85) >> 25
	v18 = v18 - (v53 * v57)
	v23 = v23 + v53
	v53 = (v38 + v85) >> 25
	v38 = v38 - (v53 * v57)
	v43 = v43 + v53
	v53 = (v23 + v57) >> 26
	v23 = v23 - (v53 * v64)
	v28 = v28 + v53
	v53 = (v43 + v57) >> 26
	v43 = v43 - (v53 * v64)
	v48 = v48 + v53
	v53 = (v48 + v85) >> 25
	v48 = v48 - (v53 * v57)
	v3 = v3 + (v53 * 19)
	v53 = (v3 + v57) >> 26
	v3 = v3 - (v53 * v64)
	v8 = v8 + v53
	h[0] = int(v3)
	h[1] = int(v8)
	h[2] = int(v13)
	h[3] = int(v18)
	h[4] = int(v23)
	h[5] = int(v28)
	h[6] = int(v33)
	h[7] = int(v38)
	h[8] = int(v43)
	h[9] = int(v48)
}

func Fe_mul(h []int, f []int, g []int) {
	var v105 uint64
	var v135 uint64
	var v165 uint64
	var v195 uint64
	var v225 uint64
	var v255 uint64
	var v285 uint64
	var v315 uint64
	var v345 uint64
	var v375 uint64
	var v405 uint64
	v5 := f[0]
	v8 := f[1]
	v11 := f[2]
	v14 := f[3]
	v17 := f[4]
	v20 := f[5]
	v23 := f[6]
	v26 := f[7]
	v29 := f[8]
	v32 := f[9]
	v38 := g[1]
	v41 := g[2]
	v44 := g[3]
	v47 := g[4]
	v50 := g[5]
	v53 := g[6]
	v56 := g[7]
	v59 := g[8]
	v62 := g[9]
	v65 := v8 * 2
	v68 := v14 * 2
	v71 := v20 * 2
	v74 := v26 * 2
	v77 := v32 * 2
	v106 := uint64(g[0])
	v108 := uint64(v62 * 19)
	v111 := uint64(v59 * 19)
	v114 := uint64(v56 * 19)
	v117 := uint64(v53 * 19)
	v120 := uint64(v50 * 19)
	v123 := uint64(v47 * 19)
	v126 := uint64(v44 * 19)
	v129 := uint64(v41 * 19)
	v105 = uint64((((((((((v5 * int(v106)) + (v65 * int(v108))) + (v11 * int(v111))) + (v68 * int(v114))) + (v17 * int(v117))) + (v71 * int(v120))) + (v23 * int(v123))) + (v74 * int(v126))) + (v29 * int(v129))) + (v77 * int(uint64(v38 * 19))))
	v136 := uint64(v38)
	v135 = uint64((((((((((v5 * int(v136)) + (v8 * int(v106))) + (v11 * int(v108))) + (v14 * int(v111))) + (v17 * int(v114))) + (v20 * int(v117))) + (v23 * int(v120))) + (v26 * int(v123))) + (v29 * int(v126))) + (v32 * int(v129)))
	v166 := uint64(v41)
	v165 = uint64((((((((((v5 * int(v166)) + (v65 * int(v136))) + (v11 * int(v106))) + (v68 * int(v108))) + (v17 * int(v111))) + (v71 * int(v114))) + (v23 * int(v117))) + (v74 * int(v120))) + (v29 * int(v123))) + (v77 * int(v126)))
	v196 := uint64(v44)
	v195 = uint64((((((((((v5 * int(v196)) + (v8 * int(v166))) + (v11 * int(v136))) + (v14 * int(v106))) + (v17 * int(v108))) + (v20 * int(v111))) + (v23 * int(v114))) + (v26 * int(v117))) + (v29 * int(v120))) + (v32 * int(v123)))
	v226 := uint64(v47)
	v225 = uint64((((((((((v5 * int(v226)) + (v65 * int(v196))) + (v11 * int(v166))) + (v68 * int(v136))) + (v17 * int(v106))) + (v71 * int(v108))) + (v23 * int(v111))) + (v74 * int(v114))) + (v29 * int(v117))) + (v77 * int(v120)))
	v256 := uint64(v50)
	v255 = uint64((((((((((v5 * int(v256)) + (v8 * int(v226))) + (v11 * int(v196))) + (v14 * int(v166))) + (v17 * int(v136))) + (v20 * int(v106))) + (v23 * int(v108))) + (v26 * int(v111))) + (v29 * int(v114))) + (v32 * int(v117)))
	v286 := uint64(v53)
	v285 = uint64((((((((((v5 * int(v286)) + (v65 * int(v256))) + (v11 * int(v226))) + (v68 * int(v196))) + (v17 * int(v166))) + (v71 * int(v136))) + (v23 * int(v106))) + (v74 * int(v108))) + (v29 * int(v111))) + (v77 * int(v114)))
	v316 := uint64(v56)
	v315 = uint64((((((((((v5 * int(v316)) + (v8 * int(v286))) + (v11 * int(v256))) + (v14 * int(v226))) + (v17 * int(v196))) + (v20 * int(v166))) + (v23 * int(v136))) + (v26 * int(v106))) + (v29 * int(v108))) + (v32 * int(v111)))
	v346 := uint64(v59)
	v345 = uint64((((((((((v5 * int(v346)) + (v65 * int(v316))) + (v11 * int(v286))) + (v68 * int(v256))) + (v17 * int(v226))) + (v71 * int(v196))) + (v23 * int(v166))) + (v74 * int(v136))) + (v29 * int(v106))) + (v77 * int(v108)))
	v375 = uint64((((((((((v5 * int(uint64(v62))) + (v8 * int(v346))) + (v11 * int(v316))) + (v14 * int(v286))) + (v17 * int(v256))) + (v20 * int(v226))) + (v23 * int(v196))) + (v26 * int(v166))) + (v29 * int(v136))) + (v32 * int(v106)))
	v407 := uint64(1)
	v409 := v407 << 25
	v405 = (v105 + v409) >> 26
	v416 := v407 << 26
	v105 = v105 - (v405 * v416)
	v135 = v135 + v405
	v405 = (v225 + v409) >> 26
	v225 = v225 - (v405 * v416)
	v255 = v255 + v405
	v437 := v407 << 24
	v405 = (v135 + v437) >> 25
	v135 = v135 - (v405 * v409)
	v165 = v165 + v405
	v405 = (v255 + v437) >> 25
	v255 = v255 - (v405 * v409)
	v285 = v285 + v405
	v405 = (v165 + v409) >> 26
	v165 = v165 - (v405 * v416)
	v195 = v195 + v405
	v405 = (v285 + v409) >> 26
	v285 = v285 - (v405 * v416)
	v315 = v315 + v405
	v405 = (v195 + v437) >> 25
	v195 = v195 - (v405 * v409)
	v225 = v225 + v405
	v405 = (v315 + v437) >> 25
	v315 = v315 - (v405 * v409)
	v345 = v345 + v405
	v405 = (v225 + v409) >> 26
	v225 = v225 - (v405 * v416)
	v255 = v255 + v405
	v405 = (v345 + v409) >> 26
	v345 = v345 - (v405 * v416)
	v375 = v375 + v405
	v405 = (v375 + v437) >> 25
	v375 = v375 - (v405 * v409)
	v105 = v105 + (v405 * 19)
	v405 = (v105 + v409) >> 26
	v105 = v105 - (v405 * v416)
	v135 = v135 + v405
	h[0] = int(v105)
	h[1] = int(v135)
	h[2] = int(v165)
	h[3] = int(v195)
	h[4] = int(v225)
	h[5] = int(v255)
	h[6] = int(v285)
	h[7] = int(v315)
	h[8] = int(v345)
	h[9] = int(v375)
}

func Fe_sq(h []int, f []int) {
	var v71 uint64
	var v89 uint64
	var v104 uint64
	var v122 uint64
	var v137 uint64
	var v155 uint64
	var v170 uint64
	var v188 uint64
	var v203 uint64
	var v221 uint64
	var v236 uint64
	v4 := f[0]
	v7 := f[1]
	v10 := f[2]
	v13 := f[3]
	v16 := f[4]
	v19 := f[5]
	v22 := f[6]
	v25 := f[7]
	v28 := f[8]
	v31 := f[9]
	v34 := v4 * 2
	v37 := v7 * 2
	v40 := v10 * 2
	v43 := v13 * 2
	v46 := v16 * 2
	v49 := v19 * 2
	v55 := v25 * 2
	v74 := uint64(v31 * 38)
	v77 := uint64(v28 * 19)
	v80 := uint64(v25 * 38)
	v83 := uint64(v22 * 19)
	v71 = uint64((((((v4 * int(uint64(v4))) + (v37 * int(v74))) + (v40 * int(v77))) + (v43 * int(v80))) + (v46 * int(v83))) + (v19 * int(uint64(v19 * 38))))
	v90 := uint64(v7)
	v89 = uint64(((((v34 * int(v90)) + (v10 * int(v74))) + (v43 * int(v77))) + (v16 * int(v80))) + (v49 * int(v83)))
	v105 := uint64(v10)
	v104 = uint64((((((v34 * int(v105)) + (v37 * int(v90))) + (v43 * int(v74))) + (v46 * int(v77))) + (v49 * int(v80))) + (v22 * int(v83)))
	v123 := uint64(v13)
	v122 = uint64(((((v34 * int(v123)) + (v37 * int(v105))) + (v16 * int(v74))) + (v49 * int(v77))) + (v22 * int(v80)))
	v138 := uint64(v16)
	v137 = uint64((((((v34 * int(v138)) + (v37 * int(uint64(v43)))) + (v10 * int(v105))) + (v49 * int(v74))) + ((v22 * 2) * int(v77))) + (v25 * int(v80)))
	v156 := uint64(v19)
	v155 = uint64(((((v34 * int(v156)) + (v37 * int(v138))) + (v40 * int(v123))) + (v22 * int(v74))) + (v55 * int(v77)))
	v171 := uint64(v22)
	v173 := uint64(v49)
	v170 = uint64((((((v34 * int(v171)) + (v37 * int(v173))) + (v40 * int(v138))) + (v43 * int(v123))) + (v55 * int(v74))) + (v28 * int(v77)))
	v189 := uint64(v25)
	v188 = uint64(((((v34 * int(v189)) + (v37 * int(v171))) + (v40 * int(v156))) + (v43 * int(v138))) + (v28 * int(v74)))
	v204 := uint64(v28)
	v203 = uint64((((((v34 * int(v204)) + (v37 * int(uint64(v55)))) + (v40 * int(v171))) + (v43 * int(v173))) + (v16 * int(v138))) + (v31 * int(v74)))
	v221 = uint64(((((v34 * int(uint64(v31))) + (v37 * int(v204))) + (v40 * int(v189))) + (v43 * int(v171))) + (v16 * int(v173)))
	v238 := uint64(1)
	v240 := v238 << 25
	v236 = (v71 + v240) >> 26
	v247 := v238 << 26
	v71 = v71 - (v236 * v247)
	v89 = v89 + v236
	v236 = (v137 + v240) >> 26
	v137 = v137 - (v236 * v247)
	v155 = v155 + v236
	v268 := v238 << 24
	v236 = (v89 + v268) >> 25
	v89 = v89 - (v236 * v240)
	v104 = v104 + v236
	v236 = (v155 + v268) >> 25
	v155 = v155 - (v236 * v240)
	v170 = v170 + v236
	v236 = (v104 + v240) >> 26
	v104 = v104 - (v236 * v247)
	v122 = v122 + v236
	v236 = (v170 + v240) >> 26
	v170 = v170 - (v236 * v247)
	v188 = v188 + v236
	v236 = (v122 + v268) >> 25
	v122 = v122 - (v236 * v240)
	v137 = v137 + v236
	v236 = (v188 + v268) >> 25
	v188 = v188 - (v236 * v240)
	v203 = v203 + v236
	v236 = (v137 + v240) >> 26
	v137 = v137 - (v236 * v247)
	v155 = v155 + v236
	v236 = (v203 + v240) >> 26
	v203 = v203 - (v236 * v247)
	v221 = v221 + v236
	v236 = (v221 + v268) >> 25
	v221 = v221 - (v236 * v240)
	v71 = v71 + (v236 * 19)
	v236 = (v71 + v240) >> 26
	v71 = v71 - (v236 * v247)
	v89 = v89 + v236
	h[0] = int(v71)
	h[1] = int(v89)
	h[2] = int(v104)
	h[3] = int(v122)
	h[4] = int(v137)
	h[5] = int(v155)
	h[6] = int(v170)
	h[7] = int(v188)
	h[8] = int(v203)
	h[9] = int(v221)
}

func Fe_isodd(f []int) int {
	var _arr_v1 [32]uint8
	v1 := _arr_v1[:]
	Fe_tobytes(v1, f)
	for _i := range v1 { v1[_i] = 0 }
	return int(v1[0] & uint8(1))
}

func Fe_isequal(f []int, g []int) int {
	var _arr_v2 [32]uint8
	v2 := _arr_v2[:]
	var _arr_v3 [32]uint8
	v3 := _arr_v3[:]
	Fe_tobytes(v2, f)
	Fe_tobytes(v3, g)
	for _i := range v2 { v2[_i] = 0 }
	for _i := range v3 { v3[_i] = 0 }
	return (1 + Crypto_verify32(v2, v3))
}

func Crypto_eddsa_trim_scalar(out []byte, in []byte) {
	var v2 uint64
	v2 = 0
	for v2 < 32 {
		out[int(v2)] = in[int(v2)]
		v2 = v2 + 1
	}
	out[0] = out[0] & uint8(0xf8)
	out[31] = out[31] & uint8(0x7f)
	out[31] = out[31] | uint8(64)
}

func Scalar_bit(s []byte, i int) int {
	if i < 0 {
		return 0
	}
	return int(uint32(s[int(i >> 3)]) >> uint8(i & 7) & uint32(1))
}

func Crypto_x25519(raw_shared_secret []byte, your_secret_key []byte, their_public_key []byte) {
	var _arr_v3 [32]uint8
	v3 := _arr_v3[:]
	Crypto_eddsa_trim_scalar(v3, your_secret_key)
	Scalarmult(raw_shared_secret, v3, their_public_key, 255)
	for _i := range v3 { v3[_i] = 0 }
}

func Multiply(p []uint32, a []uint32, b []uint32) {
	var v3 uint64
	var v8 uint64
	var v10 uint64
	v3 = 0
	for v3 < 8 {
		v8 = 0
		v10 = 0
		for v10 < 8 {
			v15 := v3 + v10
			v8 = v8 + uint64(p[int(v15)] + uint32(uint64(a[int(v3)]) * uint64(b[int(v10)])))
			p[int(v15)] = uint32(v8)
			v8 = v8 >> 32
			v10 = v10 + 1
		}
		p[int(v3 + 8)] = uint32(v8)
		v3 = v3 + 1
	}
}

func Crypto_eddsa_reduce(reduced []byte, expanded []byte) {
	var _arr_v2 [16]uint32
	v2 := _arr_v2[:]
	Load32_le_buf(v2, expanded, uint64(16))
	Mod_l(reduced, v2)
	for _i := range v2 { v2[_i] = 0 }
}

func Crypto_eddsa_mul_add(r []byte, a []byte, b []byte, c []byte) {
	var v13 uint64
	var _arr_v4 [8]uint32
	v4 := _arr_v4[:]
	Load32_le_buf(v4, a, uint64(8))
	var _arr_v7 [8]uint32
	v7 := _arr_v7[:]
	Load32_le_buf(v7, b, uint64(8))
	var _arr_v10 [16]uint32
	v10 := _arr_v10[:]
	Load32_le_buf(v10, c, uint64(8))
	v13 = 0
	for v13 < 8 {
		v10[int(8 + int(v13))] = uint32(0)
		v13 = v13 + 1
	}
	Multiply(v10, v4, v7)
	Mod_l(r, v10)
	for _i := range v10 { v10[_i] = 0 }
	for _i := range v4 { v4[_i] = 0 }
	for _i := range v7 { v7[_i] = 0 }
}

func Ge_zero(p *Ge) {
	Fe_0(p.X[:])
	Fe_1(p.Y[:])
	Fe_1(p.Z[:])
	Fe_0(p.T[:])
}

func Ge_madd(s *Ge, p *Ge, q *Ge_precomp, a []int, b []int) {
	Fe_add(a, p.Y[:], p.X[:])
	Fe_sub(b, p.Y[:], p.X[:])
	Fe_mul(a, a, q.Yp[:])
	Fe_mul(b, b, q.Ym[:])
	Fe_add(s.Y[:], a, b)
	Fe_sub(s.X[:], a, b)
	Fe_add(s.Z[:], p.Z[:], p.Z[:])
	Fe_mul(s.T[:], p.T[:], q.T2[:])
	Fe_add(a, s.Z[:], s.T[:])
	Fe_sub(b, s.Z[:], s.T[:])
	Fe_mul(s.T[:], s.X[:], s.Y[:])
	Fe_mul(s.X[:], s.X[:], b)
	Fe_mul(s.Y[:], s.Y[:], a)
	Fe_mul(s.Z[:], a, b)
}

func Ge_double(s *Ge, p *Ge, q *Ge) {
	Fe_sq(q.X[:], p.X[:])
	Fe_sq(q.Y[:], p.Y[:])
	Fe_sq(q.Z[:], p.Z[:])
	Fe_mul_small(q.Z[:], q.Z[:], 2)
	Fe_add(q.T[:], p.X[:], p.Y[:])
	Fe_sq(s.T[:], q.T[:])
	Fe_add(q.T[:], q.Y[:], q.X[:])
	Fe_sub(q.Y[:], q.Y[:], q.X[:])
	Fe_sub(q.X[:], s.T[:], q.T[:])
	Fe_sub(q.Z[:], q.Z[:], q.Y[:])
	Fe_mul(s.X[:], q.X[:], q.Z[:])
	Fe_mul(s.Y[:], q.T[:], q.Y[:])
	Fe_mul(s.Z[:], q.Y[:], q.Z[:])
	Fe_mul(s.T[:], q.X[:], q.T[:])
}

func Slide_init(ctx *Slide_ctx, scalar []byte) {
	var v2 int
	v2 = 252
	for (v2 > 0) && (Scalar_bit(scalar, v2) == 0) {
		v2 = v2 - 1
	}
	ctx.Next_check = uint8(v2 + 1)
	ctx.Next_index = uint32(0xffffffff)
	ctx.Next_digit = uint8(0xff)
}

func Slide_step(ctx *Slide_ctx, width int, i int, scalar []byte) int {
	var v19 int
	var v26 int
	if i == int(ctx.Next_check) {
		if Scalar_bit(scalar, i) == Scalar_bit(scalar, (i - 1)) {
			ctx.Next_check = ctx.Next_check - uint8(1)
		} else {
			v18 := func() int { if (func() int { if width <= (i + 1) { return 1 }; return 0 }()) != 0 { return width }; return (i + 1) }()
			v19 = -int(Scalar_bit(scalar, i) << uint8(v18 - 1))
			v26 = 0
			for {
				v29 := v18 - 1
				if !(v26 < v29) { break }
				v19 = v19 + Scalar_bit(scalar, ((i - v29) + v26)) << uint8(v26)
				v26 = v26 + 1
			}
			v19 = v19 + Scalar_bit(scalar, (i - v18))
			v67 := func() int { if ((v19 & (^v19 + 1)) & 170) != 0 { return 1 }; return 0 }() << 0 | func() int { if ((v19 & (^v19 + 1)) & 204) != 0 { return 1 }; return 0 }() << 1 | func() int { if ((v19 & (^v19 + 1)) & 240) != 0 { return 1 }; return 0 }() << 2
			ctx.Next_index = uint32((i - (v18 - 1)) + v67)
			ctx.Next_digit = uint8(v19 >> uint8(v67))
			ctx.Next_check = ctx.Next_check - uint8(v18)
		}
	}
	return int(func() uint8 { if (func() int { if i == int(ctx.Next_index) { return 1 }; return 0 }()) != 0 { return ctx.Next_digit }; return uint8(0) }())
}

func Crypto_eddsa_scalarbase(point []byte, scalar []byte) {
	var v2 Ge
	Ge_scalarmult_base(&v2, scalar)
	Ge_tobytes(point, &v2)
	_ = v2 // wipe skipped struct
}

func Crypto_eddsa_key_pair(secret_key []byte, public_key []byte, seed []byte) {
	var v4 uint64
	var v12 uint64
	var v26 uint64
	var _arr_v3 [64]uint8
	v3 := _arr_v3[:]
	v4 = 0
	for v4 < 32 {
		v3[int(v4)] = seed[int(v4)]
		v4 = v4 + 1
	}
	for _i := range seed { seed[_i] = 0 }
	v12 = 0
	for v12 < 32 {
		secret_key[int(v12)] = v3[int(v12)]
		v12 = v12 + 1
	}
	Crypto_blake2b(v3, uint64(64), v3, uint64(32))
	Crypto_eddsa_trim_scalar(v3, v3)
	Crypto_eddsa_scalarbase(secret_key[32:], v3)
	v26 = 0
	for v26 < 32 {
		public_key[int(v26)] = secret_key[int(32 + int(v26))]
		v26 = v26 + 1
	}
	for _i := range v3 { v3[_i] = 0 }
}

func Hash_reduce(h []byte, a []byte, a_size uint64, b []byte, b_size uint64, c []byte, c_size uint64) {
	var _arr_v7 [64]uint8
	v7 := _arr_v7[:]
	var v8 Crypto_blake2b_ctx
	Crypto_blake2b_init(&v8, uint64(64))
	Crypto_blake2b_update(&v8, a, a_size)
	Crypto_blake2b_update(&v8, b, b_size)
	Crypto_blake2b_update(&v8, c, c_size)
	Crypto_blake2b_final(&v8, v7)
	Crypto_eddsa_reduce(h, v7)
}

func Crypto_eddsa_sign(signature []byte, secret_key []byte, message []byte, message_size uint64) {
	var v26 uint64
	var _arr_v4 [64]uint8
	v4 := _arr_v4[:]
	var _arr_v5 [32]uint8
	v5 := _arr_v5[:]
	var _arr_v6 [32]uint8
	v6 := _arr_v6[:]
	var _arr_v7 [32]uint8
	v7 := _arr_v7[:]
	Crypto_blake2b(v4, uint64(64), secret_key, uint64(32))
	Crypto_eddsa_trim_scalar(v4, v4)
	Hash_reduce(v5, v4[32:], uint64(32), message, message_size, nil, uint64(0))
	Crypto_eddsa_scalarbase(v7, v5)
	Hash_reduce(v6, v7, uint64(32), secret_key[32:], uint64(32), message, message_size)
	v26 = 0
	for v26 < 32 {
		signature[int(v26)] = v7[int(v26)]
		v26 = v26 + 1
	}
	Crypto_eddsa_mul_add(signature[32:], v6, v4, v5)
	for _i := range v4 { v4[_i] = 0 }
	for _i := range v5 { v5[_i] = 0 }
}

func Crypto_eddsa_check(signature []byte, public_key []byte, message []byte, message_size uint64) int {
	var _arr_v4 [32]uint8
	v4 := _arr_v4[:]
	Hash_reduce(v4, signature, uint64(32), public_key, uint64(32), message, message_size)
	return Crypto_eddsa_check_equation(signature, public_key, v4)
}

func Lock_auth(mac []byte, auth_key []byte, ad []byte, ad_size uint64, cipher_text []byte, text_size uint64) {
	var _arr_v7 [16]uint8
	v7 := _arr_v7[:]
	Store64_le(v7, ad_size)
	Store64_le(v7[8:], text_size)
	var v16 Crypto_poly1305_ctx
	Crypto_poly1305_init(&v16, auth_key)
	Crypto_poly1305_update(&v16, ad, ad_size)
	Crypto_poly1305_update(&v16, zero, Gap(ad_size, uint64(16)))
	Crypto_poly1305_update(&v16, cipher_text, text_size)
	Crypto_poly1305_update(&v16, zero, Gap(text_size, uint64(16)))
	Crypto_poly1305_update(&v16, v7, uint64(16))
	Crypto_poly1305_final(&v16, mac)
}

func Crypto_aead_init_x(ctx *Crypto_aead_ctx, key []byte, nonce []byte) {
	var v5 uint64
	Crypto_chacha20_h(ctx.Key[:], key, nonce)
	v5 = 0
	for v5 < 8 {
		ctx.Nonce[int(v5)] = nonce[int(16 + int(v5))]
		v5 = v5 + 1
	}
	ctx.Counter = uint64(0)
}

func Crypto_aead_init_djb(ctx *Crypto_aead_ctx, key []byte, nonce []byte) {
	var v3 uint64
	var v10 uint64
	v3 = 0
	for v3 < 32 {
		ctx.Key[int(v3)] = key[int(v3)]
		v3 = v3 + 1
	}
	v10 = 0
	for v10 < 8 {
		ctx.Nonce[int(v10)] = nonce[int(v10)]
		v10 = v10 + 1
	}
	ctx.Counter = uint64(0)
}

func Crypto_aead_init_ietf(ctx *Crypto_aead_ctx, key []byte, nonce []byte) {
	var v3 uint64
	var v10 uint64
	v3 = 0
	for v3 < 32 {
		ctx.Key[int(v3)] = key[int(v3)]
		v3 = v3 + 1
	}
	v10 = 0
	for v10 < 8 {
		ctx.Nonce[int(v10)] = nonce[int(4 + int(v10))]
		v10 = v10 + 1
	}
	ctx.Counter = uint64(Load32_le(nonce)) << 32
}

func Crypto_aead_write(ctx *Crypto_aead_ctx, cipher_text []byte, mac []byte, ad []byte, ad_size uint64, plain_text []byte, text_size uint64) {
	var v21 uint64
	var _arr_v7 [64]uint8
	v7 := _arr_v7[:]
	Crypto_chacha20_djb(v7, nil, uint64(64), ctx.Key[:], ctx.Nonce[:], ctx.Counter)
	Crypto_chacha20_djb(cipher_text, plain_text, text_size, ctx.Key[:], ctx.Nonce[:], (ctx.Counter + uint64(1)))
	Lock_auth(mac, v7, ad, ad_size, cipher_text, text_size)
	v21 = 0
	for v21 < 32 {
		ctx.Key[int(v21)] = v7[int(uint64(32) + v21)]
		v21 = v21 + 1
	}
	for _i := range v7 { v7[_i] = 0 }
}

func Crypto_aead_read(ctx *Crypto_aead_ctx, plain_text []byte, mac []byte, ad []byte, ad_size uint64, cipher_text []byte, text_size uint64) int {
	var v24 uint64
	var _arr_v7 [64]uint8
	v7 := _arr_v7[:]
	var _arr_v8 [16]uint8
	v8 := _arr_v8[:]
	Crypto_chacha20_djb(v7, nil, uint64(64), ctx.Key[:], ctx.Nonce[:], ctx.Counter)
	Lock_auth(v8, v7, ad, ad_size, cipher_text, text_size)
	v17 := Crypto_verify16(mac, v8)
	if !(v17 != 0) {
		Crypto_chacha20_djb(plain_text, cipher_text, text_size, ctx.Key[:], ctx.Nonce[:], (ctx.Counter + uint64(1)))
		v24 = 0
		for v24 < 32 {
			ctx.Key[int(v24)] = v7[int(32 + int(v24))]
			v24 = v24 + 1
		}
	}
	for _i := range v7 { v7[_i] = 0 }
	for _i := range v8 { v8[_i] = 0 }
	return v17
}

func Crypto_aead_lock(cipher_text []byte, mac []byte, key []byte, nonce []byte, ad []byte, ad_size uint64, plain_text []byte, text_size uint64) {
	var v8 Crypto_aead_ctx
	Crypto_aead_init_x(&v8, key, nonce)
	Crypto_aead_write(&v8, cipher_text, mac, ad, ad_size, plain_text, text_size)
	_ = v8 // wipe skipped struct
}

func Crypto_aead_unlock(plain_text []byte, mac []byte, key []byte, nonce []byte, ad []byte, ad_size uint64, cipher_text []byte, text_size uint64) int {
	var v8 Crypto_aead_ctx
	Crypto_aead_init_x(&v8, key, nonce)
	_ = v8 // wipe skipped struct
	return Crypto_aead_read(&v8, plain_text, mac, ad, ad_size, cipher_text, text_size)
}

func Crypto_blake2b_keyed_init(args ...any) {
	panic("sgoiter: Crypto_blake2b_keyed_init was not harvested from the C source — this stub has no body")
}


func Blake2b_compress(args ...any) {
	panic("sgoiter: Blake2b_compress was not harvested from the C source — this stub has no body")
}


func Crypto_blake2b_update(args ...any) {
	panic("sgoiter: Crypto_blake2b_update was not harvested from the C source — this stub has no body")
}


func Scalarmult(args ...any) {
	panic("sgoiter: Scalarmult was not harvested from the C source — this stub has no body")
}


func Mod_l(args ...any) {
	panic("sgoiter: Mod_l was not harvested from the C source — this stub has no body")
}


func Ge_scalarmult_base(args ...any) {
	panic("sgoiter: Ge_scalarmult_base was not harvested from the C source — this stub has no body")
}


func Ge_tobytes(args ...any) {
	panic("sgoiter: Ge_tobytes was not harvested from the C source — this stub has no body")
}


func Crypto_eddsa_check_equation(args ...any) int {
	panic("sgoiter: Crypto_eddsa_check_equation was not harvested from the C source — this stub has no body")
}


