// Code generated by sgoiter emit go127; DO NOT EDIT.
// sgoiter-stamp: sha256=883beb1a90533b923926fef1a7b4d9057490373bc1c1dbfaf9584a965695a2c5
package c2pcre

type C2_regex_op_t struct {
	Opcode    byte
	Ch        byte
	Target_op byte
}

type C2_regex_t struct {
	Ops   [128]C2_regex_op_t
	N_ops uint32
}

type C2_match_t struct {
	Start int
	End   int
}

func C2_pcre_compile(pattern []byte, pat_len uint32, re *C2_regex_t) int {
	var v4 uint32
	var v12 byte
	var v28 uint32
	var v46 uint32
	var v50 byte
	var v101 uint32
	var v109 bool
	var v113 byte
	var v114 byte
	var v143 uint32
	var v163 uint32
	var v183 uint32
	var v197 uint32
	var v220 uint32
	var v241 uint32
	var v262 uint32
	var v278 uint32
	if uint32(len(pattern)) < pat_len {
		pat_len = uint32(len(pattern))
	}
	re.N_ops = 0
	v4 = 0
	for {
		v10 := (v4 < pat_len) && (re.N_ops < 0x7f)
		if !v10 {
			break
		}
		v12 = pattern[v4]
		if v12 == 0x5e {
			re.Ops[re.N_ops].Opcode = 3
			re.Ops[re.N_ops].Ch = 0
			re.Ops[re.N_ops].Target_op = 0
			v28 = re.N_ops + 1
			re.N_ops = v28
			v4++
		} else {
			if v12 == 36 {
				re.Ops[re.N_ops].Opcode = 4
				re.Ops[re.N_ops].Ch = 0
				re.Ops[re.N_ops].Target_op = 0
				v46 = re.N_ops + 1
				re.N_ops = v46
				v4++
			} else {
				if v12 == 46 {
					v50 = 2
					var cond_60 bool
					if (v4 + 1) < pat_len {
						if pattern[v4+1] == 42 {
							cond_60 = true
						}
					}
					if cond_60 {
						v50 = 8
						v4++
					} else {
						var cond_72 bool
						if (v4 + 1) < pat_len {
							if pattern[v4+1] == 43 {
								cond_72 = true
							}
						}
						if cond_72 {
							v50 = 9
							v4++
						} else {
							if (v4 + 1) < pat_len {
								if pattern[v4+1] == 63 {
									v50 = 10
									v4++
								}
							}
						}
					}
					re.Ops[re.N_ops].Opcode = v50
					re.Ops[re.N_ops].Ch = 46
					re.Ops[re.N_ops].Target_op = 2
					v101 = re.N_ops + 1
					re.N_ops = v101
					v4++
				} else {
					v109 = (v12 == 0x5c) && ((v4 + 1) < pat_len)
					if v109 {
						v113 = pattern[v4+1]
						v114 = 1
						if v113 == 'd' {
							v114 = 5
						} else {
							if v113 == 'w' {
								v114 = 6
							} else {
								if v113 == 's' {
									v114 = 7
								}
							}
						}
						v4 += 2
						var cond_130 bool
						if v4 < pat_len {
							if pattern[v4] == 42 {
								cond_130 = true
							}
						}
						if cond_130 {
							re.Ops[re.N_ops].Opcode = 8
							re.Ops[re.N_ops].Ch = v113
							re.Ops[re.N_ops].Target_op = v114
							v143 = re.N_ops + 1
							re.N_ops = v143
							v4++
						} else {
							var cond_150 bool
							if v4 < pat_len {
								if pattern[v4] == 43 {
									cond_150 = true
								}
							}
							if cond_150 {
								re.Ops[re.N_ops].Opcode = 9
								re.Ops[re.N_ops].Ch = v113
								re.Ops[re.N_ops].Target_op = v114
								v163 = re.N_ops + 1
								re.N_ops = v163
								v4++
							} else {
								var cond_170 bool
								if v4 < pat_len {
									if pattern[v4] == 63 {
										cond_170 = true
									}
								}
								if cond_170 {
									re.Ops[re.N_ops].Opcode = 10
									re.Ops[re.N_ops].Ch = v113
									re.Ops[re.N_ops].Target_op = v114
									v183 = re.N_ops + 1
									re.N_ops = v183
									v4++
								} else {
									re.Ops[re.N_ops].Opcode = v114
									re.Ops[re.N_ops].Ch = v113
									re.Ops[re.N_ops].Target_op = v114
									v197 = re.N_ops + 1
									re.N_ops = v197
								}
							}
						}
					} else {
						v4++
						var cond_206 bool
						if v4 < pat_len {
							if pattern[v4] == 42 {
								cond_206 = true
							}
						}
						if cond_206 {
							re.Ops[re.N_ops].Opcode = 8
							re.Ops[re.N_ops].Ch = v12
							re.Ops[re.N_ops].Target_op = 1
							v220 = re.N_ops + 1
							re.N_ops = v220
							v4++
						} else {
							var cond_227 bool
							if v4 < pat_len {
								if pattern[v4] == 43 {
									cond_227 = true
								}
							}
							if cond_227 {
								re.Ops[re.N_ops].Opcode = 9
								re.Ops[re.N_ops].Ch = v12
								re.Ops[re.N_ops].Target_op = 1
								v241 = re.N_ops + 1
								re.N_ops = v241
								v4++
							} else {
								var cond_248 bool
								if v4 < pat_len {
									if pattern[v4] == 63 {
										cond_248 = true
									}
								}
								if cond_248 {
									re.Ops[re.N_ops].Opcode = 10
									re.Ops[re.N_ops].Ch = v12
									re.Ops[re.N_ops].Target_op = 1
									v262 = re.N_ops + 1
									re.N_ops = v262
									v4++
								} else {
									re.Ops[re.N_ops].Opcode = 1
									re.Ops[re.N_ops].Ch = v12
									re.Ops[re.N_ops].Target_op = 1
									v278 = re.N_ops + 1
									re.N_ops = v278
								}
							}
						}
					}
				}
			}
		}
	}
	return int(re.N_ops)
}

func match_one(opcode byte, ch byte, subject_char byte) bool {
	var v8 bool
	var v17 bool
	var v23 bool
	var v28 bool
	var v34 bool
	if opcode == 2 {
		v8 = (subject_char != 0) && (subject_char != 10)
		return bool(v8)
	}
	if opcode == 1 {
		return bool(subject_char == ch)
	}
	if opcode == 5 {
		v17 = (subject_char >= '0') && (subject_char <= '9')
		return bool(v17)
	}
	if opcode == 6 {
		v23 = (subject_char >= 'a') && (subject_char <= 'z')
		v28 = (subject_char >= 'A') && (subject_char <= 'Z')
		v34 = (subject_char >= '0') && (subject_char <= '9')
		return bool(((v23 || v28) || v34) || (subject_char == '_'))
	}
	if opcode == 7 {
		return bool((((subject_char == 32) || (subject_char == 9)) || (subject_char == 10)) || (subject_char == 13))
	}
	return false
}

func match_here(re *C2_regex_t, op_idx uint32, text []byte, text_len uint32, pos uint32, out_end *int) bool {
	var v11 byte
	var v15 byte
	var v19 byte
	var v35 uint32
	var v58 uint32
	if uint32(len(text)) < text_len {
		text_len = uint32(len(text))
	}
	_ = 0
	if op_idx >= re.N_ops {
		*out_end = int(pos)
		return true
	}
	v11 = re.Ops[op_idx].Opcode
	v15 = re.Ops[op_idx].Ch
	v19 = re.Ops[op_idx].Target_op
	if v11 == 3 {
		if pos == 0 {
			return bool(match_here(re, (op_idx + 1), text[:], text_len, pos, out_end))
		}
		return false
	}
	if v11 == 4 {
		if pos == text_len {
			return bool(match_here(re, (op_idx + 1), text[:], text_len, pos, out_end))
		}
		return false
	}
	if v11 == 8 {
		for v35 = pos; v35 < text_len; v35++ {
			if match_one(v19, v15, text[v35]) == false {
				break
			}
		}
		for v35 >= pos {
			if match_here(re, (op_idx + 1), text[:], text_len, v35, out_end) {
				return true
			}
			if v35 == 0 {
				break
			}
			v35--
		}
		return false
	}
	if v11 == 9 {
		if (pos >= text_len) || (match_one(v19, v15, text[pos]) == false) {
			return false
		}
		for v58 = pos + 1; v58 < text_len; v58++ {
			if match_one(v19, v15, text[v58]) == false {
				break
			}
		}
		for v58 > pos {
			if match_here(re, (op_idx + 1), text[:], text_len, v58, out_end) {
				return true
			}
			v58--
		}
		return false
	}
	if v11 == 10 {
		if pos < text_len {
			if match_one(v19, v15, text[pos]) {
				if match_here(re, (op_idx + 1), text[:], text_len, (pos + 1), out_end) {
					return true
				}
			}
		}
		return bool(match_here(re, (op_idx + 1), text[:], text_len, pos, out_end))
	}
	if pos < text_len {
		if match_one(v11, v15, text[pos]) {
			return bool(match_here(re, (op_idx + 1), text[:], text_len, (pos + 1), out_end))
		}
	}
	return false
}

func C2_pcre_exec(re *C2_regex_t, text []byte, text_len uint32, match *C2_match_t) int {
	var v17 int
	var v27 bool
	var v32 uint32
	var v38 bool
	if uint32(len(text)) < text_len {
		text_len = uint32(len(text))
	}
	_ = 0
	if match != nil {
		match.Start = -1
		match.End = -1
	}
	if re.N_ops == 0 {
		if match != nil {
			match.Start = 0
			match.End = 0
		}
		return 1
	}
	v17 = 0
	if re.Ops[0].Opcode == 3 {
		v27 = match_here(re, uint32(0), text[:], text_len, uint32(0), &v17)
		if v27 {
			if match != nil {
				match.Start = 0
				match.End = v17
			}
			return 1
		}
		return 0
	}
	for v32 = 0; v32 <= text_len; v32++ {
		v38 = match_here(re, uint32(0), text[:], text_len, v32, &v17)
		if v38 {
			if match != nil {
				match.Start = int(v32)
				match.End = v17
			}
			return 1
		}
	}
	return 0
}
