// Code generated by sgoiter emit go127; DO NOT EDIT.
package src

import "encoding/binary"

func Fast_xor_bytes(dst []byte, src1 []byte, src2 []byte, len uint64) {
	var v26 uint8
	var v4 uint64
	var v7 uint64
	var v13 uint64
	var v18 uint64
	var v15 uint64
	var v20 uint64
	var v23 uint64
	var v28 uint8
	var v9 uint64
	var v14 uint64
	var v10 uint64
	var v19 uint64
	var v27 uint8
	var v25 uint64
	v4 = uint64(0)
	v7 = v4 + uint64(8)
	for v7 <= len {
	v13 = v4 / uint64(8)
	v14 = binary.LittleEndian.Uint64(src1[int(int(v13)):])
	v10 = v14
	v18 = v4 / uint64(8)
	v19 = binary.LittleEndian.Uint64(src2[int(int(v18)):])
	v15 = v19
	v20 = v10 ^ v15
	v23 = v4 / uint64(8)
	binary.LittleEndian.PutUint64(dst[int(int(v23))*8:], v20)
	v9 = v4 + uint64(8)
	v4 = v9
	}
	for v4 < len {
	v26 = src1[int(int(v4))]
	v27 = src2[int(int(v4))]
	v28 = v26 ^ v27
	dst[int(int(v4))] = v28
	v25 = v4 + uint64(1)
	v4 = v25
	}
}

