// Code generated by sgoiter emit go127; DO NOT EDIT.
// sgoiter-stamp: sha256=7f4f5982b815b02711667a2d93523c80412d1cfa174e6e5b1c6d61142975fa07
package c2mem

type C2_cleanup_entry_t struct {
	Resource_id uint32
	Flags       uint32
	Param       int64
}

type C2_arena_t struct {
	Buffer       []byte
	Capacity     uint32
	Offset       uint32
	Peak_offset  uint32
	N_cleanups   uint32
	Max_cleanups uint32
	Cleanups     []C2_cleanup_entry_t
}

func C2_arena_init(arena *C2_arena_t, buffer []byte, capacity uint32, cleanup_buf []C2_cleanup_entry_t, max_cleanups uint32) {
	arena.Buffer = buffer[:]
	arena.Capacity = capacity
	arena.Offset = 0
	arena.Peak_offset = 0
	arena.N_cleanups = 0
	arena.Max_cleanups = max_cleanups
	arena.Cleanups = cleanup_buf
}

func C2_arena_alloc(arena *C2_arena_t, size uint32) int {
	var v2 uint32
	var v16 uint32
	_ = 0
	v2 = (size + 7) & 0xfffffff8
	if v2 == 0 {
		v2 = 8
	}
	if (arena.Offset + v2) > arena.Capacity {
		return -1
	}
	v16 = arena.Offset
	arena.Offset = v16 + v2
	if arena.Offset > arena.Peak_offset {
		arena.Peak_offset = arena.Offset
	}
	return int(v16)
}

func C2_arena_register_cleanup(arena *C2_arena_t, resource_id uint32, flags uint32, param int64) bool {
	var v14 uint32
	_ = 0
	if (arena.N_cleanups >= arena.Max_cleanups) || (arena.Cleanups == nil) {
		return false
	}
	v14 = arena.N_cleanups
	arena.N_cleanups = v14
	v18 := arena.N_cleanups + 1
	arena.N_cleanups = v18
	arena.Cleanups[v14].Resource_id = resource_id
	arena.Cleanups[v14].Flags = flags
	arena.Cleanups[v14].Param = param
	return true
}

func C2_arena_reset(arena *C2_arena_t) uint32 {
	var v1 uint32
	v1 = arena.N_cleanups
	arena.Offset = 0
	arena.N_cleanups = 0
	return v1
}
