// Code generated by sgoiter emit go127; DO NOT EDIT.
package chacha20_qr

func Chacha20_quarter_round(a []uint32, b []uint32, c []uint32, d []uint32) {
	v4 := b[0]
	v5 := a[0]
	v6 := v5 + v4
	a[0] = v6
	v7 := a[0]
	v8 := d[0]
	v9 := v8 ^ v7
	d[0] = v9
	v10 := d[0]
	v12 := v10 << uint8(16)
	v13 := d[0]
	v16 := 32 - 16
	v17 := v13 >> uint8(v16)
	v18 := v12 | v17
	d[0] = v18
	v19 := d[0]
	v20 := c[0]
	v21 := v20 + v19
	c[0] = v21
	v22 := c[0]
	v23 := b[0]
	v24 := v23 ^ v22
	b[0] = v24
	v25 := b[0]
	v27 := v25 << uint8(12)
	v28 := b[0]
	v31 := 32 - 12
	v32 := v28 >> uint8(v31)
	v33 := v27 | v32
	b[0] = v33
	v34 := b[0]
	v35 := a[0]
	v36 := v35 + v34
	a[0] = v36
	v37 := a[0]
	v38 := d[0]
	v39 := v38 ^ v37
	d[0] = v39
	v40 := d[0]
	v42 := v40 << uint8(8)
	v43 := d[0]
	v46 := 32 - 8
	v47 := v43 >> uint8(v46)
	v48 := v42 | v47
	d[0] = v48
	v49 := d[0]
	v50 := c[0]
	v51 := v50 + v49
	c[0] = v51
	v52 := c[0]
	v53 := b[0]
	v54 := v53 ^ v52
	b[0] = v54
	v55 := b[0]
	v57 := v55 << uint8(7)
	v58 := b[0]
	v61 := 32 - 7
	v62 := v58 >> uint8(v61)
	v63 := v57 | v62
	b[0] = v63
}

