// Code generated by sgoiter emit go127; DO NOT EDIT.
package murmur3_x86_32

import "encoding/binary"

func Rotl32(x uint32, r uint8) uint32 {
	v2 := x << r
	v4 := uint32(32) - uint32(r)
	v5 := x >> uint8(v4)
	v6 := v2 | v5
	return v6
}

func Fmix32(h uint32) uint32 {
	v2 := h >> uint8(16)
	v3 := h ^ v2
	h = v3
	v5 := h * uint32(2246822507)
	h = v5
	v7 := h >> uint8(13)
	v8 := h ^ v7
	h = v8
	v10 := h * uint32(3266489909)
	h = v10
	v12 := h >> uint8(16)
	v13 := h ^ v12
	h = v13
	return h
}

func Murmur3_x86_32(key []byte, len uint64, seed uint32) uint32 {
	v6 := len / uint64(4)
	v4 := v6
	v7 := seed
	v8 := uint32(3432918353)
	v10 := uint32(461845907)
	v14 := v4 * uint64(4)
	v19 := -int(int(v4))
	v17 := v19
	for v17 != 0 {
	v25 := v17 * 4
	v26 := int(v14) + v25
	v23 := binary.LittleEndian.Uint32(key[int(v26):])
	v22 := v23
	v27 := v22 * v8
	v22 = v27
	v29 := Rotl32(v22, uint8(15))
	v22 = v29
	v30 := v22 * v10
	v22 = v30
	v31 := v7 ^ v22
	v7 = v31
	v33 := Rotl32(v7, uint8(13))
	v7 = v33
	v35 := v7 * uint32(5)
	v37 := v35 + uint32(3864292196)
	v7 = v37
	v21 := v17 + 1
	v17 = v21
	}
	v40 := v4 * uint64(4)
	v43 := uint32(0)
	v46 := len & uint64(3)
	switch uint32(v46) {
	case 3:
	v49 := v40 + uint64(2)
	v48 := key[int(int(v49))]
	v51 := uint32(v48) << uint8(16)
	v52 := v43 ^ v51
	v43 = v52
		fallthrough
	case 2:
	v55 := v40 + uint64(1)
	v54 := key[int(int(v55))]
	v57 := uint32(v54) << uint8(8)
	v58 := v43 ^ v57
	v43 = v58
		fallthrough
	case 1:
	v61 := v40
	v60 := key[int(int(v61))]
	v62 := v43 ^ uint32(v60)
	v43 = v62
	v63 := v43 * v8
	v43 = v63
	v65 := Rotl32(v43, uint8(15))
	v43 = v65
	v66 := v43 * v10
	v43 = v66
	v67 := v7 ^ v43
	v7 = v67
	}
	v68 := v7 ^ uint32(len)
	v7 = v68
	v69 := Fmix32(v7)
	return v69
}

