// Code generated by sgoiter emit go127; DO NOT EDIT.
package src

import "encoding/binary"

type MD5_CTX_RAW struct {
	Count [2]uint32
	State [4]uint32
	Buffer [64]uint8
}

func Md5_transform_block(state []uint32, block []byte) {
	var v57 uint32
	var v69 uint32
	var v2 uint32
	var v25 uint32
	var v56 int
	var v85 uint32
	var v88 uint32
	var v91 uint32
	var v108 uint32
	var v87 uint32
	var v13 uint32
	var v38 uint32
	var v39 uint32
	var v46 uint32
	var v65 uint32
	var v70 uint32
	var v82 uint32
	var v5 uint32
	var v10 uint32
	var v32 uint32
	var v72 uint32
	var v107 uint32
	var v4 uint32
	var v8 uint32
	var v75 int
	var v19 int
	var v53 uint32
	var v66 uint32
	var v76 uint32
	var v95 uint32
	var v28 uint32
	var v51 uint32
	var v68 uint32
	var v112 uint32
	var v58 uint32
	var v79 uint32
	var v94 int
	var v99 uint32
	var v15 int
	var v40 uint32
	var v44 uint32
	var v47 uint32
	var v96 uint32
	var v111 uint32
	var v34 uint32
	var v49 uint32
	var v103 uint32
	var v7 uint32
	var v11 uint32
	var v24 uint32
	var v104 uint32
	var v81 uint32
	var v22 uint32
	var v37 int
	var v50 uint32
	var v59 uint32
	var v77 uint32
	var v78 uint32
	var v97 uint32
	var v43 uint32
	var v63 uint32
	var v27 uint32
	var v60 uint32
	var v84 uint32
	var v89 uint32
	var v62 uint32
	var v30 uint32
	var v31 uint32
	var v100 uint32
	var v21 uint32
	var v41 uint32
	v4 = state[int(0)]
	v2 = v4
	v7 = state[int(1)]
	v5 = v7
	v10 = state[int(2)]
	v8 = v10
	v13 = state[int(3)]
	v11 = v13
	var _arr_v14 [16]uint32
	v14 := _arr_v14[:]
	v15 = 0
	for v15 < 16 {
	v21 = binary.LittleEndian.Uint32(block[int(v15):])
	v14[int(v15)] = v21
	v19 = v15 + 1
	v15 = v19
	}
	v22 = v5 & v8
	v23 := ^v5
	_ = v23
	v24 = v23 & v11
	v25 = v22 | v24
	v27 = v14[int(0)]
	v28 = v25 + v27
	v30 = uint32(3614090360)
	v31 = v28 + v30
	v32 = v2 + v31
	v2 = v32
	v34 = v2 << uint8(7)
	v37 = 32 - 7
	v38 = v2 >> uint8(v37)
	v39 = v34 | v38
	v2 = v39
	v40 = v2 + v5
	v2 = v40
	v41 = v2 & v5
	v42 := ^v2
	_ = v42
	v43 = v42 & v8
	v44 = v41 | v43
	v46 = v14[int(1)]
	v47 = v44 + v46
	v49 = uint32(3905402710)
	v50 = v47 + v49
	v51 = v11 + v50
	v11 = v51
	v53 = v11 << uint8(12)
	v56 = 32 - 12
	v57 = v11 >> uint8(v56)
	v58 = v53 | v57
	v11 = v58
	v59 = v11 + v2
	v11 = v59
	v60 = v11 & v2
	v61 := ^v11
	_ = v61
	v62 = v61 & v5
	v63 = v60 | v62
	v65 = v14[int(2)]
	v66 = v63 + v65
	v68 = uint32(606105819)
	v69 = v66 + v68
	v70 = v8 + v69
	v8 = v70
	v72 = v8 << uint8(17)
	v75 = 32 - 17
	v76 = v8 >> uint8(v75)
	v77 = v72 | v76
	v8 = v77
	v78 = v8 + v11
	v8 = v78
	v79 = v8 & v11
	v80 := ^v8
	_ = v80
	v81 = v80 & v2
	v82 = v79 | v81
	v84 = v14[int(3)]
	v85 = v82 + v84
	v87 = uint32(3250441966)
	v88 = v85 + v87
	v89 = v5 + v88
	v5 = v89
	v91 = v5 << uint8(22)
	v94 = 32 - 22
	v95 = v5 >> uint8(v94)
	v96 = v91 | v95
	v5 = v96
	v97 = v5 + v8
	v5 = v97
	v99 = state[int(0)]
	v100 = v99 + v2
	state[int(0)] = v100
	v103 = state[int(1)]
	v104 = v103 + v5
	state[int(1)] = v104
	v107 = state[int(2)]
	v108 = v107 + v8
	state[int(2)] = v108
	v111 = state[int(3)]
	v112 = v111 + v11
	state[int(3)] = v112
}

