// Code generated by sgoiter emit go127; DO NOT EDIT.
package src

import "encoding/binary"

func Siphash24(in []byte, inlen uint64, k []byte) uint64 {
	var v180 uint64
	var v205 uint64
	var v185 uint64
	var v232 uint64
	var v33 uint64
	var v31 uint64
	var v219 uint64
	var v241 uint64
	var v250 uint64
	var v59 uint64
	var v260 uint64
	var v332 uint64
	var v217 uint64
	var v228 uint64
	var v244 uint64
	var v251 uint64
	var v14 uint64
	var v17 uint64
	var v213 uint64
	var v257 uint64
	var v173 uint64
	var v176 uint8
	var v184 uint64
	var v192 uint64
	var v247 uint64
	var v194 uint64
	var v35 uint64
	var v72 uint64
	var v88 uint64
	var v101 uint64
	var v170 uint64
	var v252 uint64
	var v8 uint64
	var v81 uint64
	var v167 uint64
	var v212 uint64
	var v237 uint64
	var v78 uint64
	var v222 uint64
	var v233 uint64
	var v242 uint64
	var v561 uint64
	var v97 uint64
	var v226 uint64
	var v235 uint64
	var v178 uint64
	var v204 uint8
	var v20 uint64
	var v169 uint8
	var v183 uint8
	var v190 uint8
	var v224 uint64
	var v266 uint64
	var v42 uint64
	var v261 uint64
	var v162 uint64
	var v187 uint64
	var v191 uint64
	var v197 uint8
	var v271 uint64
	var v54 uint64
	var v62 uint64
	var v91 uint64
	var v201 uint64
	var v206 uint64
	var v264 uint64
	var v223 uint64
	var v231 uint64
	var v82 uint64
	var v211 uint8
	var v255 uint64
	var v23 uint64
	var v45 uint64
	var v63 uint64
	var v262 uint64
	var v26 uint64
	var v199 uint64
	var v208 uint64
	var v177 uint64
	var v3 uint64
	var v270 uint64
	var v53 uint64
	var v245 uint64
	var v16 uint64
	var v240 uint64
	var v68 uint64
	var v92 uint64
	var v198 uint64
	var v50 uint64
	var v71 uint64
	var v171 uint64
	var v254 uint64
	var v330 uint64
	var v562 uint64
	var v563 uint64
	v3 = uint64(0)
	v8 = binary.LittleEndian.Uint64(k[int(0):])
	v16 = uint64(8)
	v14 = binary.LittleEndian.Uint64(k[int(v16):])
	v17 = uint64(8317987319222330741) ^ v8
	v20 = uint64(7237128888980173921) ^ v14
	v23 = uint64(7816392313619706465) ^ v8
	v26 = uint64(8387220255154660723) ^ v14
	v31 = v3 + inlen
	v33 = inlen % uint64(8)
	v35 = v31 - v33
	for v3 != v35 {
		v45 = v3
		v42 = binary.LittleEndian.Uint64(in[int(v45):])
		v26 = v26 ^ v42
		v17 = v17 + v20
		v50 = v20 << uint8(13)
		v53 = uint64(64) - uint64(13)
		v54 = v20 >> uint8(v53)
		v20 = v50 | v54
		v20 = v20 ^ v17
		v59 = v17 << uint8(32)
		v62 = uint64(64) - uint64(32)
		v63 = v17 >> uint8(v62)
		v17 = v59 | v63
		v23 = v23 + v26
		v68 = v26 << uint8(16)
		v71 = uint64(64) - uint64(16)
		v72 = v26 >> uint8(v71)
		v26 = v68 | v72
		v26 = v26 ^ v23
		v17 = v17 + v26
		v78 = v26 << uint8(21)
		v81 = uint64(64) - uint64(21)
		v82 = v26 >> uint8(v81)
		v26 = v78 | v82
		v26 = v26 ^ v17
		v23 = v23 + v20
		v88 = v20 << uint8(17)
		v91 = uint64(64) - uint64(17)
		v92 = v20 >> uint8(v91)
		v20 = v88 | v92
		v20 = v20 ^ v23
		v97 = v23 << uint8(32)
		v101 = v23 >> uint8(v62)
		v23 = v97 | v101
		v17 = v17 + v20
		v50 = v20 << uint8(13)
		v54 = v20 >> uint8(v53)
		v20 = v50 | v54
		v20 = v20 ^ v17
		v59 = v17 << uint8(32)
		v63 = v17 >> uint8(v62)
		v17 = v59 | v63
		v23 = v23 + v26
		v68 = v26 << uint8(16)
		v72 = v26 >> uint8(v71)
		v26 = v68 | v72
		v26 = v26 ^ v23
		v17 = v17 + v26
		v78 = v26 << uint8(21)
		v82 = v26 >> uint8(v81)
		v26 = v78 | v82
		v26 = v26 ^ v17
		v23 = v23 + v20
		v88 = v20 << uint8(17)
		v92 = v20 >> uint8(v91)
		v20 = v88 | v92
		v20 = v20 ^ v23
		v97 = v23 << uint8(32)
		v101 = v23 >> uint8(v62)
		v23 = v97 | v101
		v17 = v17 ^ v42
		v3 = v3 + uint64(8)
	}
	v162 = inlen << uint8(56)
	v167 = inlen & uint64(7)
	switch v167 {
		case 7:
			v170 = v3 + uint64(6)
			v169 = in[int(v170)]
			v171 = uint64(v169)
			v173 = v171 << uint8(48)
			v162 = v162 | v173
		fallthrough
		case 6:
			v177 = v3 + uint64(5)
			v176 = in[int(v177)]
			v178 = uint64(v176)
			v180 = v178 << uint8(40)
			v162 = v162 | v180
		fallthrough
		case 5:
			v184 = v3 + uint64(4)
			v183 = in[int(v184)]
			v185 = uint64(v183)
			v187 = v185 << uint8(32)
			v162 = v162 | v187
		fallthrough
		case 4:
			v191 = v3 + uint64(3)
			v190 = in[int(v191)]
			v192 = uint64(v190)
			v194 = v192 << uint8(24)
			v162 = v162 | v194
		fallthrough
		case 3:
			v198 = v3 + uint64(2)
			v197 = in[int(v198)]
			v199 = uint64(v197)
			v201 = v199 << uint8(16)
			v162 = v162 | v201
		fallthrough
		case 2:
			v205 = v3 + uint64(1)
			v204 = in[int(v205)]
			v206 = uint64(v204)
			v208 = v206 << uint8(8)
			v162 = v162 | v208
		fallthrough
		case 1:
			v212 = v3
			v211 = in[int(v212)]
			v213 = uint64(v211)
			v162 = v162 | v213
		fallthrough
		case 0:
	}
	v26 = v26 ^ v162
	v17 = v17 + v20
	v219 = v20 << uint8(13)
	v222 = uint64(64) - uint64(13)
	v223 = v20 >> uint8(v222)
	v20 = v219 | v223
	v20 = v20 ^ v17
	v228 = v17 << uint8(32)
	v231 = uint64(64) - uint64(32)
	v232 = v17 >> uint8(v231)
	v17 = v228 | v232
	v23 = v23 + v26
	v237 = v26 << uint8(16)
	v240 = uint64(64) - uint64(16)
	v241 = v26 >> uint8(v240)
	v26 = v237 | v241
	v26 = v26 ^ v23
	v17 = v17 + v26
	v247 = v26 << uint8(21)
	v250 = uint64(64) - uint64(21)
	v251 = v26 >> uint8(v250)
	v26 = v247 | v251
	v26 = v26 ^ v17
	v23 = v23 + v20
	v257 = v20 << uint8(17)
	v260 = uint64(64) - uint64(17)
	v261 = v20 >> uint8(v260)
	v20 = v257 | v261
	v20 = v20 ^ v23
	v266 = v23 << uint8(32)
	v270 = v23 >> uint8(v231)
	v23 = v266 | v270
	v17 = v17 + v20
	v219 = v20 << uint8(13)
	v223 = v20 >> uint8(v222)
	v20 = v219 | v223
	v20 = v20 ^ v17
	v228 = v17 << uint8(32)
	v232 = v17 >> uint8(v231)
	v17 = v228 | v232
	v23 = v23 + v26
	v237 = v26 << uint8(16)
	v241 = v26 >> uint8(v240)
	v26 = v237 | v241
	v244 = v26 ^ v23
	v26 = v244
	v245 = v17 + v26
	v17 = v245
	v247 = v26 << uint8(21)
	v251 = v26 >> uint8(v250)
	v252 = v247 | v251
	v26 = v252
	v254 = v26 ^ v17
	v26 = v254
	v255 = v23 + v20
	v23 = v255
	v257 = v20 << uint8(17)
	v261 = v20 >> uint8(v260)
	v262 = v257 | v261
	v20 = v262
	v264 = v20 ^ v23
	v20 = v264
	v266 = v23 << uint8(32)
	v270 = v23 >> uint8(v231)
	v271 = v266 | v270
	v23 = v271
	v330 = v17 ^ v162
	v17 = v330
	v332 = v23 ^ uint64(255)
	v23 = v332
	v217 = v17 + v20
	v17 = v217
	v219 = v20 << uint8(13)
	v223 = v20 >> uint8(v222)
	v224 = v219 | v223
	v20 = v224
	v226 = v20 ^ v17
	v20 = v226
	v228 = v17 << uint8(32)
	v232 = v17 >> uint8(v231)
	v233 = v228 | v232
	v17 = v233
	v235 = v23 + v26
	v23 = v235
	v237 = v26 << uint8(16)
	v241 = v26 >> uint8(v240)
	v242 = v237 | v241
	v26 = v242
	v244 = v26 ^ v23
	v26 = v244
	v245 = v17 + v26
	v17 = v245
	v247 = v26 << uint8(21)
	v251 = v26 >> uint8(v250)
	v252 = v247 | v251
	v26 = v252
	v254 = v26 ^ v17
	v26 = v254
	v255 = v23 + v20
	v23 = v255
	v257 = v20 << uint8(17)
	v261 = v20 >> uint8(v260)
	v262 = v257 | v261
	v20 = v262
	v264 = v20 ^ v23
	v20 = v264
	v266 = v23 << uint8(32)
	v270 = v23 >> uint8(v231)
	v271 = v266 | v270
	v23 = v271
	v217 = v17 + v20
	v17 = v217
	v219 = v20 << uint8(13)
	v223 = v20 >> uint8(v222)
	v224 = v219 | v223
	v20 = v224
	v226 = v20 ^ v17
	v20 = v226
	v228 = v17 << uint8(32)
	v232 = v17 >> uint8(v231)
	v233 = v228 | v232
	v17 = v233
	v235 = v23 + v26
	v23 = v235
	v237 = v26 << uint8(16)
	v241 = v26 >> uint8(v240)
	v242 = v237 | v241
	v26 = v242
	v244 = v26 ^ v23
	v26 = v244
	v245 = v17 + v26
	v17 = v245
	v247 = v26 << uint8(21)
	v251 = v26 >> uint8(v250)
	v252 = v247 | v251
	v26 = v252
	v254 = v26 ^ v17
	v26 = v254
	v255 = v23 + v20
	v23 = v255
	v257 = v20 << uint8(17)
	v261 = v20 >> uint8(v260)
	v262 = v257 | v261
	v20 = v262
	v264 = v20 ^ v23
	v20 = v264
	v266 = v23 << uint8(32)
	v270 = v23 >> uint8(v231)
	v271 = v266 | v270
	v23 = v271
	v217 = v17 + v20
	v17 = v217
	v219 = v20 << uint8(13)
	v223 = v20 >> uint8(v222)
	v224 = v219 | v223
	v20 = v224
	v226 = v20 ^ v17
	v20 = v226
	v228 = v17 << uint8(32)
	v232 = v17 >> uint8(v231)
	v233 = v228 | v232
	v17 = v233
	v235 = v23 + v26
	v23 = v235
	v237 = v26 << uint8(16)
	v241 = v26 >> uint8(v240)
	v242 = v237 | v241
	v26 = v242
	v244 = v26 ^ v23
	v26 = v244
	v245 = v17 + v26
	v17 = v245
	v247 = v26 << uint8(21)
	v251 = v26 >> uint8(v250)
	v252 = v247 | v251
	v26 = v252
	v254 = v26 ^ v17
	v26 = v254
	v255 = v23 + v20
	v23 = v255
	v257 = v20 << uint8(17)
	v261 = v20 >> uint8(v260)
	v262 = v257 | v261
	v20 = v262
	v264 = v20 ^ v23
	v20 = v264
	v266 = v23 << uint8(32)
	v270 = v23 >> uint8(v231)
	v271 = v266 | v270
	v23 = v271
	v217 = v17 + v20
	v17 = v217
	v219 = v20 << uint8(13)
	v223 = v20 >> uint8(v222)
	v224 = v219 | v223
	v20 = v224
	v226 = v20 ^ v17
	v20 = v226
	v228 = v17 << uint8(32)
	v232 = v17 >> uint8(v231)
	v233 = v228 | v232
	v17 = v233
	v235 = v23 + v26
	v23 = v235
	v237 = v26 << uint8(16)
	v241 = v26 >> uint8(v240)
	v242 = v237 | v241
	v26 = v242
	v244 = v26 ^ v23
	v26 = v244
	v245 = v17 + v26
	v17 = v245
	v247 = v26 << uint8(21)
	v251 = v26 >> uint8(v250)
	v252 = v247 | v251
	v26 = v252
	v254 = v26 ^ v17
	v26 = v254
	v255 = v23 + v20
	v23 = v255
	v257 = v20 << uint8(17)
	v261 = v20 >> uint8(v260)
	v262 = v257 | v261
	v20 = v262
	v264 = v20 ^ v23
	v20 = v264
	v266 = v23 << uint8(32)
	v270 = v23 >> uint8(v231)
	v271 = v266 | v270
	v23 = v271
	v561 = v17 ^ v20
	v562 = v561 ^ v23
	v563 = v562 ^ v26
	return uint64(v563)
}

