// Code generated by sgoiter emit go127; DO NOT EDIT.
// sgoiter-stamp: sha256=94e09f9fecbc29bb7435cfa19741cae82008f95caeb72bc347cda733be6f5420
package c2poly1305

import "runtime"

type Crypto_poly1305_ctx struct {
	C     [16]byte
	C_idx uint64
	R     [4]uint32
	Pad   [4]uint32
	H     [5]uint32
}

func gap(x uint64, pow_2 uint64) uint64 {
	v7 := (^x + 1) & (pow_2 - 1)
	return uint64(v7)
}

func load32_le(s []byte) uint32 {
	_ = s[3]
	return uint32(s[0]) | uint32(s[1])<<8 | uint32(s[2])<<16 | uint32(s[3])<<24
}

func store32_le(out []byte, in uint32) {
	v3 := in & 0xff
	out[0] = byte(v3)
	v8 := uint32(in>>8) & 0xff
	out[1] = byte(v8)
	v13 := uint32(in>>16) & 0xff
	out[2] = byte(v13)
	v18 := uint32(in>>24) & 0xff
	out[3] = byte(v18)
}

func load32_le_buf(dst []uint32, src []byte, size uint64) {
	var v3 uint64
	for v3 = 0; v3 < size; v3++ {
		dst[v3] = load32_le(src[int(v3*4) : int(v3*4)+4])
	}
}

func Crypto_wipe(secret []byte, size uint64) {
	if uint64(len(secret)) < size {
		size = uint64(len(secret))
	}
	clear(secret[:size])
}

func poly_blocks(ctx *Crypto_poly1305_ctx, in []byte, nb_blocks uint64, end uint32) {
	var v4 uint64
	var v9 uint32
	var v13 uint32
	var v17 uint32
	var v21 uint32
	var v27 uint32
	var v31 uint32
	var v35 uint32
	var v42 uint32
	var v46 uint32
	var v50 uint32
	var v54 uint32
	var v58 uint32
	var v62 uint64
	var v70 uint64
	var v77 uint64
	var v84 uint64
	var v91 uint64
	var v95 uint32
	var v105 uint64
	var v115 uint64
	var v125 uint64
	var v135 uint64
	var v138 uint32
	var v148 uint64
	var v149 uint64
	var v154 uint64
	var v158 uint64
	var v163 uint64
	var v167 uint64
	var v172 uint64
	var v176 uint64
	var v181 uint32
	var v184 uint64
	var v186 uint64
	var v188 uint64
	var v190 uint64
	v4 = 0
	v9 = ctx.R[0]
	v13 = ctx.R[1]
	v17 = ctx.R[2]
	v21 = ctx.R[3]
	v27 = uint32(uint64(uint64(v13)>>2) + uint64(v13))
	v31 = uint32(uint64(uint64(v17)>>2) + uint64(v17))
	v35 = uint32(uint64(uint64(v21)>>2) + uint64(v21))
	v41 := v9 & 3
	v42 = ctx.H[0]
	v46 = ctx.H[1]
	v50 = ctx.H[2]
	v54 = ctx.H[3]
	v58 = ctx.H[4]
	for v62 = 0; v62 < nb_blocks; v62++ {
		v70 = uint64(v42) + uint64(load32_le(in[v4:v4+4]))
		v4 += 4
		v77 = uint64(v46) + uint64(load32_le(in[v4:v4+4]))
		v4 += 4
		v84 = uint64(v50) + uint64(load32_le(in[v4:v4+4]))
		v4 += 4
		v91 = uint64(v54) + uint64(load32_le(in[v4:v4+4]))
		v4 += 4
		v95 = v58 + end
		v105 = (v70*uint64(v9) + v77*uint64(v35)) + ((v84 * uint64(v31)) + (v91*uint64(v27) + uint64(v95*uint32(uint64(uint64(v9)>>2)*5))))
		v115 = (v70*uint64(v13) + v77*uint64(v9)) + ((v84 * uint64(v35)) + (v91*uint64(v31) + uint64(v95*v27)))
		v125 = (v70*uint64(v17) + v77*uint64(v13)) + ((v84 * uint64(v9)) + (v91*uint64(v35) + uint64(v95*v31)))
		v135 = (v70*uint64(v21) + v77*uint64(v17)) + ((v84 * uint64(v13)) + (v91*uint64(v9) + uint64(v95*v35)))
		v138 = uint32(uint64(v95*v41) + uint64(v135>>32))
		v148 = v105 & 0xffffffff
		v149 = (uint64(uint64(v138)>>2) * 5) + v148
		v154 = v115 & 0xffffffff
		v158 = (uint64(v149>>32) + v154) + uint64(v105>>32)
		v163 = v125 & 0xffffffff
		v167 = (uint64(v158>>32) + v163) + uint64(v115>>32)
		v172 = v135 & 0xffffffff
		v176 = (uint64(v167>>32) + v172) + uint64(v125>>32)
		v181 = v138 & 3
		v184 = v149 & 0xffffffff
		v42 = uint32(v184)
		v186 = v158 & 0xffffffff
		v46 = uint32(v186)
		v188 = v167 & 0xffffffff
		v50 = uint32(v188)
		v190 = v176 & 0xffffffff
		v54 = uint32(v190)
		v58 = uint32(uint64(v176>>32) + uint64(v181))
	}
	ctx.H[0] = v42
	ctx.H[1] = v46
	ctx.H[2] = v50
	ctx.H[3] = v54
	ctx.H[4] = v58
}

func Crypto_poly1305_init(ctx *Crypto_poly1305_ctx, key []byte) {
	var v27 uint32
	var v29 uint64
	var v37 uint32
	clear(ctx.H[:5])
	ctx.C_idx = 0
	load32_le_buf(ctx.R[:], key[:], uint64(4))
	load32_le_buf(ctx.Pad[:], key[16:], uint64(4))
	v27 = ctx.R[0] & 0xfffffff
	ctx.R[0] = v27
	for v29 = 1; v29 < 4; v29++ {
		v37 = ctx.R[v29] & 0xffffffc
		ctx.R[v29] = v37
	}
}

func Crypto_poly1305_update(ctx *Crypto_poly1305_ctx, message []byte, message_size uint64) {
	var v3 uint64
	var v14 uint64
	var v15 uint64
	var v24 uint64
	var v49 uint64
	var v59 uint64
	v3 = 0
	_ = v3
	if message_size == 0 {
		return
	}
	v14 = min(gap(ctx.C_idx, 16), message_size)
	for v15 = 0; v15 < v14; v15++ {
		ctx.C[ctx.C_idx] = message[v3]
		v24 = ctx.C_idx + 1
		ctx.C_idx = v24
		v3++
		message_size--
	}
	if ctx.C_idx == 16 {
		poly_blocks(ctx, ctx.C[:], uint64(1), uint32(1))
		ctx.C_idx = 0
	}
	v40 := uint64(message_size >> 4)
	poly_blocks(ctx, message[v3:], v40, uint32(1))
	v3 += uint64(v40 << 4)
	v48 := message_size & 15
	message_size = v48
	for v49 = 0; v49 < message_size; v49++ {
		ctx.C[ctx.C_idx] = message[v3+v49]
		v59 = ctx.C_idx + 1
		ctx.C_idx = v59
	}
}

func Crypto_poly1305_final(ctx *Crypto_poly1305_ctx, mac []byte) {
	var v6 uint64
	var v25 uint64
	_ = 0
	if ctx.C_idx != 0 {
		for v6 = 0; v6 < (uint64(16) - ctx.C_idx); v6++ {
			ctx.C[ctx.C_idx+v6] = 0
		}
		ctx.C[ctx.C_idx] = 1
		poly_blocks(ctx, ctx.C[:], uint64(1), uint32(0))
	}
	v25 = 5
	v25 += uint64(ctx.H[0])
	v25 = uint64(v25 >> 32)
	v25 += uint64(ctx.H[1])
	v25 = uint64(v25 >> 32)
	v25 += uint64(ctx.H[2])
	v25 = uint64(v25 >> 32)
	v25 += uint64(ctx.H[3])
	v25 = uint64(v25 >> 32)
	v25 += uint64(ctx.H[4])
	v25 = uint64(v25>>2) * 5
	v25 += (uint64(ctx.H[0]) + uint64(ctx.Pad[0]))
	store32_le(mac[int(0*4):], uint32(v25))
	v25 = uint64(v25 >> 32)
	v25 += (uint64(ctx.H[1]) + uint64(ctx.Pad[1]))
	store32_le(mac[int(1*4):], uint32(v25))
	v25 = uint64(v25 >> 32)
	v25 += (uint64(ctx.H[2]) + uint64(ctx.Pad[2]))
	store32_le(mac[int(2*4):], uint32(v25))
	v25 = uint64(v25 >> 32)
	v25 += (uint64(ctx.H[3]) + uint64(ctx.Pad[3]))
	store32_le(mac[int(3*4):], uint32(v25))
	v25 = uint64(v25 >> 32)
	*ctx = Crypto_poly1305_ctx{}
	runtime.KeepAlive(ctx)
}

func Crypto_poly1305(mac []byte, message []byte, message_size uint64, key []byte) {
	var v5 *Crypto_poly1305_ctx
	var v4 Crypto_poly1305_ctx
	v5 = &v4
	Crypto_poly1305_init(v5, key[:])
	Crypto_poly1305_update(v5, message[:], message_size)
	Crypto_poly1305_final(v5, mac[:])
}
