// Code generated by sgoiter emit go127; DO NOT EDIT.
package c2quic

type C2quic_vint_t struct {
	Value  uint64
	Nbytes uint32
	Status uint32
}

type C2quic_cursor_t struct {
	Off    uint32
	Status uint32
	Value  uint64
	Nbytes uint32
	Pad    uint32
}

type C2quic_batch8_t struct {
	Offs   [8]uint32
	Vals   [8]uint64
	Nbytes [8]uint32
	Status [8]uint32
}

type C2quic_hp_io_t struct {
	Sample [16]byte
	Mask   [5]byte
	Pad    [3]byte
	Pn_len uint32
	Pn     uint64
}

type C2quic_frame_t struct {
	Typ         uint32
	Flags       uint32
	Id          uint64
	Offset      uint64
	Length      uint64
	Extra       uint64
	Payload_off uint32
	Payload_len uint32
}

type C2quic_frame_slab_t struct {
	Frames [64]C2quic_frame_t
	N      uint32
	Status uint32
}

var C2quic_vint_len_tab = [4]uint32{1, 2, 4, 8}

func C2quic_select64(cond uint64, a uint64, b uint64) uint64 {
	var v9 uint64
	v5 := func() uint64 {
		if cond != 0 {
			return 1
		}
		return 0
	}()
	v9 = uint64(-int(int64(v5)))
	v10 := a & v9
	v12 := b & ^v9
	return uint64(v10 | v12)
}

func C2quic_vint_nbytes(value uint64) uint32 {
	var v2 uint32
	v2 = 0
	v5 := func() uint32 {
		if value >= 64 {
			return 1
		}
		return 0
	}()
	v2 += v5
	v9 := func() uint32 {
		if value >= 0x4000 {
			return 1
		}
		return 0
	}()
	v2 += v9
	v13 := func() uint32 {
		if value >= 0x40000000 {
			return 1
		}
		return 0
	}()
	v2 += v13
	return uint32(C2quic_vint_len_tab[v2])
}

func C2quic_vint_decode(buf []byte, len_ uint32, off uint32, out *C2quic_vint_t) uint32 {
	var v8 uint32
	var v28 uint32
	if uint32(len(buf)) < len_ {
		len_ = uint32(len(buf))
	}
	v9 := uint64(0)
	_ = v9
	if out == nil {
		return 3
	}
	out.Value = 0
	out.Nbytes = 0
	out.Status = 1
	if (buf == nil) || (off >= len_) {
		return 1
	}
	v28 = uint32(C2quic_vint_len_tab[int(uint32(uint32(buf[int(uint32(v9)+off)])>>6))])
	if (len_ - off) < v28 {
		return 1
	}
	v34 := buf[int(uint32(v9)+off)] & 63
	out.Value = uint64(v34)
	for v8 = 1; v8 < v28; v8++ {
		out.Value = uint64(out.Value<<8) | uint64(buf[int(uint32(v9)+(off+v8))])
	}
	out.Nbytes = v28
	out.Status = 0
	return 0
}

func C2quic_vint_encode(value uint64, buf []byte, len_ uint32, off uint32, out *C2quic_vint_t) uint32 {
	var v6 uint32
	var v7 uint32
	var v63 uint64
	if uint32(len(buf)) < len_ {
		len_ = uint32(len(buf))
	}
	v10 := uint64(0)
	_ = v10
	if out == nil {
		return 3
	}
	out.Value = value
	out.Nbytes = 0
	out.Status = 2
	if value >= 0x4000000000000000 {
		return 2
	}
	v18 := C2quic_vint_nbytes(value)
	v6 = 0
	v21 := func() uint32 {
		if v18 == 2 {
			return 1
		}
		return 0
	}()
	v6 = uint32(C2quic_select64(uint64(v21), uint64(1), uint64(v6)))
	v26 := func() uint32 {
		if v18 == 4 {
			return 1
		}
		return 0
	}()
	v6 = uint32(C2quic_select64(uint64(v26), uint64(2), uint64(v6)))
	v31 := func() uint32 {
		if v18 == 8 {
			return 1
		}
		return 0
	}()
	v6 = uint32(C2quic_select64(uint64(v31), uint64(3), uint64(v6)))
	if buf == nil {
		out.Status = 1
		return 1
	}
	if off > len_ {
		out.Status = 1
		return 1
	}
	if (len_ - off) < v18 {
		out.Status = 1
		return 1
	}
	for v7 = 0; v7 < v18; v7++ {
		v63 = uint64((value|uint64(uint64(v6)<<byte(uint32(v18<<3)-2)))>>byte(((v18-1)-v7)<<3)) & 0xff
		buf[int(uint32(v10)+(off+v7))] = byte(v63)
	}
	out.Nbytes = v18
	out.Status = 0
	return 0
}

func C2quic_vint_decode_batch8_scalar(buf []byte, len_ uint32, b *C2quic_batch8_t) {
	var v3 int
	var v17 *C2quic_vint_t
	if uint32(len(buf)) < len_ {
		len_ = uint32(len(buf))
	}
	_ = 0
	var v4 C2quic_vint_t
	if b == nil {
		return
	}
	for v3 = 0; v3 < 8; v3++ {
		v4.Value = 0
		v4.Nbytes = 0
		v4.Status = 3
		v17 = &v4
		C2quic_vint_decode(buf[:], len_, b.Offs[v3], v17)
		b.Vals[v3] = v4.Value
		b.Nbytes[v3] = v4.Nbytes
		b.Status[v3] = v4.Status
	}
}

func C2quic_vint_decode_batch8(buf []byte, len_ uint32, b *C2quic_batch8_t) {
	if uint32(len(buf)) < len_ {
		len_ = uint32(len(buf))
	}
	C2quic_vint_decode_batch8_scalar(buf[:], len_, b)
}

func C2quic_hp_sample(pkt []byte, len_ uint32, pn_off uint32, io *C2quic_hp_io_t) uint32 {
	var v5 uint32
	if uint32(len(pkt)) < len_ {
		len_ = uint32(len(pkt))
	}
	if (pkt == nil) || (io == nil) {
		return 3
	}
	if pn_off > 0xfffffffb {
		return 1
	}
	v15 := pn_off + 4
	if (len_ < v15) || ((len_ - v15) < 16) {
		return 1
	}
	for v5 = 0; v5 < 16; v5++ {
		io.Sample[v5] = pkt[v15+v5]
	}
	return 0
}

func C2quic_hp_apply(pkt []byte, len_ uint32, pn_off uint32, pn_len uint32, io *C2quic_hp_io_t) uint32 {
	var v6 uint32
	if uint32(len(pkt)) < len_ {
		len_ = uint32(len(pkt))
	}
	if uint32(len(pkt)) < pn_len {
		pn_len = uint32(len(pkt))
	}
	if ((pkt == nil) || (io == nil)) || (len_ == 0) {
		return 3
	}
	if (pn_len < 1) || (pn_len > 4) {
		return 3
	}
	if (pn_off >= len_) || ((len_ - pn_off) < pn_len) {
		return 1
	}
	v28 := pkt[0]
	v30 := v28 & 0x80
	v32 := func() uint32 {
		if v30 != 0 {
			return 1
		}
		return 0
	}()
	v43 := io.Mask[0] & byte(uint32(C2quic_select64(uint64(v32), uint64(15), uint64(31))))
	pkt[0] = v28 ^ v43
	for v6 = 0; v6 < pn_len; v6++ {
		pkt[pn_off+v6] = pkt[pn_off+v6] ^ io.Mask[v6+1]
	}
	return 0
}

func C2quic_hp_remove(pkt []byte, len_ uint32, pn_off uint32, io *C2quic_hp_io_t) uint32 {
	var v6 uint32
	var v40 uint32
	if uint32(len(pkt)) < len_ {
		len_ = uint32(len(pkt))
	}
	if ((pkt == nil) || (io == nil)) || (len_ == 0) {
		return 3
	}
	v18 := pkt[0]
	v20 := v18 & 0x80
	v22 := func() uint32 {
		if v20 != 0 {
			return 1
		}
		return 0
	}()
	v33 := io.Mask[0] & byte(uint32(C2quic_select64(uint64(v22), uint64(15), uint64(31))))
	v34 := v18 ^ v33
	v37 := v34 & 3
	v40 = uint32(v37 + 1)
	if (pn_off >= len_) || ((len_ - pn_off) < v40) {
		return 1
	}
	pkt[0] = v34
	for v6 = 0; v6 < v40; v6++ {
		pkt[pn_off+v6] = pkt[pn_off+v6] ^ io.Mask[v6+1]
	}
	io.Pn_len = v40
	return 0
}

func C2quic_hp_read_pn(pkt []byte, len_ uint32, pn_off uint32, pn_len uint32, io *C2quic_hp_io_t) uint32 {
	var v5 uint64
	var v6 uint32
	if uint32(len(pkt)) < len_ {
		len_ = uint32(len(pkt))
	}
	if uint32(len(pkt)) < pn_len {
		pn_len = uint32(len(pkt))
	}
	v7 := uint64(0)
	_ = v7
	if io == nil {
		return 3
	}
	io.Pn = 0
	if ((pkt == nil) || (pn_len < 1)) || (pn_len > 4) {
		return 3
	}
	if (pn_off > len_) || ((len_ - pn_off) < pn_len) {
		return 1
	}
	v5 = 0
	for v6 = 0; v6 < pn_len; v6++ {
		v5 = uint64(v5<<8) | uint64(pkt[int(uint32(v7)+(pn_off+v6))])
	}
	io.Pn = v5
	return 0
}

func C2quic_eat_vint(buf []byte, len_ uint32, cur *C2quic_cursor_t) uint32 {
	var v10 *C2quic_vint_t
	if uint32(len(buf)) < len_ {
		len_ = uint32(len(buf))
	}
	_ = 0
	var v3 C2quic_vint_t
	if cur == nil {
		return 3
	}
	v10 = &v3
	v11 := C2quic_vint_decode(buf[:], len_, cur.Off, v10)
	cur.Status = v11
	cur.Value = v3.Value
	cur.Nbytes = v3.Nbytes
	if v11 != 0 {
		return uint32(v11)
	}
	cur.Off += v3.Nbytes
	return 0
}

func C2quic_unpack_frames(buf []byte, len_ uint32, slab *C2quic_frame_slab_t) uint32 {
	var v4 uint32
	var v6 uint32
	var v7 uint64
	var v8 uint64
	var v35 *C2quic_cursor_t
	var v43 uint32
	var v77 bool
	var v79 uint32
	var v83 *C2quic_cursor_t
	var v90 uint32
	var v93 *C2quic_cursor_t
	var v100 uint32
	var v103 *C2quic_cursor_t
	var v149 *C2quic_cursor_t
	var v156 *C2quic_cursor_t
	var v163 *C2quic_cursor_t
	var v170 *C2quic_cursor_t
	var v181 *C2quic_cursor_t
	var v185 *C2quic_cursor_t
	var v192 *C2quic_cursor_t
	var v196 *C2quic_cursor_t
	var v200 *C2quic_cursor_t
	var v214 *C2quic_cursor_t
	var v221 *C2quic_cursor_t
	var v228 *C2quic_cursor_t
	var v246 *C2quic_cursor_t
	if uint32(len(buf)) < len_ {
		len_ = uint32(len(buf))
	}
	v9 := uint64(0)
	_ = v9
	var v3 C2quic_cursor_t
	if slab == nil {
		return 3
	}
	slab.N = 0
	slab.Status = 0
	if buf == nil {
		slab.Status = 3
		return 3
	}
	v3.Off = 0
	v3.Status = 0
	v3.Value = 0
	v3.Nbytes = 0
	v3.Pad = 0
	v4 = 0
	for v3.Off < len_ {
		if buf[int(uint32(v9)+v3.Off)] == 0 {
			v3.Off += 1
			continue
		}
		v35 = &v3
		v6 = C2quic_eat_vint(buf[v9:], len_, v35)
		if v6 != 0 {
			slab.Status = v6
			return v6
		}
		if v3.Value > 0xffffffff {
			slab.Status = 3
			return 3
		}
		v43 = uint32(v3.Value)
		if v4 >= 64 {
			slab.N = v4
			slab.Status = 4
			return 4
		}
		slab.Frames[v4].Typ = v43
		slab.Frames[v4].Flags = 0
		slab.Frames[v4].Id = 0
		slab.Frames[v4].Offset = 0
		slab.Frames[v4].Length = 0
		slab.Frames[v4].Extra = 0
		slab.Frames[v4].Payload_off = 0
		slab.Frames[v4].Payload_len = 0
		if v43 == 1 {
			v4++
			continue
		}
		v77 = (v43 >= 8) && (v43 <= 15)
		if v77 {
			v79 = v43 & 7
			slab.Frames[v4].Flags = v79
			v83 = &v3
			v6 = C2quic_eat_vint(buf[v9:], len_, v83)
			if v6 != 0 {
				slab.Status = v6
				return v6
			}
			slab.Frames[v4].Id = v3.Value
			v90 = v43 & 4
			if v90 != 0 {
				v93 = &v3
				v6 = C2quic_eat_vint(buf[v9:], len_, v93)
				if v6 != 0 {
					slab.Status = v6
					return v6
				}
				slab.Frames[v4].Offset = v3.Value
			}
			v100 = v43 & 2
			if v100 != 0 {
				v103 = &v3
				v6 = C2quic_eat_vint(buf[v9:], len_, v103)
				if v6 != 0 {
					slab.Status = v6
					return v6
				}
				slab.Frames[v4].Length = v3.Value
			} else {
				slab.Frames[v4].Length = uint64(len_ - v3.Off)
			}
			if slab.Frames[v4].Length > uint64(len_-v3.Off) {
				slab.Status = 1
				return 1
			}
			slab.Frames[v4].Payload_off = v3.Off
			slab.Frames[v4].Payload_len = uint32(slab.Frames[v4].Length)
			v3.Off += uint32(slab.Frames[v4].Length)
			v4++
			continue
		}
		if (v43 == 2) || (v43 == 3) {
			if v43 == 3 {
				slab.Frames[v4].Flags = 8
			}
			v149 = &v3
			v6 = C2quic_eat_vint(buf[v9:], len_, v149)
			if v6 != 0 {
				slab.Status = v6
				return v6
			}
			slab.Frames[v4].Id = v3.Value
			v156 = &v3
			v6 = C2quic_eat_vint(buf[v9:], len_, v156)
			if v6 != 0 {
				slab.Status = v6
				return v6
			}
			slab.Frames[v4].Offset = v3.Value
			v163 = &v3
			v6 = C2quic_eat_vint(buf[v9:], len_, v163)
			if v6 != 0 {
				slab.Status = v6
				return v6
			}
			v7 = v3.Value
			slab.Frames[v4].Length = v7
			v170 = &v3
			v6 = C2quic_eat_vint(buf[v9:], len_, v170)
			if v6 != 0 {
				slab.Status = v6
				return v6
			}
			slab.Frames[v4].Extra = v3.Value
			slab.Frames[v4].Payload_off = v3.Off
			for v8 = 0; v8 < v7; v8++ {
				v181 = &v3
				v6 = C2quic_eat_vint(buf[v9:], len_, v181)
				if v6 != 0 {
					slab.Status = v6
					return v6
				}
				v185 = &v3
				v6 = C2quic_eat_vint(buf[v9:], len_, v185)
				if v6 != 0 {
					slab.Status = v6
					return v6
				}
			}
			if v43 == 3 {
				v192 = &v3
				v6 = C2quic_eat_vint(buf[v9:], len_, v192)
				if v6 != 0 {
					slab.Status = v6
					return v6
				}
				v196 = &v3
				v6 = C2quic_eat_vint(buf[v9:], len_, v196)
				if v6 != 0 {
					slab.Status = v6
					return v6
				}
				v200 = &v3
				v6 = C2quic_eat_vint(buf[v9:], len_, v200)
				if v6 != 0 {
					slab.Status = v6
					return v6
				}
			}
			slab.Frames[v4].Payload_len = v3.Off - slab.Frames[v4].Payload_off
			v4++
			continue
		}
		if v43 == 4 {
			v214 = &v3
			v6 = C2quic_eat_vint(buf[v9:], len_, v214)
			if v6 != 0 {
				slab.Status = v6
				return v6
			}
			slab.Frames[v4].Id = v3.Value
			v221 = &v3
			v6 = C2quic_eat_vint(buf[v9:], len_, v221)
			if v6 != 0 {
				slab.Status = v6
				return v6
			}
			slab.Frames[v4].Extra = v3.Value
			v228 = &v3
			v6 = C2quic_eat_vint(buf[v9:], len_, v228)
			if v6 != 0 {
				slab.Status = v6
				return v6
			}
			slab.Frames[v4].Length = v3.Value
			v4++
			continue
		}
		if (v43 == 48) || (v43 == 49) {
			if v43 == 49 {
				slab.Frames[v4].Flags = 2
				v246 = &v3
				v6 = C2quic_eat_vint(buf[v9:], len_, v246)
				if v6 != 0 {
					slab.Status = v6
					return v6
				}
				slab.Frames[v4].Length = v3.Value
			} else {
				slab.Frames[v4].Length = uint64(len_ - v3.Off)
			}
			if slab.Frames[v4].Length > uint64(len_-v3.Off) {
				slab.Status = 1
				return 1
			}
			slab.Frames[v4].Payload_off = v3.Off
			slab.Frames[v4].Payload_len = uint32(slab.Frames[v4].Length)
			v3.Off += uint32(slab.Frames[v4].Length)
			v4++
			continue
		}
		slab.Status = 3
		return 3
	}
	slab.N = v4
	return 0
}
