// Code generated by sgoiter emit go127; DO NOT EDIT.
// sgoiter-stamp: sha256=d1982c815cee7e89b389aa5d06a44c58208dafa0909d00ae23f422d3382d75ab
package c2ordered_swiss

type Swiss_val_t struct {
	Type_ uint32
	Flags uint32
	I64   int64
}

type Swiss_element_t struct {
	Val     Swiss_val_t
	Hash    uint64
	Str_key []byte
	Str_len uint32
	Int_key int64
}

type Swiss_table_t struct {
	Ctrl          []byte
	Ctrl_to_dense []uint32
	Entries       []Swiss_element_t
	Capacity_hash uint32
	Capacity_data uint32
	N_elements    uint32
	N_used        uint32
	N_tombstones  uint32
	Flags         uint32
}

func Swiss_hash_str(str []byte, len_ uint32) uint64 {
	var v2 uint64
	var v4 uint32
	if uint32(len(str)) < len_ {
		len_ = uint32(len(str))
	}
	v2 = 0x1505
	for v4 = 0; v4 < len_; v4++ {
		v2 = (uint64(v2<<5) + v2) + uint64(str[v4])
	}
	v15 := func() uint64 {
		if v2 == 0 {
			return 1
		}
		return 0
	}()
	return uint64(v2 | v15)
}

func Swiss_hash_int(val int64) uint64 {
	var v1 uint64
	v1 = uint64(val) + 0x9e3779b97f4a7c15
	v1 = (v1 ^ uint64(v1>>30)) * 0xbf58476d1ce4e5b9
	v1 = (v1 ^ uint64(v1>>27)) * 0x94d049bb133111eb
	return uint64(v1 ^ uint64(v1>>31))
}

func swiss_match_tag_16(ctrl_group []byte, h2 byte) uint32 {
	var v2 uint32
	var v4 uint32
	v2 = 0
	for v4 = 0; v4 < 16; v4++ {
		if ctrl_group[v4] == h2 {
			v2 |= (1 << byte(v4))
		}
	}
	return v2
}

func swiss_match_empty_16(ctrl_group []byte) uint32 {
	var v1 uint32
	var v3 uint32
	v1 = 0
	for v3 = 0; v3 < 16; v3++ {
		if ctrl_group[v3] == 0x80 {
			v1 |= (1 << byte(v3))
		}
	}
	return v1
}

func swiss_match_free_16(ctrl_group []byte) uint32 {
	var v1 uint32
	var v3 uint32
	v1 = 0
	for v3 = 0; v3 < 16; v3++ {
		if (ctrl_group[v3] == 0x80) || (ctrl_group[v3] == 0xfe) {
			v1 |= (1 << byte(v3))
		}
	}
	return v1
}

func swiss_lowest_bit(mask uint32) uint32 {
	var v1 uint32
	v1 = 0
	for {
		v5 := mask & (1 << byte(v1))
		if v5 != 0 {
			break
		}
		v1++
	}
	return v1
}

func swiss_ctrl_set(ht *Swiss_table_t, slot_idx uint32, c byte) {
	ht.Ctrl[slot_idx] = c
	if slot_idx < 16 {
		ht.Ctrl[ht.Capacity_hash+slot_idx] = c
	}
}

func swiss_ctrl_usable(ht *Swiss_table_t) bool {
	var v1 uint32
	var v9 bool
	var v12 bool
	var v18 bool
	v1 = ht.Capacity_hash
	v9 = (ht.Ctrl != nil) && (ht.Ctrl_to_dense != nil)
	v12 = v9 && (v1 >= 16)
	v15 := v1 & (v1 - 1)
	v18 = v12 && (v15 == 0)
	return bool(v18)
}

func swiss_load_ok(ht *Swiss_table_t) bool {
	return bool((((uint64(ht.N_used) + uint64(ht.N_tombstones)) + 1) * 8) < (uint64(ht.Capacity_hash) * 7))
}

func swiss_ctrl_find_free(ht *Swiss_table_t, hash uint64, slot_out *uint32) bool {
	var v7 uint32
	var v12 uint32
	var v18 uint32
	var v22 uint32
	v6 := ht.Capacity_hash - 1
	v10 := uint64(hash>>7) & uint64(v6)
	v7 = uint32(v10)
	v12 = 0
	for v12 <= v6 {
		v18 = swiss_match_free_16(ht.Ctrl[v7:])
		if v18 != 0 {
			v22 = (v7 + swiss_lowest_bit(v18)) & v6
			*slot_out = v22
			return true
		}
		v12 += 16
		v7 = (v7 + v12) & v6
	}
	return false
}

func swiss_ctrl_claim(ht *Swiss_table_t, slot_idx uint32, hash uint64, dense_idx uint32) {
	var v11 uint32
	_ = 0
	if ht.Ctrl[slot_idx] == 0xfe {
		v11 = ht.N_tombstones - 1
		ht.N_tombstones = v11
	}
	v13 := hash & 0x7f
	swiss_ctrl_set(ht, slot_idx, byte(v13))
	ht.Ctrl_to_dense[slot_idx] = dense_idx
}

func swiss_ctrl_place(ht *Swiss_table_t, hash uint64, dense_idx uint32) bool {
	var v3 uint32
	v3 = 0
	v6 := swiss_ctrl_find_free(ht, hash, &v3)
	if v6 == false {
		return false
	}
	swiss_ctrl_claim(ht, v3, hash, dense_idx)
	return true
}

func swiss_ctrl_unlink(ht *Swiss_table_t, hash uint64, dense_idx uint32) {
	var v11 uint32
	var v16 uint32
	var v21 uint32
	var v28 uint32
	var v37 uint32
	_ = 0
	v6 := ht.Capacity_hash - 1
	v9 := hash & 0x7f
	v14 := uint64(hash>>7) & uint64(v6)
	v11 = uint32(v14)
	v16 = 0
	for v16 <= v6 {
		v21 = swiss_match_tag_16(ht.Ctrl[v11:], byte(v9))
		for v21 != 0 {
			v28 = (v11 + swiss_lowest_bit(v21)) & v6
			if ht.Ctrl_to_dense[v28] == dense_idx {
				swiss_ctrl_set(ht, v28, uint8(0xfe))
				v37 = ht.N_tombstones + 1
				ht.N_tombstones = v37
				return
			}
			v21 &= (v21 - 1)
		}
		if swiss_match_empty_16(ht.Ctrl[v11:]) != 0 {
			return
		}
		v16 += 16
		v11 = (v11 + v16) & v6
	}
}

func swiss_ctrl_rebuild(ht *Swiss_table_t) {
	var v7 uint32
	var v13 uint32
	var v19 uint64
	_ = 0
	v5 := ht.Capacity_hash + 16
	func() {
		p := ht.Ctrl[:]
		v := byte(128)
		n := int(v5)
		for i := 0; i < n && i < len(p); i++ {
			p[i] = v
		}
	}()
	v7 = 0
	for v7 < ht.N_used {
		if ht.Entries[v7].Val.Type_ == 0 {
			v13 = v7 + 1
			v7 = v13
			continue
		}
		v19 = ht.Entries[v7].Hash
		if ht.Entries[v7].Str_key == nil {
			v19 = Swiss_hash_int(ht.Entries[v7].Int_key)
			ht.Entries[v7].Hash = v19
		}
		swiss_ctrl_place(ht, v19, v7)
		v13 = v7 + 1
		v7 = v13
	}
}

func Swiss_init(ht *Swiss_table_t, ctrl_buf []byte, slots_buf []uint32, entries_buf []Swiss_element_t, cap_hash uint32, cap_data uint32) {
	var v16 bool
	ht.Ctrl = ctrl_buf[:]
	ht.Ctrl_to_dense = slots_buf[:]
	ht.Entries = entries_buf
	ht.Capacity_hash = cap_hash
	ht.Capacity_data = cap_data
	ht.N_elements = 0
	ht.N_used = 0
	ht.N_tombstones = 0
	ht.Flags = 3
	v16 = (ctrl_buf != nil) && (cap_hash > 0)
	if v16 {
		func() {
			p := ctrl_buf[0:]
			v := byte(128)
			n := int(cap_hash + 16)
			for i := 0; i < n && i < len(p); i++ {
				p[i] = v
			}
		}()
	}
}

func Swiss_unpack(ht *Swiss_table_t) bool {
	v3 := ht.Flags & 2
	if v3 == 0 {
		return true
	}
	if swiss_ctrl_usable(ht) == false {
		return false
	}
	v14 := ht.Flags & 0xfffffffd
	ht.Flags = v14
	ht.N_tombstones = 0
	swiss_ctrl_rebuild(ht)
	return true
}

func Swiss_find_str(ht *Swiss_table_t, key []byte, key_len uint32, hash uint64) int {
	var v22 uint32
	var v27 uint32
	var v32 uint32
	var v39 uint32
	var v42 uint32
	var v68 int
	if uint32(len(key)) < key_len {
		key_len = uint32(len(key))
	}
	_ = 0
	v11 := ht.Flags & 2
	if (ht.N_elements == 0) || (v11 != 0) {
		return -1
	}
	v17 := ht.Capacity_hash - 1
	v20 := hash & 0x7f
	v25 := uint64(hash>>7) & uint64(v17)
	v22 = uint32(v25)
	v27 = 0
	for v27 <= v17 {
		v32 = swiss_match_tag_16(ht.Ctrl[v22:], byte(v20))
		for v32 != 0 {
			v39 = (v22 + swiss_lowest_bit(v32)) & v17
			v42 = ht.Ctrl_to_dense[v39]
			if ht.Entries[v42].Val.Type_ != 0 {
				if ht.Entries[v42].Hash == hash {
					if ht.Entries[v42].Str_len == key_len {
						if ht.Entries[v42].Str_key != nil {
							v68 = func(a, b []byte, n int) int {
								for i := 0; i < n && i < len(a) && i < len(b); i++ {
									if a[i] != b[i] {
										if a[i] < b[i] {
											return -1
										}
										return 1
									}
								}
								return 0
							}(ht.Entries[v42].Str_key, key[:], int(key_len))
							if v68 == 0 {
								return int(v42)
							}
						}
					}
				}
			}
			v32 &= (v32 - 1)
		}
		if swiss_match_empty_16(ht.Ctrl[v22:]) != 0 {
			return -1
		}
		v27 += 16
		v22 = (v22 + v27) & v17
	}
	return -1
}

func Swiss_find_int(ht *Swiss_table_t, key int64) int {
	var v15 bool
	var v17 uint32
	var v35 uint32
	var v40 uint32
	var v45 uint32
	var v52 uint32
	var v55 uint32
	_ = 0
	if ht.N_elements == 0 {
		return -1
	}
	v9 := ht.Flags & 2
	if v9 != 0 {
		v15 = (key >= 0) && (key < int64(ht.N_used))
		if v15 {
			v17 = uint32(key)
			if ht.Entries[v17].Val.Type_ != 0 {
				return int(v17)
			}
		}
		return -1
	}
	v26 := Swiss_hash_int(key)
	v30 := ht.Capacity_hash - 1
	v33 := v26 & 0x7f
	v38 := uint64(v26>>7) & uint64(v30)
	v35 = uint32(v38)
	v40 = 0
	for v40 <= v30 {
		v45 = swiss_match_tag_16(ht.Ctrl[v35:], byte(v33))
		for v45 != 0 {
			v52 = (v35 + swiss_lowest_bit(v45)) & v30
			v55 = ht.Ctrl_to_dense[v52]
			if ht.Entries[v55].Val.Type_ != 0 {
				if ht.Entries[v55].Str_key == nil {
					if ht.Entries[v55].Int_key == key {
						return int(v55)
					}
				}
			}
			v45 &= (v45 - 1)
		}
		if swiss_match_empty_16(ht.Ctrl[v35:]) != 0 {
			return -1
		}
		v40 += 16
		v35 = (v35 + v40) & v30
	}
	return -1
}

func Swiss_insert_packed_int(ht *Swiss_table_t, key int64, val_type uint32, val_i64 int64) bool {
	var v18 bool
	var v19 uint32
	var v23 uint32
	var v47 uint32
	_ = 0
	v6 := ht.Flags & 2
	if v6 == 0 {
		return false
	}
	v18 = (key == int64(ht.N_used)) && (ht.N_used < ht.Capacity_data)
	if v18 {
		v19 = ht.N_used
		ht.N_used = v19
		v23 = ht.N_used + 1
		ht.N_used = v23
		ht.Entries[v19].Val.Type_ = val_type
		ht.Entries[v19].Val.Flags = 0
		ht.Entries[v19].Val.I64 = val_i64
		ht.Entries[v19].Hash = 0
		ht.Entries[v19].Str_key = nil
		ht.Entries[v19].Str_len = 0
		ht.Entries[v19].Int_key = key
		v47 = ht.N_elements + 1
		ht.N_elements = v47
		return true
	}
	return false
}

func swiss_append_hashed(ht *Swiss_table_t, hash uint64, str_key []byte, str_len uint32, int_key int64, val_type uint32, val_i64 int64) bool {
	var v12 uint32
	var v28 uint32
	if uint32(len(str_key)) < str_len {
		str_len = uint32(len(str_key))
	}
	_ = 0
	if ht.N_used >= ht.Capacity_data {
		return false
	}
	v12 = 0
	v15 := swiss_ctrl_find_free(ht, hash, &v12)
	if v15 == false {
		return false
	}
	if ht.Ctrl[v12] != 0xfe {
		if swiss_load_ok(ht) == false {
			return false
		}
	}
	v28 = ht.N_used
	swiss_ctrl_claim(ht, v12, hash, v28)
	ht.N_used = v28
	v33 := ht.N_used + 1
	ht.N_used = v33
	ht.Entries[v28].Val.Type_ = val_type
	ht.Entries[v28].Val.Flags = 0
	ht.Entries[v28].Val.I64 = val_i64
	ht.Entries[v28].Hash = hash
	ht.Entries[v28].Str_key = str_key[:]
	ht.Entries[v28].Str_len = str_len
	ht.Entries[v28].Int_key = int_key
	v54 := ht.N_elements + 1
	ht.N_elements = v54
	return true
}

func Swiss_insert_int(ht *Swiss_table_t, key int64, val_type uint32, val_i64 int64) bool {
	if val_type == 0 {
		return false
	}
	v7 := Swiss_find_int(ht, key)
	if v7 >= 0 {
		ht.Entries[v7].Val.Type_ = val_type
		ht.Entries[v7].Val.Flags = 0
		ht.Entries[v7].Val.I64 = val_i64
		return true
	}
	v22 := ht.Flags & 2
	if v22 != 0 {
		if key == int64(ht.N_used) {
			return bool(Swiss_insert_packed_int(ht, key, val_type, val_i64))
		}
		if Swiss_unpack(ht) == false {
			return false
		}
	}
	return bool(swiss_append_hashed(ht, Swiss_hash_int(key), nil, uint32(0), key, val_type, val_i64))
}

func Swiss_insert_str(ht *Swiss_table_t, key []byte, key_len uint32, val_type uint32, val_i64 int64) bool {
	if uint32(len(key)) < key_len {
		key_len = uint32(len(key))
	}
	if (key == nil) || (val_type == 0) {
		return false
	}
	v12 := Swiss_hash_str(key[:], key_len)
	v15 := ht.Flags & 2
	if v15 != 0 {
		if Swiss_unpack(ht) == false {
			return false
		}
	}
	v21 := Swiss_find_str(ht, key[:], key_len, v12)
	if v21 >= 0 {
		ht.Entries[v21].Val.Type_ = val_type
		ht.Entries[v21].Val.Flags = 0
		ht.Entries[v21].Val.I64 = val_i64
		return true
	}
	return bool(swiss_append_hashed(ht, v12, key[:], key_len, int64(0), val_type, val_i64))
}

func Swiss_compact(ht *Swiss_table_t) {
	var v5 uint32
	var v7 uint32
	var v9 uint32
	var v32 bool
	_ = 0
	if ht.N_tombstones == 0 {
		return
	}
	v5 = 0
	v7 = ht.N_used
	for v9 = 0; v9 < v7; v9++ {
		if ht.Entries[v9].Val.Type_ != 0 {
			if v5 != v9 {
				ht.Entries[v5] = ht.Entries[v9]
			}
			v5++
		}
	}
	ht.N_used = v5
	ht.N_tombstones = 0
	v26 := ht.Flags & 2
	v32 = (v26 == 0) && (ht.Ctrl != nil)
	if v32 {
		swiss_ctrl_rebuild(ht)
	}
}

func Swiss_pop(ht *Swiss_table_t) bool {
	var v16 uint32
	var v24 uint32
	var v37 uint32
	var v40 uint32
	var v46 uint32
	var v49 uint32
	_ = 0
	if (ht.N_elements == 0) || (ht.N_used == 0) {
		return false
	}
	for ht.N_used > 0 {
		v16 = ht.N_used - 1
		if ht.Entries[v16].Val.Type_ != 0 {
			v24 = ht.Flags & 2
			if v24 == 0 {
				swiss_ctrl_unlink(ht, ht.Entries[v16].Hash, v16)
			}
			ht.Entries[v16].Val.Type_ = 0
			v37 = ht.N_used - 1
			ht.N_used = v37
			v40 = ht.N_elements - 1
			ht.N_elements = v40
			return true
		}
		if ht.N_tombstones > 0 {
			v46 = ht.N_tombstones - 1
			ht.N_tombstones = v46
		}
		v49 = ht.N_used - 1
		ht.N_used = v49
	}
	return false
}
