// Code generated by sgoiter emit go127; DO NOT EDIT.
// sgoiter-stamp: sha256=2971ffad5651fe2f0cc967378245181b5b0de230ed6b2708ed5b8eed1202f16e
package c2ordered_swiss

type Swiss_val_t struct {
	Type_ uint32
	Flags uint32
	I64   int64
}

type Swiss_element_t struct {
	Val     Swiss_val_t
	Hash    uint64
	Str_key []byte
	Str_len uint32
	Int_key int64
}

type Swiss_table_t struct {
	Ctrl          []byte
	Ctrl_to_dense []uint32
	Entries       []Swiss_element_t
	Capacity_hash uint32
	Capacity_data uint32
	N_elements    uint32
	N_used        uint32
	N_tombstones  uint32
	Flags         uint32
}

func swiss_hash_str(str []byte, len_ uint32) uint64 {
	var v2 uint64
	var v4 uint32
	if uint32(len(str)) < len_ {
		len_ = uint32(len(str))
	}
	v2 = 0x1505
	for v4 = 0; v4 < len_; v4++ {
		v2 = (uint64(v2<<5) + v2) + uint64(str[v4])
	}
	v15 := func() uint64 {
		if v2 == 0 {
			return 1
		}
		return 0
	}()
	return uint64(v2 | v15)
}

func swiss_hash_int(val int64) uint64 {
	var v1 uint64
	v1 = uint64(val) + 0x9e3779b97f4a7c15
	v1 = (v1 ^ uint64(v1>>30)) * 0xbf58476d1ce4e5b9
	v1 = (v1 ^ uint64(v1>>27)) * 0x94d049bb133111eb
	return uint64(v1 ^ uint64(v1>>31))
}

func swiss_match_tag_16(ctrl_group []byte, h2 byte) uint32 {
	var v2 uint32
	var v4 uint32
	v2 = 0
	for v4 = 0; v4 < 16; v4++ {
		if ctrl_group[v4] == h2 {
			v2 |= (1 << byte(v4))
		}
	}
	return v2
}

func swiss_match_empty_16(ctrl_group []byte) uint32 {
	var v1 uint32
	var v3 uint32
	v1 = 0
	for v3 = 0; v3 < 16; v3++ {
		if ctrl_group[v3] == 0x80 {
			v1 |= (1 << byte(v3))
		}
	}
	return v1
}

func Swiss_init(ht *Swiss_table_t, ctrl_buf []byte, slots_buf []uint32, entries_buf []Swiss_element_t, cap_hash uint32, cap_data uint32) {
	var v16 bool
	ht.Ctrl = ctrl_buf[:]
	ht.Ctrl_to_dense = slots_buf[:]
	ht.Entries = entries_buf
	ht.Capacity_hash = cap_hash
	ht.Capacity_data = cap_data
	ht.N_elements = 0
	ht.N_used = 0
	ht.N_tombstones = 0
	ht.Flags = 3
	v16 = (ctrl_buf != nil) && (cap_hash > 0)
	if v16 {
		func() {
			p := ctrl_buf[0:]
			v := byte(128)
			n := int(cap_hash + 16)
			for i := 0; i < n && i < len(p); i++ {
				p[i] = v
			}
		}()
	}
}

func Swiss_find_str(ht *Swiss_table_t, key []byte, key_len uint32, hash uint64) int {
	var v22 uint32
	var v27 uint32
	var v33 uint32
	var v37 uint32
	var v41 uint32
	var v47 uint32
	var v50 uint32
	var v76 int
	if uint32(len(key)) < key_len {
		key_len = uint32(len(key))
	}
	_ = 0
	v11 := ht.Flags & 2
	if (ht.N_elements == 0) || (v11 != 0) {
		return -1
	}
	v17 := ht.Capacity_hash - 1
	v20 := hash & 0x7f
	v25 := uint64(hash>>7) & uint64(v17)
	v22 = uint32(v25)
	v27 = 0
	for {
		v33 = swiss_match_tag_16(ht.Ctrl[v22:], byte(v20))
		for v33 != 0 {
			v37 = 0
			for {
				v41 = v33 & (1 << byte(v37))
				if v41 != 0 {
					break
				}
				v37++
			}
			v47 = (v22 + v37) & v17
			v50 = ht.Ctrl_to_dense[v47]
			if ht.Entries[v50].Val.Type_ != 0 {
				if ht.Entries[v50].Hash == hash {
					if ht.Entries[v50].Str_len == key_len {
						if ht.Entries[v50].Str_key != nil {
							v76 = func(a, b []byte, n int) int {
								for i := 0; i < n && i < len(a) && i < len(b); i++ {
									if a[i] != b[i] {
										if a[i] < b[i] {
											return -1
										}
										return 1
									}
								}
								return 0
							}(ht.Entries[v50].Str_key, key[:], int(key_len))
							if v76 == 0 {
								return int(v50)
							}
						}
					}
				}
			}
			v33 &= (v33 - 1)
		}
		if swiss_match_empty_16(ht.Ctrl[v22:]) != 0 {
			return -1
		}
		v27 += 16
		v22 = (v22 + v27) & v17
	}
}

func Swiss_find_int(ht *Swiss_table_t, key int64) int {
	var v15 bool
	var v17 uint32
	var v35 uint32
	var v40 uint32
	var v46 uint32
	var v50 uint32
	var v54 uint32
	var v60 uint32
	var v63 uint32
	_ = 0
	if ht.N_elements == 0 {
		return -1
	}
	v9 := ht.Flags & 2
	if v9 != 0 {
		v15 = (key >= 0) && (uint32(key) < ht.N_used)
		if v15 {
			v17 = uint32(key)
			if ht.Entries[v17].Val.Type_ != 0 {
				return int(v17)
			}
		}
		return -1
	}
	v26 := swiss_hash_int(key)
	v30 := ht.Capacity_hash - 1
	v33 := v26 & 0x7f
	v38 := uint64(v26>>7) & uint64(v30)
	v35 = uint32(v38)
	v40 = 0
	for {
		v46 = swiss_match_tag_16(ht.Ctrl[v35:], byte(v33))
		for v46 != 0 {
			v50 = 0
			for {
				v54 = v46 & uint32(int64(1<<byte(v50)))
				if v54 != 0 {
					break
				}
				v50++
			}
			v60 = (v35 + v50) & v30
			v63 = ht.Ctrl_to_dense[v60]
			if ht.Entries[v63].Val.Type_ != 0 {
				if ht.Entries[v63].Str_key == nil {
					if ht.Entries[v63].Int_key == key {
						return int(v63)
					}
				}
			}
			v46 &= (v46 - 1)
		}
		if swiss_match_empty_16(ht.Ctrl[v35:]) != 0 {
			return -1
		}
		v40 += 16
		v35 = (v35 + v40) & v30
	}
}

func Swiss_insert_packed_int(ht *Swiss_table_t, key int64, val_type uint32, val_i64 int64) bool {
	var v18 bool
	var v19 uint32
	var v23 uint32
	var v47 uint32
	_ = 0
	v6 := ht.Flags & 2
	if v6 == 0 {
		return false
	}
	v18 = (key == int64(ht.N_used)) && (ht.N_used < ht.Capacity_data)
	if v18 {
		v19 = ht.N_used
		ht.N_used = v19
		v23 = ht.N_used + 1
		ht.N_used = v23
		ht.Entries[v19].Val.Type_ = val_type
		ht.Entries[v19].Val.Flags = 0
		ht.Entries[v19].Val.I64 = val_i64
		ht.Entries[v19].Hash = 0
		ht.Entries[v19].Str_key = nil
		ht.Entries[v19].Str_len = 0
		ht.Entries[v19].Int_key = key
		v47 = ht.N_elements + 1
		ht.N_elements = v47
		return true
	}
	return false
}

func Swiss_compact(ht *Swiss_table_t) {
	var v5 uint32
	var v7 uint32
	var v9 uint32
	var v32 bool
	var v33 uint32
	var v37 uint32
	var v43 uint32
	var v48 uint64
	var v64 uint64
	var v65 byte
	var v66 uint32
	var v69 uint64
	var v71 uint32
	var v79 uint32
	var v81 uint32
	var v85 uint32
	var v91 uint32
	_ = 0
	if ht.N_tombstones == 0 {
		return
	}
	v5 = 0
	v7 = ht.N_used
	for v9 = 0; v9 < v7; v9++ {
		if ht.Entries[v9].Val.Type_ != 0 {
			if v5 != v9 {
				ht.Entries[v5] = ht.Entries[v9]
			}
			v5++
		}
	}
	ht.N_used = v5
	ht.N_tombstones = 0
	v26 := ht.Flags & 2
	v32 = (v26 == 0) && (ht.Ctrl != nil)
	if v32 {
		v33 = ht.Capacity_hash
		v37 = v33 - 1
		func() {
			p := ht.Ctrl[:]
			v := byte(128)
			n := int(v33 + 16)
			for i := 0; i < n && i < len(p); i++ {
				p[i] = v
			}
		}()
		for v43 = 0; v43 < ht.N_used; v43++ {
			v48 = ht.Entries[v43].Hash
			if ht.Entries[v43].Str_key == nil {
				v48 = swiss_hash_int(ht.Entries[v43].Int_key)
				ht.Entries[v43].Hash = v48
			}
			v64 = v48 & 0x7f
			v65 = byte(v64)
			v69 = uint64(v48>>7) & uint64(v37)
			v66 = uint32(v69)
			v71 = 0
			for {
				v79 = swiss_match_empty_16(ht.Ctrl[v66:])
				if v79 != 0 {
					v81 = 0
					for {
						v85 = v79 & uint32(int64(1<<byte(v81)))
						if v85 != 0 {
							break
						}
						v81++
					}
					v91 = (v66 + v81) & v37
					ht.Ctrl[v91] = v65
					ht.Ctrl_to_dense[v91] = v43
					if v91 < 16 {
						ht.Ctrl[v33+v91] = v65
					}
					break
				}
				v71 += 16
				v66 = (v66 + v71) & v37
			}
		}
	}
}

func Swiss_pop(ht *Swiss_table_t) bool {
	var v16 uint32
	var v28 uint32
	var v31 uint32
	var v35 uint32
	_ = 0
	if (ht.N_elements == 0) || (ht.N_used == 0) {
		return false
	}
	for ht.N_used > 0 {
		v16 = ht.N_used - 1
		if ht.Entries[v16].Val.Type_ != 0 {
			ht.Entries[v16].Val.Type_ = 0
			v28 = ht.N_used - 1
			ht.N_used = v28
			v31 = ht.N_elements - 1
			ht.N_elements = v31
			return true
		}
		v35 = ht.N_used - 1
		ht.N_used = v35
	}
	return false
}
