// Code generated by sgoiter emit go127; DO NOT EDIT.
// sgoiter-stamp: sha256=0268a84e2b1468cfab357aa5455f204172f5eb9fa146492da6a199a6a527b054
package c2vtparser

type C2_cell_t struct {
	Rune_ uint32
	Fg    byte
	Bg    byte
	Flags byte
	Width byte
}

type C2_vt_parser_t struct {
	State        int
	Cursor_x     int
	Cursor_y     int
	Cur_fg       int
	Cur_bg       int
	Cur_attr     int
	Width        int
	Height       int
	Prm          int
	Nparams      int
	Params       [4]int
	Pending_utf8 [4]byte
	Pending_len  int
}

func C2_grid_clear(cells []C2_cell_t, n int, fg byte, bg byte) {
	var v4 int
	if len(cells) < n {
		n = int(len(cells))
	}
	v4 = 0
	{
		_cells := cells[:n]
		for v4 = 0; v4 < n; v4++ {
			_cells[v4].Rune_ = 32
			_cells[v4].Fg = fg
			_cells[v4].Bg = bg
			_cells[v4].Flags = 0
			_cells[v4].Width = 1
		}
	}
}

func C2_grid_clear_row(cells []C2_cell_t, y int, stride int, width int, fg byte, bg byte) {
	var v6 int
	var v13 int
	for v6 = 0; v6 < width; v6++ {
		v13 = (y * stride) + v6
		cells[v13].Rune_ = 32
		cells[v13].Fg = fg
		cells[v13].Bg = bg
		cells[v13].Flags = 0
		cells[v13].Width = 1
	}
}

func C2_grid_scroll_up(cells []C2_cell_t, width int, height int, stride int, nlines int) {
	var v5 int
	var v6 int
	var v22 int
	var v25 int
	if nlines < 1 {
		return
	}
	if nlines > height {
		nlines = height
	}
	v12 := height - nlines
	for v5 = 0; v5 < v12; v5++ {
		v6 = 0
		for v6 < width {
			v22 = ((v5 + nlines) * stride) + v6
			v25 = (v5 * stride) + v6
			cells[v25].Rune_ = cells[v22].Rune_
			cells[v25].Fg = cells[v22].Fg
			cells[v25].Bg = cells[v22].Bg
			cells[v25].Flags = cells[v22].Flags
			cells[v25].Width = cells[v22].Width
			v6++
		}
	}
	if stride == width {
		move := v12 * stride
		C2_grid_clear(cells[move:], (height-v12)*stride, byte(0), byte(0))
	} else {
		for v5 = v12; v5 < height; v5++ {
			C2_grid_clear_row(cells[:], v5, stride, width, byte(0), byte(0))
		}
	}
}

func C2_vt_init(p *C2_vt_parser_t, width int, height int) {
	p.State = 0
	p.Cursor_x = 0
	p.Cursor_y = 0
	p.Cur_fg = 0
	p.Cur_bg = 0
	p.Cur_attr = 0
	p.Width = width
	p.Height = height
	p.Prm = 0
	p.Nparams = 0
	p.Pending_len = 0
}

func C2_vt_put(p *C2_vt_parser_t, cells []C2_cell_t, r uint32) {
	var v3 int
	var v5 int
	_ = 0
	v3 = p.Width
	v5 = p.Height
	if (v3 <= 0) || (v5 <= 0) {
		return
	}
	if p.Cursor_x >= v3 {
		p.Cursor_x = 0
		p.Cursor_y++
	}
	if p.Cursor_y >= v5 {
		p.Cursor_y = v5 - 1
	}
	v26 := (p.Cursor_y * v3) + p.Cursor_x
	cells[v26].Rune_ = r
	cells[v26].Fg = byte(p.Cur_fg)
	cells[v26].Bg = byte(p.Cur_bg)
	cells[v26].Flags = byte(p.Cur_attr)
	cells[v26].Width = 1
	p.Cursor_x++
}

func C2_vt_add_digit(p *C2_vt_parser_t, b byte) {
	var v2 int
	var v6 int
	v2 = int(b)
	v2 -= 48
	v6 = p.Prm
	v6 *= 10
	v6 += v2
	if v6 > 0x270f {
		v6 = 0x270f
	}
	p.Prm = v6
}

func C2_vt_finish_prm(p *C2_vt_parser_t) {
	_ = 0
	if p.Nparams < 4 {
		p.Params[p.Nparams] = p.Prm
		p.Nparams++
	}
	p.Prm = 0
}

func C2_vt_param(p *C2_vt_parser_t, i int, def int) int {
	_ = 0
	if i < p.Nparams {
		if p.Params[i] != 0 {
			return p.Params[i]
		}
	}
	return def
}

func C2_vt_sgr(p *C2_vt_parser_t) {
	var v1 int
	var v10 int
	var v31 bool
	var v38 bool
	_ = 0
	for v1 = 0; v1 < p.Nparams; v1++ {
		v10 = p.Params[v1]
		if v10 == 0 {
			p.Cur_fg = 0
			p.Cur_bg = 0
			p.Cur_attr = 0
		}
		if v10 == 1 {
			p.Cur_attr |= 1
		}
		if v10 == 4 {
			p.Cur_attr |= 4
		}
		if v10 == 7 {
			p.Cur_attr |= 8
		}
		v31 = (v10 >= 30) && (v10 <= 37)
		if v31 {
			p.Cur_fg = v10 - 30
		}
		v38 = (v10 >= 40) && (v10 <= 47)
		if v38 {
			p.Cur_bg = v10 - 40
		}
	}
}

func C2_vt_clear_span(cells []C2_cell_t, i0 int, i1 int, fg byte, bg byte) {
	for i0 < i1 {
		cells[i0].Rune_ = 32
		cells[i0].Fg = fg
		cells[i0].Bg = bg
		cells[i0].Flags = 0
		cells[i0].Width = 1
		i0++
	}
}

func C2_vt_csi(p *C2_vt_parser_t, cells []C2_cell_t, b byte) {
	var v3 int
	var v4 int
	var v5 int
	var v6 int
	var v22 int
	var v41 bool
	var v51 bool
	var v76 bool
	var v92 bool
	_ = 0
	C2_vt_finish_prm(p)
	v4 = p.Width
	v5 = p.Height
	if (b == 'H') || (b == 'f') {
		v22 = C2_vt_param(p, 1, 1)
		p.Cursor_y = C2_vt_param(p, 0, 1) - 1
		p.Cursor_x = v22 - 1
		if p.Cursor_y < 0 {
			p.Cursor_y = 0
		}
		if p.Cursor_x < 0 {
			p.Cursor_x = 0
		}
		v41 = (p.Height > 0) && (p.Cursor_y >= p.Height)
		if v41 {
			p.Cursor_y = p.Height - 1
		}
		v51 = (p.Width > 0) && (p.Cursor_x >= p.Width)
		if v51 {
			p.Cursor_x = p.Width - 1
		}
	}
	if b == 'A' {
		v3 = C2_vt_param(p, 0, 1)
		p.Cursor_y -= v3
		if p.Cursor_y < 0 {
			p.Cursor_y = 0
		}
	}
	if b == 'B' {
		v3 = C2_vt_param(p, 0, 1)
		p.Cursor_y += v3
		v76 = (p.Height > 0) && (p.Cursor_y >= p.Height)
		if v76 {
			p.Cursor_y = p.Height - 1
		}
	}
	if b == 'C' {
		v3 = C2_vt_param(p, 0, 1)
		p.Cursor_x += v3
		v92 = (p.Width > 0) && (p.Cursor_x >= p.Width)
		if v92 {
			p.Cursor_x = p.Width - 1
		}
	}
	if b == 'D' {
		v3 = C2_vt_param(p, 0, 1)
		p.Cursor_x -= v3
		if p.Cursor_x < 0 {
			p.Cursor_x = 0
		}
	}
	if b == 'm' {
		C2_vt_sgr(p)
	}
	if b == 'J' {
		v3 = C2_vt_param(p, 0, 0)
		v6 = (p.Cursor_y * v4) + p.Cursor_x
		if v3 == 0 {
			C2_vt_clear_span(cells[:], v6, (v4 * v5), byte(p.Cur_fg), byte(p.Cur_bg))
		}
		if v3 == 1 {
			C2_vt_clear_span(cells[:], 0, (v6 + 1), byte(p.Cur_fg), byte(p.Cur_bg))
		}
		if v3 == 2 {
			C2_vt_clear_span(cells[:], 0, (v4 * v5), byte(p.Cur_fg), byte(p.Cur_bg))
		}
	}
	if b == 'K' {
		v3 = C2_vt_param(p, 0, 0)
		v6 = p.Cursor_y * v4
		if v3 == 0 {
			C2_vt_clear_span(cells[:], (v6 + p.Cursor_x), (v6 + v4), byte(p.Cur_fg), byte(p.Cur_bg))
		}
		if v3 == 1 {
			C2_vt_clear_span(cells[:], v6, ((v6 + p.Cursor_x) + 1), byte(p.Cur_fg), byte(p.Cur_bg))
		}
		if v3 == 2 {
			C2_vt_clear_span(cells[:], v6, (v6 + v4), byte(p.Cur_fg), byte(p.Cur_bg))
		}
	}
	p.State = 0
}

func C2_vt_feed_byte(p *C2_vt_parser_t, cells []C2_cell_t, b byte) int {
	var v28 bool
	var v45 bool
	var v55 bool
	_ = 0
	if p.Height < 0 {
		cells[0].Rune_ = 0
	}
	switch p.State {
	case 0:
		if b == 27 {
			p.State = 1
			return 0
		}
		if b == 10 {
			p.Cursor_y++
			p.Cursor_x = 0
			return 1
		}
		if b == 13 {
			p.Cursor_x = 0
			return 1
		}
		v28 = (b >= 32) && (b <= 0x7e)
		if v28 {
			C2_vt_put(p, cells[:], uint32(b))
			return 1
		}
	case 1:
		if b == 0x5b {
			p.State = 2
			p.Prm = 0
			p.Nparams = 0
			return 0
		}
		if b == 0x5d {
			p.State = 3
			return 0
		}
		p.State = 0
	case 2:
		v45 = (b >= '0') && (b <= '9')
		if v45 {
			C2_vt_add_digit(p, b)
			return 0
		}
		if b == ';' {
			C2_vt_finish_prm(p)
			return 0
		}
		v55 = (b >= 64) && (b <= 0x7e)
		if v55 {
			C2_vt_csi(p, cells[:], b)
			return 0
		}
	case 3:
		if (b == 7) || (b == 27) {
			p.State = 0
			return 0
		}
	}
	return 0
}
