// Code generated by sgoiter emit go127; DO NOT EDIT.
package src

func Crc32_ieee(data []byte, len uint64) uint32 {
	var v17 uint32
	var v18 int
	var v15 uint32
	var v23 uint32
	var v26 uint32
	var v4 uint32
	var v5 uint32
	var v21 uint32
	var v25 uint32
	var v14 uint32
	var v8 uint32
	var v2 uint32
	var v9 uint8
	var v10 uint32
	v2 = uint32(4294967295)
	v4 = uint32(0)
	for uint64(v4) < len {
	v9 = data[int(int(v4))]
	v10 = v2 ^ uint32(v9)
	v2 = v10
	v5 = uint32(0)
	for v5 < uint32(8) {
	v17 = v2 & uint32(1)
	v18 = int(v17)
	v20 := -int(v18)
	_ = v20
	v21 = uint32(v20)
	v15 = v21
	v23 = v2 >> uint8(1)
	v25 = uint32(3988292384) & v15
	v26 = v23 ^ v25
	v2 = v26
	v14 = v5 + uint32(1)
	v5 = v14
	}
	v8 = v4 + uint32(1)
	v4 = v8
	}
	v27 := ^v2
	_ = v27
	return uint32(v27)
}

