// Code generated by sgoiter emit go127; DO NOT EDIT.
package fast_xor

import "encoding/binary"

func Fast_xor_bytes(dst []byte, src1 []byte, src2 []byte, len uint64) {
	v4 := uint64(0)
	v7 := v4 + uint64(8)
	for v7 <= len {
	v13 := v4 / uint64(8)
	v16 := v13 * uint64(8)
	v14 := binary.LittleEndian.Uint64(src1[int(int(v16)):])
	v10 := v14
	v20 := v4 / uint64(8)
	v23 := v20 * uint64(8)
	v21 := binary.LittleEndian.Uint64(src2[int(int(v23)):])
	v17 := v21
	v24 := v10 ^ v17
	v26 := v4 / uint64(8)
	binary.LittleEndian.PutUint64(dst[int(int(v26))*8:], v24)
	v9 := v4 + uint64(8)
	v4 = v9
	}
	for v4 < len {
	v29 := src1[int(int(v4))]
	v30 := src2[int(int(v4))]
	v31 := v29 ^ v30
	dst[int(int(v4))] = v31
	v28 := v4 + uint64(1)
	v4 = v28
	}
}

