// Code generated by sgoiter emit go127; DO NOT EDIT.
package src

import "encoding/binary"

func Siphash24(in []byte, inlen uint64, k []byte) uint64 {
	var v282 uint64
	var v332 uint64
	var v405 uint64
	var v422 uint64
	var v489 uint64
	var v50 uint64
	var v116 uint64
	var v283 uint64
	var v291 uint64
	var v367 uint64
	var v457 uint64
	var v535 uint64
	var v536 uint64
	var v17 uint64
	var v28 uint64
	var v58 uint64
	var v80 uint64
	var v139 uint64
	var v210 uint64
	var v430 uint64
	var v487 uint64
	var v46 uint64
	var v131 uint64
	var v266 uint64
	var v500 uint64
	var v514 uint64
	var v543 uint64
	var v562 uint64
	var v136 uint64
	var v191 uint64
	var v211 uint64
	var v244 uint64
	var v256 uint64
	var v402 uint64
	var v427 uint64
	var v446 uint64
	var v148 uint64
	var v187 uint64
	var v420 uint64
	var v440 uint64
	var v477 uint64
	var v517 uint64
	var v519 uint64
	var v544 uint64
	var v112 uint64
	var v285 uint64
	var v315 uint64
	var v374 uint64
	var v467 uint64
	var v488 uint64
	var v522 uint64
	var v126 uint64
	var v166 uint8
	var v380 uint64
	var v381 uint64
	var v394 uint64
	var v93 uint64
	var v460 uint64
	var v560 uint64
	var v107 uint64
	var v156 uint64
	var v314 uint64
	var v432 uint64
	var v468 uint64
	var v41 uint64
	var v118 uint64
	var v301 uint64
	var v79 uint64
	var v184 uint64
	var v409 uint64
	var v505 uint64
	var v7 uint64
	var v34 uint64
	var v110 uint64
	var v115 uint64
	var v234 uint64
	var v297 uint64
	var v476 uint64
	var v551 uint64
	var v145 uint64
	var v238 uint64
	var v326 uint64
	var v124 uint64
	var v217 uint64
	var v248 uint64
	var v443 uint64
	var v563 uint64
	var v293 uint64
	var v16 uint64
	var v14 uint64
	var v52 uint64
	var v129 uint64
	var v192 uint64
	var v208 uint64
	var v243 uint64
	var v10 uint64
	var v146 uint64
	var v195 uint64
	var v279 uint64
	var v382 uint64
	var v431 uint64
	var v19 uint64
	var v31 uint64
	var v49 uint64
	var v64 uint64
	var v155 uint64
	var v354 uint64
	var v438 uint64
	var v553 uint64
	var v97 uint64
	var v216 uint64
	var v236 uint64
	var v410 uint64
	var v451 uint64
	var v186 uint64
	var v396 uint64
	var v55 uint64
	var v412 uint64
	var v471 uint64
	var v531 uint64
	var v168 uint64
	var v228 uint64
	var v288 uint64
	var v344 uint64
	var v389 uint64
	var v479 uint64
	var v3 uint64
	var v90 uint64
	var v98 uint64
	var v121 uint64
	var v138 uint64
	var v167 uint64
	var v229 uint64
	var v305 uint64
	var v20 uint64
	var v60 uint64
	var v150 uint64
	var v357 uint64
	var v361 uint64
	var v365 uint64
	var v448 uint64
	var v465 uint64
	var v22 uint64
	var v199 uint64
	var v202 uint64
	var v272 uint64
	var v313 uint64
	var v320 uint64
	var v474 uint64
	var v485 uint64
	var v89 uint64
	var v125 uint64
	var v263 uint64
	var v339 uint64
	var v498 uint64
	var v503 uint64
	var v532 uint64
	var v548 uint64
	var v26 uint64
	var v137 uint64
	var v141 uint64
	var v260 uint64
	var v300 uint64
	var v322 uint64
	var v348 uint64
	var v372 uint64
	var v6 uint64
	var v220 uint64
	var v401 uint64
	var v456 uint64
	var v541 uint64
	var v561 uint64
	var v29 uint64
	var v486 uint64
	var v62 uint64
	var v67 uint64
	var v119 uint64
	var v247 uint64
	var v254 uint64
	var v317 uint64
	var v555 uint64
	var v59 uint64
	var v101 uint64
	var v240 uint64
	var v414 uint64
	var v525 uint64
	var v78 uint64
	var v275 uint64
	var v286 uint64
	var v383 uint64
	var v449 uint64
	var v552 uint64
	var v564 uint64
	var v82 uint64
	var v106 uint64
	var v134 uint64
	var v157 uint64
	var v303 uint64
	var v458 uint64
	var v538 uint64
	var v545 uint64
	var v154 uint64
	var v170 uint64
	var v207 uint64
	var v331 uint64
	var v335 uint64
	var v390 uint64
	var v478 uint64
	var v565 uint64
	var v117 uint64
	var v179 uint64
	var v258 uint64
	var v284 uint64
	var v391 uint64
	var v403 uint64
	var v523 uint64
	var v161 uint64
	var v182 uint8
	var v269 uint64
	var v434 uint64
	var v469 uint64
	var v71 uint64
	var v459 uint64
	var v475 uint64
	var v513 uint64
	var v163 uint64
	var v214 uint8
	var v373 uint64
	var v528 uint64
	var v109 uint64
	var v226 uint64
	var v267 uint64
	var v307 uint64
	var v329 uint64
	var v353 uint64
	var v399 uint64
	var v462 uint64
	var v250 uint64
	var v351 uint64
	var v206 uint8
	var v273 uint64
	var v417 uint64
	var v542 uint64
	var v13 uint64
	var v53 uint64
	var v171 uint64
	var v183 uint64
	var v292 uint64
	var v453 uint64
	var v176 uint64
	var v337 uint64
	var v437 uint64
	var v484 uint64
	var v504 uint64
	var v38 uint64
	var v84 uint64
	var v135 uint64
	var v408 uint64
	var v494 uint64
	var v506 uint64
	var v178 uint64
	var v225 uint64
	var v310 uint64
	var v371 uint64
	var v411 uint64
	var v81 uint64
	var v159 uint64
	var v418 uint64
	var v419 uint64
	var v566 uint64
	var v42 uint64
	var v72 uint64
	var v147 uint64
	var v158 uint64
	var v295 uint64
	var v87 uint64
	var v364 uint64
	var v384 uint64
	var v508 uint64
	var v526 uint64
	var v200 uint64
	var v274 uint64
	var v302 uint64
	var v311 uint64
	var v429 uint64
	var v77 uint64
	var v88 uint64
	var v174 uint8
	var v194 uint64
	var v227 uint64
	var v343 uint64
	var v375 uint64
	var v11 uint64
	var v44 uint64
	var v96 uint64
	var v190 uint8
	var v312 uint64
	var v516 uint64
	var v534 uint64
	var v218 uint64
	var v360 uint64
	var v491 uint64
	var v127 uint64
	var v128 uint64
	var v215 uint64
	var v245 uint64
	var v352 uint64
	var v466 uint64
	var v99 uint64
	var v321 uint64
	var v333 uint64
	var v61 uint64
	var v235 uint64
	var v257 uint64
	var v153 uint64
	var v253 uint64
	var v265 uint64
	var v370 uint64
	var v447 uint64
	var v496 uint64
	var v51 uint64
	var v69 uint64
	var v294 uint64
	var v424 uint64
	var v108 uint64
	var v255 uint64
	var v363 uint64
	var v386 uint64
	var v392 uint64
	var v421 uint64
	var v554 uint64
	var v68 uint64
	var v74 uint64
	var v246 uint64
	var v323 uint64
	var v324 uint64
	var v342 uint64
	var v345 uint64
	var v355 uint64
	var v237 uint64
	var v264 uint64
	var v304 uint64
	var v346 uint64
	var v377 uint64
	var v495 uint64
	var v510 uint64
	var v546 uint64
	var v277 uint64
	var v400 uint64
	var v557 uint64
	var v231 uint64
	var v330 uint64
	var v441 uint64
	var v497 uint64
	var v198 uint8
	var v362 uint64
	var v481 uint64
	var v524 uint64
	var v175 uint64
	var v91 uint64
	var v70 uint64
	var v203 uint64
	var v428 uint64
	var v439 uint64
	var v515 uint64
	var v533 uint64
	var v103 uint64
	var v144 uint64
	var v222 uint64
	v6 = binary.LittleEndian.Uint64(k[int(0):])
	v3 = v6
	v10 = binary.LittleEndian.Uint64(k[int(1):])
	v7 = v10
	v13 = uint64(8317987319222330741) ^ v3
	v11 = v13
	v16 = uint64(7237128888980173921) ^ v7
	v14 = v16
	v19 = uint64(7816392313619706465) ^ v3
	v17 = v19
	v22 = uint64(8387220255154660723) ^ v7
	v20 = v22
	v26 = inlen % uint64(8)
	v28 = inlen - v26
	v29 = uint64(0)
	v31 = v28
	for v29 != v31 {
	v35 := in[int(int(v29)):]
	_ = v35
	v41 = v29
	v38 = binary.LittleEndian.Uint64(in[int(int(v41)):])
	v34 = v38
	v42 = v20 ^ v34
	v20 = v42
	for {
	v44 = v11 + v14
	v11 = v44
	v46 = v14 << uint8(13)
	v49 = uint64(64) - uint64(13)
	v50 = v14 >> uint8(v49)
	v51 = v46 | v50
	v52 = v51
	v14 = v52
	v53 = v14 ^ v11
	v14 = v53
	v55 = v11 << uint8(32)
	v58 = uint64(64) - uint64(32)
	v59 = v11 >> uint8(v58)
	v60 = v55 | v59
	v61 = v60
	v11 = v61
	v62 = v17 + v20
	v17 = v62
	v64 = v20 << uint8(16)
	v67 = uint64(64) - uint64(16)
	v68 = v20 >> uint8(v67)
	v69 = v64 | v68
	v70 = v69
	v20 = v70
	v71 = v20 ^ v17
	v20 = v71
	v72 = v11 + v20
	v11 = v72
	v74 = v20 << uint8(21)
	v77 = uint64(64) - uint64(21)
	v78 = v20 >> uint8(v77)
	v79 = v74 | v78
	v80 = v79
	v20 = v80
	v81 = v20 ^ v11
	v20 = v81
	v82 = v17 + v14
	v17 = v82
	v84 = v14 << uint8(17)
	v87 = uint64(64) - uint64(17)
	v88 = v14 >> uint8(v87)
	v89 = v84 | v88
	v90 = v89
	v14 = v90
	v91 = v14 ^ v17
	v14 = v91
	v93 = v17 << uint8(32)
	v96 = uint64(64) - uint64(32)
	v97 = v17 >> uint8(v96)
	v98 = v93 | v97
	v99 = v98
	v17 = v99
		if !(uint64(0) != 0) { break }
	}
	for {
	v101 = v11 + v14
	v11 = v101
	v103 = v14 << uint8(13)
	v106 = uint64(64) - uint64(13)
	v107 = v14 >> uint8(v106)
	v108 = v103 | v107
	v109 = v108
	v14 = v109
	v110 = v14 ^ v11
	v14 = v110
	v112 = v11 << uint8(32)
	v115 = uint64(64) - uint64(32)
	v116 = v11 >> uint8(v115)
	v117 = v112 | v116
	v118 = v117
	v11 = v118
	v119 = v17 + v20
	v17 = v119
	v121 = v20 << uint8(16)
	v124 = uint64(64) - uint64(16)
	v125 = v20 >> uint8(v124)
	v126 = v121 | v125
	v127 = v126
	v20 = v127
	v128 = v20 ^ v17
	v20 = v128
	v129 = v11 + v20
	v11 = v129
	v131 = v20 << uint8(21)
	v134 = uint64(64) - uint64(21)
	v135 = v20 >> uint8(v134)
	v136 = v131 | v135
	v137 = v136
	v20 = v137
	v138 = v20 ^ v11
	v20 = v138
	v139 = v17 + v14
	v17 = v139
	v141 = v14 << uint8(17)
	v144 = uint64(64) - uint64(17)
	v145 = v14 >> uint8(v144)
	v146 = v141 | v145
	v147 = v146
	v14 = v147
	v148 = v14 ^ v17
	v14 = v148
	v150 = v17 << uint8(32)
	v153 = uint64(64) - uint64(32)
	v154 = v17 >> uint8(v153)
	v155 = v150 | v154
	v156 = v155
	v17 = v156
		if !(uint64(0) != 0) { break }
	}
	v157 = v11 ^ v34
	v11 = v157
	v33 := in[int(8):]
	_ = v33
	in = v33
	}
	v159 = inlen
	v161 = v159 << uint8(56)
	v158 = v161
	v163 = inlen & uint64(7)
	switch v163 {
	case 7:
	v164 := in[int(int(v29)):]
	_ = v164
	v167 = v29 + uint64(6)
	v166 = in[int(int(v167))]
	v168 = uint64(v166)
	v170 = v168 << uint8(48)
	v171 = v158 | v170
	v158 = v171
		fallthrough
	case 6:
	v172 := in[int(int(v29)):]
	_ = v172
	v175 = v29 + uint64(5)
	v174 = in[int(int(v175))]
	v176 = uint64(v174)
	v178 = v176 << uint8(40)
	v179 = v158 | v178
	v158 = v179
		fallthrough
	case 5:
	v180 := in[int(int(v29)):]
	_ = v180
	v183 = v29 + uint64(4)
	v182 = in[int(int(v183))]
	v184 = uint64(v182)
	v186 = v184 << uint8(32)
	v187 = v158 | v186
	v158 = v187
		fallthrough
	case 4:
	v188 := in[int(int(v29)):]
	_ = v188
	v191 = v29 + uint64(3)
	v190 = in[int(int(v191))]
	v192 = uint64(v190)
	v194 = v192 << uint8(24)
	v195 = v158 | v194
	v158 = v195
		fallthrough
	case 3:
	v196 := in[int(int(v29)):]
	_ = v196
	v199 = v29 + uint64(2)
	v198 = in[int(int(v199))]
	v200 = uint64(v198)
	v202 = v200 << uint8(16)
	v203 = v158 | v202
	v158 = v203
		fallthrough
	case 2:
	v204 := in[int(int(v29)):]
	_ = v204
	v207 = v29 + uint64(1)
	v206 = in[int(int(v207))]
	v208 = uint64(v206)
	v210 = v208 << uint8(8)
	v211 = v158 | v210
	v158 = v211
		fallthrough
	case 1:
	v212 := in[int(int(v29)):]
	_ = v212
	v215 = v29
	v214 = in[int(int(v215))]
	v216 = uint64(v214)
	v217 = v158 | v216
	v158 = v217
		fallthrough
	case 0:
	}
	v218 = v20 ^ v158
	v20 = v218
	for {
	v220 = v11 + v14
	v11 = v220
	v222 = v14 << uint8(13)
	v225 = uint64(64) - uint64(13)
	v226 = v14 >> uint8(v225)
	v227 = v222 | v226
	v228 = v227
	v14 = v228
	v229 = v14 ^ v11
	v14 = v229
	v231 = v11 << uint8(32)
	v234 = uint64(64) - uint64(32)
	v235 = v11 >> uint8(v234)
	v236 = v231 | v235
	v237 = v236
	v11 = v237
	v238 = v17 + v20
	v17 = v238
	v240 = v20 << uint8(16)
	v243 = uint64(64) - uint64(16)
	v244 = v20 >> uint8(v243)
	v245 = v240 | v244
	v246 = v245
	v20 = v246
	v247 = v20 ^ v17
	v20 = v247
	v248 = v11 + v20
	v11 = v248
	v250 = v20 << uint8(21)
	v253 = uint64(64) - uint64(21)
	v254 = v20 >> uint8(v253)
	v255 = v250 | v254
	v256 = v255
	v20 = v256
	v257 = v20 ^ v11
	v20 = v257
	v258 = v17 + v14
	v17 = v258
	v260 = v14 << uint8(17)
	v263 = uint64(64) - uint64(17)
	v264 = v14 >> uint8(v263)
	v265 = v260 | v264
	v266 = v265
	v14 = v266
	v267 = v14 ^ v17
	v14 = v267
	v269 = v17 << uint8(32)
	v272 = uint64(64) - uint64(32)
	v273 = v17 >> uint8(v272)
	v274 = v269 | v273
	v275 = v274
	v17 = v275
		if !(uint64(0) != 0) { break }
	}
	for {
	v277 = v11 + v14
	v11 = v277
	v279 = v14 << uint8(13)
	v282 = uint64(64) - uint64(13)
	v283 = v14 >> uint8(v282)
	v284 = v279 | v283
	v285 = v284
	v14 = v285
	v286 = v14 ^ v11
	v14 = v286
	v288 = v11 << uint8(32)
	v291 = uint64(64) - uint64(32)
	v292 = v11 >> uint8(v291)
	v293 = v288 | v292
	v294 = v293
	v11 = v294
	v295 = v17 + v20
	v17 = v295
	v297 = v20 << uint8(16)
	v300 = uint64(64) - uint64(16)
	v301 = v20 >> uint8(v300)
	v302 = v297 | v301
	v303 = v302
	v20 = v303
	v304 = v20 ^ v17
	v20 = v304
	v305 = v11 + v20
	v11 = v305
	v307 = v20 << uint8(21)
	v310 = uint64(64) - uint64(21)
	v311 = v20 >> uint8(v310)
	v312 = v307 | v311
	v313 = v312
	v20 = v313
	v314 = v20 ^ v11
	v20 = v314
	v315 = v17 + v14
	v17 = v315
	v317 = v14 << uint8(17)
	v320 = uint64(64) - uint64(17)
	v321 = v14 >> uint8(v320)
	v322 = v317 | v321
	v323 = v322
	v14 = v323
	v324 = v14 ^ v17
	v14 = v324
	v326 = v17 << uint8(32)
	v329 = uint64(64) - uint64(32)
	v330 = v17 >> uint8(v329)
	v331 = v326 | v330
	v332 = v331
	v17 = v332
		if !(uint64(0) != 0) { break }
	}
	v333 = v11 ^ v158
	v11 = v333
	v335 = v17 ^ uint64(255)
	v17 = v335
	for {
	v337 = v11 + v14
	v11 = v337
	v339 = v14 << uint8(13)
	v342 = uint64(64) - uint64(13)
	v343 = v14 >> uint8(v342)
	v344 = v339 | v343
	v345 = v344
	v14 = v345
	v346 = v14 ^ v11
	v14 = v346
	v348 = v11 << uint8(32)
	v351 = uint64(64) - uint64(32)
	v352 = v11 >> uint8(v351)
	v353 = v348 | v352
	v354 = v353
	v11 = v354
	v355 = v17 + v20
	v17 = v355
	v357 = v20 << uint8(16)
	v360 = uint64(64) - uint64(16)
	v361 = v20 >> uint8(v360)
	v362 = v357 | v361
	v363 = v362
	v20 = v363
	v364 = v20 ^ v17
	v20 = v364
	v365 = v11 + v20
	v11 = v365
	v367 = v20 << uint8(21)
	v370 = uint64(64) - uint64(21)
	v371 = v20 >> uint8(v370)
	v372 = v367 | v371
	v373 = v372
	v20 = v373
	v374 = v20 ^ v11
	v20 = v374
	v375 = v17 + v14
	v17 = v375
	v377 = v14 << uint8(17)
	v380 = uint64(64) - uint64(17)
	v381 = v14 >> uint8(v380)
	v382 = v377 | v381
	v383 = v382
	v14 = v383
	v384 = v14 ^ v17
	v14 = v384
	v386 = v17 << uint8(32)
	v389 = uint64(64) - uint64(32)
	v390 = v17 >> uint8(v389)
	v391 = v386 | v390
	v392 = v391
	v17 = v392
		if !(uint64(0) != 0) { break }
	}
	for {
	v394 = v11 + v14
	v11 = v394
	v396 = v14 << uint8(13)
	v399 = uint64(64) - uint64(13)
	v400 = v14 >> uint8(v399)
	v401 = v396 | v400
	v402 = v401
	v14 = v402
	v403 = v14 ^ v11
	v14 = v403
	v405 = v11 << uint8(32)
	v408 = uint64(64) - uint64(32)
	v409 = v11 >> uint8(v408)
	v410 = v405 | v409
	v411 = v410
	v11 = v411
	v412 = v17 + v20
	v17 = v412
	v414 = v20 << uint8(16)
	v417 = uint64(64) - uint64(16)
	v418 = v20 >> uint8(v417)
	v419 = v414 | v418
	v420 = v419
	v20 = v420
	v421 = v20 ^ v17
	v20 = v421
	v422 = v11 + v20
	v11 = v422
	v424 = v20 << uint8(21)
	v427 = uint64(64) - uint64(21)
	v428 = v20 >> uint8(v427)
	v429 = v424 | v428
	v430 = v429
	v20 = v430
	v431 = v20 ^ v11
	v20 = v431
	v432 = v17 + v14
	v17 = v432
	v434 = v14 << uint8(17)
	v437 = uint64(64) - uint64(17)
	v438 = v14 >> uint8(v437)
	v439 = v434 | v438
	v440 = v439
	v14 = v440
	v441 = v14 ^ v17
	v14 = v441
	v443 = v17 << uint8(32)
	v446 = uint64(64) - uint64(32)
	v447 = v17 >> uint8(v446)
	v448 = v443 | v447
	v449 = v448
	v17 = v449
		if !(uint64(0) != 0) { break }
	}
	for {
	v451 = v11 + v14
	v11 = v451
	v453 = v14 << uint8(13)
	v456 = uint64(64) - uint64(13)
	v457 = v14 >> uint8(v456)
	v458 = v453 | v457
	v459 = v458
	v14 = v459
	v460 = v14 ^ v11
	v14 = v460
	v462 = v11 << uint8(32)
	v465 = uint64(64) - uint64(32)
	v466 = v11 >> uint8(v465)
	v467 = v462 | v466
	v468 = v467
	v11 = v468
	v469 = v17 + v20
	v17 = v469
	v471 = v20 << uint8(16)
	v474 = uint64(64) - uint64(16)
	v475 = v20 >> uint8(v474)
	v476 = v471 | v475
	v477 = v476
	v20 = v477
	v478 = v20 ^ v17
	v20 = v478
	v479 = v11 + v20
	v11 = v479
	v481 = v20 << uint8(21)
	v484 = uint64(64) - uint64(21)
	v485 = v20 >> uint8(v484)
	v486 = v481 | v485
	v487 = v486
	v20 = v487
	v488 = v20 ^ v11
	v20 = v488
	v489 = v17 + v14
	v17 = v489
	v491 = v14 << uint8(17)
	v494 = uint64(64) - uint64(17)
	v495 = v14 >> uint8(v494)
	v496 = v491 | v495
	v497 = v496
	v14 = v497
	v498 = v14 ^ v17
	v14 = v498
	v500 = v17 << uint8(32)
	v503 = uint64(64) - uint64(32)
	v504 = v17 >> uint8(v503)
	v505 = v500 | v504
	v506 = v505
	v17 = v506
		if !(uint64(0) != 0) { break }
	}
	for {
	v508 = v11 + v14
	v11 = v508
	v510 = v14 << uint8(13)
	v513 = uint64(64) - uint64(13)
	v514 = v14 >> uint8(v513)
	v515 = v510 | v514
	v516 = v515
	v14 = v516
	v517 = v14 ^ v11
	v14 = v517
	v519 = v11 << uint8(32)
	v522 = uint64(64) - uint64(32)
	v523 = v11 >> uint8(v522)
	v524 = v519 | v523
	v525 = v524
	v11 = v525
	v526 = v17 + v20
	v17 = v526
	v528 = v20 << uint8(16)
	v531 = uint64(64) - uint64(16)
	v532 = v20 >> uint8(v531)
	v533 = v528 | v532
	v534 = v533
	v20 = v534
	v535 = v20 ^ v17
	v20 = v535
	v536 = v11 + v20
	v11 = v536
	v538 = v20 << uint8(21)
	v541 = uint64(64) - uint64(21)
	v542 = v20 >> uint8(v541)
	v543 = v538 | v542
	v544 = v543
	v20 = v544
	v545 = v20 ^ v11
	v20 = v545
	v546 = v17 + v14
	v17 = v546
	v548 = v14 << uint8(17)
	v551 = uint64(64) - uint64(17)
	v552 = v14 >> uint8(v551)
	v553 = v548 | v552
	v554 = v553
	v14 = v554
	v555 = v14 ^ v17
	v14 = v555
	v557 = v17 << uint8(32)
	v560 = uint64(64) - uint64(32)
	v561 = v17 >> uint8(v560)
	v562 = v557 | v561
	v563 = v562
	v17 = v563
		if !(uint64(0) != 0) { break }
	}
	v564 = v11 ^ v14
	v565 = v564 ^ v17
	v566 = v565 ^ v20
	return uint64(v566)
}

