// Code generated by sgoiter emit go127; DO NOT EDIT.
// sgoiter-stamp: sha256=9421fe7cbbf906d23678aed28dd5f1ec8fd37f20c25d6bb7f07f7acc5d8a95df
package c2myers

var (
	__str_4f9f73b3 = []byte("120000")
	__str_cb0b20f9 = []byte("160000")
)

func C2_myers_ses(a []int, n int, b []int, m int, v []int, vlen int) int {
	var v10 bool
	var v32 int
	var v36 int
	var v41 int
	var v55 bool
	var v67 int
	var v83 bool
	if len(v) < vlen {
	}
	v10 = (n == 0) && (m == 0)
	if v10 {
		return 0
	}
	if (n < 0) || (m < 0) {
		return -1
	}
	v19 := n + m
	v23 := (v19 + v19) + 1
	if v23 > int(len(v)) {
		return -1
	}
	{
		_v := v[:v23]
		clear(_v[:v23])
	}
	for v32 = 0; v32 <= v19; v32++ {
		v36 = -v32
		for v36 <= v32 {
			v55 = (v36 != v32) && (v[int((v36-1)+v19)] < v[v36+1+v19])
			if (v36 == -v32) || v55 {
				v41 = v[v36+1+v19]
			} else {
				v41 = v[int((v36-1)+v19)] + 1
			}
			v67 = v41 - v36
			for v41 < n && v67 < m && a[v41] == b[v67] {
				v41++
				v67++
			}
			v[v36+v19] = v41
			v83 = (v41 >= n) && (v67 >= m)
			if v83 {
				return v32
			}
			v36 += 2
		}
	}
	return -1
}

func C2_validate_patch_mode(mode_str []byte) int {
	var v1 uint64
	v1 = 0
	if mode_str == nil {
		return 1
	}
	v7 := func() int {
		a, b := mode_str[v1:], __str_4f9f73b3
		i := 0
		for ; i < len(a) && i < len(b); i++ {
			if a[i] != b[i] {
				if a[i] < b[i] {
					return -1
				}
				return 1
			}
			if a[i] == 0 {
				return 0
			}
		}
		if i < len(a) && a[i] != 0 {
			return 1
		}
		if i < len(b) && b[i] != 0 {
			return -1
		}
		return 0
	}()
	if v7 == 0 {
		return 0
	}
	v12 := func() int {
		a, b := mode_str[v1:], __str_cb0b20f9
		i := 0
		for ; i < len(a) && i < len(b); i++ {
			if a[i] != b[i] {
				if a[i] < b[i] {
					return -1
				}
				return 1
			}
			if a[i] == 0 {
				return 0
			}
		}
		if i < len(a) && a[i] != 0 {
			return 1
		}
		if i < len(b) && b[i] != 0 {
			return -1
		}
		return 0
	}()
	if v12 == 0 {
		return 0
	}
	return 1
}
