// Code generated by sgoiter emit go127; DO NOT EDIT.
// sgoiter-stamp: sha256=a58b0fceb244fe9d93d4232c8ba8396f898a9587af6aba41c1e2124017985a90
package c2myers

var (
	__str_4f9f73b3 = []byte("120000")
	__str_cb0b20f9 = []byte("160000")
)

func C2_myers_ses(a []int, n int, b []int, m int, v []int, vlen int) int {
	var v10 bool
	var v36 int
	var v40 int
	var v45 int
	var v59 bool
	var v71 int
	var v87 bool
	if len(v) < vlen {
	}
	v10 = (n == 0) && (m == 0)
	if v10 {
		return 0
	}
	if (n < 0) || (m < 0) {
		return -1
	}
	v21 := n + m
	v25 := (v21 + v21) + 1
	if v25 > int(len(v)) {
		return -1
	}
	{
		_v := v[:v25]
		clear(_v[:v25])
	}
	for v36 = 0; v36 <= v21; v36++ {
		v40 = -v36
		for v40 <= v36 {
			v59 = (v40 != v36) && (v[int((v40-1)+v21)] < v[v40+1+v21])
			if (v40 == -v36) || v59 {
				v45 = v[v40+1+v21]
			} else {
				v45 = v[int((v40-1)+v21)] + 1
			}
			v71 = v45 - v40
			for v45 < n && v71 < m && a[v45] == b[v71] {
				v45++
				v71++
			}
			v[v40+v21] = v45
			v87 = (v45 >= n) && (v71 >= m)
			if v87 {
				return v36
			}
			v40 += 2
		}
	}
	return -1
}

func C2_validate_patch_mode(mode_str []byte) int {
	var v1 uint64
	v1 = 0
	if mode_str == nil {
		return 1
	}
	v7 := func() int {
		a, b := mode_str[v1:], __str_4f9f73b3
		i := 0
		for ; i < len(a) && i < len(b); i++ {
			if a[i] != b[i] {
				if a[i] < b[i] {
					return -1
				}
				return 1
			}
			if a[i] == 0 {
				return 0
			}
		}
		if i < len(a) && a[i] != 0 {
			return 1
		}
		if i < len(b) && b[i] != 0 {
			return -1
		}
		return 0
	}()
	if v7 == 0 {
		return 0
	}
	v12 := func() int {
		a, b := mode_str[v1:], __str_cb0b20f9
		i := 0
		for ; i < len(a) && i < len(b); i++ {
			if a[i] != b[i] {
				if a[i] < b[i] {
					return -1
				}
				return 1
			}
			if a[i] == 0 {
				return 0
			}
		}
		if i < len(a) && a[i] != 0 {
			return 1
		}
		if i < len(b) && b[i] != 0 {
			return -1
		}
		return 0
	}()
	if v12 == 0 {
		return 0
	}
	return 1
}
