// Code generated by sgoiter emit go127; DO NOT EDIT.
package c2blueteam

import "syscall"

func C2bt_init_inplace(ctx *C2bt_ctx_t, cfg *C2bt_config_t) int {
	var v12 *Probe_channel_t
	var v15 *Probe_channel_t
	var v18 *Probe_channel_t
	var v21 *Probe_channel_t
	var v24 *C2bt_tracker_table_t
	if ctx == nil {
		return -1
	}
	*ctx = C2bt_ctx_t{}
	if cfg != nil {
		ctx.Config = *cfg
	}
	v12 = &ctx.Chan_proc
	C2bt_channel_init(v12)
	v15 = &ctx.Chan_file
	C2bt_channel_init(v15)
	v18 = &ctx.Chan_net
	C2bt_channel_init(v18)
	v21 = &ctx.Chan_mcp
	C2bt_channel_init(v21)
	v24 = &ctx.Tracker_table
	C2bt_tracker_init(v24)
	ctx.Sealed_mem_fd = -1
	ctx.Fanotify_fd = -1
	ctx.Mcp_proxy_fd = -1
	ctx.Running = 0
	return 0
}

func C2bt_start(ctx *C2bt_ctx_t) int {
	if ctx == nil {
		return -1
	}
	ctx.Running = 1
	return 0
}

func C2bt_stop(ctx *C2bt_ctx_t) int {
	_ = 0
	if ctx == nil {
		return -1
	}
	ctx.Running = 0
	if ctx.Sealed_mem_fd >= 0 {
		syscall.Close(int(ctx.Sealed_mem_fd))
		ctx.Sealed_mem_fd = -1
	}
	if ctx.Fanotify_fd >= 0 {
		syscall.Close(int(ctx.Fanotify_fd))
		ctx.Fanotify_fd = -1
	}
	if ctx.Mcp_proxy_fd >= 0 {
		syscall.Close(int(ctx.Mcp_proxy_fd))
		ctx.Mcp_proxy_fd = -1
	}
	return 0
}

func C2bt_poll_batch(ctx *C2bt_ctx_t, out_batch []Probe_event_t, max_events int) int {
	var v7 bool
	var v16 int
	var v18 int
	var v26 *Probe_channel_t
	var v27 *Probe_event_t
	var v31 bool
	var v32 int
	var v38 *Probe_channel_t
	var v39 *Probe_event_t
	var v43 bool
	var v44 int
	var v50 *Probe_channel_t
	var v51 *Probe_event_t
	var v55 bool
	var v56 int
	var v62 *Probe_channel_t
	var v63 *Probe_event_t
	var v67 bool
	var v68 int
	var v75 int
	var v79 uint32
	var v85 *C2bt_tracker_table_t
	var v86 *Probe_event_t
	var v87 *uint32
	if len(out_batch) < max_events {
		max_events = int(len(out_batch))
	}
	v7 = (ctx == nil) || (out_batch == nil)
	if (v7 || (max_events <= 0)) || (ctx.Running == 0) {
		return 0
	}
	v16 = 0
	v18 = 1
	for {
		v20 := v16 < max_events
		v21 := v20 && (v18 != 0)
		if !v21 {
			break
		}
		v18 = 0
		var v23 Probe_event_t
		v26 = &ctx.Chan_proc
		v27 = &v23
		v31 = v20 && (C2bt_channel_read(v26, v27) == 1)
		if v31 {
			v32 = v16
			v16++
			out_batch[v32] = v23
			v18 = 1
		}
		v38 = &ctx.Chan_file
		v39 = &v23
		v43 = (v16 < max_events) && (C2bt_channel_read(v38, v39) == 1)
		if v43 {
			v44 = v16
			v16++
			out_batch[v44] = v23
			v18 = 1
		}
		v50 = &ctx.Chan_net
		v51 = &v23
		v55 = (v16 < max_events) && (C2bt_channel_read(v50, v51) == 1)
		if v55 {
			v56 = v16
			v16++
			out_batch[v56] = v23
			v18 = 1
		}
		v62 = &ctx.Chan_mcp
		v63 = &v23
		v67 = (v16 < max_events) && (C2bt_channel_read(v62, v63) == 1)
		if v67 {
			v68 = v16
			v16++
			out_batch[v68] = v23
			v18 = 1
		}
	}
	if v16 == 0 {
		return 0
	}
	C2bt_eval_rules_batch(out_batch[:], out_batch[:], v16)
	v75 = 0
	{
		_out_batch := out_batch[:v16]
		for v75 = 0; v75 < v16; v75++ {
			v79 = _out_batch[v75].Flags
			var v82 Probe_event_t
			v82 = _out_batch[v75]
			v85 = &ctx.Tracker_table
			v86 = &v82
			v87 = &v79
			C2bt_correlate_event(v85, v86, v87, 1000000000)
			v82.Flags = v79
		}
	}
	return v16
}
