// Code generated by sgoiter emit go127; DO NOT EDIT.
package c2blueteam

func C2bt_tracker_init(table *C2bt_tracker_table_t) {
	if table == nil {
		return
	}
	*table = C2bt_tracker_table_t{}
}

func C2bt_tracker_reset_entry(entry *C2bt_process_tracker_t, pid uint32, ts_ns uint64) {
	if entry == nil {
		return
	}
	entry.Last_ts_ns = ts_ns
	entry.Pid = pid
	entry.Subsystems_mask = 0
	entry.Accumulated_score = 0
	entry.Last_action = 0
	entry.Event_count = 0
	entry.Reserved = 0
}

func C2bt_correlate_event(table *C2bt_tracker_table_t, ev *Probe_event_t, out_flags *uint32, window_ns uint64) int {
	var v28 uint32
	var v29 int
	var v84 bool
	var v94 uint32
	var v132 bool
	var v145 bool
	var v154 bool
	var v163 bool
	var v172 uint32
	var v184 bool
	var v191 uint32
	var v218 bool
	var v233 uint32
	var v244 uint32
	var v252 uint32
	var v254 uint32
	var v261 uint32
	var v272 uint32
	_ = 0
	if ((table == nil) || (ev == nil)) || (out_flags == nil) {
		return -1
	}
	if window_ns == 0 {
		window_ns = 0x3b9aca00
	}
	v23 := ev.Pid & 0x3ff
	v27 := uint32(ev.Src) & 0x3ff
	v28 = func() uint32 {
		if ev.Pid != 0 {
			return v23
		}
		return v27
	}()
	v29 = 0
	if (table.Entries[v28].Last_ts_ns == 0) || (table.Entries[v28].Pid != ev.Pid) {
		v29 = 1
	} else {
		if ev.Ts_ns < table.Entries[v28].Last_ts_ns {
			v29 = 1
		} else {
			if (ev.Ts_ns - table.Entries[v28].Last_ts_ns) > window_ns {
				v29 = 1
			}
		}
	}
	if v29 != 0 {
		C2bt_tracker_reset_entry(&table.Entries[v28], ev.Pid, ev.Ts_ns)
	}
	table.Entries[v28].Last_ts_ns = ev.Ts_ns
	table.Entries[v28].Event_count = table.Entries[v28].Event_count + 1
	table.Entries[v28].Last_action = ev.Action
	v84 = (ev.Subsystem > 0) && (ev.Subsystem <= 7)
	if v84 {
		table.Entries[v28].Subsystems_mask = table.Entries[v28].Subsystems_mask | uint32(1<<byte(ev.Subsystem))
	}
	v94 = 5
	v98 := ev.Flags & 8
	if v98 != 0 {
		v94 += 40
	}
	v103 := ev.Flags & 4
	if v103 != 0 {
		v94 += 30
	}
	v108 := ev.Flags & 2
	if v108 != 0 {
		v94 += 50
	}
	v113 := ev.Flags & 0x100
	if v113 != 0 {
		v94 += 35
	}
	v118 := ev.Flags & 0x80
	if v118 != 0 {
		v94 += 25
	}
	v123 := ev.Flags & 64
	if v123 != 0 {
		v94 += 20
	}
	v132 = (ev.Subsystem == 4) && (ev.Action == 4)
	if v132 {
		v94 += 15
	}
	v143 := ev.Flags & 2
	v145 = (ev.Subsystem == 2) && ((ev.Action == 6) || (v143 != 0))
	if v145 {
		v94 += 40
	}
	v154 = (ev.Subsystem == 3) && (ev.Action == 3)
	if v154 {
		v94 += 25
	}
	v163 = (ev.Subsystem == 6) && (ev.Src >= 0x578)
	if v163 {
		v94 += 25
	}
	table.Entries[v28].Accumulated_score = table.Entries[v28].Accumulated_score + v94
	v172 = table.Entries[v28].Subsystems_mask
	v179 := v172 & 16
	v183 := v172 & 2
	v184 = (v179 != 0) && (v183 != 0)
	if v184 {
		v191 = ev.Flags & 14
		if (v191 != 0) || (table.Entries[v28].Accumulated_score >= 50) {
			table.Entries[v28].Accumulated_score = table.Entries[v28].Accumulated_score + 40
		}
	}
	v208 := v172 & 64
	v212 := v172 & 2
	v216 := v172 & 16
	v218 = (v208 != 0) && ((v212 != 0) || (v216 != 0))
	if v218 {
		table.Entries[v28].Accumulated_score = table.Entries[v28].Accumulated_score + 45
	}
	v229 := v172 & 4
	if v229 != 0 {
		v233 = v172 & 2
		if v233 != 0 {
			table.Entries[v28].Accumulated_score = table.Entries[v28].Accumulated_score + 40
		}
		v244 = v172 & 8
		if v244 != 0 {
			table.Entries[v28].Accumulated_score = table.Entries[v28].Accumulated_score + 45
		}
	}
	v252 = 0
	for v254 = 1; v254 <= 7; v254++ {
		v261 = v172 & (1 << byte(v254))
		if v261 != 0 {
			v252++
		}
	}
	if v252 >= 3 {
		table.Entries[v28].Accumulated_score = table.Entries[v28].Accumulated_score + 50
	}
	v272 = ev.Flags
	if table.Entries[v28].Accumulated_score >= 0x64 {
		v272 |= 0x206
		v272 &= 0xfffffffe
	}
	*out_flags = v272
	return 0
}
