// Code generated by sgoiter emit go127; DO NOT EDIT.
package c2blueteam

import "sync/atomic"

func C2bt_channel_init(ch *Probe_channel_t) {
	var v4 *uint64
	var v9 *uint64
	var v14 *uint64
	if ch == nil {
		return
	}
	v4 = &ch.Head
	atomic.StoreUint64(v4, 0)
	v9 = &ch.Drops
	atomic.StoreUint64(v9, 0)
	v14 = &ch.Tail
	atomic.StoreUint64(v14, 0)
	clear(ch.Slots[:])
}

func C2bt_channel_write(ch *Probe_channel_t, ev *Probe_event_t) int {
	var v12 *uint64
	var v17 *uint64
	var v23 *uint64
	var v36 *uint64
	if (ch == nil) || (ev == nil) {
		return -1
	}
	v12 = &ch.Head
	v14 := atomic.LoadUint64(v12)
	v17 = &ch.Tail
	if (v14 - atomic.LoadUint64(v17)) >= 0x400 {
		v23 = &ch.Drops
		atomic.AddUint64(v23, 1)
		return -2
	}
	v32 := v14 & 0x3ff
	ch.Slots[v32] = *ev
	v36 = &ch.Head
	atomic.StoreUint64(v36, (v14 + 1))
	return 0
}

func C2bt_channel_read(ch *Probe_channel_t, ev *Probe_event_t) int {
	var v12 *uint64
	var v17 *uint64
	var v27 *uint64
	if (ch == nil) || (ev == nil) {
		return -1
	}
	v12 = &ch.Tail
	v14 := atomic.LoadUint64(v12)
	v17 = &ch.Head
	if v14 >= atomic.LoadUint64(v17) {
		return 0
	}
	v23 := v14 & 0x3ff
	*ev = ch.Slots[v23]
	v27 = &ch.Tail
	atomic.StoreUint64(v27, (v14 + 1))
	return 1
}

func C2bt_channel_read_batch(ch *Probe_channel_t, out_events []Probe_event_t, max_events int) int {
	var v14 *uint64
	var v19 *uint64
	var v26 int
	var v28 int
	var v38 uint64
	var v42 *uint64
	if len(out_events) < max_events {
		max_events = int(len(out_events))
	}
	_ = 0
	if ((ch == nil) || (out_events == nil)) || (max_events <= 0) {
		return 0
	}
	v14 = &ch.Tail
	v16 := atomic.LoadUint64(v14)
	v19 = &ch.Head
	v23 := atomic.LoadUint64(v19) - v16
	if v23 == 0 {
		return 0
	}
	v26 = int(v23)
	if v26 > max_events {
		v26 = max_events
	}
	v28 = 0
	{
		_out_events := out_events[:v26]
		for v28 = 0; v28 < v26; v28++ {
			v38 = (v16 + uint64(v28)) & 0x3ff
			_out_events[v28] = ch.Slots[v38]
		}
	}
	v42 = &ch.Tail
	atomic.StoreUint64(v42, (v16 + uint64(v26)))
	return v26
}

func C2bt_channel_get_drops(ch *Probe_channel_t) uint64 {
	var v5 *uint64
	if ch == nil {
		return 0
	}
	v5 = &ch.Drops
	return uint64(atomic.LoadUint64(v5))
}
