// Code generated by sgoiter emit go127; DO NOT EDIT.
package c2blueteam

var __str_427e4b79 = []byte("curl")
var __str_570e342d = []byte("wget")
var __str_0be47733 = []byte("nc")
var __str_6413b570 = []byte("ncat")
var __str_332c7a7d = []byte("netcat")
var __str_b45af0d0 = []byte("socat")
var __str_371a286d = []byte("base64")
var __str_11a4a60b = []byte("python")
var __str_f0c929a9 = []byte("perl")
var __str_b9138194 = []byte("ruby")
var __str_12a5d18e = []byte("php")
var __str_dc436b32 = []byte("lua")
var __str_89c4ec9f = []byte("sh")
var __str_37d2b12d = []byte("bash")
var __str_a26e3765 = []byte("zsh")
var __str_af9d2c92 = []byte("dash")
var __str_037d390c = []byte("ash")
var __str_7cb52b38 = []byte("| sh")
var __str_9604b2e2 = []byte("| bash")
var __str_535d6959 = []byte("|sh")
var __str_2dc7bb63 = []byte("|bash")
var __str_3aa78388 = []byte("rm -rf")
var __str_f49034ae = []byte("rm -r ")
var __str_188d1a63 = []byte("chmod 777")
var __str_3f5e076a = []byte("mkfs")
var __str_f8f28268 = []byte("dd if=")
var __str_e026f56c = []byte(".claude")
var __str_6ebdb617 = []byte("CLAUDE.md")
var __str_a54ff182 = []byte("AGENTS.md")

func Check_lolbas_comm(comm []byte) int {
	var v9 int
	var v21 bool
	var v25 int
	var v43 int
	var v44 int
	var v64 bool
	var v73 bool
	var v82 bool
	var v91 bool
	var v100 bool
	var v109 bool
	var v118 bool
	var v127 bool
	var v136 bool
	var v145 bool
	var v154 bool
	var v163 bool
	var v172 bool
	var v181 bool
	var v190 bool
	var v199 bool
	var v208 bool
	if (comm == nil) || (comm[0] == 0) {
		return 0
	}
	v9 = 0
	for {
		v11 := comm[v9]
		if v11 == 0 {
			break
		}
		v21 = (v11 != 32) && (v11 != 9)
		if v21 {
			break
		}
		v9++
	}
	if comm[v9] == 0 {
		return 0
	}
	v25 = v9
	for {
		v26 := comm[v25]
		if v26 == 0 {
			break
		}
		if (((v26 == 32) || (v26 == 9)) || (v26 == 13)) || (v26 == 10) {
			break
		}
		v25++
	}
	v43 = v9
	for v44 = v9; v44 < v25; v44++ {
		if comm[v44] == 47 {
			v43 = v44 + 1
		}
	}
	v52 := v25 - v43
	if v52 <= 0 {
		return 0
	}
	v56 := comm[v43:]
	v61 := func(a, b []byte, n int) int {
		for i := 0; i < n && i < len(a) && i < len(b); i++ {
			if a[i] != b[i] {
				if a[i] < b[i] {
					return -1
				}
				return 1
			}
			if a[i] == 0 {
				break
			}
		}
		return 0
	}(v56[:], []byte(__str_427e4b79), 4)
	v64 = (v52 == 4) && (v61 == 0)
	if v64 {
		return 1
	}
	v70 := func(a, b []byte, n int) int {
		for i := 0; i < n && i < len(a) && i < len(b); i++ {
			if a[i] != b[i] {
				if a[i] < b[i] {
					return -1
				}
				return 1
			}
			if a[i] == 0 {
				break
			}
		}
		return 0
	}(v56[:], []byte(__str_570e342d), 4)
	v73 = (v52 == 4) && (v70 == 0)
	if v73 {
		return 1
	}
	v79 := func(a, b []byte, n int) int {
		for i := 0; i < n && i < len(a) && i < len(b); i++ {
			if a[i] != b[i] {
				if a[i] < b[i] {
					return -1
				}
				return 1
			}
			if a[i] == 0 {
				break
			}
		}
		return 0
	}(v56[:], []byte(__str_0be47733), 2)
	v82 = (v52 == 2) && (v79 == 0)
	if v82 {
		return 1
	}
	v88 := func(a, b []byte, n int) int {
		for i := 0; i < n && i < len(a) && i < len(b); i++ {
			if a[i] != b[i] {
				if a[i] < b[i] {
					return -1
				}
				return 1
			}
			if a[i] == 0 {
				break
			}
		}
		return 0
	}(v56[:], []byte(__str_6413b570), 4)
	v91 = (v52 == 4) && (v88 == 0)
	if v91 {
		return 1
	}
	v97 := func(a, b []byte, n int) int {
		for i := 0; i < n && i < len(a) && i < len(b); i++ {
			if a[i] != b[i] {
				if a[i] < b[i] {
					return -1
				}
				return 1
			}
			if a[i] == 0 {
				break
			}
		}
		return 0
	}(v56[:], []byte(__str_332c7a7d), 6)
	v100 = (v52 == 6) && (v97 == 0)
	if v100 {
		return 1
	}
	v106 := func(a, b []byte, n int) int {
		for i := 0; i < n && i < len(a) && i < len(b); i++ {
			if a[i] != b[i] {
				if a[i] < b[i] {
					return -1
				}
				return 1
			}
			if a[i] == 0 {
				break
			}
		}
		return 0
	}(v56[:], []byte(__str_b45af0d0), 5)
	v109 = (v52 == 5) && (v106 == 0)
	if v109 {
		return 1
	}
	v115 := func(a, b []byte, n int) int {
		for i := 0; i < n && i < len(a) && i < len(b); i++ {
			if a[i] != b[i] {
				if a[i] < b[i] {
					return -1
				}
				return 1
			}
			if a[i] == 0 {
				break
			}
		}
		return 0
	}(v56[:], []byte(__str_371a286d), 6)
	v118 = (v52 == 6) && (v115 == 0)
	if v118 {
		return 1
	}
	v124 := func(a, b []byte, n int) int {
		for i := 0; i < n && i < len(a) && i < len(b); i++ {
			if a[i] != b[i] {
				if a[i] < b[i] {
					return -1
				}
				return 1
			}
			if a[i] == 0 {
				break
			}
		}
		return 0
	}(v56[:], []byte(__str_11a4a60b), 6)
	v127 = (v52 >= 6) && (v124 == 0)
	if v127 {
		return 1
	}
	v133 := func(a, b []byte, n int) int {
		for i := 0; i < n && i < len(a) && i < len(b); i++ {
			if a[i] != b[i] {
				if a[i] < b[i] {
					return -1
				}
				return 1
			}
			if a[i] == 0 {
				break
			}
		}
		return 0
	}(v56[:], []byte(__str_f0c929a9), 4)
	v136 = (v52 == 4) && (v133 == 0)
	if v136 {
		return 1
	}
	v142 := func(a, b []byte, n int) int {
		for i := 0; i < n && i < len(a) && i < len(b); i++ {
			if a[i] != b[i] {
				if a[i] < b[i] {
					return -1
				}
				return 1
			}
			if a[i] == 0 {
				break
			}
		}
		return 0
	}(v56[:], []byte(__str_b9138194), 4)
	v145 = (v52 == 4) && (v142 == 0)
	if v145 {
		return 1
	}
	v151 := func(a, b []byte, n int) int {
		for i := 0; i < n && i < len(a) && i < len(b); i++ {
			if a[i] != b[i] {
				if a[i] < b[i] {
					return -1
				}
				return 1
			}
			if a[i] == 0 {
				break
			}
		}
		return 0
	}(v56[:], []byte(__str_12a5d18e), 3)
	v154 = (v52 >= 3) && (v151 == 0)
	if v154 {
		return 1
	}
	v160 := func(a, b []byte, n int) int {
		for i := 0; i < n && i < len(a) && i < len(b); i++ {
			if a[i] != b[i] {
				if a[i] < b[i] {
					return -1
				}
				return 1
			}
			if a[i] == 0 {
				break
			}
		}
		return 0
	}(v56[:], []byte(__str_dc436b32), 3)
	v163 = (v52 >= 3) && (v160 == 0)
	if v163 {
		return 1
	}
	v169 := func(a, b []byte, n int) int {
		for i := 0; i < n && i < len(a) && i < len(b); i++ {
			if a[i] != b[i] {
				if a[i] < b[i] {
					return -1
				}
				return 1
			}
			if a[i] == 0 {
				break
			}
		}
		return 0
	}(v56[:], []byte(__str_89c4ec9f), 2)
	v172 = (v52 == 2) && (v169 == 0)
	if v172 {
		return 1
	}
	v178 := func(a, b []byte, n int) int {
		for i := 0; i < n && i < len(a) && i < len(b); i++ {
			if a[i] != b[i] {
				if a[i] < b[i] {
					return -1
				}
				return 1
			}
			if a[i] == 0 {
				break
			}
		}
		return 0
	}(v56[:], []byte(__str_37d2b12d), 4)
	v181 = (v52 == 4) && (v178 == 0)
	if v181 {
		return 1
	}
	v187 := func(a, b []byte, n int) int {
		for i := 0; i < n && i < len(a) && i < len(b); i++ {
			if a[i] != b[i] {
				if a[i] < b[i] {
					return -1
				}
				return 1
			}
			if a[i] == 0 {
				break
			}
		}
		return 0
	}(v56[:], []byte(__str_a26e3765), 3)
	v190 = (v52 == 3) && (v187 == 0)
	if v190 {
		return 1
	}
	v196 := func(a, b []byte, n int) int {
		for i := 0; i < n && i < len(a) && i < len(b); i++ {
			if a[i] != b[i] {
				if a[i] < b[i] {
					return -1
				}
				return 1
			}
			if a[i] == 0 {
				break
			}
		}
		return 0
	}(v56[:], []byte(__str_af9d2c92), 4)
	v199 = (v52 == 4) && (v196 == 0)
	if v199 {
		return 1
	}
	v205 := func(a, b []byte, n int) int {
		for i := 0; i < n && i < len(a) && i < len(b); i++ {
			if a[i] != b[i] {
				if a[i] < b[i] {
					return -1
				}
				return 1
			}
			if a[i] == 0 {
				break
			}
		}
		return 0
	}(v56[:], []byte(__str_037d390c), 3)
	v208 = (v52 == 3) && (v205 == 0)
	if v208 {
		return 1
	}
	return 0
}

func C2bt_eval_rules_batch(in_events []Probe_event_t, out_events []Probe_event_t, count int) int {
	var v11 int
	var v16 uint32
	var v22 []byte
	var v40 int
	var v42 int
	var v44 int
	var v46 int
	var v47 int
	var v50 int
	var v52 int
	var v54 int
	var v56 int
	var v57 int
	var v59 int
	var v61 int
	var v62 int
	var v64 int
	var v66 int
	var v67 int
	var v69 int
	var v73 int
	var v78 int
	var v83 int
	var v88 int
	var v92 bool
	var v95 int
	var v100 int
	var v105 int
	var v110 uint32
	var v124 uint64
	var v131 uint32
	var v138 uint32
	var v149 uint32
	var v158 uint32
	var v167 int
	var v171 int
	var v176 int
	if len(in_events) < count {
		count = int(len(in_events))
	}
	if len(out_events) < count {
		count = int(len(out_events))
	}
	if count <= 0 {
		return 0
	}
	if in_events == nil {
		return 0
	}
	if out_events == nil {
		return 0
	}
	for v11 = 0; v11 < count; v11++ {
		out_events[v11] = in_events[v11]
		v16 = out_events[v11].Flags
		v22 = out_events[v11].Payload[:]
		switch out_events[v11].Subsystem {
		case 1:
			if out_events[v11].Action == 1 {
				if Check_lolbas_comm(v22[:]) != 0 {
					v16 |= 12
				} else {
					v16 |= 1
				}
			}
		case 4:
			if out_events[v11].Action == 4 {
				v40 = func(a, b []byte) int {
					if len(b) == 0 {
						return 1
					}
					for i := 0; i+len(b) <= len(a); i++ {
						if a[i] == 0 {
							break
						}
						eq := true
						for j := 0; j < len(b); j++ {
							if a[i+j] == 0 || a[i+j] != b[j] {
								eq = false
								break
							}
						}
						if eq {
							return 1
						}
					}
					return 0
				}(v22[:], []byte(__str_427e4b79))
				v42 = func() int {
					if v40 != 0 {
						return 1
					}
					return 0
				}()
				v44 = func(a, b []byte) int {
					if len(b) == 0 {
						return 1
					}
					for i := 0; i+len(b) <= len(a); i++ {
						if a[i] == 0 {
							break
						}
						eq := true
						for j := 0; j < len(b); j++ {
							if a[i+j] == 0 || a[i+j] != b[j] {
								eq = false
								break
							}
						}
						if eq {
							return 1
						}
					}
					return 0
				}(v22[:], []byte(__str_570e342d))
				v46 = func() int {
					if v44 != 0 {
						return 1
					}
					return 0
				}()
				v47 = func() int {
					if (v42 != 0) || (v46 != 0) {
						return 1
					}
					return 0
				}()
				v50 = func(a, b []byte) int {
					if len(b) == 0 {
						return 1
					}
					for i := 0; i+len(b) <= len(a); i++ {
						if a[i] == 0 {
							break
						}
						eq := true
						for j := 0; j < len(b); j++ {
							if a[i+j] == 0 || a[i+j] != b[j] {
								eq = false
								break
							}
						}
						if eq {
							return 1
						}
					}
					return 0
				}(v22[:], []byte(__str_7cb52b38))
				v52 = func() int {
					if v50 != 0 {
						return 1
					}
					return 0
				}()
				v54 = func(a, b []byte) int {
					if len(b) == 0 {
						return 1
					}
					for i := 0; i+len(b) <= len(a); i++ {
						if a[i] == 0 {
							break
						}
						eq := true
						for j := 0; j < len(b); j++ {
							if a[i+j] == 0 || a[i+j] != b[j] {
								eq = false
								break
							}
						}
						if eq {
							return 1
						}
					}
					return 0
				}(v22[:], []byte(__str_9604b2e2))
				v56 = func() int {
					if v54 != 0 {
						return 1
					}
					return 0
				}()
				v57 = func() int {
					if (v52 != 0) || (v56 != 0) {
						return 1
					}
					return 0
				}()
				v59 = func(a, b []byte) int {
					if len(b) == 0 {
						return 1
					}
					for i := 0; i+len(b) <= len(a); i++ {
						if a[i] == 0 {
							break
						}
						eq := true
						for j := 0; j < len(b); j++ {
							if a[i+j] == 0 || a[i+j] != b[j] {
								eq = false
								break
							}
						}
						if eq {
							return 1
						}
					}
					return 0
				}(v22[:], []byte(__str_535d6959))
				v61 = func() int {
					if v59 != 0 {
						return 1
					}
					return 0
				}()
				v62 = func() int {
					if (v57 != 0) || (v61 != 0) {
						return 1
					}
					return 0
				}()
				v64 = func(a, b []byte) int {
					if len(b) == 0 {
						return 1
					}
					for i := 0; i+len(b) <= len(a); i++ {
						if a[i] == 0 {
							break
						}
						eq := true
						for j := 0; j < len(b); j++ {
							if a[i+j] == 0 || a[i+j] != b[j] {
								eq = false
								break
							}
						}
						if eq {
							return 1
						}
					}
					return 0
				}(v22[:], []byte(__str_2dc7bb63))
				v66 = func() int {
					if v64 != 0 {
						return 1
					}
					return 0
				}()
				v67 = func() int {
					if (v62 != 0) || (v66 != 0) {
						return 1
					}
					return 0
				}()
				v69 = func(a, b []byte) int {
					if len(b) == 0 {
						return 1
					}
					for i := 0; i+len(b) <= len(a); i++ {
						if a[i] == 0 {
							break
						}
						eq := true
						for j := 0; j < len(b); j++ {
							if a[i+j] == 0 || a[i+j] != b[j] {
								eq = false
								break
							}
						}
						if eq {
							return 1
						}
					}
					return 0
				}(v22[:], []byte(__str_3aa78388))
				v73 = func(a, b []byte) int {
					if len(b) == 0 {
						return 1
					}
					for i := 0; i+len(b) <= len(a); i++ {
						if a[i] == 0 {
							break
						}
						eq := true
						for j := 0; j < len(b); j++ {
							if a[i+j] == 0 || a[i+j] != b[j] {
								eq = false
								break
							}
						}
						if eq {
							return 1
						}
					}
					return 0
				}(v22[:], []byte(__str_f49034ae))
				v78 = func(a, b []byte) int {
					if len(b) == 0 {
						return 1
					}
					for i := 0; i+len(b) <= len(a); i++ {
						if a[i] == 0 {
							break
						}
						eq := true
						for j := 0; j < len(b); j++ {
							if a[i+j] == 0 || a[i+j] != b[j] {
								eq = false
								break
							}
						}
						if eq {
							return 1
						}
					}
					return 0
				}(v22[:], []byte(__str_188d1a63))
				v83 = func(a, b []byte) int {
					if len(b) == 0 {
						return 1
					}
					for i := 0; i+len(b) <= len(a); i++ {
						if a[i] == 0 {
							break
						}
						eq := true
						for j := 0; j < len(b); j++ {
							if a[i+j] == 0 || a[i+j] != b[j] {
								eq = false
								break
							}
						}
						if eq {
							return 1
						}
					}
					return 0
				}(v22[:], []byte(__str_3f5e076a))
				v88 = func(a, b []byte) int {
					if len(b) == 0 {
						return 1
					}
					for i := 0; i+len(b) <= len(a); i++ {
						if a[i] == 0 {
							break
						}
						eq := true
						for j := 0; j < len(b); j++ {
							if a[i+j] == 0 || a[i+j] != b[j] {
								eq = false
								break
							}
						}
						if eq {
							return 1
						}
					}
					return 0
				}(v22[:], []byte(__str_f8f28268))
				v92 = (v47 != 0) && (v67 != 0)
				v95 = func(a, b []byte) int {
					if len(b) == 0 {
						return 1
					}
					for i := 0; i+len(b) <= len(a); i++ {
						if a[i] == 0 {
							break
						}
						eq := true
						for j := 0; j < len(b); j++ {
							if a[i+j] == 0 || a[i+j] != b[j] {
								eq = false
								break
							}
						}
						if eq {
							return 1
						}
					}
					return 0
				}(v22[:], []byte(__str_e026f56c))
				v100 = func(a, b []byte) int {
					if len(b) == 0 {
						return 1
					}
					for i := 0; i+len(b) <= len(a); i++ {
						if a[i] == 0 {
							break
						}
						eq := true
						for j := 0; j < len(b); j++ {
							if a[i+j] == 0 || a[i+j] != b[j] {
								eq = false
								break
							}
						}
						if eq {
							return 1
						}
					}
					return 0
				}(v22[:], []byte(__str_6ebdb617))
				v105 = func(a, b []byte) int {
					if len(b) == 0 {
						return 1
					}
					for i := 0; i+len(b) <= len(a); i++ {
						if a[i] == 0 {
							break
						}
						eq := true
						for j := 0; j < len(b); j++ {
							if a[i+j] == 0 || a[i+j] != b[j] {
								eq = false
								break
							}
						}
						if eq {
							return 1
						}
					}
					return 0
				}(v22[:], []byte(__str_a54ff182))
				v110 = v16 & 0x100
				if (((((((((v69 != 0) || (v73 != 0)) || (v78 != 0)) || (v83 != 0)) || (v88 != 0)) || v92) || (v95 != 0)) || (v100 != 0)) || (v105 != 0)) || (v110 != 0) {
					v16 |= 6
				} else {
					v16 |= 1
				}
			}
		case 6:
			v124 = out_events[v11].Src & 0xffffffff
			v131 = uint32(uint64(out_events[v11].Src >> 32))
			v138 = v16 & 0x100
			if ((v131 == 4) || (uint32(v124) >= 0x780)) || (v138 != 0) {
				v16 |= 0x106
			} else {
				v149 = v16 & 0x80
				if (v131 == 3) || (v149 != 0) {
					v16 |= 0x84
				} else {
					v158 = v16 & 64
					if (v131 == 2) || (v158 != 0) {
						v16 |= 0x44
					} else {
						v16 |= 1
					}
				}
			}
		case 2:
			v167 = func(a, b []byte) int {
				if len(b) == 0 {
					return 1
				}
				for i := 0; i+len(b) <= len(a); i++ {
					if a[i] == 0 {
						break
					}
					eq := true
					for j := 0; j < len(b); j++ {
						if a[i+j] == 0 || a[i+j] != b[j] {
							eq = false
							break
						}
					}
					if eq {
						return 1
					}
				}
				return 0
			}(v22[:], []byte(__str_e026f56c))
			v171 = func(a, b []byte) int {
				if len(b) == 0 {
					return 1
				}
				for i := 0; i+len(b) <= len(a); i++ {
					if a[i] == 0 {
						break
					}
					eq := true
					for j := 0; j < len(b); j++ {
						if a[i+j] == 0 || a[i+j] != b[j] {
							eq = false
							break
						}
					}
					if eq {
						return 1
					}
				}
				return 0
			}(v22[:], []byte(__str_6ebdb617))
			v176 = func(a, b []byte) int {
				if len(b) == 0 {
					return 1
				}
				for i := 0; i+len(b) <= len(a); i++ {
					if a[i] == 0 {
						break
					}
					eq := true
					for j := 0; j < len(b); j++ {
						if a[i+j] == 0 || a[i+j] != b[j] {
							eq = false
							break
						}
					}
					if eq {
						return 1
					}
				}
				return 0
			}(v22[:], []byte(__str_a54ff182))
			if ((v167 != 0) || (v171 != 0)) || (v176 != 0) {
				if (out_events[v11].Action == 6) || (out_events[v11].Action == 2) {
					v16 |= 6
				}
			} else {
				v16 |= 1
			}
		default:
			v16 |= 1
		}
		out_events[v11].Flags = v16
	}
	return count
}
