// Code generated by sgoiter emit go127; DO NOT EDIT.
package c2blueteam

type C2bt_entropy_profile_t struct {
	Entropy_q8     uint32
	Char_mask      uint32
	Distinct_count uint16
	Payload_class  uint16
	Len_           uint64
}

type Probe_event_t struct {
	Ts_ns     uint64
	Pid       uint32
	Tid       uint32
	Subsystem uint16
	Action    uint16
	Flags     uint32
	Src       uint64
	Payload   [96]byte
}

type Probe_channel_t struct {
	Slots [1024]Probe_event_t
	Head  uint64
	Drops uint64
	Pad1  [48]byte
	Tail  uint64
	Pad2  [56]byte
}

type C2bt_config_t struct {
	Enable_proc      byte
	Enable_file      byte
	Enable_net       byte
	Enable_mcp       byte
	Enable_entropy   byte
	Enable_gpu       byte
	Enforce_mode     byte
	Fail_safe_policy byte
	Mcp_socket_path  []byte
	Harness_dir      []byte
}

type C2bt_process_tracker_t struct {
	Last_ts_ns        uint64
	Pid               uint32
	Subsystems_mask   uint32
	Accumulated_score uint32
	Last_action       uint16
	Event_count       uint16
	Reserved          uint32
}

type C2bt_tracker_table_t struct {
	Entries [1024]C2bt_process_tracker_t
}

type C2bt_ctx_t struct {
	Config        C2bt_config_t
	Chan_proc     Probe_channel_t
	Chan_file     Probe_channel_t
	Chan_net      Probe_channel_t
	Chan_mcp      Probe_channel_t
	Tracker_table C2bt_tracker_table_t
	Batch_buf     [8]Probe_event_t
	Running       int
	Sealed_mem_fd int
	Fanotify_fd   int
	Mcp_proxy_fd  int
}
