// Code generated by sgoiter emit go127; DO NOT EDIT.
// sgoiter-stamp: sha256=539fd04a8466719909b7a12325bed5a63ce3400184604d20f71db0cc3f8292d7
package c2strsimd

func C2_memchr(src []byte, len_ uint64, target byte) int64 {
	var v3 uint64
	if uint64(len(src)) < len_ {
		len_ = uint64(len(src))
	}
	for v3 = 0; v3 < len_; v3++ {
		if src[v3] == target {
			return int64(v3)
		}
	}
	return -1
}

func C2_strpos(haystack []byte, h_len uint64, needle []byte, n_len uint64) int64 {
	var v24 uint64
	var v42 []byte
	var v48 int
	if n_len == 0 {
		return 0
	}
	if h_len < n_len {
		return -1
	}
	if n_len == 1 {
		return int64(C2_memchr(haystack[:], h_len, needle[0]))
	}
	for v24 = 0; v24 < ((h_len - n_len) + 1); v24++ {
		if haystack[v24] == needle[0] {
			if haystack[int((v24+n_len)-1)] == needle[int(n_len-1)] {
				v42 = haystack[int(v24+1):]
				v48 = func(a, b []byte, n int) int {
					for i := 0; i < n && i < len(a) && i < len(b); i++ {
						if a[i] != b[i] {
							if a[i] < b[i] {
								return -1
							}
							return 1
						}
					}
					return 0
				}(v42[:], needle[1:], int(n_len-2))
				if (n_len <= 2) || (v48 == 0) {
					return int64(v24)
				}
			}
		}
	}
	return -1
}

func C2_strtoupper(dst []byte, src []byte, len_ uint64) {
	var v3 uint64
	var v8 byte
	var v14 uint64
	for v3 = 0; v3 < len_; v3++ {
		v8 = src[v3]
		v14 = func() uint64 {
			if (v8 - 'a') <= 25 {
				return 1
			}
			return 0
		}()
		dst[v3] = v8 - (byte(v14) * 32)
	}
}

func C2_strtolower(dst []byte, src []byte, len_ uint64) {
	var v3 uint64
	var v8 byte
	var v14 uint64
	for v3 = 0; v3 < len_; v3++ {
		v8 = src[v3]
		v14 = func() uint64 {
			if (v8 - 'A') <= 25 {
				return 1
			}
			return 0
		}()
		dst[v3] = v8 + (byte(v14) * 32)
	}
}

func C2_mb_strlen_utf8(src []byte, byte_len uint64) uint64 {
	var v2 uint64
	var v4 uint64
	var v10 byte
	if uint64(len(src)) < byte_len {
		byte_len = uint64(len(src))
	}
	v2 = 0
	for v4 = 0; v4 < byte_len; v4++ {
		v10 = src[v4] & 0xc0
		if v10 != 0x80 {
			v2++
		}
	}
	return v2
}

func C2_ltrim_offset(src []byte, len_ uint64, cutset_bitmap_32b []byte) uint64 {
	var v3 uint64
	var v8 byte
	var v14 byte
	var v17 uint64
	for v3 = 0; v3 < len_; v3++ {
		v8 = src[v3]
		v14 = v8 & 7
		v17 = uint64(uint64(cutset_bitmap_32b[int(uint64(uint64(v8)>>3))])>>v14) & 1
		if byte(v17) == 0 {
			return v3
		}
	}
	return len_
}

func C2_rtrim_len(src []byte, len_ uint64, cutset_bitmap_32b []byte) uint64 {
	var v7 byte
	var v13 byte
	var v16 uint64
	for len_ > 0 {
		v7 = src[int(len_-1)]
		v13 = v7 & 7
		v16 = uint64(uint64(cutset_bitmap_32b[int(uint64(uint64(v7)>>3))])>>v13) & 1
		if byte(v16) == 0 {
			break
		}
		len_--
	}
	return len_
}
