// Code generated by sgoiter emit go127; DO NOT EDIT.
package crc32_ieee

func Crc32_ieee(data []byte, len uint64) uint32 {
	v2 := uint32(4294967295)
	v4 := uint32(0)
	for uint64(v4) < len {
	v9 := data[int(int(v4))]
	v10 := v2 ^ uint32(v9)
	v2 = v10
	v5 := uint32(0)
	for v5 < uint32(8) {
	v17 := v2 & uint32(1)
	v19 := -int(int(v17))
	v15 := v19
	v21 := v2 >> uint8(1)
	v23 := uint32(3988292384) & uint32(v15)
	v24 := v21 ^ v23
	v2 = v24
	v14 := v5 + uint32(1)
	v5 = v14
	}
	v8 := v4 + uint32(1)
	v4 = v8
	}
	v25 := ^v2
	return v25
}

