// Code generated by sgoiter emit go127; DO NOT EDIT.
// sgoiter-stamp: sha256=4338c7b410a45ea5b9530a164fa69769366cb1dd9dae5980d548d09b392418ba
package c2ssim

var C2_gauss_weights = [11]int{67, 498, 2360, 7167, 13959, 17434, 13959, 7167, 2360, 498, 67}

func c2_clamp_coord(coord int, max_val int) int {
	if coord < 0 {
		return 0
	}
	if coord >= max_val {
		return (max_val - 1)
	}
	return coord
}

func C2_gaussian_blur_1d_h(src []byte, tmp []uint16, width int, height int, stride int) {
	var v6 int
	var v8 int
	var v10 int
	var v27 int64
	v6 = 0
	v8 = 0
	v10 = 0
	if (width <= 0) || (height <= 0) {
		return
	}
	for v6 = 0; v6 < height; v6++ {
		v8 = 0
		for v8 < width {
			v27 = 0x8000
			v10 = -5
			for v10 <= 5 {
				v27 += (int64(int(C2_gauss_weights[(v10+5)])) * int64(src[int((v6*stride)+c2_clamp_coord((v8+v10), width))]))
				v10++
			}
			tmp[int((v6*width)+v8)] = uint16(int64(v27 >> 16))
			v8++
		}
	}
}

func C2_gaussian_blur_1d_v(tmp []uint16, dst []byte, width int, height int, stride int) {
	var v6 int
	var v8 int
	var v10 int
	var v25 int64
	var v48 int64
	v6 = 0
	v8 = 0
	v10 = 0
	if (width <= 0) || (height <= 0) {
		return
	}
	for v6 = 0; v6 < height; v6++ {
		v8 = 0
		for v8 < width {
			v25 = 0x8000
			v10 = -5
			for v10 <= 5 {
				v25 += (int64(int(C2_gauss_weights[(v10+5)])) * int64(tmp[int((c2_clamp_coord((v6+v10), height)*width)+v8)]))
				v10++
			}
			v48 = int64(v25 >> 16)
			if v48 > 255 {
				v48 = 255
			}
			dst[int((v6*stride)+v8)] = byte(v48)
			v8++
		}
	}
}

func C2_gaussian_blur_2d(src []byte, dst []byte, tmp []uint16, width int, height int, stride int) {
	C2_gaussian_blur_1d_h(src[:], tmp, width, height, stride)
	C2_gaussian_blur_1d_v(tmp, dst[:], width, height, stride)
}

func C2_gaussian_blur_1d_h_u32(src []uint32, tmp []uint32, width int, height int, stride int) {
	var v6 int
	var v8 int
	var v10 int
	var v27 int64
	v6 = 0
	v8 = 0
	v10 = 0
	if (width <= 0) || (height <= 0) {
		return
	}
	for v6 = 0; v6 < height; v6++ {
		v8 = 0
		for v8 < width {
			v27 = 0x8000
			v10 = -5
			for v10 <= 5 {
				v27 += (int64(int(C2_gauss_weights[(v10+5)])) * int64(src[int((v6*stride)+c2_clamp_coord((v8+v10), width))]))
				v10++
			}
			tmp[int((v6*width)+v8)] = uint32(int64(v27 >> 16))
			v8++
		}
	}
}

func C2_gaussian_blur_1d_v_u32(tmp []uint32, dst []uint32, width int, height int, stride int) {
	var v6 int
	var v8 int
	var v10 int
	var v25 int64
	v6 = 0
	v8 = 0
	v10 = 0
	if (width <= 0) || (height <= 0) {
		return
	}
	for v6 = 0; v6 < height; v6++ {
		v8 = 0
		for v8 < width {
			v25 = 0x8000
			v10 = -5
			for v10 <= 5 {
				v25 += (int64(int(C2_gauss_weights[(v10+5)])) * int64(tmp[int((c2_clamp_coord((v6+v10), height)*width)+v8)]))
				v10++
			}
			dst[int((v6*stride)+v8)] = uint32(int64(v25 >> 16))
			v8++
		}
	}
}

func C2_gaussian_blur_2d_u32(src []uint32, dst []uint32, tmp []uint32, width int, height int, stride int) {
	C2_gaussian_blur_1d_h_u32(src[:], tmp[:], width, height, stride)
	C2_gaussian_blur_1d_v_u32(tmp[:], dst[:], width, height, stride)
}

func C2_ssim_compute_milli(img1 []byte, img2 []byte, width int, height int, stride int) int64 {
	var v6 int
	var v8 int
	var v10 int64
	var v12 int64
	var v14 int64
	var v16 int64
	var v36 int64
	var v38 int64
	var v40 int64
	var v42 int64
	var v44 int64
	var v46 int
	var v48 int
	var v83 int64
	var v86 int
	var v92 int64
	var v95 int64
	var v115 int64
	var v118 int64
	var v128 int64
	var v131 int64
	var v161 int64
	var v163 int64
	v6 = 0
	v8 = 0
	v10 = 0
	v12 = v10
	v14 = 0x28a
	v16 = 0x16dc
	if (((width <= 0) || (height <= 0)) || (img1 == nil)) || (img2 == nil) {
		return 0
	}
	for v6 = 0; v6 < height; v6++ {
		v8 = 0
		for v8 < width {
			v36 = 0x8000
			v38 = v36
			v40 = v38
			v42 = v40
			v44 = v42
			v46 = 0
			v48 = 0
			v46 = -5
			for v46 <= 5 {
				v48 = -5
				for v48 <= 5 {
					v83 = int64(((int64(int(C2_gauss_weights[(v46+5)])) * int64(int(C2_gauss_weights[(v48+5)]))) + 0x8000) >> 16)
					v86 = (c2_clamp_coord((v6+v46), height) * stride) + c2_clamp_coord((v8+v48), width)
					v92 = int64(img1[v86])
					v36 += (v83 * v92)
					v95 = int64(img2[v86])
					v38 += (v83 * v95)
					v40 += (v83 * (v92 * v92))
					v42 += (v83 * (v95 * v95))
					v44 += (v83 * (v92 * v95))
					v48++
				}
				v46++
			}
			v115 = int64(v36 >> 16)
			v118 = int64(v38 >> 16)
			v128 = int64(v40>>16) - (v115 * v115)
			v131 = int64(v42>>16) - (v118 * v118)
			if v128 < 0 {
				v128 = 0
			}
			if v131 < 0 {
				v131 = 0
			}
			v161 = (((v115 * v115) + (v118 * v118)) + v14) * ((v128 + v131) + v16)
			if v161 != 0 {
				v163 = (((((2 * v115) * v118) + v14) * ((2 * (int64(v44>>16) - (v115 * v118))) + v16)) * 0xf4240) / v161
				if v163 > 0xf4240 {
					v163 = 0xf4240
				}
				if v163 < -1000000 {
					v163 = -1000000
				}
				v10 += v163
			}
			v12++
			v8++
		}
	}
	if v12 == 0 {
		return 0
	}
	return int64(v10 / v12)
}

func C2_ssim_compute_q16(img1 []byte, img2 []byte, width int, height int, stride int) int64 {
	return int64(((C2_ssim_compute_milli(img1[:], img2[:], width, height, stride) * 0x10000) + 0x7a120) / 0xf4240)
}
