// Code generated by sgoiter emit go127; DO NOT EDIT.
// sgoiter-stamp: sha256=5e05d90a5932c74cbfb5cfbbeb5ef5bd803739d4e1a0628cc7d4e9745e7a514a
package c2ssim

var C2_gauss_weights = [11]int{67, 498, 2360, 7167, 13959, 17434, 13959, 7167, 2360, 498, 67}

func c2_clamp_coord(coord int, max_val int) int {
	if coord < 0 {
		return 0
	}
	if coord >= max_val {
		return (max_val - 1)
	}
	return coord
}

func C2_gaussian_blur_1d_h(src []byte, tmp []uint16, width int, height int, stride int) {
	var v6 int
	var v8 int
	var v10 int
	var v27 int64
	v6 = 0
	v8 = 0
	v10 = 0
	if (width <= 0) || (height <= 0) {
		return
	}
	for v6 = 0; v6 < height; v6++ {
		v8 = 0
		for v8 < width {
			v27 = 0x8000
			v10 = -5
			for v10 <= 5 {
				v27 += (int64(int(C2_gauss_weights[(v10+5)])) * int64(src[int((v6*stride)+c2_clamp_coord((v8+v10), width))]))
				v10++
			}
			tmp[int((v6*width)+v8)] = uint16(int64(v27 >> 16))
			v8++
		}
	}
}

func C2_gaussian_blur_1d_v(tmp []uint16, dst []byte, width int, height int, stride int) {
	var v6 int
	var v8 int
	var v10 int
	var v25 int64
	var v46 int64
	v6 = 0
	v8 = 0
	v10 = 0
	if (width <= 0) || (height <= 0) {
		return
	}
	for v6 = 0; v6 < height; v6++ {
		v8 = 0
		for v8 < width {
			v25 = 0x8000
			v10 = -5
			for v10 <= 5 {
				v25 += (int64(int(C2_gauss_weights[(v10+5)])) * int64(tmp[int((c2_clamp_coord((v6+v10), height)*width)+v8)]))
				v10++
			}
			v46 = int64(v25 >> 16)
			if v46 > 255 {
				v46 = 255
			}
			dst[int((v6*stride)+v8)] = byte(v46)
			v8++
		}
	}
}

func C2_gaussian_blur_2d(src []byte, dst []byte, tmp []uint16, width int, height int, stride int) {
	C2_gaussian_blur_1d_h(src[:], tmp, width, height, stride)
	C2_gaussian_blur_1d_v(tmp, dst[:], width, height, stride)
}

func C2_gaussian_blur_1d_h_u32(src []uint32, tmp []uint32, width int, height int, stride int) {
	var v6 int
	var v8 int
	var v10 int
	var v27 int64
	v6 = 0
	v8 = 0
	v10 = 0
	if (width <= 0) || (height <= 0) {
		return
	}
	for v6 = 0; v6 < height; v6++ {
		v8 = 0
		for v8 < width {
			v27 = 0x8000
			v10 = -5
			for v10 <= 5 {
				v27 += (int64(int(C2_gauss_weights[(v10+5)])) * int64(src[int((v6*stride)+c2_clamp_coord((v8+v10), width))]))
				v10++
			}
			tmp[int((v6*width)+v8)] = uint32(int64(v27 >> 16))
			v8++
		}
	}
}

func C2_gaussian_blur_1d_v_u32(tmp []uint32, dst []uint32, width int, height int, stride int) {
	var v6 int
	var v8 int
	var v10 int
	var v25 int64
	v6 = 0
	v8 = 0
	v10 = 0
	if (width <= 0) || (height <= 0) {
		return
	}
	for v6 = 0; v6 < height; v6++ {
		v8 = 0
		for v8 < width {
			v25 = 0x8000
			v10 = -5
			for v10 <= 5 {
				v25 += (int64(int(C2_gauss_weights[(v10+5)])) * int64(tmp[int((c2_clamp_coord((v6+v10), height)*width)+v8)]))
				v10++
			}
			dst[int((v6*stride)+v8)] = uint32(int64(v25 >> 16))
			v8++
		}
	}
}

func C2_gaussian_blur_2d_u32(src []uint32, dst []uint32, tmp []uint32, width int, height int, stride int) {
	C2_gaussian_blur_1d_h_u32(src[:], tmp[:], width, height, stride)
	C2_gaussian_blur_1d_v_u32(tmp[:], dst[:], width, height, stride)
}

func C2_ssim_compute_milli(img1 []byte, img2 []byte, width int, height int, stride int) int64 {
	var v6 int
	var v8 int
	var v10 int64
	var v12 int64
	var v14 int64
	var v16 int64
	var v36 int64
	var v38 int64
	var v40 int64
	var v42 int64
	var v44 int64
	var v46 int
	var v48 int
	var v79 int64
	var v82 int
	var v88 int64
	var v91 int64
	var v111 int64
	var v114 int64
	var v124 int64
	var v127 int64
	var v157 int64
	var v159 int64
	v6 = 0
	v8 = 0
	v10 = 0
	v12 = v10
	v14 = 0x28a
	v16 = 0x16dc
	if (((width <= 0) || (height <= 0)) || (img1 == nil)) || (img2 == nil) {
		return 0
	}
	for v6 = 0; v6 < height; v6++ {
		v8 = 0
		for v8 < width {
			v36 = 0x8000
			v38 = v36
			v40 = v38
			v42 = v40
			v44 = v42
			v46 = 0
			v48 = 0
			v46 = -5
			for v46 <= 5 {
				v48 = -5
				for v48 <= 5 {
					v79 = int64(((int64(int(C2_gauss_weights[(v46+5)])) * int64(int(C2_gauss_weights[(v48+5)]))) + 0x8000) >> 16)
					v82 = (c2_clamp_coord((v6+v46), height) * stride) + c2_clamp_coord((v8+v48), width)
					v88 = int64(img1[v82])
					v36 += (v79 * v88)
					v91 = int64(img2[v82])
					v38 += (v79 * v91)
					v40 += (v79 * (v88 * v88))
					v42 += (v79 * (v91 * v91))
					v44 += (v79 * (v88 * v91))
					v48++
				}
				v46++
			}
			v111 = int64(v36 >> 16)
			v114 = int64(v38 >> 16)
			v124 = int64(v40>>16) - (v111 * v111)
			v127 = int64(v42>>16) - (v114 * v114)
			if v124 < 0 {
				v124 = 0
			}
			if v127 < 0 {
				v127 = 0
			}
			v157 = (((v111 * v111) + (v114 * v114)) + v14) * ((v124 + v127) + v16)
			if v157 != 0 {
				v159 = (((((2 * v111) * v114) + v14) * ((2 * (int64(v44>>16) - (v111 * v114))) + v16)) * 0xf4240) / v157
				if v159 > 0xf4240 {
					v159 = 0xf4240
				}
				if v159 < -1000000 {
					v159 = -1000000
				}
				v10 += v159
			}
			v12++
			v8++
		}
	}
	if v12 == 0 {
		return 0
	}
	return int64(v10 / v12)
}

func C2_ssim_compute_q16(img1 []byte, img2 []byte, width int, height int, stride int) int64 {
	return int64(((C2_ssim_compute_milli(img1[:], img2[:], width, height, stride) * 0x10000) + 0x7a120) / 0xf4240)
}
