// Code generated by sgoiter emit go127; DO NOT EDIT.
// sgoiter-stamp: sha256=af50adfb3a64db0babb5a062ce9f131a6039bbfc91546710cc41bee425715708
package c2ryu

func C2_u64_to_str(v uint64, dst []byte) uint32 {
	var v3 uint32
	var v17 uint32
	var v22 uint32
	var v2 [24]byte
	v3 = 0
	if v == 0 {
		dst[0] = '0'
		dst[1] = 0
		return 1
	}
	for v > 0 {
		v17 = v3
		v3++
		v2[v17] = byte(uint64(48) + (v % uint64(10)))
		v = v / 10
	}
	for v22 = 0; v22 < v3; v22++ {
		dst[v22] = v2[int((v3-1)-v22)]
	}
	dst[v3] = 0
	return v3
}

func C2_i64_to_str(v int64, dst []byte) uint32 {
	if v < 0 {
		dst[0] = 45
		return uint32(uint32(1) + C2_u64_to_str((uint64(-int(v+1))+1), dst[1:]))
	}
	return uint32(C2_u64_to_str(uint64(v), dst[:]))
}

func C2_d2s_buffered(f float64, dst []byte) uint32 {
	var v33 uint32
	var v37 uint32
	var v43 uint64
	var v44 float64
	var v53 uint32
	var v56 int
	var v64 uint32
	var v68 uint32
	var v77 uint32
	if f != f {
		dst[0] = 'N'
		dst[1] = 'A'
		dst[2] = 'N'
		dst[3] = 0
		return 3
	}
	if f > float64(1e+300) {
		dst[0] = 'I'
		dst[1] = 'N'
		dst[2] = 'F'
		dst[3] = 0
		return 3
	}
	if f < float64(-1e+300) {
		dst[0] = 45
		dst[1] = 'I'
		dst[2] = 'N'
		dst[3] = 'F'
		dst[4] = 0
		return 4
	}
	v33 = 0
	if f < float64(0) {
		v37 = v33
		v33++
		dst[v37] = 45
		f = -f
	}
	v43 = uint64(f)
	v44 = f - float64(v43)
	v33 += C2_u64_to_str(v43, dst[v33:])
	if v44 > float64(1e-12) {
		v53 = v33
		v33++
		dst[v53] = 46
		for v56 = 0; v56 < 9; v56++ {
			v44 *= float64(10)
			v64 = uint32(v44)
			v68 = v33
			v33++
			dst[v68] = byte(uint32(48) + v64)
			v44 -= float64(v64)
			if v44 < float64(1e-12) {
				break
			}
		}
		for v33 > 0 {
			v77 = v33 - 1
			if !(dst[v77] == '0') {
				break
			}
			v33 = v77
		}
		if v33 > 0 {
			if dst[int(v33-1)] == 46 {
				v33--
			}
		}
	}
	dst[v33] = 0
	return v33
}
