// Code generated by sgoiter emit go127; DO NOT EDIT.
// sgoiter-stamp: sha256=c8215d687d910b4d07189dcdcb7e85a8923046406453c3f725866a12c0d28e6e
package c2grid

type C2_cell_t struct {
	Rune_ uint32
	Fg    byte
	Bg    byte
	Flags byte
	Width byte
}

func C2_grid_clear(cells []C2_cell_t, n int, fg byte, bg byte) {
	var v4 int
	if len(cells) < n {
		n = int(len(cells))
	}
	v4 = 0
	{
		_cells := cells[:n]
		for v4 = 0; v4 < n; v4++ {
			_cells[v4].Rune_ = 32
			_cells[v4].Fg = fg
			_cells[v4].Bg = bg
			_cells[v4].Flags = 0
			_cells[v4].Width = 1
		}
	}
}

func C2_grid_clear_row(cells []C2_cell_t, y int, stride int, width int, fg byte, bg byte) {
	var v6 int
	var v13 int
	for v6 = 0; v6 < width; v6++ {
		v13 = (y * stride) + v6
		cells[v13].Rune_ = 32
		cells[v13].Fg = fg
		cells[v13].Bg = bg
		cells[v13].Flags = 0
		cells[v13].Width = 1
	}
}

func C2_grid_scroll_up(cells []C2_cell_t, width int, height int, stride int, nlines int) {
	var v5 int
	var v6 int
	var v22 int
	var v25 int
	if nlines < 1 {
		return
	}
	if nlines > height {
		nlines = height
	}
	v12 := height - nlines
	for v5 = 0; v5 < v12; v5++ {
		v6 = 0
		for v6 < width {
			v22 = ((v5 + nlines) * stride) + v6
			v25 = (v5 * stride) + v6
			cells[v25].Rune_ = cells[v22].Rune_
			cells[v25].Fg = cells[v22].Fg
			cells[v25].Bg = cells[v22].Bg
			cells[v25].Flags = cells[v22].Flags
			cells[v25].Width = cells[v22].Width
			v6++
		}
	}
	if stride == width {
		move := v12 * stride
		C2_grid_clear(cells[move:], (height-v12)*stride, byte(0), byte(0))
	} else {
		for v5 = v12; v5 < height; v5++ {
			C2_grid_clear_row(cells[:], v5, stride, width, byte(0), byte(0))
		}
	}
}
