// Code generated by sgoiter emit go127; DO NOT EDIT.
package src

var b64_table = []byte("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/")

func Base64_encode_stream(src []byte, len uint64, dst []byte) uint64 {
	var v18 uint8
	var v56 uint64
	var v87 uint64
	var v95 uint64
	var v101 uint64
	var v3 []byte
	var v24 uint8
	var v13 uint8
	var v27 uint64
	var v66 uint64
	var v4 uint64
	var v49 uint64
	var v73 uint64
	var v5 uint64
	var v23 uint64
	var v29 uint64
	var v51 uint64
	var v52 uint8
	var v57 uint8
	var v91 uint64
	var v69 uint64
	var v72 uint8
	var v80 uint8
	var v47 uint64
	var v33 uint64
	var v31 uint64
	var v37 uint64
	var v41 uint64
	var v45 uint64
	var v64 uint8
	var v67 uint64
	var v15 uint64
	var v35 uint64
	var v38 uint8
	var v71 uint64
	var v83 uint64
	var v90 uint8
	var v99 uint64
	var v25 uint64
	var v55 uint64
	var v77 uint64
	var v93 uint64
	var v53 uint64
	var v89 uint64
	var v81 uint64
	var v85 uint64
	var v46 uint8
	var v9 uint64
	var v21 uint64
	var v61 uint64
	var v17 uint64
	var v30 uint8
	var v39 uint64
	var v43 uint64
	var v11 uint64
	var v63 uint64
	var v79 uint64
	var v20 uint64
	var v12 uint64
	var v59 uint64
	var v75 uint64
	var v97 uint64
	v3 = b64_table
	v5 = uint64(0)
	v4 = uint64(0)
	v9 = v4 + uint64(2)
	for v9 < len {
	v13 = src[int(int(v4))]
	v15 = uint64(v13) << uint8(16)
	v17 = v4 + uint64(1)
	v18 = src[int(int(v17))]
	v20 = uint64(v18) << uint8(8)
	v21 = v15 | v20
	v23 = v4 + uint64(2)
	v24 = src[int(int(v23))]
	v25 = v21 | uint64(v24)
	v12 = v25
	v27 = v12 >> uint8(18)
	v29 = v27 & uint64(63)
	v30 = v3[int(int(v29))]
	v31 = v5
	v33 = v5 + uint64(1)
	v5 = v33
	dst[int(int(v31))] = v30
	v35 = v12 >> uint8(12)
	v37 = v35 & uint64(63)
	v38 = v3[int(int(v37))]
	v39 = v5
	v41 = v5 + uint64(1)
	v5 = v41
	dst[int(int(v39))] = v38
	v43 = v12 >> uint8(6)
	v45 = v43 & uint64(63)
	v46 = v3[int(int(v45))]
	v47 = v5
	v49 = v5 + uint64(1)
	v5 = v49
	dst[int(int(v47))] = v46
	v51 = v12 & uint64(63)
	v52 = v3[int(int(v51))]
	v53 = v5
	v55 = v5 + uint64(1)
	v5 = v55
	dst[int(int(v53))] = v52
	v11 = v4 + uint64(3)
	v4 = v11
	}
	if v4 < len {
	v57 = src[int(int(v4))]
	v59 = uint64(v57) << uint8(16)
	v56 = v59
	v61 = v4 + uint64(1)
	if v61 < len {
	v63 = v4 + uint64(1)
	v64 = src[int(int(v63))]
	v66 = uint64(v64) << uint8(8)
	v67 = v56 | v66
	v56 = v67
	}
	v69 = v56 >> uint8(18)
	v71 = v69 & uint64(63)
	v72 = v3[int(int(v71))]
	v73 = v5
	v75 = v5 + uint64(1)
	v5 = v75
	dst[int(int(v73))] = v72
	v77 = v56 >> uint8(12)
	v79 = v77 & uint64(63)
	v80 = v3[int(int(v79))]
	v81 = v5
	v83 = v5 + uint64(1)
	v5 = v83
	dst[int(int(v81))] = v80
	v85 = v4 + uint64(1)
	if v85 < len {
	v87 = v56 >> uint8(6)
	v89 = v87 & uint64(63)
	v90 = v3[int(int(v89))]
	v91 = v5
	v93 = v5 + uint64(1)
	v5 = v93
	dst[int(int(v91))] = v90
	} else {
	v95 = v5
	v97 = v5 + uint64(1)
	v5 = v97
	dst[int(int(v95))] = uint8(61)
	}
	v99 = v5
	v101 = v5 + uint64(1)
	v5 = v101
	dst[int(int(v99))] = uint8(61)
	}
	return uint64(v5)
}

