// Code generated by sgoiter emit go127; DO NOT EDIT.
// sgoiter-stamp: sha256=94041fcd32606afb8f5807ca46ef57b7aeaa0145d4b4e21fd9e5dfac526947cb
package c2lz4

func Lz4_decompress_safe(src []byte, src_len int, dst []byte, dst_len int) int {
	var v18 int
	var v20 int
	var v23 int
	var v26 byte
	var v27 int
	var v31 uint32
	var v34 int
	var v37 byte
	var v51 int
	var v74 uint16
	var v85 int
	var v87 byte
	var v92 int
	var v95 byte
	if len(src) < src_len {
		src_len = int(len(src))
	}
	if len(dst) < dst_len {
		dst_len = int(len(dst))
	}
	if (((src == nil) || (src_len <= 0)) || (dst == nil)) || (dst_len <= 0) {
		return -1
	}
	v18 = 0
	v20 = 0
	for v18 < src_len {
		v23 = v18
		v18++
		v26 = src[v23]
		v31 = (uint32(v26) >> 4) & 15
		v27 = int(v31)
		if v27 == 15 {
			for v18 < src_len {
				v34 = v18
				v18++
				v37 = src[v34]
				v27 += int(v37)
				if v37 != 0xff {
					break
				}
			}
		}
		if ((v27 < 0) || ((v20 + v27) > dst_len)) || ((v18 + v27) > src_len) {
			return -2
		}
		for v51 = 0; v51 < v27; v51++ {
			dst[v20+v51] = src[v18+v51]
		}
		v20 += v27
		v18 += v27
		if v18 >= src_len {
			break
		}
		if (v18 + 2) > src_len {
			return -3
		}
		v74 = uint16(src[v18]) | (uint16(src[(v18+1)]) << 8)
		v18 += 2
		if (v74 == 0) || (int(v74) > v20) {
			return -4
		}
		v87 = v26 & 15
		v85 = int(v87 + 4)
		if v85 == 19 {
			for v18 < src_len {
				v92 = v18
				v18++
				v95 = src[v92]
				v85 += int(v95)
				if v95 != 0xff {
					break
				}
			}
		}
		if (v85 < 0) || ((v20 + v85) > dst_len) {
			return -5
		}
		for v51 = 0; v51 < v85; v51++ {
			dst[v20+v51] = dst[int((v20-int(v74))+v51)]
		}
		v20 += v85
	}
	return v20
}

func Lz4_compress_fast(src []byte, src_len int, dst []byte, dst_max_len int) int {
	var v16 int
	var v18 int
	var v20 int
	var v23 int
	var v56 uint32
	var v61 uint32
	var v63 int
	var v69 bool
	var v73 bool
	var v98 int
	var v100 int
	var v102 int
	var v114 int
	var v119 int
	var v128 int
	var v135 int
	var v139 int
	var v145 int
	var v152 int
	var v161 int
	var v166 uint16
	var v171 uint16
	var v173 int
	var v179 uint16
	var v181 int
	var v185 int
	var v193 int
	var v200 int
	var v213 int
	var v219 int
	var v223 int
	var v229 int
	var v236 int
	var v245 int
	if len(src) < src_len {
		src_len = int(len(src))
	}
	if (((src == nil) || (src_len <= 0)) || (dst == nil)) || (dst_max_len <= 0) {
		return 0
	}
	v16 = 0
	v18 = 0
	v20 = 0
	var v22 [4096]int
	for v23 = 0; v23 < 0x1000; v23++ {
		v22[v23] = -1
	}
	for (v16 + 4) <= src_len {
		v56 = ((uint32(src[v16]) | (uint32(src[(v16+1)]) << 8)) | (uint32(src[(v16+2)]) << 16)) | (uint32(src[(v16+3)]) << 24)
		v61 = (v56 * 0x9e3779b1) >> 20
		v63 = v22[v61]
		v22[v61] = v16
		v69 = (v63 >= 0) && ((v16 - v63) < 0x10000)
		v73 = v69 && ((v63 + 4) <= src_len)
		if v73 {
			if v56 == (((uint32(src[v63]) | (uint32(src[(v63+1)]) << 8)) | (uint32(src[(v63+2)]) << 16)) | (uint32(src[(v63+3)]) << 24)) {
				v98 = 4
				for {
					v100 = v16 + v98
					if !(v100 < src_len) {
						break
					}
					v102 = v63 + v98
					if !(v102 < v16) {
						break
					}
					if !(src[v100] == src[v102]) {
						break
					}
					v98++
				}
				v114 = v16 - v20
				v119 = min(v114, 15)
				v128 = min((v98 - 4), 15)
				if v18 >= dst_max_len {
					return 0
				}
				v135 = v18
				v18++
				dst[v135] = byte((v119 << 4) | v128)
				if v119 == 15 {
					v139 = v114 - 15
					for v139 >= 255 {
						if v18 >= dst_max_len {
							return 0
						}
						v145 = v18
						v18++
						dst[v145] = 0xff
						v139 -= 255
					}
					if v18 >= dst_max_len {
						return 0
					}
					v152 = v18
					v18++
					dst[v152] = byte(v139)
				}
				for v23 = 0; v23 < v114; v23++ {
					if v18 >= dst_max_len {
						return 0
					}
					v161 = v18
					v18++
					dst[v161] = src[v20+v23]
				}
				v166 = uint16(v16 - v63)
				if (v18 + 2) > dst_max_len {
					return 0
				}
				v171 = v166 & 0xff
				v173 = v18
				v18++
				dst[v173] = byte(v171)
				v179 = (v166 >> 8) & 0xff
				v181 = v18
				v18++
				dst[v181] = byte(v179)
				if v128 == 15 {
					v185 = (v98 - 4) - 15
					for v185 >= 255 {
						if v18 >= dst_max_len {
							return 0
						}
						v193 = v18
						v18++
						dst[v193] = 0xff
						v185 -= 255
					}
					if v18 >= dst_max_len {
						return 0
					}
					v200 = v18
					v18++
					dst[v200] = byte(v185)
				}
				v16 += v98
				v20 = v16
				continue
			}
		}
		v16++
	}
	v207 := src_len - v20
	if v207 > 0 {
		v213 = min(v207, 15)
		if v18 >= dst_max_len {
			return 0
		}
		v219 = v18
		v18++
		dst[v219] = byte(v213 << 4)
		if v213 == 15 {
			v223 = v207 - 15
			for v223 >= 255 {
				if v18 >= dst_max_len {
					return 0
				}
				v229 = v18
				v18++
				dst[v229] = 0xff
				v223 -= 255
			}
			if v18 >= dst_max_len {
				return 0
			}
			v236 = v18
			v18++
			dst[v236] = byte(v223)
		}
		for v23 = 0; v23 < v207; v23++ {
			if v18 >= dst_max_len {
				return 0
			}
			v245 = v18
			v18++
			dst[v245] = src[v20+v23]
		}
	}
	return v18
}
