// Code generated by sgoiter emit go127; DO NOT EDIT.
package c2dxgi

type C2_dxgi_sample_desc_t struct {
	Count   uint32
	Quality uint32
}

type C2_dxgi_rational_t struct {
	Numerator   uint32
	Denominator uint32
}

type C2_dxgi_mode_desc_t struct {
	Width             uint32
	Height            uint32
	Refresh_rate      C2_dxgi_rational_t
	Format            uint32
	Scanline_ordering uint32
	Scaling           uint32
}

type C2_dxgi_swap_chain_desc_t struct {
	Buffer_desc   C2_dxgi_mode_desc_t
	Sample_desc   C2_dxgi_sample_desc_t
	Buffer_usage  uint32
	Buffer_count  uint32
	Output_window uint64
	Windowed      int
	Swap_effect   uint32
	Flags         uint32
}

type C2_dxgi_swap_chain_desc1_t struct {
	Width        uint32
	Height       uint32
	Format       uint32
	Stereo       int
	Sample_desc  C2_dxgi_sample_desc_t
	Buffer_usage uint32
	Buffer_count uint32
	Scaling      uint32
	Swap_effect  uint32
	Alpha_mode   uint32
	Flags        uint32
}

type C2_d3d11_texture2d_desc_t struct {
	Width            uint32
	Height           uint32
	Mip_levels       uint32
	Array_size       uint32
	Format           uint32
	Sample_desc      C2_dxgi_sample_desc_t
	Usage            uint32
	Bind_flags       uint32
	Cpu_access_flags uint32
	Misc_flags       uint32
}

type C2_d3d11_subresource_data_t struct {
	P_sys_mem           uint64
	Sys_mem_pitch       uint32
	Sys_mem_slice_pitch uint32
}

type C2_d3d11_mapped_subresource_t struct {
	P_data      uint64
	Row_pitch   uint32
	Depth_pitch uint32
}

type C2_guid_t struct {
	Data1 uint32
	Data2 uint16
	Data3 uint16
	Data4 [8]byte
}

func C2_dxgi_get_swapchain_desc_size() uint32 {
	return 44
}

func C2_dxgi_get_swapchain_desc1_size() uint32 {
	return 48
}

func C2_d3d11_get_texture2d_desc_size() uint32 {
	return 44
}

func C2_d3d11_get_subresource_data_size() uint32 {
	return 16
}

func C2_dxgi_get_slot(interface_id uint32, method_id uint32) uint32 {
	if interface_id == 1 {
		if method_id == 0 {
			return 0
		}
		if method_id == 1 {
			return 1
		}
		if method_id == 2 {
			return 2
		}
	} else {
		if interface_id == 2 {
			if method_id == 0 {
				return 8
			}
			if method_id == 1 {
				return 9
			}
			if method_id == 2 {
				return 13
			}
		} else {
			if interface_id == 3 {
				if method_id == 0 {
					return 18
				}
				if method_id == 1 {
					return 22
				}
			} else {
				if interface_id == 4 {
					if method_id == 0 {
						return 5
					}
					if method_id == 1 {
						return 9
					}
					if method_id == 2 {
						return 40
					}
				} else {
					if interface_id == 5 {
						if method_id == 0 {
							return 48
						}
						if method_id == 1 {
							return 14
						}
						if method_id == 2 {
							return 15
						}
						if method_id == 3 {
							return 0x6f
						}
					}
				}
			}
		}
	}
	return 0xffffffff
}

func C2_dxgi_get_iid(iid_type uint32, out_guid *C2_guid_t) {
	if out_guid == nil {
		return
	}
	if iid_type == 1 {
		out_guid.Data1 = 0
		out_guid.Data2 = 0
		out_guid.Data3 = 0
		out_guid.Data4[0] = 0xc0
		out_guid.Data4[1] = 0
		out_guid.Data4[2] = 0
		out_guid.Data4[3] = 0
		out_guid.Data4[4] = 0
		out_guid.Data4[5] = 0
		out_guid.Data4[6] = 0
		out_guid.Data4[7] = 'F'
	} else {
		if iid_type == 2 {
			out_guid.Data1 = 0x310d36a0
			out_guid.Data2 = 0xd2e7
			out_guid.Data3 = 0x4c0a
			out_guid.Data4[0] = 0xaa
			out_guid.Data4[1] = 4
			out_guid.Data4[2] = 'j'
			out_guid.Data4[3] = 0x9d
			out_guid.Data4[4] = 35
			out_guid.Data4[5] = 0xb8
			out_guid.Data4[6] = 0x88
			out_guid.Data4[7] = 'j'
		} else {
			if iid_type == 3 {
				out_guid.Data1 = 0x790a45f8
				out_guid.Data2 = 0x93a3
				out_guid.Data3 = 0x4f86
				out_guid.Data4[0] = 0xae
				out_guid.Data4[1] = 0xc3
				out_guid.Data4[2] = 0x7b
				out_guid.Data4[3] = 'd'
				out_guid.Data4[4] = ';'
				out_guid.Data4[5] = 0xf7
				out_guid.Data4[6] = 0xaf
				out_guid.Data4[7] = 0xa7
			} else {
				if iid_type == 4 {
					out_guid.Data1 = 0x6f15aaf2
					out_guid.Data2 = 0xd208
					out_guid.Data3 = 0x4e89
					out_guid.Data4[0] = 0x9a
					out_guid.Data4[1] = 0xb4
					out_guid.Data4[2] = 'H'
					out_guid.Data4[3] = 0x95
					out_guid.Data4[4] = '5'
					out_guid.Data4[5] = 0xd3
					out_guid.Data4[6] = 'O'
					out_guid.Data4[7] = 0x9c
				} else {
					if iid_type == 5 {
						out_guid.Data1 = 0xdb6f6ddb
						out_guid.Data2 = 0xac77
						out_guid.Data3 = 0x4e88
						out_guid.Data4[0] = 0x82
						out_guid.Data4[1] = 'S'
						out_guid.Data4[2] = 0x81
						out_guid.Data4[3] = 0x9d
						out_guid.Data4[4] = 0xf9
						out_guid.Data4[5] = 0xbb
						out_guid.Data4[6] = 0xf1
						out_guid.Data4[7] = 64
					}
				}
			}
		}
	}
}
