// Code generated by sgoiter emit go127; DO NOT EDIT.
package tweetnacl_dogfood

func L32(x uint32, c int) uint32 {
	v2 := x << uint8(c)
	v4 := x & uint32(4294967295)
	v6 := 32 - c
	v7 := v4 >> uint8(v6)
	v8 := v2 | v7
	return v8
}

func Ld32(x []byte) uint32 {
	v3 := x[int(3)]
	v1 := v3
	v5 := uint32(v1) << uint8(8)
	v7 := x[int(2)]
	v8 := v5 | uint32(v7)
	v1 = uint8(v8)
	v10 := uint32(v1) << uint8(8)
	v12 := x[int(1)]
	v13 := v10 | uint32(v12)
	v1 = uint8(v13)
	v15 := uint32(v1) << uint8(8)
	v17 := x[int(0)]
	v18 := v15 | uint32(v17)
	return v18
}

func Dl64(x []byte) uint64 {
	v2 := uint64(0)
	v1 := uint64(0)
	for v1 < uint64(8) {
	v9 := v2 << uint8(8)
	v10 := x[int(int(v1))]
	v11 := v9 | uint64(v10)
	v2 = v11
	v7 := v1 + uint64(1)
	v1 = v7
	}
	return v2
}

func Vn(x []byte, y []byte, n int) int {
	v4 := 0
	v3 := 0
	for v3 < n {
	v9 := x[int(v3)]
	v10 := y[int(v3)]
	v11 := v9 ^ v10
	v12 := v4 | int(v11)
	v4 = v12
	v8 := v3 + 1
	v3 = v8
	}
	v15 := v4 - 1
	v17 := v15 >> uint8(8)
	v18 := 1 & v17
	v20 := v18 - 1
	return v20
}

func Crypto_verify_16(x []byte, y []byte) int {
	v3 := Vn(x, y, 16)
	return v3
}

func Crypto_verify_32(x []byte, y []byte) int {
	v3 := Vn(x, y, 32)
	return v3
}

func Crypto_core_salsa20(out []byte, in []byte, k []byte, c []byte) int {
	Core(out, in, k, c, 0)
	return 0
}

func Crypto_core_hsalsa20(out []byte, in []byte, k []byte, c []byte) int {
	Core(out, in, k, c, 1)
	return 0
}

func Crypto_stream_salsa20(c []byte, d uint64, n []byte, k []byte) int {
	v5 := Crypto_stream_salsa20_xor(c, 0, d, n, k)
	return v5
}

func Crypto_onetimeauth_verify(h []byte, m []byte, n uint64, k []byte) int {
	var _arr_v4 [16]uint8
	v4 := _arr_v4[:]
	Crypto_onetimeauth(v4, m, n, k)
	v6 := Crypto_verify_16(h, v4)
	return v6
}

func Crypto_secretbox(c []byte, m []byte, d uint64, n []byte, k []byte) int {
	if d < uint64(32) {
	v9 := -int(1)
	return v9
	}
	Crypto_stream_xor(c, m, d, n, k)
	v16 := d - uint64(32)
	Crypto_onetimeauth(c, c, v16, c)
	v5 := 0
	for v5 < 16 {
	c[int(v5)] = uint8(0)
	v21 := v5 + 1
	v5 = v21
	}
	return 0
}

func Crypto_secretbox_open(m []byte, c []byte, d uint64, n []byte, k []byte) int {
	var _arr_v6 [32]uint8
	v6 := _arr_v6[:]
	if d < uint64(32) {
	v10 := -int(1)
	return v10
	}
	Crypto_stream(v6, 32, n, k)
	v18 := d - uint64(32)
	v19 := Crypto_onetimeauth_verify(c, c, v18, v6)
	if v19 != 0 {
	v23 := -int(1)
	return v23
	}
	Crypto_stream_xor(m, c, d, n, k)
	v5 := 0
	for v5 < 32 {
	m[int(v5)] = uint8(0)
	v28 := v5 + 1
	v5 = v28
	}
	return 0
}

func Neq25519(a int, b int) int {
	var _arr_v2 [32]uint8
	v2 := _arr_v2[:]
	var _arr_v3 [32]uint8
	v3 := _arr_v3[:]
	Pack25519(v2, a)
	Pack25519(v3, b)
	v6 := Crypto_verify_32(v2, v3)
	return v6
}

func Par25519(a int) uint8 {
	var _arr_v1 [32]uint8
	v1 := _arr_v1[:]
	Pack25519(v1, a)
	v4 := v1[int(0)]
	v6 := v4 & uint8(1)
	return v6
}

func Crypto_box_keypair(y []byte, x []byte) int {
	Randombytes(x, 32)
	v4 := Crypto_scalarmult_base(y, x)
	return v4
}

func Crypto_box_afternm(c []byte, m []byte, d uint64, n []byte, k []byte) int {
	v5 := Crypto_secretbox(c, m, d, n, k)
	return v5
}

func Crypto_box_open_afternm(m []byte, c []byte, d uint64, n []byte, k []byte) int {
	v5 := Crypto_secretbox_open(m, c, d, n, k)
	return v5
}

func Crypto_box(c []byte, m []byte, d uint64, n []byte, y []byte, x []byte) int {
	var _arr_v6 [32]uint8
	v6 := _arr_v6[:]
	Crypto_box_beforenm(v6, y, x)
	v8 := Crypto_box_afternm(c, m, d, n, v6)
	return v8
}

func Crypto_box_open(m []byte, c []byte, d uint64, n []byte, y []byte, x []byte) int {
	var _arr_v6 [32]uint8
	v6 := _arr_v6[:]
	Crypto_box_beforenm(v6, y, x)
	v8 := Crypto_box_open_afternm(m, c, d, n, v6)
	return v8
}

func R(x uint64, c int) uint64 {
	v2 := x >> uint8(c)
	v4 := 64 - c
	v5 := x << uint8(v4)
	v6 := v2 | v5
	return v6
}

func Ch(x uint64, y uint64, z uint64) uint64 {
	v3 := x & y
	v4 := x & z
	v5 := ^v4
	v6 := v3 ^ v5
	return v6
}

func Maj(x uint64, y uint64, z uint64) uint64 {
	v3 := x & y
	v4 := x & z
	v5 := v3 ^ v4
	v6 := y & z
	v7 := v5 ^ v6
	return v7
}

func Core(args ...any) {
	return
}

func Crypto_stream_salsa20_xor(args ...any) int {
	return 0
}

func Crypto_onetimeauth(args ...any) {
	return
}

func Crypto_stream_xor(args ...any) {
	return
}

func Crypto_stream(args ...any) {
	return
}

func Pack25519(args ...any) {
	return
}

func Randombytes(args ...any) {
	return
}

func Crypto_scalarmult_base(args ...any) int {
	return 0
}

func Crypto_box_beforenm(args ...any) {
	return
}

