//go:build goexperiment.simd

// Code generated by sgoiter emit go127; DO NOT EDIT.
package c2archsimd

import "simd/archsimd"

// HasAVX2 reports whether AVX2 hardware acceleration is supported by the CPU.
func HasAVX2() bool {
	return archsimd.X86.AVX2()
}

var __str_9f9f5111 = []byte("0123456789abcdef")

func C2archsimd_lut16_avx2(in []byte, t16 *C2archsimd_table16_t, out []byte) {
	mm256_broadcastsi128_si256(archsimd.LoadUint8x16(t16.B[:16])).PermuteOrZeroGrouped(archsimd.LoadUint8x32(in[:32]).And(archsimd.BroadcastUint8x32(byte(15))).AsInt8x32()).Store(out[:32])
}

func C2archsimd_lut256_avx2(in []byte, t_lo *C2archsimd_table16_t, t_hi *C2archsimd_table16_t, out []byte) {
	mm256_broadcastsi128_si256(archsimd.LoadUint8x16(t_lo.B[:16])).PermuteOrZeroGrouped(archsimd.LoadUint8x32(in[:32]).And(archsimd.BroadcastUint8x32(byte(15))).AsInt8x32()).And(mm256_broadcastsi128_si256(archsimd.LoadUint8x16(t_hi.B[:16])).PermuteOrZeroGrouped(archsimd.LoadUint8x32(in[:32]).AsUint16x16().ShiftAllRight(4).AsUint8x32().And(archsimd.BroadcastUint8x32(byte(15))).AsInt8x32())).Store(out[:32])
}

func C2archsimd_hex_encode16_avx2(in []byte, out []byte) {
	v4 := archsimd.LoadUint8x16(in[:16])
	v7 := archsimd.BroadcastUint8x16(byte(15))
	v11 := v4.AsUint16x8().ShiftAllRight(4).AsUint8x16().And(v7)
	v13 := v4.And(v7)
	v21 := archsimd.LoadUint8x16(__str_9f9f5111[:16])
	v21.PermuteOrZero(mm_unpacklo_epi8(v11, v13).AsInt8x16()).Store(out[:16])
	v21.PermuteOrZero(mm_unpackhi_epi8(v11, v13).AsInt8x16()).Store(out[16:][:16])
}

func C2archsimd_vint_lens32_avx2(in []byte, out []byte) {
	v19 := archsimd.LoadUint8x16Array(&[16]byte{1, 2, 4, 8, 1, 2, 4, 8, 1, 2, 4, 8, 1, 2, 4, 8})
	mm256_broadcastsi128_si256(v19).PermuteOrZeroGrouped(archsimd.LoadUint8x32(in[:32]).AsUint16x16().ShiftAllRight(6).AsUint8x32().And(archsimd.BroadcastUint8x32(byte(3))).AsInt8x32()).Store(out[:32])
}

func mm256_broadcastsi128_si256(v archsimd.Uint8x16) archsimd.Uint8x32 {
	var a [32]byte
	v.Store(a[:16])
	v.Store(a[16:])
	return archsimd.LoadUint8x32Array(&a)
}

func mm_unpacklo_epi8(a, b archsimd.Uint8x16) archsimd.Uint8x16 {
	var ra, rb, out [16]byte
	a.Store(ra[:])
	b.Store(rb[:])
	for i := 0; i < 8; i++ {
		out[i*2] = ra[i]
		out[i*2+1] = rb[i]
	}
	return archsimd.LoadUint8x16Array(&out)
}

func mm_unpackhi_epi8(a, b archsimd.Uint8x16) archsimd.Uint8x16 {
	var ra, rb, out [16]byte
	a.Store(ra[:])
	b.Store(rb[:])
	for i := 0; i < 8; i++ {
		out[i*2] = ra[8+i]
		out[i*2+1] = rb[8+i]
	}
	return archsimd.LoadUint8x16Array(&out)
}
