// Code generated by sgoiter emit go127; DO NOT EDIT.
// sgoiter-stamp: sha256=7cec9de1a4416351a4c020d3b3c9513944345a6d5bb6ec52c4b5470e234ae69e
package c2pngfilter

func stbi_paeth(a int, b int, c int) byte {
	var v6 int
	var v11 int
	var v16 int
	var v23 bool
	v5 := (a + b) - c
	v6 = v5 - a
	if v6 < 0 {
		v6 = -v6
	}
	v11 = v5 - b
	if v11 < 0 {
		v11 = -v11
	}
	v16 = v5 - c
	if v16 < 0 {
		v16 = -v16
	}
	v23 = (v6 <= v11) && (v6 <= v16)
	if v23 {
		return byte(a)
	}
	if v11 <= v16 {
		return byte(b)
	}
	return byte(c)
}

func Stbi_unfilter_row(recon []byte, scanline []byte, prev []byte, len_ uint64, bpp int, filter_type int) {
	var v13 uint64
	var v18 bool
	var v22 uint64
	var v31 uint64
	var v40 uint64
	var v45 bool
	var v54 uint64
	var v69 uint64
	var v74 bool
	var v84 uint64
	if filter_type == 0 {
		copy(recon[:len_], scanline[:len_])
	} else {
		if filter_type == 1 {
			v13 = 0
			for {
				v18 = (v13 < uint64(bpp)) && (v13 < len_)
				if !v18 {
					break
				}
				recon[v13] = scanline[v13]
				v13++
			}
			for v22 = uint64(bpp); v22 < len_; v22++ {
				recon[v22] = scanline[v22] + recon[int(v22-uint64(bpp))]
			}
		} else {
			if filter_type == 2 {
				for v31 = 0; v31 < len_; v31++ {
					recon[v31] = scanline[v31] + prev[v31]
				}
			} else {
				if filter_type == 3 {
					v40 = 0
					for {
						v45 = (v40 < uint64(bpp)) && (v40 < len_)
						if !v45 {
							break
						}
						recon[v40] = byte(uint64(scanline[v40]) + uint64(uint64(prev[v40])>>1))
						v40++
					}
					for v54 = uint64(bpp); v54 < len_; v54++ {
						recon[v54] = byte(int(scanline[v54]) + ((int(recon[int(v54-uint64(bpp))]) + int(prev[v54])) >> 1))
					}
				} else {
					if filter_type == 4 {
						v69 = 0
						for {
							v74 = (v69 < uint64(bpp)) && (v69 < len_)
							if !v74 {
								break
							}
							recon[v69] = scanline[v69] + stbi_paeth(0, int(prev[v69]), 0)
							v69++
						}
						for v84 = uint64(bpp); v84 < len_; v84++ {
							recon[v84] = scanline[v84] + stbi_paeth(int(recon[int(v84-uint64(bpp))]), int(prev[v84]), int(prev[int(v84-uint64(bpp))]))
						}
					}
				}
			}
		}
	}
}
