// Code generated by sgoiter emit go127; DO NOT EDIT.
package fnv1a_64

func Fnv1a_64(data []byte, len uint64) uint64 {
	v2 := uint64(14695981039346656037)
	v4 := uint64(0)
	for v4 < len {
	v8 := data[int(int(v4))]
	v9 := v2 ^ uint64(v8)
	v2 = v9
	v11 := v2 * uint64(1099511628211)
	v2 = v11
	v7 := v4 + uint64(1)
	v4 = v7
	}
	return v2
}

