// Code generated by sgoiter emit go127; DO NOT EDIT.
package c2swizzle

func C2_swizzle_pixel(pixel uint32) uint32 {
	v2 := pixel & 0xff00ff00
	v4 := pixel & 0xff
	v9 := pixel & 0xff0000
	return uint32((v2 | uint32(v4<<16)) | uint32(v9>>16))
}

func C2_swizzle_pair(pair uint64) uint64 {
	v2 := pair & 0xff00ff00ff00ff00
	v4 := pair & 0xff000000ff
	v9 := pair & 0xff000000ff0000
	return uint64((v2 | uint64(v4<<16)) | uint64(v9>>16))
}

func C2_swizzle_block4(in []byte, out []byte) {
	_ = in[15]
	_ = out[15]
	out[0] = in[2]
	out[1] = in[1]
	out[2] = in[0]
	out[3] = in[3]
	out[4] = in[6]
	out[5] = in[5]
	out[6] = in[4]
	out[7] = in[7]
	out[8] = in[10]
	out[9] = in[9]
	out[10] = in[8]
	out[11] = in[11]
	out[12] = in[14]
	out[13] = in[13]
	out[14] = in[12]
	out[15] = in[15]
}

func C2_swizzle_block8(in []byte, out []byte) {
	C2_swizzle_block4(in[:], out[:])
	C2_swizzle_block4(in[16:], out[16:])
}

func C2_swizzle_block16(in []byte, out []byte) {
	C2_swizzle_block4(in[:], out[:])
	C2_swizzle_block4(in[16:], out[16:])
	C2_swizzle_block4(in[32:], out[32:])
	C2_swizzle_block4(in[48:], out[48:])
}

func C2_swizzle_rgba_bgra(src []byte, dst []byte, num_pixels uint64) {
	var v3 uint64
	var v24 uint64
	var v26 uint64
	v3 = 0
	v10 := uint64(uint64(num_pixels>>4) << 4)
	for v3 = 0; v3 < v10; v3 += 16 {
		C2_swizzle_block16(src[int(v3*4):], dst[int(v3*4):])
	}
	for v3 = v10; v3 < num_pixels; v3++ {
		v24 = v3 * 4
		v26 = v24 + 2
		dst[v24] = src[v26]
		dst[v24+1] = src[v24+1]
		dst[v26] = src[v24]
		dst[v24+3] = src[v24+3]
	}
}

func C2_swizzle_rgba_bgra_inplace(data []byte, num_pixels uint64) {
	var v2 uint64
	var v15 uint64
	var v19 byte
	var v21 uint64
	var v29 uint64
	var v33 byte
	var v35 uint64
	var v43 uint64
	var v47 byte
	var v49 uint64
	var v57 uint64
	var v61 byte
	var v63 uint64
	var v71 uint64
	var v75 byte
	var v77 uint64
	var v85 uint64
	var v89 byte
	var v91 uint64
	var v99 uint64
	var v103 byte
	var v105 uint64
	var v113 uint64
	var v117 byte
	var v119 uint64
	var v129 uint64
	var v133 byte
	var v135 uint64
	v2 = 0
	v9 := uint64(uint64(num_pixels>>3) << 3)
	for v2 = 0; v2 < v9; v2 += 8 {
		v15 = v2 * 4
		v19 = data[v15]
		v21 = v15 + 2
		data[v15] = data[v21]
		data[v21] = v19
		v29 = v15 + 4
		v33 = data[v29]
		v35 = v29 + 2
		data[v29] = data[v35]
		data[v35] = v33
		v43 = v15 + 8
		v47 = data[v43]
		v49 = v43 + 2
		data[v43] = data[v49]
		data[v49] = v47
		v57 = v15 + 12
		v61 = data[v57]
		v63 = v57 + 2
		data[v57] = data[v63]
		data[v63] = v61
		v71 = v15 + 16
		v75 = data[v71]
		v77 = v71 + 2
		data[v71] = data[v77]
		data[v77] = v75
		v85 = v15 + 20
		v89 = data[v85]
		v91 = v85 + 2
		data[v85] = data[v91]
		data[v91] = v89
		v99 = v15 + 24
		v103 = data[v99]
		v105 = v99 + 2
		data[v99] = data[v105]
		data[v105] = v103
		v113 = v15 + 28
		v117 = data[v113]
		v119 = v113 + 2
		data[v113] = data[v119]
		data[v119] = v117
	}
	for v2 = v9; v2 < num_pixels; v2++ {
		v129 = v2 * 4
		v133 = data[v129]
		v135 = v129 + 2
		data[v129] = data[v135]
		data[v135] = v133
	}
}

func C2_swizzle_argb_to_rgba(src []byte, dst []byte, num_pixels uint64) {
	var v3 uint64
	var v10 uint64
	var v17 uint64
	var v21 uint64
	var v25 uint64
	for v3 = 0; v3 < num_pixels; v3++ {
		v10 = v3 * 4
		v17 = v10 + 1
		v21 = v10 + 2
		v25 = v10 + 3
		dst[v10] = src[v17]
		dst[v17] = src[v21]
		dst[v21] = src[v25]
		dst[v25] = src[v10]
	}
}

func C2_swizzle_rgba_to_argb(src []byte, dst []byte, num_pixels uint64) {
	var v3 uint64
	var v10 uint64
	var v17 uint64
	var v21 uint64
	var v25 uint64
	for v3 = 0; v3 < num_pixels; v3++ {
		v10 = v3 * 4
		v17 = v10 + 1
		v21 = v10 + 2
		v25 = v10 + 3
		dst[v10] = src[v25]
		dst[v17] = src[v10]
		dst[v21] = src[v17]
		dst[v25] = src[v21]
	}
}

func C2_swizzle_argb_to_bgra(src []byte, dst []byte, num_pixels uint64) {
	var v3 uint64
	var v10 uint64
	var v17 uint64
	var v21 uint64
	var v25 uint64
	for v3 = 0; v3 < num_pixels; v3++ {
		v10 = v3 * 4
		v17 = v10 + 1
		v21 = v10 + 2
		v25 = v10 + 3
		dst[v10] = src[v25]
		dst[v17] = src[v21]
		dst[v21] = src[v17]
		dst[v25] = src[v10]
	}
}

func C2_swizzle_rgba_bgra_stride(src []byte, dst []byte, width int, height int, src_stride int, dst_stride int) {
	var v6 int
	v6 = 0
	if (width <= 0) || (height <= 0) {
		return
	}
	for v6 = 0; v6 < height; v6++ {
		C2_swizzle_rgba_bgra(src[int(uint64(v6)*uint64(src_stride)):], dst[int(uint64(v6)*uint64(dst_stride)):], uint64(width))
	}
}
