// Code generated by sgoiter emit go127; DO NOT EDIT.
// sgoiter-stamp: sha256=b40fb7808cc401a6f60eb32edbfbf80570de09f72a497b87621fec774cd8871c
package c2poly1305x8

type Crypto_poly1305x8_ctx struct {
	C     [128]byte
	C_idx uint64
	R     [5]uint32
	R2    [5]uint32
	R3    [5]uint32
	R4    [5]uint32
	R5    [5]uint32
	R6    [5]uint32
	R7    [5]uint32
	R8    [5]uint32
	Pad   [4]uint32
	H     [5]uint32
}

func load32_le(p []byte) uint32 {
	_ = p[3]
	return uint32(p[0]) | uint32(p[1])<<8 | uint32(p[2])<<16 | uint32(p[3])<<24
}

func store32_le(p []byte, v uint32) {
	_ = p[3]
	v3 := v & 0xff
	p[0] = byte(v3)
	v9 := uint32(v>>8) & 0xff
	p[1] = byte(v9)
	v15 := uint32(v>>16) & 0xff
	p[2] = byte(v15)
	v21 := uint32(v>>24) & 0xff
	p[3] = byte(v21)
}

func poly_mul(h []uint32, r []uint32) {
	var v4 uint32
	var v7 uint32
	var v10 uint32
	var v13 uint32
	var v16 uint32
	var v29 uint32
	var v32 uint32
	var v35 uint32
	var v38 uint32
	var v41 uint32
	var v45 uint64
	var v47 uint64
	var v50 uint64
	var v53 uint64
	var v56 uint64
	var v59 uint64
	var v74 uint64
	var v89 uint64
	var v104 uint64
	var v119 uint64
	_ = h[4]
	_ = r[4]
	v4 = r[0]
	v7 = r[1]
	v10 = r[2]
	v13 = r[3]
	v16 = r[4]
	v22 := v10 * 5
	v25 := v13 * 5
	v28 := v16 * 5
	v29 = h[0]
	v32 = h[1]
	v35 = h[2]
	v38 = h[3]
	v41 = h[4]
	v45 = uint64(v29)
	v47 = uint64(v32)
	v50 = uint64(v35)
	v53 = uint64(v38)
	v56 = uint64(v41)
	v58 := ((((v45 * uint64(v4)) + (v47 * uint64(v28))) + (v50 * uint64(v25))) + (v53 * uint64(v22))) + (v56 * uint64(v7*5))
	v59 = (v45*uint64(v7) + v47*uint64(v4)) + ((v50 * uint64(v28)) + (v53*uint64(v25) + v56*uint64(v22)))
	v74 = (v45*uint64(v10) + v47*uint64(v7)) + ((v50 * uint64(v4)) + (v53*uint64(v28) + v56*uint64(v25)))
	v89 = (v45*uint64(v13) + v47*uint64(v10)) + ((v50 * uint64(v7)) + (v53*uint64(v4) + v56*uint64(v28)))
	v104 = (v45*uint64(v16) + v47*uint64(v13)) + ((v50 * uint64(v10)) + (v53*uint64(v7) + v56*uint64(v4)))
	v119 = uint64(v58 >> 26)
	v29 = uint32(v58) & 0x3ffffff
	v59 += v119
	v119 = uint64(v59 >> 26)
	v32 = uint32(v59) & 0x3ffffff
	v74 += v119
	v119 = uint64(v74 >> 26)
	v35 = uint32(v74) & 0x3ffffff
	v89 += v119
	v119 = uint64(v89 >> 26)
	v38 = uint32(v89) & 0x3ffffff
	v104 += v119
	v119 = uint64(v104 >> 26)
	v41 = uint32(v104) & 0x3ffffff
	v29 += (uint32(v119) * 5)
	v119 = uint64(uint64(v29) >> 26)
	v29 &= 0x3ffffff
	v32 += uint32(v119)
	h[0] = v29
	h[1] = v32
	h[2] = v35
	h[3] = v38
	h[4] = v41
}

func poly_add_block(h []uint32, m []byte, hibit uint32) {
	_ = h[4]
	_ = m[15]
	v26 := (((uint32(m[0]) | uint32(uint32(m[1])<<8)) | uint32(uint32(m[2])<<16)) | uint32(uint32(m[3])<<24)) & 0x3ffffff
	h[0] += v26
	v34 := uint32((((uint32(m[3])|uint32(uint32(m[4])<<8))|uint32(uint32(m[5])<<16))|uint32(uint32(m[6])<<24))>>2) & 0x3ffffff
	h[1] += v34
	v42 := uint32((((uint32(m[6])|uint32(uint32(m[7])<<8))|uint32(uint32(m[8])<<16))|uint32(uint32(m[9])<<24))>>4) & 0x3ffffff
	h[2] += v42
	v50 := uint32((((uint32(m[9])|uint32(uint32(m[10])<<8))|uint32(uint32(m[11])<<16))|uint32(uint32(m[12])<<24))>>6) & 0x3ffffff
	h[3] += v50
	h[4] += (uint32((((uint32(m[12])|uint32(uint32(m[13])<<8))|uint32(uint32(m[14])<<16))|uint32(uint32(m[15])<<24))>>8) | hibit)
}

func poly_block_r(ctx *Crypto_poly1305x8_ctx, m []byte) {
	poly_add_block(ctx.H[:], m[:], uint32(0x1000000))
	poly_mul(ctx.H[:], ctx.R[:])
}

func poly_add5(h []uint32, t []uint32) {
	var v2 uint64
	_ = h[4]
	_ = t[4]
	v2 = uint64(h[0]) + uint64(t[0])
	v11 := uint32(v2) & 0x3ffffff
	h[0] = v11
	v2 = (uint64(v2>>26) + uint64(h[1])) + uint64(t[1])
	v24 := uint32(v2) & 0x3ffffff
	h[1] = v24
	v2 = (uint64(v2>>26) + uint64(h[2])) + uint64(t[2])
	v37 := uint32(v2) & 0x3ffffff
	h[2] = v37
	v2 = (uint64(v2>>26) + uint64(h[3])) + uint64(t[3])
	v50 := uint32(v2) & 0x3ffffff
	h[3] = v50
	v2 = (uint64(v2>>26) + uint64(h[4])) + uint64(t[4])
	h[4] = uint32(v2)
}

func poly_octa(ctx *Crypto_poly1305x8_ctx, m []byte) {
	var v2 [5]uint32
	poly_add_block(ctx.H[:], m[:], uint32(0x1000000))
	poly_mul(ctx.H[:], ctx.R8[:])
	v2[0] = 0
	v2[1] = 0
	v2[2] = 0
	v2[3] = 0
	v2[4] = 0
	poly_add_block(v2[:], m[16:], uint32(0x1000000))
	poly_mul(v2[:], ctx.R7[:])
	poly_add5(ctx.H[:], v2[:])
	v2[0] = 0
	v2[1] = 0
	v2[2] = 0
	v2[3] = 0
	v2[4] = 0
	poly_add_block(v2[:], m[32:], uint32(0x1000000))
	poly_mul(v2[:], ctx.R6[:])
	poly_add5(ctx.H[:], v2[:])
	v2[0] = 0
	v2[1] = 0
	v2[2] = 0
	v2[3] = 0
	v2[4] = 0
	poly_add_block(v2[:], m[48:], uint32(0x1000000))
	poly_mul(v2[:], ctx.R5[:])
	poly_add5(ctx.H[:], v2[:])
	v2[0] = 0
	v2[1] = 0
	v2[2] = 0
	v2[3] = 0
	v2[4] = 0
	poly_add_block(v2[:], m[64:], uint32(0x1000000))
	poly_mul(v2[:], ctx.R4[:])
	poly_add5(ctx.H[:], v2[:])
	v2[0] = 0
	v2[1] = 0
	v2[2] = 0
	v2[3] = 0
	v2[4] = 0
	poly_add_block(v2[:], m[80:], uint32(0x1000000))
	poly_mul(v2[:], ctx.R3[:])
	poly_add5(ctx.H[:], v2[:])
	v2[0] = 0
	v2[1] = 0
	v2[2] = 0
	v2[3] = 0
	v2[4] = 0
	poly_add_block(v2[:], m[96:], uint32(0x1000000))
	poly_mul(v2[:], ctx.R2[:])
	poly_add5(ctx.H[:], v2[:])
	v2[0] = 0
	v2[1] = 0
	v2[2] = 0
	v2[3] = 0
	v2[4] = 0
	poly_add_block(v2[:], m[112:], uint32(0x1000000))
	poly_mul(v2[:], ctx.R[:])
	poly_add5(ctx.H[:], v2[:])
}

func Crypto_poly1305x8_init(ctx *Crypto_poly1305x8_ctx, key []byte) {
	_ = key[31]
	v185 := ((uint32(key[0]) | uint32(uint32(key[1])<<8)) | uint32(uint32(key[2])<<16)) | uint32(uint32(key[3])<<24)
	v206 := ((uint32(key[4]) | uint32(uint32(key[5])<<8)) | uint32(uint32(key[6])<<16)) | uint32(uint32(key[7])<<24)
	v227 := ((uint32(key[8]) | uint32(uint32(key[9])<<8)) | uint32(uint32(key[10])<<16)) | uint32(uint32(key[11])<<24)
	v248 := ((uint32(key[12]) | uint32(uint32(key[13])<<8)) | uint32(uint32(key[14])<<16)) | uint32(uint32(key[15])<<24)
	v20 := v185 & 0x3ffffff
	ctx.R[0] = v20
	v29 := (uint32(v185>>26) | uint32(v206<<6)) & 0x3ffff03
	ctx.R[1] = v29
	v38 := (uint32(v206>>20) | uint32(v227<<12)) & 0x3ffc0ff
	ctx.R[2] = v38
	v47 := (uint32(v227>>14) | uint32(v248<<18)) & 0x3f03fff
	ctx.R[3] = v47
	v53 := uint32(v248>>8) & 0xfffff
	ctx.R[4] = v53
	copy(ctx.R2[:5], ctx.R[:5])
	poly_mul(ctx.R2[:], ctx.R[:])
	copy(ctx.R3[:5], ctx.R2[:5])
	poly_mul(ctx.R3[:], ctx.R[:])
	copy(ctx.R4[:5], ctx.R3[:5])
	poly_mul(ctx.R4[:], ctx.R[:])
	copy(ctx.R5[:5], ctx.R4[:5])
	poly_mul(ctx.R5[:], ctx.R[:])
	copy(ctx.R6[:5], ctx.R5[:5])
	poly_mul(ctx.R6[:], ctx.R[:])
	copy(ctx.R7[:5], ctx.R6[:5])
	poly_mul(ctx.R7[:], ctx.R[:])
	copy(ctx.R8[:5], ctx.R7[:5])
	poly_mul(ctx.R8[:], ctx.R[:])
	ctx.Pad[0] = ((uint32(key[16]) | uint32(uint32(key[17])<<8)) | uint32(uint32(key[18])<<16)) | uint32(uint32(key[19])<<24)
	ctx.Pad[1] = ((uint32(key[20]) | uint32(uint32(key[21])<<8)) | uint32(uint32(key[22])<<16)) | uint32(uint32(key[23])<<24)
	ctx.Pad[2] = ((uint32(key[24]) | uint32(uint32(key[25])<<8)) | uint32(uint32(key[26])<<16)) | uint32(uint32(key[27])<<24)
	ctx.Pad[3] = ((uint32(key[28]) | uint32(uint32(key[29])<<8)) | uint32(uint32(key[30])<<16)) | uint32(uint32(key[31])<<24)
	clear(ctx.H[:5])
	ctx.C_idx = 0
}

func Crypto_poly1305x8_update(ctx *Crypto_poly1305x8_ctx, m []byte, n uint64) {
	var v3 uint64
	var v12 uint64
	var v13 uint64
	var v24 uint64
	var v52 uint64
	if uint64(len(m)) < n {
		n = uint64(len(m))
	}
	v3 = 0
	_ = v3
	if ctx.C_idx > 0 {
		v12 = 0x80 - ctx.C_idx
		if n < v12 {
			for v13 = 0; v13 < n; v13++ {
				ctx.C[ctx.C_idx+v13] = m[v3+v13]
			}
			ctx.C_idx += n
			return
		}
		for v24 = 0; v24 < v12; v24++ {
			ctx.C[ctx.C_idx+v24] = m[v3+v24]
		}
		v3 += v12
		n -= v12
		poly_octa(ctx, ctx.C[:])
		ctx.C_idx = 0
	}
	for n >= 0x80 {
		poly_octa(ctx, m[v3:])
		v3 += 0x80
		n -= 0x80
	}
	for n >= 16 {
		poly_block_r(ctx, m[v3:])
		v3 += 16
		n -= 16
	}
	for v52 = 0; v52 < n; v52++ {
		ctx.C[v52] = m[v3+v52]
	}
	ctx.C_idx = n
}

func Crypto_poly1305x8_final(ctx *Crypto_poly1305x8_ctx, mac []byte) {
	var v6 uint64
	var v8 uint64
	var v21 uint64
	var v29 uint64
	var v42 uint32
	var v43 uint32
	var v44 uint32
	var v45 uint32
	var v46 uint32
	var v47 uint32
	var v48 uint32
	var v49 uint64
	var v52 uint32
	var v55 uint32
	var v69 uint32
	var v72 uint32
	var v86 uint32
	var v89 uint32
	var v103 uint32
	var v106 uint32
	var v120 uint32
	var v123 uint32
	var v261 uint64
	_ = 0
	if ctx.C_idx > 0 {
		v6 = ctx.C_idx
		v8 = 0
		for v6 >= 16 {
			poly_block_r(ctx, ctx.C[v8:])
			v8 += 16
			v6 -= 16
		}
		if v6 > 0 {
			var v20 [16]byte
			for v21 = 0; v21 < v6; v21++ {
				v20[v21] = ctx.C[v8+v21]
			}
			v20[v6] = 1
			for v29 = v6 + 1; v29 < 16; v29++ {
				v20[v29] = 0
			}
			poly_add_block(ctx.H[:], v20[:], uint32(0))
			poly_mul(ctx.H[:], ctx.R[:])
		}
	}
	v52 = ctx.H[0]
	v47 = uint32(v52 >> 26)
	v55 = v52 & 0x3ffffff
	ctx.H[1] += v47
	v69 = ctx.H[1]
	v47 = uint32(v69 >> 26)
	v72 = v69 & 0x3ffffff
	ctx.H[2] += v47
	v86 = ctx.H[2]
	v47 = uint32(v86 >> 26)
	v89 = v86 & 0x3ffffff
	ctx.H[3] += v47
	v103 = ctx.H[3]
	v47 = uint32(v103 >> 26)
	v106 = v103 & 0x3ffffff
	ctx.H[4] += v47
	v120 = ctx.H[4]
	v47 = uint32(v120 >> 26)
	v123 = v120 & 0x3ffffff
	v55 += (v47 * 5)
	v47 = uint32(v55 >> 26)
	v55 &= 0x3ffffff
	v72 += v47
	v42 = v55 + 5
	v47 = uint32(v42 >> 26)
	v42 &= 0x3ffffff
	v43 = v72 + v47
	v47 = uint32(v43 >> 26)
	v43 &= 0x3ffffff
	v44 = v89 + v47
	v47 = uint32(v44 >> 26)
	v44 &= 0x3ffffff
	v45 = v106 + v47
	v47 = uint32(v45 >> 26)
	v45 &= 0x3ffffff
	v46 = (v123 + v47) - 0x4000000
	v48 = uint32(v46>>31) - 1
	v42 &= v48
	v43 &= v48
	v44 &= v48
	v45 &= v48
	v46 &= v48
	v48 = ^v48
	v171 := v55 & v48
	v55 = v171 | v42
	v173 := v72 & v48
	v72 = v173 | v43
	v175 := v89 & v48
	v89 = v175 | v44
	v177 := v106 & v48
	v106 = v177 | v45
	v179 := v123 & v48
	v55 = (v55 | uint32(v72<<26)) & 0xffffffff
	v72 = (uint32(v72>>6) | uint32(v89<<20)) & 0xffffffff
	v89 = (uint32(v89>>12) | uint32(v106<<14)) & 0xffffffff
	v106 = (uint32(v106>>18) | uint32((v179|v46)<<8)) & 0xffffffff
	v49 = uint64(v55) + uint64(ctx.Pad[0])
	v55 = uint32(v49)
	v49 = (uint64(v72) + uint64(ctx.Pad[1])) + uint64(v49>>32)
	v72 = uint32(v49)
	v49 = (uint64(v89) + uint64(ctx.Pad[2])) + uint64(v49>>32)
	v89 = uint32(v49)
	v49 = (uint64(v106) + uint64(ctx.Pad[3])) + uint64(v49>>32)
	v106 = uint32(v49)
	v292 := v55 & 0xff
	mac[0] = byte(v292)
	v298 := uint32(v55>>8) & 0xff
	mac[1] = byte(v298)
	v304 := uint32(v55>>16) & 0xff
	mac[2] = byte(v304)
	v310 := uint32(v55>>24) & 0xff
	mac[3] = byte(v310)
	v243 := mac[4:]
	v314 := v72 & 0xff
	v243[0] = byte(v314)
	v320 := uint32(v72>>8) & 0xff
	v243[1] = byte(v320)
	v326 := uint32(v72>>16) & 0xff
	v243[2] = byte(v326)
	v332 := uint32(v72>>24) & 0xff
	v243[3] = byte(v332)
	v247 := mac[8:]
	v336 := v89 & 0xff
	v247[0] = byte(v336)
	v342 := uint32(v89>>8) & 0xff
	v247[1] = byte(v342)
	v348 := uint32(v89>>16) & 0xff
	v247[2] = byte(v348)
	v354 := uint32(v89>>24) & 0xff
	v247[3] = byte(v354)
	v251 := mac[12:]
	v358 := v106 & 0xff
	v251[0] = byte(v358)
	v364 := uint32(v106>>8) & 0xff
	v251[1] = byte(v364)
	v370 := uint32(v106>>16) & 0xff
	v251[2] = byte(v370)
	v376 := uint32(v106>>24) & 0xff
	v251[3] = byte(v376)
	clear(ctx.C[:0x80])
	ctx.C_idx = 0
	for v261 = 0; v261 < 5; v261++ {
		ctx.R[v261] = 0
		ctx.R2[v261] = 0
		ctx.R3[v261] = 0
		ctx.R4[v261] = 0
		ctx.R5[v261] = 0
		ctx.R6[v261] = 0
		ctx.R7[v261] = 0
		ctx.R8[v261] = 0
		ctx.H[v261] = 0
	}
	clear(ctx.Pad[:4])
}

func Crypto_poly1305x8(mac []byte, message []byte, message_size uint64, key []byte) {
	var v4 Crypto_poly1305x8_ctx
	Crypto_poly1305x8_init(&v4, key[:])
	Crypto_poly1305x8_update(&v4, message[:], message_size)
	Crypto_poly1305x8_final(&v4, mac[:])
}
