// Code generated by sgoiter emit go127; DO NOT EDIT.
package md5_transform

import "encoding/binary"

func Md5_transform_block(state []uint32, block []byte) {
	v4 := state[int(0)]
	v2 := v4
	v7 := state[int(1)]
	v5 := v7
	v10 := state[int(2)]
	v8 := v10
	v13 := state[int(3)]
	v11 := v13
	var _arr_v14 [16]uint32
	v14 := _arr_v14[:]
	v15 := 0
	for v15 < 16 {
	v23 := v15 * 4
	v21 := binary.LittleEndian.Uint32(block[int(v23):])
	v14[int(v15)] = v21
	v19 := v15 + 1
	v15 = v19
	}
	v24 := v5 & v8
	v25 := ^v5
	v26 := v25 & v11
	v27 := v24 | v26
	v29 := v14[int(0)]
	v30 := v27 + v29
	v32 := v30 + uint32(3614090360)
	v33 := v2 + v32
	v2 = v33
	v35 := v2 << uint8(7)
	v38 := 32 - 7
	v39 := v2 >> uint8(v38)
	v40 := v35 | v39
	v2 = v40
	v41 := v2 + v5
	v2 = v41
	v42 := v2 & v5
	v43 := ^v2
	v44 := v43 & v8
	v45 := v42 | v44
	v47 := v14[int(1)]
	v48 := v45 + v47
	v50 := v48 + uint32(3905402710)
	v51 := v11 + v50
	v11 = v51
	v53 := v11 << uint8(12)
	v56 := 32 - 12
	v57 := v11 >> uint8(v56)
	v58 := v53 | v57
	v11 = v58
	v59 := v11 + v2
	v11 = v59
	v60 := v11 & v2
	v61 := ^v11
	v62 := v61 & v5
	v63 := v60 | v62
	v65 := v14[int(2)]
	v66 := v63 + v65
	v68 := v66 + uint32(606105819)
	v69 := v8 + v68
	v8 = v69
	v71 := v8 << uint8(17)
	v74 := 32 - 17
	v75 := v8 >> uint8(v74)
	v76 := v71 | v75
	v8 = v76
	v77 := v8 + v11
	v8 = v77
	v78 := v8 & v11
	v79 := ^v8
	v80 := v79 & v2
	v81 := v78 | v80
	v83 := v14[int(3)]
	v84 := v81 + v83
	v86 := v84 + uint32(3250441966)
	v87 := v5 + v86
	v5 = v87
	v89 := v5 << uint8(22)
	v92 := 32 - 22
	v93 := v5 >> uint8(v92)
	v94 := v89 | v93
	v5 = v94
	v95 := v5 + v8
	v5 = v95
	v97 := state[int(0)]
	v98 := v97 + v2
	state[int(0)] = v98
	v101 := state[int(1)]
	v102 := v101 + v5
	state[int(1)] = v102
	v105 := state[int(2)]
	v106 := v105 + v8
	state[int(2)] = v106
	v109 := state[int(3)]
	v110 := v109 + v11
	state[int(3)] = v110
}

