// Code generated by sgoiter emit go127; DO NOT EDIT.
// sgoiter-stamp: sha256=af210557af1984f5d5451e600ba5c894b32b2cd2892838cf39bc7921bd5f9caa
package c2poly1305x2

import "encoding/binary"

type Crypto_poly1305x2_ctx struct {
	C     [32]byte
	C_idx uint64
	R     [5]uint32
	R2    [5]uint32
	Pad   [4]uint32
	H     [5]uint32
}

func load32_le(p []byte) uint32 {
	return binary.LittleEndian.Uint32(p)
}

func store32_le(p []byte, v uint32) {
	v3 := v & 0xff
	p[0] = byte(v3)
	v9 := uint32(v>>8) & 0xff
	p[1] = byte(v9)
	v15 := uint32(v>>16) & 0xff
	p[2] = byte(v15)
	v21 := uint32(v>>24) & 0xff
	p[3] = byte(v21)
}

func poly_mul(h []uint32, r []uint32) {
	var v4 uint32
	var v7 uint32
	var v10 uint32
	var v13 uint32
	var v16 uint32
	var v29 uint32
	var v32 uint32
	var v35 uint32
	var v38 uint32
	var v41 uint32
	var v45 uint64
	var v47 uint64
	var v50 uint64
	var v53 uint64
	var v56 uint64
	var v59 uint64
	var v74 uint64
	var v89 uint64
	var v104 uint64
	var v119 uint64
	v4 = r[0]
	v7 = r[1]
	v10 = r[2]
	v13 = r[3]
	v16 = r[4]
	v22 := v10 * 5
	v25 := v13 * 5
	v28 := v16 * 5
	v29 = h[0]
	v32 = h[1]
	v35 = h[2]
	v38 = h[3]
	v41 = h[4]
	v45 = uint64(v29)
	v47 = uint64(v32)
	v50 = uint64(v35)
	v53 = uint64(v38)
	v56 = uint64(v41)
	v58 := ((((v45 * uint64(v4)) + (v47 * uint64(v28))) + (v50 * uint64(v25))) + (v53 * uint64(v22))) + (v56 * uint64(v7*5))
	v59 = (v45*uint64(v7) + v47*uint64(v4)) + ((v50 * uint64(v28)) + (v53*uint64(v25) + v56*uint64(v22)))
	v74 = (v45*uint64(v10) + v47*uint64(v7)) + ((v50 * uint64(v4)) + (v53*uint64(v28) + v56*uint64(v25)))
	v89 = (v45*uint64(v13) + v47*uint64(v10)) + ((v50 * uint64(v7)) + (v53*uint64(v4) + v56*uint64(v28)))
	v104 = (v45*uint64(v16) + v47*uint64(v13)) + ((v50 * uint64(v10)) + (v53*uint64(v7) + v56*uint64(v4)))
	v119 = uint64(v58 >> 26)
	v29 = uint32(v58) & 0x3ffffff
	v59 += v119
	v119 = uint64(v59 >> 26)
	v32 = uint32(v59) & 0x3ffffff
	v74 += v119
	v119 = uint64(v74 >> 26)
	v35 = uint32(v74) & 0x3ffffff
	v89 += v119
	v119 = uint64(v89 >> 26)
	v38 = uint32(v89) & 0x3ffffff
	v104 += v119
	v119 = uint64(v104 >> 26)
	v41 = uint32(v104) & 0x3ffffff
	v29 += (uint32(v119) * 5)
	v119 = uint64(uint64(v29) >> 26)
	v29 &= 0x3ffffff
	v32 += uint32(v119)
	h[0] = v29
	h[1] = v32
	h[2] = v35
	h[3] = v38
	h[4] = v41
}

func poly_add_block(h []uint32, m []byte, hibit uint32) {
	v26 := load32_le(m[:]) & 0x3ffffff
	h[0] += v26
	v34 := uint32(load32_le(m[3:])>>2) & 0x3ffffff
	h[1] += v34
	v42 := uint32(load32_le(m[6:])>>4) & 0x3ffffff
	h[2] += v42
	v50 := uint32(load32_le(m[9:])>>6) & 0x3ffffff
	h[3] += v50
	h[4] += (uint32(load32_le(m[12:])>>8) | hibit)
}

func poly_add5(h []uint32, t []uint32) {
	var v2 uint64
	v2 = uint64(h[0]) + uint64(t[0])
	v11 := uint32(v2) & 0x3ffffff
	h[0] = v11
	v2 = (uint64(v2>>26) + uint64(h[1])) + uint64(t[1])
	v24 := uint32(v2) & 0x3ffffff
	h[1] = v24
	v2 = (uint64(v2>>26) + uint64(h[2])) + uint64(t[2])
	v37 := uint32(v2) & 0x3ffffff
	h[2] = v37
	v2 = (uint64(v2>>26) + uint64(h[3])) + uint64(t[3])
	v50 := uint32(v2) & 0x3ffffff
	h[3] = v50
	v2 = (uint64(v2>>26) + uint64(h[4])) + uint64(t[4])
	h[4] = uint32(v2)
}

func poly_block_r(ctx *Crypto_poly1305x2_ctx, m []byte) {
	poly_add_block(ctx.H[:], m[:], uint32(0x1000000))
	poly_mul(ctx.H[:], ctx.R[:])
}

func poly_block_r_final(ctx *Crypto_poly1305x2_ctx, m []byte) {
	poly_add_block(ctx.H[:], m[:], uint32(0))
	poly_mul(ctx.H[:], ctx.R[:])
}

func poly_pair(ctx *Crypto_poly1305x2_ctx, m []byte) {
	var v2 [5]uint32
	poly_add_block(ctx.H[:], m[:], uint32(0x1000000))
	poly_mul(ctx.H[:], ctx.R2[:])
	v2[0] = 0
	v2[1] = 0
	v2[2] = 0
	v2[3] = 0
	v2[4] = 0
	poly_add_block(v2[:], m[16:], uint32(0x1000000))
	poly_mul(v2[:], ctx.R[:])
	poly_add5(ctx.H[:], v2[:])
}

func Crypto_poly1305x2_init(ctx *Crypto_poly1305x2_ctx, key []byte) {
	v3 := load32_le(key[:])
	v8 := load32_le(key[4:])
	v13 := load32_le(key[8:])
	v18 := load32_le(key[12:])
	v21 := v3 & 0x3ffffff
	ctx.R[0] = v21
	v30 := (uint32(v3>>26) | uint32(v8<<6)) & 0x3ffff03
	ctx.R[1] = v30
	v39 := (uint32(v8>>20) | uint32(v13<<12)) & 0x3ffc0ff
	ctx.R[2] = v39
	v48 := (uint32(v13>>14) | uint32(v18<<18)) & 0x3f03fff
	ctx.R[3] = v48
	v54 := uint32(v18>>8) & 0xfffff
	ctx.R[4] = v54
	ctx.R2[0] = ctx.R[0]
	ctx.R2[1] = ctx.R[1]
	ctx.R2[2] = ctx.R[2]
	ctx.R2[3] = ctx.R[3]
	ctx.R2[4] = ctx.R[4]
	poly_mul(ctx.R2[:], ctx.R[:])
	ctx.Pad[0] = load32_le(key[16:])
	ctx.Pad[1] = load32_le(key[20:])
	ctx.Pad[2] = load32_le(key[24:])
	ctx.Pad[3] = load32_le(key[28:])
	ctx.H[0] = 0
	ctx.H[1] = 0
	ctx.H[2] = 0
	ctx.H[3] = 0
	ctx.H[4] = 0
	ctx.C_idx = 0
	clear(ctx.C[:32])
}

func Crypto_poly1305x2_update(ctx *Crypto_poly1305x2_ctx, message []byte, message_size uint64) {
	var v3 uint64
	var v5 uint64
	var v6 uint64
	v3 = 0
	_ = v3
	if message_size == 0 {
		return
	}
	if ctx.C_idx != 0 {
		v6 = 32 - ctx.C_idx
		if v6 > message_size {
			v6 = message_size
		}
		for v5 = 0; v5 < v6; v5++ {
			ctx.C[ctx.C_idx] = message[v3]
			ctx.C_idx += 1
			v3++
			message_size--
		}
		if ctx.C_idx == 32 {
			poly_pair(ctx, ctx.C[:])
			ctx.C_idx = 0
		}
	}
	v37 := uint64(message_size >> 5)
	for v5 = 0; v5 < v37; v5++ {
		poly_pair(ctx, message[v3:])
		v3 += 32
		message_size -= 32
	}
	for v5 = 0; v5 < message_size; v5++ {
		ctx.C[ctx.C_idx] = message[v3+v5]
		ctx.C_idx += 1
	}
}

func Crypto_poly1305x2_final(ctx *Crypto_poly1305x2_ctx, mac []byte) {
	var v2 uint64
	var v4 uint32
	var v5 uint32
	var v6 uint32
	var v7 uint32
	var v8 uint32
	var v9 uint32
	var v10 uint32
	var v11 uint32
	var v12 uint32
	var v13 uint32
	var v14 uint32
	var v15 uint32
	var v16 uint64
	var v25 uint64
	_ = 0
	if ctx.C_idx >= 16 {
		poly_block_r(ctx, ctx.C[:])
		v25 = ctx.C_idx - 16
		for v2 = 0; v2 < v25; v2++ {
			ctx.C[v2] = ctx.C[v2+16]
		}
		ctx.C_idx = v25
	}
	if ctx.C_idx != 0 {
		ctx.C[ctx.C_idx] = 1
		for v2 = ctx.C_idx + 1; v2 < 16; v2++ {
			ctx.C[v2] = 0
		}
		poly_block_r_final(ctx, ctx.C[:])
	}
	v4 = ctx.H[0]
	v5 = ctx.H[1]
	v6 = ctx.H[2]
	v7 = ctx.H[3]
	v8 = ctx.H[4]
	v14 = uint32(v5 >> 26)
	v5 &= 0x3ffffff
	v6 += v14
	v14 = uint32(v6 >> 26)
	v6 &= 0x3ffffff
	v7 += v14
	v14 = uint32(v7 >> 26)
	v7 &= 0x3ffffff
	v8 += v14
	v14 = uint32(v8 >> 26)
	v8 &= 0x3ffffff
	v4 += (v14 * 5)
	v14 = uint32(v4 >> 26)
	v4 &= 0x3ffffff
	v5 += v14
	v9 = v4 + 5
	v14 = uint32(v9 >> 26)
	v9 &= 0x3ffffff
	v10 = v5 + v14
	v14 = uint32(v10 >> 26)
	v10 &= 0x3ffffff
	v11 = v6 + v14
	v14 = uint32(v11 >> 26)
	v11 &= 0x3ffffff
	v12 = v7 + v14
	v14 = uint32(v12 >> 26)
	v12 &= 0x3ffffff
	v13 = (v8 + v14) - (1 << 26)
	v15 = uint32(v13>>31) - 1
	v9 &= v15
	v10 &= v15
	v11 &= v15
	v12 &= v15
	v13 &= v15
	v15 = ^v15
	v128 := v4 & v15
	v4 = v128 | v9
	v130 := v5 & v15
	v5 = v130 | v10
	v132 := v6 & v15
	v6 = v132 | v11
	v134 := v7 & v15
	v7 = v134 | v12
	v136 := v8 & v15
	v8 = v136 | v13
	v4 = (v4 | uint32(v5<<26)) & 0xffffffff
	v5 = (uint32(v5>>6) | uint32(v6<<20)) & 0xffffffff
	v6 = (uint32(v6>>12) | uint32(v7<<14)) & 0xffffffff
	v7 = (uint32(v7>>18) | uint32(v8<<8)) & 0xffffffff
	v16 = uint64(v4) + uint64(ctx.Pad[0])
	v4 = uint32(v16)
	v16 = (uint64(v5) + uint64(ctx.Pad[1])) + uint64(v16>>32)
	v5 = uint32(v16)
	v16 = (uint64(v6) + uint64(ctx.Pad[2])) + uint64(v16>>32)
	v6 = uint32(v16)
	v16 = (uint64(v7) + uint64(ctx.Pad[3])) + uint64(v16>>32)
	v7 = uint32(v16)
	store32_le(mac[:], v4)
	store32_le(mac[4:], v5)
	store32_le(mac[8:], v6)
	store32_le(mac[12:], v7)
	clear(ctx.C[:32])
	ctx.C_idx = 0
	v2 = 0
	ctx.R[0] = 0
	ctx.R2[0] = 0
	ctx.H[0] = 0
	ctx.R[1] = 0
	ctx.R2[1] = 0
	ctx.H[1] = 0
	ctx.R[2] = 0
	ctx.R2[2] = 0
	ctx.H[2] = 0
	ctx.R[3] = 0
	ctx.R2[3] = 0
	ctx.H[3] = 0
	ctx.R[4] = 0
	ctx.R2[4] = 0
	ctx.H[4] = 0
	clear(ctx.Pad[:4])
}

func Crypto_poly1305x2(mac []byte, message []byte, message_size uint64, key []byte) {
	var v5 *Crypto_poly1305x2_ctx
	var v4 Crypto_poly1305x2_ctx
	v5 = &v4
	Crypto_poly1305x2_init(v5, key[:])
	Crypto_poly1305x2_update(v5, message[:], message_size)
	Crypto_poly1305x2_final(v5, mac[:])
}
