// Code generated by sgoiter emit go127; DO NOT EDIT.
// sgoiter-stamp: sha256=ea6af7e3eea1e90eeda3007435946bc3c199b22f01f18796d9f9abcceb2e833f
package c2json

func Is_ws(c byte) int {
	if c == 32 {
		return 1
	}
	if c == 9 {
		return 1
	}
	if c == 10 {
		return 1
	}
	if c == 13 {
		return 1
	}
	return 0
}

func Is_num_char(c byte) int {
	var v5 bool
	v5 = (c >= '0') && (c <= '9')
	if v5 {
		return 1
	}
	if c == 46 {
		return 1
	}
	if (c == 'e') || (c == 'E') {
		return 1
	}
	if (c == 43) || (c == 45) {
		return 1
	}
	return 0
}

func Skip_ws(json []byte, len_ int, pos int) int {
	if len(json) < len_ {
		len_ = int(len(json))
	}
	for pos < len_ {
		if Is_ws(json[pos]) == 0 {
			break
		}
		pos++
	}
	return pos
}

func C2json_skip_value(json []byte, len_ int, pos int, end_pos *int, val_type *int) int {
	var v5 int
	var v7 int
	var v9 int
	var v11 byte
	var v13 byte
	var v42 bool
	var v72 bool
	var v190 bool
	if len(json) < len_ {
		len_ = int(len(json))
	}
	_ = 0
	v5 = 0
	v7 = 0
	v9 = 0
	v11 = 0
	v13 = v11
	pos = Skip_ws(json[:], len_, pos)
	if pos >= len_ {
		return 0
	}
	v11 = json[pos]
	if v11 == 34 {
		pos++
		for pos < len_ {
			if json[pos] == 0x5c {
				pos += 2
			} else {
				if json[pos] == 34 {
					pos++
					*end_pos = pos
					*val_type = 3
					return 1
				} else {
					pos++
				}
			}
		}
		return 0
	}
	if v11 == 0x7b {
		v5 = 1
		v7 = 0
		pos++
		for {
			v42 = (pos < len_) && (v5 > 0)
			if !v42 {
				break
			}
			v13 = json[pos]
			if v7 != 0 {
				if v13 == 0x5c {
					pos += 2
					continue
				} else {
					if v13 == 34 {
						v7 = 0
					}
				}
			} else {
				if v13 == 34 {
					v7 = 1
				} else {
					if v13 == 0x7b {
						v5++
					} else {
						if v13 == 0x7d {
							v5--
						}
					}
				}
			}
			pos++
		}
		if v5 == 0 {
			*end_pos = pos
			*val_type = 1
			return 1
		}
		return 0
	}
	if v11 == 0x5b {
		v5 = 1
		v7 = 0
		pos++
		for {
			v72 = (pos < len_) && (v5 > 0)
			if !v72 {
				break
			}
			v13 = json[pos]
			if v7 != 0 {
				if v13 == 0x5c {
					pos += 2
					continue
				} else {
					if v13 == 34 {
						v7 = 0
					}
				}
			} else {
				if v13 == 34 {
					v7 = 1
				} else {
					if v13 == 0x5b {
						v5++
					} else {
						if v13 == 0x5d {
							v5--
						}
					}
				}
			}
			pos++
		}
		if v5 == 0 {
			*end_pos = pos
			*val_type = 2
			return 1
		}
		return 0
	}
	if v11 == 't' {
		if (pos + 3) < len_ {
			if json[(pos+1)] == 'r' {
				if json[(pos+2)] == 'u' {
					if json[(pos+3)] == 'e' {
						*end_pos = pos + 4
						*val_type = 5
						return 1
					}
				}
			}
		}
	}
	if v11 == 'f' {
		if (pos + 4) < len_ {
			if json[(pos+1)] == 'a' {
				if json[(pos+2)] == 'l' {
					if json[(pos+3)] == 's' {
						if json[(pos+4)] == 'e' {
							*end_pos = pos + 5
							*val_type = 6
							return 1
						}
					}
				}
			}
		}
	}
	if v11 == 'n' {
		if (pos + 3) < len_ {
			if json[(pos+1)] == 'u' {
				if json[(pos+2)] == 'l' {
					if json[(pos+3)] == 'l' {
						*end_pos = pos + 4
						*val_type = 7
						return 1
					}
				}
			}
		}
	}
	v190 = (v11 >= '0') && (v11 <= '9')
	if (v11 == 45) || v190 {
		v9 = pos
		if v11 == 45 {
			pos++
		}
		for pos < len_ {
			if Is_num_char(json[pos]) == 0 {
				break
			}
			pos++
		}
		if pos > v9 {
			*end_pos = pos
			*val_type = 4
			return 1
		}
		return 0
	}
	return 0
}

func C2json_validate(json []byte, len_ int) int {
	var v2 int
	var v4 int
	if len(json) < len_ {
		len_ = int(len(json))
	}
	v2 = 0
	v4 = 0
	if (json == nil) || (len_ <= 0) {
		return 0
	}
	v13 := &v2
	v14 := &v4
	if C2json_skip_value(json[:], len_, 0, v13, v14) == 0 {
		return 0
	}
	v2 = Skip_ws(json[:], len_, v2)
	if v2 == len_ {
		return 1
	}
	return 0
}

func C2json_find_key(json []byte, len_ int, key []byte, key_len int, val_start *int, val_len *int, val_type *int) int {
	var v7 int
	var v9 int
	var v11 int
	var v13 int
	var v15 int
	var v17 int
	var v19 int
	var v21 int
	var v56 byte
	var v80 int
	var v81 int
	var v82 *int
	var v83 *int
	if len(key) < key_len {
		key_len = int(len(key))
	}
	v7 = 0
	v9 = 0
	v11 = 0
	v13 = 0
	v15 = 0
	v17 = 0
	v19 = 0
	v21 = 0
	if (((json == nil) || (len_ <= 0)) || (key == nil)) || (key_len <= 0) {
		return 0
	}
	v7 = Skip_ws(json[:], len_, 0)
	if (v7 >= len_) || (json[v7] != 0x7b) {
		return 0
	}
	v7++
	for v7 < len_ {
		v7 = Skip_ws(json[:], len_, v7)
		if v7 >= len_ {
			return 0
		}
		if json[v7] == 0x7d {
			return 0
		}
		if json[v7] != 34 {
			return 0
		}
		v7++
		v9 = v7
		for v7 < len_ {
			v56 = json[v7]
			if !(v56 != 34) {
				break
			}
			if v56 == 0x5c {
				v7 += 2
			} else {
				v7++
			}
		}
		if v7 >= len_ {
			return 0
		}
		v11 = v7 - v9
		v7++
		v7 = Skip_ws(json[:], len_, v7)
		if (v7 >= len_) || (json[v7] != ':') {
			return 0
		}
		v7++
		v7 = Skip_ws(json[:], len_, v7)
		v13 = v7
		v15 = v80
		v17 = v81
		v82 = &v15
		v83 = &v17
		if C2json_skip_value(json[:], len_, v7, v82, v83) == 0 {
			return 0
		}
		if v11 == key_len {
			v19 = 1
			for v21 = 0; v21 < key_len; v21++ {
				if json[v9+v21] != key[v21] {
					v19 = 0
					break
				}
			}
			if v19 != 0 {
				*val_start = v13
				*val_len = v15 - v13
				*val_type = v17
				return 1
			}
		}
		v7 = Skip_ws(json[:], len_, v15)
		if v7 >= len_ {
			return 0
		}
		if json[v7] == 44 {
			v7++
		} else {
			if json[v7] == 0x7d {
				return 0
			} else {
				return 0
			}
		}
	}
	return 0
}

func C2json_get_string(json []byte, len_ int, key []byte, key_len int, out []byte, out_max int) int {
	var v6 int
	var v8 int
	var v10 int
	var v12 int
	var v14 int
	var v16 int
	var v18 byte
	var v20 byte
	var v47 int
	var v54 bool
	var v55 int
	var v61 int
	var v66 int
	var v71 int
	var v76 int
	var v81 int
	var v86 int
	var v89 int
	var v92 int
	if len(key) < key_len {
		key_len = int(len(key))
	}
	v6 = 0
	v8 = 0
	v10 = 0
	v12 = 0
	v14 = 0
	v16 = 0
	v18 = 0
	v20 = v18
	v22 := &v6
	v23 := &v8
	v24 := &v10
	if C2json_find_key(json[:], len_, key[:], key_len, v22, v23, v24) == 0 {
		return -1
	}
	if (v10 != 3) || (v8 < 2) {
		return -1
	}
	v12 = v6 + 1
	v14 = (v6 + v8) - 1
	v16 = 0
	for {
		v46 := (v12 < v14) && (v16 < out_max)
		if !v46 {
			break
		}
		v47 = v12
		v12++
		v18 = json[v47]
		v54 = (v18 == 0x5c) && (v12 < v14)
		if v54 {
			v55 = v12
			v12++
			v20 = json[v55]
			if v20 == 34 {
				v61 = v16
				v16++
				out[v61] = 34
			} else {
				if v20 == 0x5c {
					v66 = v16
					v16++
					out[v66] = 0x5c
				} else {
					if v20 == 'n' {
						v71 = v16
						v16++
						out[v71] = 10
					} else {
						if v20 == 't' {
							v76 = v16
							v16++
							out[v76] = 9
						} else {
							if v20 == 'r' {
								v81 = v16
								v16++
								out[v81] = 13
							} else {
								if v20 == 47 {
									v86 = v16
									v16++
									out[v86] = 47
								} else {
									v89 = v16
									v16++
									out[v89] = v20
								}
							}
						}
					}
				}
			}
		} else {
			v92 = v16
			v16++
			out[v92] = v18
		}
	}
	return v16
}

func C2json_get_int64(json []byte, len_ int, key []byte, key_len int, out *int64) int {
	var v5 int
	var v7 int
	var v9 int
	var v11 int
	var v13 int
	var v15 int64
	var v17 int64
	if len(key) < key_len {
		key_len = int(len(key))
	}
	v5 = 0
	v7 = 0
	v9 = 0
	v11 = 0
	v13 = 0
	v15 = 1
	v17 = 0
	v19 := &v5
	v20 := &v7
	v21 := &v9
	if C2json_find_key(json[:], len_, key[:], key_len, v19, v20, v21) == 0 {
		return 0
	}
	if (v9 != 4) || (v7 <= 0) {
		return 0
	}
	v11 = v5
	v13 = v5 + v7
	v15 = 1
	if json[v11] == 45 {
		v15 = -1
		v11++
	}
	v17 = 0
	for v11 < v13 {
		v42 := json[v11]
		if !(v42 >= '0') {
			break
		}
		if !(v42 <= '9') {
			break
		}
		v17 = (v17 * 10) + (int64(v42) - 48)
		v11++
	}
	*out = v17 * v15
	return 1
}

func C2json_get_bool(json []byte, len_ int, key []byte, key_len int, out *int) int {
	var v5 int
	var v7 int
	var v9 int
	if len(key) < key_len {
		key_len = int(len(key))
	}
	v5 = 0
	v7 = 0
	v9 = 0
	v11 := &v5
	v12 := &v7
	v13 := &v9
	if C2json_find_key(json[:], len_, key[:], key_len, v11, v12, v13) == 0 {
		return 0
	}
	if v9 == 5 {
		*out = 1
		return 1
	}
	if v9 == 6 {
		*out = 0
		return 1
	}
	return 0
}
