// Code generated by sgoiter emit go127; DO NOT EDIT.
// sgoiter-stamp: sha256=4699e0dc98bc11a9f606190efd92bbc26af94393b5f0dc2da6154cf46a6840c5
package c2raster

func c2_sqrtf(x float32) float32 {
	var v3 float32
	var v6 int
	if x <= float32(0) {
		return float32(0)
	}
	v3 = x
	if v3 < float32(1) {
		v3 = float32(1)
	}
	for v6 = 0; v6 < 8; v6++ {
		v3 = float32(0.5) * (v3 + (x / v3))
	}
	return float32(v3)
}

func c2_isqrt64(val int64) int64 {
	var v3 int64
	var v5 int64
	if val <= 0 {
		return 0
	}
	v3 = 0
	v5 = int64(uint64(1 << 62))
	for v5 > val {
		v5 = int64(v5 >> 2)
	}
	for v5 != 0 {
		if val >= (v3 + v5) {
			val -= (v3 + v5)
			v3 = int64(v3>>1) + v5
		} else {
			v3 = int64(v3 >> 1)
		}
		v5 = int64(v5 >> 2)
	}
	return v3
}

func c2_blend_pixel(dst uint32, src uint32) uint32 {
	var v43 uint32
	var v50 uint32
	var v57 uint32
	var v64 uint32
	v6 := uint32(src>>24) & 0xff
	if v6 == 0xff {
		return src
	}
	if v6 == 0 {
		return dst
	}
	v11 := src & 0xff
	v16 := uint32(src>>8) & 0xff
	v21 := uint32(src>>16) & 0xff
	v24 := dst & 0xff
	v29 := uint32(dst>>8) & 0xff
	v34 := uint32(dst>>16) & 0xff
	v39 := uint32(dst>>24) & 0xff
	v42 := uint32(0xff) - v6
	v43 = v11 + (((v24 * v42) + 0x7f) / 0xff)
	v50 = v16 + (((v29 * v42) + 0x7f) / 0xff)
	v57 = v21 + (((v34 * v42) + 0x7f) / 0xff)
	v64 = v6 + (((v39 * v42) + 0x7f) / 0xff)
	if v43 > 0xff {
		v43 = 0xff
	}
	if v50 > 0xff {
		v50 = 0xff
	}
	if v57 > 0xff {
		v57 = 0xff
	}
	if v64 > 0xff {
		v64 = 0xff
	}
	return uint32(((v43 | uint32(v50<<8)) | uint32(v57<<16)) | uint32(v64<<24))
}

func c2_blend_pixel_cov(dst uint32, src uint32, cov uint32) uint32 {
	if cov == 0 {
		return dst
	}
	if cov >= 0xff {
		return uint32(c2_blend_pixel(dst, src))
	}
	v8 := src & 0xff
	v18 := uint32(src>>8) & 0xff
	v28 := uint32(src>>16) & 0xff
	v38 := uint32(src>>24) & 0xff
	return uint32(c2_blend_pixel(dst, ((((((v8 * cov) + 0x7f) / 0xff) | uint32((((v18*cov)+0x7f)/0xff)<<8)) | uint32((((v28*cov)+0x7f)/0xff)<<16)) | uint32((((v38*cov)+0x7f)/0xff)<<24))))
}

func fill_solid_rect(framebuffer []uint32, stride int, x int, y int, w int, h int, color uint32) {
	var v12 int
	var v15 int
	var v18 int
	var v31 int
	var v36 int
	var v43 int
	var v48 int
	_ = 0
	if (w <= 0) || (h <= 0) {
		return
	}
	v12 = x
	if v12 < 0 {
		v12 = 0
	}
	v15 = y
	if v15 < 0 {
		v15 = 0
	}
	v18 = x + w
	v21 := y + h
	if v18 > stride {
		v18 = stride
	}
	if (v12 >= v18) || (v15 >= v21) {
		return
	}
	v29 := uint32(color>>24) & 0xff
	if v29 == 0xff {
		for v31 = v15; v31 < v21; v31++ {
			v36 = v12
			for v36 < v18 {
				framebuffer[int((v31*stride)+v36)] = color
				v36++
			}
		}
	} else {
		if v29 > 0 {
			for v43 = v15; v43 < v21; v43++ {
				v48 = v12
				for v48 < v18 {
					framebuffer[int((v43*stride)+v48)] = c2_blend_pixel(framebuffer[int((v43*stride)+v48)], color)
					v48++
				}
			}
		}
	}
}

func Rasterize_bezier_quad(x0 float32, y0 float32, x1 float32, y1 float32, x2 float32, y2 float32, coverage []byte, w int, h int) {
	var v28 float32
	var v31 float32
	var v34 float32
	var v37 float32
	var v40 int
	var v44 int
	var v48 int
	var v52 int
	var v67 int
	var v75 float32
	var v78 float32
	var v80 float32
	var v84 float32
	var v86 float32
	var v97 int
	var v103 float32
	var v106 int
	var v114 float32
	var v115 float32
	var v117 int
	var v123 float32
	var v125 float32
	var v128 int
	var v135 float32
	var v137 float32
	var v141 float32
	var v143 float32
	var v145 float32
	var v146 float32
	var v148 float32
	var v175 float32
	var v176 int
	var v193 int
	_ = 0
	if ((w <= 0) || (h <= 0)) || (coverage == nil) {
		return
	}
	if (((((x0 != x0) || (y0 != y0)) || (x1 != x1)) || (y1 != y1)) || (x2 != x2)) || (y2 != y2) {
		return
	}
	v28 = x0
	if x1 < v28 {
		v28 = x1
	}
	if x2 < v28 {
		v28 = x2
	}
	v31 = x0
	if x1 > v31 {
		v31 = x1
	}
	if x2 > v31 {
		v31 = x2
	}
	v34 = y0
	if y1 < v34 {
		v34 = y1
	}
	if y2 < v34 {
		v34 = y2
	}
	v37 = y0
	if y1 > v37 {
		v37 = y1
	}
	if y2 > v37 {
		v37 = y2
	}
	v40 = int(v28) - 2
	v44 = int(v31) + 3
	v48 = int(v34) - 2
	v52 = int(v37) + 3
	if v40 < 0 {
		v40 = 0
	}
	if v48 < 0 {
		v48 = 0
	}
	if v44 > w {
		v44 = w
	}
	if v52 > h {
		v52 = h
	}
	if (v40 >= v44) || (v48 >= v52) {
		return
	}
	var v65 [33]float32
	var v66 [33]float32
	for v67 = 0; v67 <= 32; v67++ {
		v75 = float32(v67) / float32(32)
		v78 = float32(1) - v75
		v80 = v78 * v78
		v84 = (float32(2) * v78) * v75
		v86 = v75 * v75
		v65[v67] = ((v80 * x0) + (v84 * x1)) + (v86 * x2)
		v66[v67] = ((v80 * y0) + (v84 * y1)) + (v86 * y2)
	}
	for v97 = v48; v97 < v52; v97++ {
		v103 = float32(v97) + float32(0.5)
		v106 = v40
		for v106 < v44 {
			v114 = float32(v106) + float32(0.5)
			v115 = float32(1e+06)
			v117 = 0
			for v117 < 32 {
				v123 = v65[v117]
				v125 = v66[v117]
				v128 = v117 + 1
				v135 = v65[v128] - v123
				v137 = v66[v128] - v125
				v141 = (v135 * v135) + (v137 * v137)
				v143 = v114 - v123
				v145 = v103 - v125
				if v141 > float32(1e-06) {
					v148 = ((v143 * v135) + (v145 * v137)) / v141
					if v148 < float32(0) {
						v148 = float32(0)
					} else {
						if v148 > float32(1) {
							v148 = float32(1)
						}
					}
					v146 = ((v114 - (v123 + (v148 * v135))) * (v114 - (v123 + (v148 * v135)))) + ((v103 - (v125 + (v148 * v137))) * (v103 - (v125 + (v148 * v137))))
				} else {
					v146 = (v143 * v143) + (v145 * v145)
				}
				if v146 < v115 {
					v115 = v146
				}
				v117++
			}
			if v115 < float32(2.25) {
				v175 = c2_sqrtf(v115)
				v176 = 0
				if v175 <= float32(0.5) {
					v176 = 255
				} else {
					if v175 < float32(1.5) {
						v176 = int(((float32(1.5) - v175) * float32(255)) + float32(0.5))
						if v176 > 255 {
							v176 = 255
						}
						if v176 < 0 {
							v176 = 0
						}
					}
				}
				v193 = (v97 * w) + v106
				if v176 > int(coverage[v193]) {
					coverage[v193] = byte(v176)
				}
			}
			v106++
		}
	}
}

func Rasterize_rounded_rect(framebuffer []uint32, stride int, x int, y int, w int, h int, radius int, color uint32) {
	var v112 int64
	var v123 int
	var v127 int
	var v129 int
	var v131 int
	var v132 int
	var v134 int
	var v136 int
	var v139 int
	var v147 int
	var v151 int
	var v152 int64
	var v161 int
	var v166 int64
	var v175 int64
	var v188 int
	_ = 0
	if (((w <= 0) || (h <= 0)) || (stride <= 0)) || (framebuffer == nil) {
		return
	}
	if radius <= 0 {
		fill_solid_rect(framebuffer[:], stride, x, y, w, h, color)
		return
	}
	if (radius * 2) > w {
		radius = w / 2
	}
	if (radius * 2) > h {
		radius = h / 2
	}
	v29 := x + radius
	v31 := 2 * radius
	fill_solid_rect(framebuffer[:], stride, v29, y, (w - v31), h, color)
	v34 := y + radius
	v37 := h - v31
	fill_solid_rect(framebuffer[:], stride, x, v34, radius, v37, color)
	v39 := x + w
	v40 := v39 - radius
	fill_solid_rect(framebuffer[:], stride, v40, v34, radius, v37, color)
	var v50 [4]int
	var v51 [4]int
	var v52 [4]int
	var v53 [4]int
	var v54 [4]int
	var v55 [4]int
	v50[0] = v29
	v51[0] = v34
	v52[0] = x
	v53[0] = y
	v54[0] = v29
	v55[0] = v34
	v50[1] = v40
	v51[1] = v34
	v52[1] = v40
	v53[1] = y
	v54[1] = v39
	v55[1] = v34
	v50[2] = v29
	v81 := y + h
	v82 := v81 - radius
	v51[2] = v82
	v52[2] = x
	v53[2] = v82
	v54[2] = v29
	v55[2] = v81
	v50[3] = v40
	v51[3] = v82
	v52[3] = v40
	v53[3] = v82
	v54[3] = v39
	v55[3] = v81
	v111 := int64(radius) - 1
	v112 = 0
	if v111 > 0 {
		v112 = v111 * v111
	}
	v123 = 0
	for v123 < 4 {
		v129 = v50[v123]
		v131 = v51[v123]
		v132 = v52[v123]
		v134 = v53[v123]
		v136 = v54[v123]
		v139 = v55[v123]
		if v132 < 0 {
			v132 = 0
		}
		if v134 < 0 {
			v134 = 0
		}
		if v136 > stride {
			v136 = stride
		}
		if (v132 >= v136) || (v134 >= v139) {
			v127 = v123 + 1
			v123 = v127
			continue
		}
		for v147 = v134; v147 < v139; v147++ {
			v151 = v147 * stride
			if v147 < v131 {
				v152 = int64(v131 - v147)
			} else {
				v152 = int64((v147 - v131) + 1)
			}
			v161 = v132
			for v161 < v136 {
				if v161 < v129 {
					v166 = int64(v129 - v161)
				} else {
					v166 = int64((v161 - v129) + 1)
				}
				v175 = (v166 * v166) + (v152 * v152)
				if v175 <= v112 {
					framebuffer[v151+v161] = c2_blend_pixel(framebuffer[v151+v161], color)
				} else {
					if v175 < (int64(radius+2) * (int64(radius) + 2)) {
						v188 = ((radius << 8) + 128) - int(c2_isqrt64(int64(v175<<16)))
						if v188 >= 255 {
							framebuffer[v151+v161] = c2_blend_pixel(framebuffer[v151+v161], color)
						} else {
							if v188 > 0 {
								framebuffer[v151+v161] = c2_blend_pixel_cov(framebuffer[v151+v161], color, uint32(v188))
							}
						}
					}
				}
				v161++
			}
		}
		v127 = v123 + 1
		v123 = v127
	}
}
