// Code generated by sgoiter emit go127; DO NOT EDIT.
// sgoiter-stamp: sha256=838b348a411cf2644a3c1b4ca7ff9f5b643162b0f1c9f1f8b1c1d8cdd119282c
package c2tuidiff

type C2_cell_t struct {
	Rune_ uint32
	Fg    byte
	Bg    byte
	Flags byte
	Width byte
}

type C2_span_t struct {
	X      int
	Y      int
	Length int
}

func C2_chunk_dirty4(front []uint64, back []uint64) int {
	var v2 int
	v2 = 0
	if front[0] != back[0] {
		v2++
	}
	if front[1] != back[1] {
		v2 += 2
	}
	if front[2] != back[2] {
		v2 += 4
	}
	if front[3] != back[3] {
		v2 += 8
	}
	return v2
}

func C2_cells_equal_at(front []C2_cell_t, back []C2_cell_t, i int) int {
	if front[i].Rune_ != back[i].Rune_ {
		return 0
	}
	if front[i].Fg != back[i].Fg {
		return 0
	}
	if front[i].Bg != back[i].Bg {
		return 0
	}
	if front[i].Flags != back[i].Flags {
		return 0
	}
	if front[i].Width != back[i].Width {
		return 0
	}
	return 1
}

func C2_diff_grid_scalar(front []C2_cell_t, back []C2_cell_t, count int, stride int, width int, spans []C2_span_t, max_spans int) int {
	var v7 int
	var v9 int
	var v11 int
	var v13 int
	var v15 int
	var v17 int
	var v19 int
	var v25 int
	var v27 int
	var v28 int
	var v72 bool
	_ = 0
	v7 = 0
	v9 = 0
	v11 = 0
	v13 = 0
	v15 = 0
	v17 = 0
	if width <= 0 {
		width = stride
	}
	for v19 = 0; v19 < count; v19++ {
		v25 = v19 % stride
		v27 = v19 / stride
		if v25 >= width {
			if v9 != 0 {
				if v7 < max_spans {
					spans[v7].X = v11
					spans[v7].Y = v13
					spans[v7].Length = v15
					v7++
				} else {
					v17 = 1
				}
				v9 = 0
				v15 = 0
			}
		} else {
			v28 = 0
			if front[v19].Rune_ != back[v19].Rune_ {
				v28 = 1
			} else {
				if front[v19].Fg != back[v19].Fg {
					v28 = 1
				} else {
					if front[v19].Bg != back[v19].Bg {
						v28 = 1
					} else {
						if front[v19].Flags != back[v19].Flags {
							v28 = 1
						} else {
							if front[v19].Width != back[v19].Width {
								v28 = 1
							}
						}
					}
				}
			}
			if v28 != 0 {
				if v9 == 0 {
					v9 = 1
					v11 = v25
					v13 = v27
					v15 = 1
				} else {
					v72 = (v27 == v13) && (v25 == (v11 + v15))
					if v72 {
						v15++
					} else {
						if v7 < max_spans {
							spans[v7].X = v11
							spans[v7].Y = v13
							spans[v7].Length = v15
							v7++
						} else {
							v17 = 1
						}
						v11 = v25
						v13 = v27
						v15 = 1
					}
				}
			} else {
				if v9 != 0 {
					if v7 < max_spans {
						spans[v7].X = v11
						spans[v7].Y = v13
						spans[v7].Length = v15
						v7++
					} else {
						v17 = 1
					}
					v9 = 0
					v15 = 0
				}
			}
		}
	}
	if v9 != 0 {
		if v7 < max_spans {
			spans[v7].X = v11
			spans[v7].Y = v13
			spans[v7].Length = v15
			v7++
		} else {
			v17 = 1
		}
	}
	if v17 != 0 {
		return -1
	}
	return v7
}
