// Code generated by sgoiter emit go127; DO NOT EDIT.
package src

func Poly1305_block5(h []uint32, r []uint32, m []uint32) {
	var v60 uint64
	var v89 uint64
	var v99 int
	var v115 uint64
	var v137 uint32
	var v177 uint32
	var v178 uint64
	var v16 uint32
	var v55 uint64
	var v95 uint64
	var v111 uint64
	var v112 uint64
	var v196 uint64
	var v200 uint64
	var v228 uint32
	var v69 uint32
	var v93 uint64
	var v166 uint32
	var v186 uint32
	var v208 uint64
	var v220 uint64
	var v267 uint64
	var v279 uint32
	var v30 uint32
	var v39 uint64
	var v42 uint64
	var v120 uint32
	var v169 uint32
	var v214 uint64
	var v255 uint64
	var v8 uint64
	var v58 uint32
	var v100 uint64
	var v138 uint64
	var v147 uint32
	var v173 uint64
	var v296 uint32
	var v301 uint32
	var v82 uint64
	var v4 uint64
	var v141 uint32
	var v191 uint64
	var v6 uint64
	var v242 uint32
	var v256 uint32
	var v283 uint64
	var v79 uint64
	var v88 int
	var v202 uint64
	var v205 uint32
	var v302 uint32
	var v70 uint64
	var v84 uint64
	var v103 uint32
	var v160 uint64
	var v172 uint32
	var v206 int
	var v211 uint64
	var v258 uint32
	var v132 uint32
	var v210 uint32
	var v277 uint32
	var v50 uint64
	var v101 uint64
	var v149 uint64
	var v150 uint64
	var v161 uint64
	var v167 uint64
	var v244 uint64
	var v41 uint32
	var v52 uint32
	var v77 uint32
	var v190 uint32
	var v61 uint64
	var v126 uint64
	var v128 uint32
	var v135 uint64
	var v152 uint32
	var v179 uint64
	var v262 uint64
	var v124 uint64
	var v225 uint64
	var v226 uint64
	var v292 uint32
	var v306 uint32
	var v243 uint64
	var v293 uint32
	var v298 uint32
	var v304 uint32
	var v36 uint32
	var v98 uint32
	var v114 uint32
	var v182 uint64
	var v213 uint32
	var v276 uint64
	var v25 uint32
	var v197 uint64
	var v288 uint32
	var v14 uint64
	var v27 uint64
	var v59 int
	var v3 uint64
	var v72 uint32
	var v155 uint64
	var v195 uint32
	var v251 uint32
	var v48 int
	var v67 uint64
	var v75 uint64
	var v130 uint64
	var v217 uint64
	var v240 uint64
	var v249 uint64
	var v253 uint64
	var v153 uint64
	var v184 uint64
	var v222 uint64
	var v234 uint64
	var v26 int
	var v53 uint64
	var v139 uint64
	var v159 int
	var v238 uint64
	var v274 uint64
	var v307 uint32
	var v17 uint64
	var v33 uint64
	var v118 uint64
	var v188 uint64
	var v284 uint32
	var v290 uint32
	var v31 uint64
	var v158 uint32
	var v270 uint32
	var v281 uint64
	var v199 uint32
	var v286 uint32
	var v11 uint64
	var v47 uint32
	var v78 uint64
	var v109 uint32
	var v265 uint32
	var v63 uint32
	var v123 uint32
	var v144 uint64
	var v163 uint32
	var v164 uint64
	var v216 uint32
	var v231 uint64
	var v38 uint64
	var v87 uint32
	var v90 uint64
	var v207 uint64
	var v73 uint64
	var v104 uint64
	var v110 int
	var v133 uint64
	var v181 uint32
	var v247 uint64
	var v37 int
	var v148 int
	var v193 uint64
	var v219 uint32
	var v224 uint32
	var v233 uint32
	var v235 uint64
	var v237 uint32
	var v22 uint64
	var v64 uint64
	var v66 uint32
	var v142 uint64
	var v175 uint64
	var v246 uint32
	var v260 uint64
	var v272 uint32
	var v13 uint32
	var v19 uint32
	var v44 uint64
	var v92 uint32
	var v121 uint64
	var v129 uint64
	var v187 uint64
	var v7 uint64
	var v20 uint64
	var v106 uint64
	var v252 uint64
	var v263 uint32
	var v269 uint64
	var v10 uint32
	var v28 uint64
	var v81 uint32
	var v117 uint32
	var v5 uint64
	var v170 uint64
	var v229 uint64
	var v49 uint64
	v10 = h[int(0)]
	v11 = uint64(v10)
	v13 = m[int(0)]
	v14 = v11 + uint64(v13)
	v16 = r[int(0)]
	v17 = v14 * uint64(v16)
	v19 = h[int(1)]
	v20 = uint64(v19)
	v22 = v20
	v25 = r[int(4)]
	v26 = 5 * int(v25)
	v27 = v22 * uint64(v26)
	v28 = v17 + v27
	v30 = h[int(2)]
	v31 = uint64(v30)
	v33 = v31
	v36 = r[int(3)]
	v37 = 5 * int(v36)
	v38 = v33 * uint64(v37)
	v39 = v28 + v38
	v41 = h[int(3)]
	v42 = uint64(v41)
	v44 = v42
	v47 = r[int(2)]
	v48 = 5 * int(v47)
	v49 = v44 * uint64(v48)
	v50 = v39 + v49
	v52 = h[int(4)]
	v53 = uint64(v52)
	v55 = v53
	v58 = r[int(1)]
	v59 = 5 * int(v58)
	v60 = v55 * uint64(v59)
	v61 = v50 + v60
	v3 = v61
	v63 = h[int(0)]
	v64 = uint64(v63)
	v66 = m[int(0)]
	v67 = v64 + uint64(v66)
	v69 = r[int(1)]
	v70 = v67 * uint64(v69)
	v72 = h[int(1)]
	v73 = uint64(v72)
	v75 = v73
	v77 = r[int(0)]
	v78 = v75 * uint64(v77)
	v79 = v70 + v78
	v81 = h[int(2)]
	v82 = uint64(v81)
	v84 = v82
	v87 = r[int(4)]
	v88 = 5 * int(v87)
	v89 = v84 * uint64(v88)
	v90 = v79 + v89
	v92 = h[int(3)]
	v93 = uint64(v92)
	v95 = v93
	v98 = r[int(3)]
	v99 = 5 * int(v98)
	v100 = v95 * uint64(v99)
	v101 = v90 + v100
	v103 = h[int(4)]
	v104 = uint64(v103)
	v106 = v104
	v109 = r[int(2)]
	v110 = 5 * int(v109)
	v111 = v106 * uint64(v110)
	v112 = v101 + v111
	v4 = v112
	v114 = h[int(0)]
	v115 = uint64(v114)
	v117 = m[int(1)]
	v118 = v115 + uint64(v117)
	v120 = r[int(2)]
	v121 = v118 * uint64(v120)
	v123 = h[int(1)]
	v124 = uint64(v123)
	v126 = v124
	v128 = r[int(1)]
	v129 = v126 * uint64(v128)
	v130 = v121 + v129
	v132 = h[int(2)]
	v133 = uint64(v132)
	v135 = v133
	v137 = r[int(0)]
	v138 = v135 * uint64(v137)
	v139 = v130 + v138
	v141 = h[int(3)]
	v142 = uint64(v141)
	v144 = v142
	v147 = r[int(4)]
	v148 = 5 * int(v147)
	v149 = v144 * uint64(v148)
	v150 = v139 + v149
	v152 = h[int(4)]
	v153 = uint64(v152)
	v155 = v153
	v158 = r[int(3)]
	v159 = 5 * int(v158)
	v160 = v155 * uint64(v159)
	v161 = v150 + v160
	v5 = v161
	v163 = h[int(0)]
	v164 = uint64(v163)
	v166 = m[int(2)]
	v167 = v164 + uint64(v166)
	v169 = r[int(3)]
	v170 = v167 * uint64(v169)
	v172 = h[int(1)]
	v173 = uint64(v172)
	v175 = v173
	v177 = r[int(2)]
	v178 = v175 * uint64(v177)
	v179 = v170 + v178
	v181 = h[int(2)]
	v182 = uint64(v181)
	v184 = v182
	v186 = r[int(1)]
	v187 = v184 * uint64(v186)
	v188 = v179 + v187
	v190 = h[int(3)]
	v191 = uint64(v190)
	v193 = v191
	v195 = r[int(0)]
	v196 = v193 * uint64(v195)
	v197 = v188 + v196
	v199 = h[int(4)]
	v200 = uint64(v199)
	v202 = v200
	v205 = r[int(4)]
	v206 = 5 * int(v205)
	v207 = v202 * uint64(v206)
	v208 = v197 + v207
	v6 = v208
	v210 = h[int(0)]
	v211 = uint64(v210)
	v213 = m[int(3)]
	v214 = v211 + uint64(v213)
	v216 = r[int(4)]
	v217 = v214 * uint64(v216)
	v219 = h[int(1)]
	v220 = uint64(v219)
	v222 = v220
	v224 = r[int(3)]
	v225 = v222 * uint64(v224)
	v226 = v217 + v225
	v228 = h[int(2)]
	v229 = uint64(v228)
	v231 = v229
	v233 = r[int(2)]
	v234 = v231 * uint64(v233)
	v235 = v226 + v234
	v237 = h[int(3)]
	v238 = uint64(v237)
	v240 = v238
	v242 = r[int(1)]
	v243 = v240 * uint64(v242)
	v244 = v235 + v243
	v246 = h[int(4)]
	v247 = uint64(v246)
	v249 = v247
	v251 = r[int(0)]
	v252 = v249 * uint64(v251)
	v253 = v244 + v252
	v7 = v253
	v255 = v3 >> uint8(26)
	v8 = v255
	v256 = uint32(v3)
	v258 = v256 & uint32(67108863)
	h[int(0)] = v258
	v260 = v4 + v8
	v4 = v260
	v262 = v4 >> uint8(26)
	v8 = v262
	v263 = uint32(v4)
	v265 = v263 & uint32(67108863)
	h[int(1)] = v265
	v267 = v5 + v8
	v5 = v267
	v269 = v5 >> uint8(26)
	v8 = v269
	v270 = uint32(v5)
	v272 = v270 & uint32(67108863)
	h[int(2)] = v272
	v274 = v6 + v8
	v6 = v274
	v276 = v6 >> uint8(26)
	v8 = v276
	v277 = uint32(v6)
	v279 = v277 & uint32(67108863)
	h[int(3)] = v279
	v281 = v7 + v8
	v7 = v281
	v283 = v7 >> uint8(26)
	v8 = v283
	v284 = uint32(v7)
	v286 = v284 & uint32(67108863)
	h[int(4)] = v286
	v288 = uint32(v8)
	v290 = v288 * uint32(5)
	v292 = h[int(0)]
	v293 = v292 + v290
	h[int(0)] = v293
	v296 = h[int(0)]
	v298 = v296 >> uint8(26)
	v8 = uint64(v298)
	v301 = h[int(0)]
	v302 = v301 & uint32(67108863)
	h[int(0)] = v302
	v304 = uint32(v8)
	v306 = h[int(1)]
	v307 = v306 + v304
	h[int(1)] = v307
}

