// Code generated by sgoiter emit go127; DO NOT EDIT.
// sgoiter-stamp: sha256=25eef9e6ab36bea26b61d44581f703735ecd8a7d1e33c098b7cdc1dbf0eab1a6
package c2base64

const B64_table = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"

func Base64_encode_stream(src []byte, len_ uint64, dst []byte) uint64 {
	n := int(len_)
	if n > len(src) {
		n = len(src)
	}
	src = src[:n]
	i, j := 0, 0
	for ; i+2 < n; i += 3 {
		v := uint32(src[i])<<16 | uint32(src[i+1])<<8 | uint32(src[i+2])
		o := dst[j : j+4]
		o[0] = B64_table[(v>>18)&63]
		o[1] = B64_table[(v>>12)&63]
		o[2] = B64_table[(v>>6)&63]
		o[3] = B64_table[v&63]
		j += 4
	}
	if i < n {
		v := uint32(src[i]) << 16
		if i+1 < n {
			v |= uint32(src[i+1]) << 8
			dst[j] = B64_table[(v>>18)&63]
			dst[j+1] = B64_table[(v>>12)&63]
			dst[j+2] = B64_table[(v>>6)&63]
			dst[j+3] = '='
			j += 4
		} else {
			dst[j] = B64_table[(v>>18)&63]
			dst[j+1] = B64_table[(v>>12)&63]
			dst[j+2] = '='
			dst[j+3] = '='
			j += 4
		}
	}
	return uint64(j)
}
